### ISSUE TITLE
Support for other cameras? HSV records question?

### ISSUE THREAD

**Issue by mkz212** [hjdhjd/homebridge-unifi-protect#1001]
**Is your feature request related to a problem? Please describe:**
A really great plugin. And after the number of closed errors I see that perfectly supported. Are you considering supporting other cameras - e.g. making this plugin or creating a copy of it to support each rstp camera?

**Describe the solution you'd like:**
Support for other cameras. 

**Describe alternatives you've considered:**
I am currently using Homebridge Camera Ui Unfortunately, the recording does not work well here. HSV often either does not record or records cut (it starts recording too late and ends too early).

**Additional context:**
Alternatively, if you are not considering support for other cameras, have you had experience with such an erroneous operation of recording in HSV and can you suggest something?

**Comment by hjdhjd** [comment]
Thanks for the request. This plugin is for UniFi Protect, only. I will not be providing support for non-Protect cameras.

My suggestion: get a Protect camera and enter the Protect ecosystem if you want a great HKSV experience. 😄 Beyond that, I’m afraid you’re on your own…I don’t keep up with what others choose to do.
