### ISSUE TITLE
Cannot connect to controller after upgrade of UniFi Protect to 2.9.30

### ISSUE THREAD

**Issue by petr-balogh** [hjdhjd/homebridge-unifi-protect#1003]
**Describe The Problem:**

Conection to unifi controller stopped working
**To Reproduce:**

after upgrade to new controller the plugin cannot log in to the unifi controller
**Logs:**

```
[24/10/2023, 15:46:27] Loaded plugin: homebridge-unifi-protect@6.15.1
[24/10/2023, 15:46:27] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[24/10/2023, 15:46:31] [homebridge-unifi-protect] Launched child bridge with PID 7578
[24/10/2023, 15:46:32] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[24/10/2023, 15:46:32] [homebridge-unifi-protect] Loaded homebridge-unifi-protect v6.15.1 child bridge successfully
[24/10/2023, 15:46:33] [homebridge-unifi-protect] Using FFmpeg version: 6.0-homebridge-alpine-armv7l-static.
[24/10/2023, 15:46:33] Homebridge v1.6.1 (HAP v0.11.1) (homebridge-unifi-protect) is running on port 35117.
[24/10/2023, 15:46:56] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[24/10/2023, 15:46:56] [Homebridge UI] [homebridge-unifi-protect] (node:7631) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
[24/10/2023, 15:47:08] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[24/10/2023, 15:47:13] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices

```

**Homebridge Configuration:**

```json
{
            "controllers": [
                {
                    "address": "192.168.1.1",
                    "name": "Dream Machine Special Edition",
                    "password": "mypasswordhidden",
                    "username": "myuserhidden"
                }
            ],
            "options": [
                "Enable.Doorbell.Trigger"
            ],
            "_bridge": {
                "username": "0E:A2:05:4B:D1:43",
                "port": 35117
            },
            "platform": "UniFi Protect"
        },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** v18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** v6.15.1
* **UniFi Protect Version:** 2.9.30 - updated to this version 21.10.2023 - probably time it's stopped working.
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** UniFi OS 3.2.5
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 17.0.3
* **Operating System and OS Version:**  Raspbian 

Is there any way how I can check more detailed logs from the plugin to see what's going on during authentication?
I have tried to uninstall plugin and install again, then where plugin wants me to again put authentication details like controller IP and username/password, it's not able to login to controller.

When using config from backup it's not working. Not sure what has changed.

**Comment by hjdhjd** [comment]
Thanks for the report, but there’s not much here I can help you with. The plugin’s working fine from the logs. If you think it’s an issue with plugin version, feel free to revert to an earlier version…but from what you’ve described, that isn’t the issue: correlation isn’t causation.

I would recommend you raise this issue on the Homebridge Discord in the unifi-protect channel…you’ll find a community that can help point you in the right direction. There’s not really much here I can help with I’m afraid.

**Comment by justme-1968** [comment]
it looks like this version stopped using the X-CSRF-Token for the login. 

scrypted already has a fix here: https://github.com/koush/unifi-protect/compare/3759ba334fd157e0100ac0e5c1fe0298df36de73...bf6fdbdc657d107bd89a376f84b55c5147254829#diff-d0299e62c4f045a054272a2f17ae15864aa97eebd0bbe52e130e799e668ad990

**Comment by gierig1977** [comment]
It’s the Upgrade to 3.2.5 (with is pulled ATM due other Issues)
scrypted got already a update, seems the handling for the CSFR Token change or get removed.
 
My Nodes Skill are to bad to adopt that small that was made in scrypted to this Homebridge Plugin for my Setup.

**Comment by justme-1968** [comment]
where did you see that it is pulled? according to the release thread here: https://community.ui.com/releases/UniFi-OS-Network-Video-Recorders-3-2-5/b9130e06-460b-422b-acee-c6bcfca2f3bd it is still available.

**Comment by gierig1977** [comment]
> where did you see that it is pulled? according to the release thread here: https://community.ui.com/releases/UniFi-OS-Network-Video-Recorders-3-2-5/b9130e06-460b-422b-acee-c6bcfca2f3bd it is still available.

May just the UDM-SE version (orin gernerll theVersion with gateway function, not the VCR Only versions)
Was Pulled as some serious issues with WAN Connection to starling and other.
Sorry to be unspecific.

**Comment by hjdhjd** [comment]
I do not support non-production releases of UniFi OS or the Protect controller. Closing the issue. Thanks.
