### ISSUE TITLE
Unable to connect with latest Unifi OS 3.2.5

### ISSUE THREAD

**Issue by Guizmos** [hjdhjd/homebridge-unifi-protect#1005]
**Describe The Problem:**
Since the last update of Unifi OS to version 3.2.5, it is impossible to connect to it with this plugin

**To Reproduce:**
Connection failed after update
Trying with IP, with local user
Completely removing the plugin, restarting HomeBridge then reinstalling the plugin, the problem is still present

**Logs:**
`[10/25/2023, 7:56:09 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[10/25/2023, 7:56:09 PM] [Homebridge UI] [homebridge-unifi-protect] (node:29538) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
[10/25/2023, 7:56:09 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getErrorMessage
[10/25/2023, 7:56:21 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[10/25/2023, 7:56:21 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getErrorMessage
[10/25/2023, 7:56:26 PM] [Homebridge UI] [homebridge-unifi-protect] Terminating child process...
[10/25/2023, 7:56:26 PM] [Homebridge UI] [homebridge-unifi-protect] Child process ended`

**Homebridge Configuration:**

**JSON**
```json
{
    "platform": "UniFi Protect",
    "name": "UniFi Protect"
}
```

**Screenshots:**
![Capture d’écran 2023-10-25 à 20 20 00](https://github.com/hjdhjd/homebridge-unifi-protect/assets/48725258/8e2a1860-07c0-4738-a5b8-4b1d47d04a02)

![Capture d’écran 2023-10-25 à 20 26 29](https://github.com/hjdhjd/homebridge-unifi-protect/assets/48725258/0094bed2-6240-426c-aff4-d68efeccdbff)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:** 6.15.1
* **UniFi Protect Version:** 2.9.30
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** 3.2.5
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** HomePod 17.1
* **Operating System and OS Version:** Docker on Synology via Portainer

**Comment by MegaraSoftware** [comment]
Have also the same problem:

Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 4852) 
Node: Node.js v20.9.0
Unifi OS: v3.2.5
Unifi Protect Version: 2.9.30
Operating System and OS Version: Raspberry Pi  Linux 6.1.21-v8+ arm - Raspbian GNU/Linux Bullseye (11)

**Comment by natestump** [comment]
Up to Date: v1.6.1

Homebridge UniFi Protect: homebridge-unifi-protect v6.15.1

Unifi Protect: Version 2.9.30
UDM SE: UniFi OS 3.2.5

This occurs here too.

**Comment by hjdhjd** [comment]
@MegaraSoftware and @natestump As I’ve said multiple times in other threads: **please do not hijack other users support requests.** If you want to open an issue to receive support, feel free to do so. I will not respond nor provide support requests for anyone other than the original opener of the issue.

**Comment by hjdhjd** [comment]
> **Describe The Problem:** Since the last update of Unifi OS to version 3.2.5, it is impossible to connect to it with this plugin
> 
> **To Reproduce:** Connection failed after update Trying with IP, with local user Completely removing the plugin, restarting HomeBridge then reinstalling the plugin, the problem is still present
> 
> **Logs:** `[10/25/2023, 7:56:09 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices [10/25/2023, 7:56:09 PM] [Homebridge UI] [homebridge-unifi-protect] (node:29538) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version. (Use `node --trace-deprecation ...` to show where the warning was created) [10/25/2023, 7:56:09 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getErrorMessage [10/25/2023, 7:56:21 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices [10/25/2023, 7:56:21 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getErrorMessage [10/25/2023, 7:56:26 PM] [Homebridge UI] [homebridge-unifi-protect] Terminating child process... [10/25/2023, 7:56:26 PM] [Homebridge UI] [homebridge-unifi-protect] Child process ended`
> 
> **Homebridge Configuration:**
> 
> **JSON**
> 
> ```json
> {
>     "platform": "UniFi Protect",
>     "name": "UniFi Protect"
> }
> ```
> 
> **Screenshots:** ![Capture d’écran 2023-10-25 à 20 20 00](https://user-images.githubusercontent.com/48725258/278110838-8e2a1860-07c0-4738-a5b8-4b1d47d04a02.png)
> 
> ![Capture d’écran 2023-10-25 à 20 26 29](https://user-images.githubusercontent.com/48725258/278111155-0094bed2-6240-426c-aff4-d68efeccdbff.png)
> 
> **Environment:**
> 
> * **Homebridge Version:** 1.6.1
> * **Node Version:**
> * **Homebridge-UniFi-Protect Plugin Version:** 6.15.1
> * **UniFi Protect Version:** 2.9.30
> * **UniFi Protect Controller Type:** UNVR
> * **UniFi Protect Controller Firmware Version:** 3.2.5
> * **Apple Device and iOS / macOS / iPadOS / tvOS Version:** HomePod 17.1
> * **Operating System and OS Version:** Docker on Synology via Portainer

Thanks for the support request - it looks like you’re running a beta version of UniFi Protect  - [HBUP is explicitly unsupported on EA/beta firmwares.](https://github.com/hjdhjd/homebridge-unifi-protect#things-to-be-aware-of) My recommendation would be to downgrade, or wait to see how Ubiquiti continues to evolve their beta firmwares.

You’re on your own, I’m afraid.
