### ISSUE TITLE
send Snapshot to iPhone and Apple Watch

### ISSUE THREAD

**Issue by stefansegers** [hjdhjd/homebridge-unifi-protect#1006]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

Right now when the doorbell ring you will receive a message someone is at the door. It would be great if you then receive a snapshot/photo of the person who is at the door. This was also done with Nest camera's and this is really handy!

**Describe alternatives you've considered:**

I tried to use Apple Home app, but could not find a way to do this.

**Additional context:**

**Comment by hjdhjd** [comment]
That’s all ultimately controlled by Apple and the Home app and we have no influence over it…there’s not much to do here I’m afraid. Most of HomeKit is a black box beyond providing it the video/snapshots it’s requesting. Best of luck!

**Comment by stefansegers** [comment]
thanks for explaining 👌🏽
