### ISSUE TITLE
Newer Unifi Firmware Rate Limits Logins - API Errors

### ISSUE THREAD

**Issue by hanzov69** [hjdhjd/homebridge-unifi-protect#1010]
**Is your feature request related to a problem? Please describe:**
Newer Unifi Firmware has introduced an annoying rate limit on authentications, which this plugin will run in to- I believe this is causing many of the API error issues that others are reporting.  

Basically, if a user is seeing the API error / "Unable to connect to Protect controller", it's likely due to this issue. Further details and a UniFi side fix are available here:
https://community.ui.com/questions/Unifi-API-Rate-Limited/ba82a718-9418-46b0-8f2f-235bfc647f9b

**Describe the solution you'd like:**
Ideally, ubiqituti wouldn't make opaque changes that potentially break things like this, but that's unreasonable to expect from them (I guess). There may be something that can be done on the homebridge-unifi-protect plugin side to cache sessions or create something with persistence? I don't know, out of my wheelhouse I'm afraid. 

**Describe alternatives you've considered:**
None to speak of. To be clear, this isn't an issue with the plugin IMO

**Additional context:**
<img width="381" alt="Screenshot 2023-10-31 at 23 18 24" src="https://github.com/hjdhjd/homebridge-unifi-protect/assets/2313928/0d3bb947-fb2f-432e-9b42-30c636e9288e">
<img width="791" alt="Screenshot 2023-10-31 at 23 20 24" src="https://github.com/hjdhjd/homebridge-unifi-protect/assets/2313928/8f9844ec-562b-499f-817b-f41e1d4974f7">

**Comment by poindexter12** [comment]
caching the API credentials will likely solve this issue for the plugin for those that don't want to edit config settings on the device.

**Comment by hjdhjd** [comment]
Thanks for the request, but it doesn’t belong here - the unifi-protect API library (a different project and repo of mine) is where it would belong…EXCEPT…

I already do all this. 😄 

HBUP only reauthenticates against the Protect controller when it detects an error with the API, specifically when tapping into the occasionally flaky livestream API that Protect has.

We do not reauthenticate regularly and already do this.

The HBUP webUI does login to the controller independently…that’s just the way it works.

Thanks for the suggestion, but we already don’t reauthenticate without reason as it is. 😄
