### ISSUE TITLE
Cameras no longer visible.

### ISSUE THREAD

**Issue by ianknight77** [hjdhjd/homebridge-unifi-protect#1014]
**Describe The Problem:**
<Having issues with the Unifi Protect plugin: none of the cameras show up. Tried reinstalling the plugin and fixing Hoobs through SSH, but no luck. Triple checked permissions and login details for Unifi Protect as well. Reflash of Hoobs did not fix problem.
>

**To Reproduce:**
<none>

**Logs:**
<10/28/2023, 6:51:05 PMUnifi Protect Bridge starting
10/28/2023, 6:51:10 PMUnifi Protect BridgeLoaded plugin 'homebridge-unifi-protect'
10/28/2023, 6:51:10 PMUnifi Protect BridgeLoading 1 platforms...
10/28/2023, 6:51:10 PMUnifi Protect BridgeBridge is running on port 51826.
10/28/2023, 6:51:10 PMUnifi Protect BridgeUniFi ProtectUsing FFmpeg version: 6.0-homebridge-alpine-armv7l-static.
10/28/2023, 6:51:10 PMUnifi Protect BridgeERROR(Use `node --trace-deprecation ...` to show where the warning was created)

Used the command to see if I could troubleshoot, get this:

hoobs@hoobs:~$ node --trace-deprecation ...

node:internal/modules/cjs/loader:1031

throw err;

^

Error: Cannot find module '/home/hoobs/...'

at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)

at Function.Module._load (node:internal/modules/cjs/loader:873:27)

at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

at node:internal/main/run_main_module:22:47 {

code: 'MODULE_NOT_FOUND',

requireStack: []

}

>

```
10/28/2023, 6:51:05 PMUnifi Protect Bridge starting
10/28/2023, 6:51:10 PMUnifi Protect BridgeLoaded plugin 'homebridge-unifi-protect'
10/28/2023, 6:51:10 PMUnifi Protect BridgeLoading 1 platforms...
10/28/2023, 6:51:10 PMUnifi Protect BridgeBridge is running on port 51826.
10/28/2023, 6:51:10 PMUnifi Protect BridgeUniFi ProtectUsing FFmpeg version: 6.0-homebridge-alpine-armv7l-static.
10/28/2023, 6:51:10 PMUnifi Protect BridgeERROR(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Homebridge Configuration:**

```json
{
    "platform": "UniFi Protect",
    "controllers": [
        {
            "address": "192.168.1.1",
            "password": "password",
            "username": "user"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** <4.3.0>
* **Node Version:** <16.20.2>
* **Homebridge-UniFi-Protect Plugin Version:**1.6.0
* **UniFi Protect Version:** 3.2.5
* **UniFi Protect Controller Type:** Dream Router
* **UniFi Protect Controller Firmware Version:** 2.9.33
* **iOS 17 MacOS Sonoma
* **Operating System and OS Version:** Raspian

**Comment by hjdhjd** [comment]
Sorry - I provide no support for anything HOOBS-related. You might want to check with the HOOBS team there.

**Comment by ianknight77** [comment]
I did. No response.
