### ISSUE TITLE
Api error 499

### ISSUE THREAD

**Issue by acfking** [hjdhjd/homebridge-unifi-protect#1022]
### Homebridge UniFi Protect Version

Latest

### Homebridge Platform and OS

Raspberry Pi 4

### Homebridge Version

Latest

### Node Version

Latest

### UniFi OS Version

Latest

### UniFi Protect Controller Version

Latest

### Describe the problem

Hiya. 
I added a new camera and no suddenly getting this error constantly. 
API error: 499

### Homebridge HBUP JSON configuration

```json
-
```

### Relevant log output

```shell
-
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
"Latest" is not a sufficient answer to provide support. Please fill out the support template as completely and accurately as possible, if you'd like support. You're also welcome to use the Discord.
