### ISSUE TITLE
Support for MFA

### ISSUE THREAD

**Issue by PocketTim** [hjdhjd/homebridge-unifi-protect#1031]
### Describe the feature request

I recently enabled two factor authentication on my UniFi account and then noticed a few days later that all my cameras were down in HomeKit.

After checking Homebridge the penny dropped and I realised it was because it couldn't auth against the account.

Is it possible to have this implemented in any way? I check to see if there was some sort of App Password option in UniFi but there is not.

### Describe the proposed solution

As above.

### Describe alternatives you have considered to the enhancement

As above.

**Comment by hjdhjd** [comment]
We explicitly don't support UI MFA and I have no plans to do so.

Recommended practice is always to create a local account just for use with HBUP.

Best of luck.
