### ISSUE TITLE
AI 360 Dewarp in Homekit

### ISSUE THREAD

**Issue by zetas** [hjdhjd/homebridge-unifi-protect#1032]
### Describe the feature request

The Ai 360 cameras we've deployed work great in the unifi protect app and can be dewarped in the app to see a proper view and pan/tilt. It'd be amazing if this functionality could be made to work in the homekit bridge as well somehow. Even if we can't pan/tilt, at least having the video dewarped would be very helpful. Unfortunately I just deployed 5 of these around my house and not being able to use them properly in homekit is a real bummer.

### Describe the proposed solution

Dewarp the video footage before sending to homekit i guess? Not sure if homekit itself is capable of adding a dewarp filter the same as unifi protect.

### Describe alternatives you have considered to the enhancement

Unfortunately the only alternative I can see is to use the unifi protect app instead of homekit for viewing these cameras. I'd be happy to sponsor this development as well if that would help.

**Comment by zetas** [comment]
bump

**Comment by hjdhjd** [comment]
I may provide support for this in the future, but it's not an immediate priority. Thanks for the request.
