### ISSUE TITLE
“Talk” button showing on unsupported cameras

### ISSUE THREAD

**Issue by herbi3** [hjdhjd/homebridge-unifi-protect#1035]
### Homebridge UniFi Protect Version

Latest

### Homebridge Platform and OS

Ubuntu VM

### Homebridge Version

Latest

### Node Version

Latest

### UniFi OS Version

Latest official

### UniFi Protect Controller Version

Latest offical

### Describe the problem

Talk button showing on unsupported cameras. Not enabled for these cameras, only enabled manually for the doorbell camera. These are G4 bullets and a standard G4 doorbell
![IMG_3296](https://github.com/hjdhjd/homebridge-unifi-protect/assets/11141749/92010883-d8b5-42d2-8792-ee6d406cc475)
![IMG_3295](https://github.com/hjdhjd/homebridge-unifi-protect/assets/11141749/31ef17d9-2d85-4ca1-87c0-bd5bfe69edd2)
![IMG_3293](https://github.com/hjdhjd/homebridge-unifi-protect/assets/11141749/cebecef0-3d14-47cd-b3ee-8bede7ec54ca)

### Homebridge HBUP JSON configuration

```json
.
```

### Relevant log output

```shell
.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by x-magic** [comment]
Same issue here. Talk button is showing up on all my G3 Flex cameras (with microphone but no speaker). 

No error is triggered, though, when using the feature. It just doing nothing.

**Comment by hjdhjd** [comment]
I'm aware of this issue and it's existed since iOS 17 was released. Appears to be a HomeKit bug but may be a Homebridge one. This was also already asked and answered previously. Thanks for the report.
