### ISSUE TITLE
Unable to process MQTT message

### ISSUE THREAD

**Issue by marrrkus** [hjdhjd/homebridge-unifi-protect#1037]
### Homebridge UniFi Protect Version

v6.16.0

### Homebridge Platform and OS

RPi4

### Homebridge Version

v1.7.0

### Node Version

v18.19.0

### UniFi OS Version

v3.2.9

### UniFi Protect Controller Version

2.10.11

### Describe the problem

Hey guys,

I have a clean install of homebridge and this wonderful plugin. Unfortunately, I get the following errors (couldn't find anything related on google or github):

> [1/24/2024, 10:21:41 AM] [UniFi Protect] Dream Machine Pro  [XXX] Front Door [G4 Doorbell]: Unable to process MQTT message: "". Error: Unexpected end of JSON input.
> [1/24/2024, 10:21:41 AM] [UniFi Protect] Dream Machine Pro [XXX]: Unable to process MQTT liveview setting: "". Error: Unexpected end of JSON **input.

Anyways, [homebridge-unifi-protect] is working for quite some time but without any notice it stops doing anything and not recognizing any more motion or ring events.

Any advice?

Thanks!
Markus

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.X.X",
            "mqttTopic": "unifi/protect",
            "mqttUrl": "mqtt://USER:PASS@192.168.X.X:XXXX",
            "password": "PASS",
            "username": "USER"
        }
    ],
    "name": "UniFi Protect",
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
[1/24/2024, 10:21:41 AM] [UniFi Protect] Dream Machine Pro  [XXX] Front Door [G4 Doorbell]: Unable to process MQTT message: "". Error: Unexpected end of JSON input.

[1/24/2024, 10:21:41 AM] [UniFi Protect] Dream Machine Pro [XXX]: Unable to process MQTT liveview setting: "". Error: Unexpected end of JSON **input.

[homebridge-unifi-protect] (node:283267) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks for the report - the error is because something is trying to speak to HBUP via MQTT and trigger an event and is doing so incorrectly or in an unsupported way. What’re you doing with MQTT?

**Comment by marrrkus** [comment]
Sorry, I was on a business trip.

I am pushing ring and motion events to ioBroker. There should not be any request coming from ioBroker.

**Comment by hjdhjd** [comment]
I would take a closer look at what’s coming across MQTT. This message is because someone is publishing a message to `unifi/protect/XYZ/liveviews/set` - I’m afraid there’s not much more I can do here. Look at the [MQTT](https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/MQTT.md) documentation for more detail on what HBUP expects (in this case a JSON) when using that message.

Best of luck!
