### ISSUE TITLE
2FA for homebridge-unifi-protect

### ISSUE THREAD

**Issue by MSank1003** [hjdhjd/homebridge-unifi-protect#1041]
### Describe the feature request

Unifi to require the use of 2FA for all Unifi accounts beginning in July of 2024.  Currently 2FA doesn't work with this plugin.   Will this be implemented?

### Describe the proposed solution

Enable 2FA support

### Describe alternatives you have considered to the enhancement

Lose integration with Apple Home.

**Comment by hjdhjd** [comment]
There are zero plans to support 2FA - in addition, you should most definitely not be using your UniFi account for HBUP...as the plugin documentation and best practices state: create a local user account specifically for Homebridge.
