### ISSUE TITLE
Trigger chime from HomeKit

### ISSUE THREAD

**Issue by cyaneous** [hjdhjd/homebridge-unifi-protect#1043]
### Describe the feature request

It would be great if it was possible to ring a chime from HomeKit automations.  This is especially useful because the native Unifi Protect behavior is to only support one doorbell at a time. With this, we could have more than one doorbell ring the chime (and any other automation too!). Plus, an extra "buzzer" sound type is very useful as well.

### Describe the proposed solution

It looks like the API is pretty simple for this on the controller. A POST to the following URLs seems to work:

chimes/{device_id}/play-speaker
chimes/{device_id}/play-buzzer

These play two different types of sound.

They would best be exposed as stateless programmable buttons in HomeKit - this would hide them from the regular UI but allow programming.

### Describe alternatives you have considered to the enhancement

Unifi does not offer this functionality.

**Comment by hjdhjd** [comment]
Stay tuned. Thanks for the suggestion.
