### ISSUE TITLE
"Unable to retrieve a snapshot" for just one camera

### ISSUE THREAD

**Issue by nyirsh** [hjdhjd/homebridge-unifi-protect#1044]
### Homebridge UniFi Protect Version

v6.18.0

### Homebridge Platform and OS

Raspberry Pi 4B+ / Raspbian GNU/Linux Bullseye (11)

### Homebridge Version

v1.7.0

### Node Version

v20.11.1

### UniFi OS Version

v3.2.9

### UniFi Protect Controller Version

v2.11.21

### Describe the problem

I'm not totally sure exactly when this issue started or what could have caused it, but the plugin was working flawlessly until a couple of weeks ago. I have 5 different cameras connected and only one of them recently started not updating its snapshot in the Home app, but if I try to livestream everything works correctly.

It is worth noting that I only just updated the node version because I thought it could help solving my issue but I actually was on v18 (sorry, don't remember exactly which subversion and I totally forgot to write it down).

The cameras and the Raspberry Pi running HB are on two separate VLANs but I know that the firewall rules have been set up correctly and that every device is on the proper subnet etc.

Thank you for your attention!

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.9.1",
            "password": "REDACTED",
            "username": "REDACTED"
        }
    ],
    "name": "UniFi Protect",
    "options": [
        "Enable.Device.SyncName",
        "Enable.Doorbell.Trigger",
        "Enable.Log.Motion",
        "Enable.Video.Transcode.Hardware",
        "Disable.Motion.Switch.E4388377FC7D",
        "Enable.Motion.SmartDetect",
        "Enable.Motion.SmartDetect.ObjectSensors"
    ],
    "_bridge": {
        "username": "REDACTED",
        "port": 47855
    },
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
[19/02/2024, 11:27:58] [UniFi Protect] Dream Machine Pro [UDM-PRO] Driveway [G5 Pro + Enhancer]: Unable to retrieve a snapshot.
[19/02/2024, 11:28:18] [UniFi Protect] Dream Machine Pro [UDM-PRO] Driveway [G5 Pro + Enhancer]: Unable to retrieve a snapshot.
[19/02/2024, 11:28:19] [UniFi Protect] Dream Machine Pro [UDM-PRO] Driveway [G5 Pro + Enhancer]: Streaming request from 192.168.8.208: 1280x720@30fps, 299 kbps. Using 1280x720@30fps (Medium), 2,000 kbps.
[19/02/2024, 11:28:27] [UniFi Protect] Dream Machine Pro [UDM-PRO] Driveway [G5 Pro + Enhancer]: Streaming parameters adjustment requested by HomeKit: 640x360, 30 fps, 132 kbps.
[19/02/2024, 11:28:30] [UniFi Protect] Dream Machine Pro [UDM-PRO] Driveway [G5 Pro + Enhancer]: Stopped video streaming session.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks for the report, unfortunately there’s not much I can do here. Snapshot errors occur when the Protect controller is unable to generate them. You might try rebooting the Protect controller and see if that helps, but I’m afraid I don’t have something else to point you toward on this one.

Best of luck.

**Comment by nyirsh** [comment]
Ah, I feel stupid, that's the only thing I didn't try and well... it worked. Thank you very much for your assistance, keep up the good work!
