### ISSUE TITLE
Rapberry Pi 5 Support

### ISSUE THREAD

**Issue by sharkannon** [hjdhjd/homebridge-unifi-protect#1046]
### Describe the feature request

It would be nice to be able to get Hardware Transcoding working on Raspberry Pi 5.  I have a 4 and it works fine, but when I enable it on my 5, the plugin doesn't detect it.

### Describe the proposed solution

None

### Describe alternatives you have considered to the enhancement

None

**Comment by hjdhjd** [comment]
Not until the Pi 5 matures a bit software-wise. This isn't a priority at the moment, but it will come. Thanks for the suggestion.
