### ISSUE TITLE
iOS 14 Home App "Camera Not Available"

### ISSUE THREAD

**Issue by bearattack11** [hjdhjd/homebridge-unifi-protect#105]
I am using this plugin with Homebridge web UI on a Raspberry Pi 3 with a G4 Doorbell. I have the doorbell and all its sensors showing correctly in the Home app, including the thumbnail of the video which seems to be updating about every 10 seconds. However, when opening the thumbnail to see a live view, the feed starts to load then fails, stating that someone else is viewing the feed. Sometimes the feed will just not load at all and the camera will be unresponsive for a few seconds.

This is reproducible every time the thumbnail is tapped. It also happens with the Home app on my MacBook running macOS Catalina 10.15.7.

Is this a known issue with this plugin or am I missing something in the configuration?

**Comment by hjdhjd** [comment]
Hi there. Would love to help you troubleshoot this, but you need to use the issue template...not ignore it. :smile:

Please open an issue and completely fill out the issue template.

Thanks!
