### ISSUE TITLE
Streaming not working over high Latency connections (5G/4G).

### ISSUE THREAD

**Issue by BenePT** [hjdhjd/homebridge-unifi-protect#1055]
### Homebridge UniFi Protect Version

6.20.0

### Homebridge Platform and OS

R Pie 4 Debian GNU/Linux Bookworm (12)

### Homebridge Version

1.7.0

### Node Version

18.18.2

### UniFi OS Version

3.2.12

### UniFi Protect Controller Version

3.0.26

### Describe the problem

Streaming not working on a high latency connection like 4G/5G i.e. Times out. Works well in intranet over Wifi. 
App Unifi Protect works well under 5G/4G. Not working via Home App in iOS

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "10.0.30.30",
            "name": "UNVR",
            "password": "************",
            "username": "*******"
        }
    ],
    "options": [
        "Enable.Video.Stream.Only.Low",
        "Enable.Motion.SmartDetect",
        "Enable.Motion.Switch",
        "Enable.Video.Transcode.Hardware.D021F9521798",
        "Enable.Video.Stream.Only.Low.D021F9521798",
        "Enable.Doorbell.Trigger.D021F9521798"
    ],
    "platform": "UniFi Protect",
    "_bridge": {
        "username": "**:**:**:**:**:**",
        "port": 35768
    }
}
```

### Relevant log output

```shell
Doorbell [G4 Doorbell Pro]: Streaming request from 10.0.30.22 (high latency connection): 640x480@30fps, 164 kbps. Hardware accelerated transcoding 480x360@15fps (Low), 200 kbps.
[04/04/2024, 22:35:02] [homebridge-unifi-protect] Doorbell [G4 Doorbell Pro]: Stopped video streaming session.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Appreciate the report, but streaming works just fine over high latency connections. 😄

I can’t do much with this report I’m afraid other than to state that streaming works fine, I use this very scenario every day. Some suggestions that might help:

* Reboot your HomeKit hubs (Apple TVs, HomePods). Remote connections go through those devices.
* If you have anything other than a pure vanilla network setup (e.g. you use VLANs or other locked down configurations), you might want to revisit and open everything up and then track down where you might have a missing rule.
* Stop forcing the stream quality and disable hardware transcoding - RPi’s hardware transcoding capabilities are okay, but not especially great.
* Use a higher-powered machine for Homebridge. A $100 RPi is a lovely device, but it’s only going to do so much at a certain point. My recommendation would be an Apple Silicon Mac.

Best of luck…you’re welcome to try the Discord as well, for some additional suggestions.
