### ISSUE TITLE
MFA Support

### ISSUE THREAD

**Issue by Blkcheech** [hjdhjd/homebridge-unifi-protect#1057]
### Describe the feature request

Unifi will soon require MFA and when it is enabled, the plugin fails to connect to Unifi Protect.

### Describe the proposed solution

Prompt for MFA code to authenticate to Unifi after Uder id/PW is entered to log in.

### Describe alternatives you have considered to the enhancement

There is no alternative. MFA must be supported.

**Comment by hjdhjd** [comment]
Please read the multitude of other closed issues on this topic.
