### ISSUE TITLE
Unifi Protect HKSV recordings cut off

### ISSUE THREAD

**Issue by MarcPow** [hjdhjd/homebridge-unifi-protect#1064]
### Homebridge UniFi Protect Version

v6.20.0

### Homebridge Platform and OS

macOS Sonoma

### Homebridge Version

v1.8.0

### Node Version

v20.12.1

### UniFi OS Version

Dunno

### UniFi Protect Controller Version

Dunno

### Describe the problem

HKSV recordings cut off

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.1.190",
            "username": "redacted",
            "password": "redacted"
        }
    ],
    "name": "UniFi Protect",
    "platform": "UniFi Protect",
    "options": [
        "Enable.Device.SyncName.245A4C546A9D",
        "Enable.Device.StatusLed.245A4C546A9D",
        "Enable.Video.Transcode.Hardware.245A4C546A9D",
        "Enable.Motion.SmartDetect.245A4C546A9D",
        "Disable.Log.Doorbell.7845582F57EF",
        "Enable.Video.Transcode.7845582F57EF",
        "Enable.Video.Stream.Only.Medium.7845582F57EF",
        "Disable.Video.HighResSnapshots.245A4C546A9D"
    ]
}
```

### Relevant log output

```shell
[4/21/2024, 11:40:22 AM] [UniFi Protect] Backyard Left [G4 Pro]: HKSV recording event ended early: An unexpected protocol failure has occured.
[HDS ::ffff:192.168.1.127] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Sorry I won't provide support if you can't completely fill out a support form including descriptions of how to recreate whatever issue you're encountering. Opening an issue and saying "it cuts off" isn't sufficient.
