### ISSUE TITLE
Unifi Baby Cry AI Detection - Device to trigger off of

### ISSUE THREAD

**Issue by southern-junior** [hjdhjd/homebridge-unifi-protect#1067]
### Describe the feature request

This may be a niche request, but if we could expose the baby cry detection to a device, i could trigger another actions to remind us that the baby is crying. Then we wouldn't have to wait for emails.

### Describe the proposed solution

a new device for "baby" or something similar to the motion detection device.

### Describe alternatives you have considered to the enhancement

i have thought about scripting a filter on my email, but keeping it in homekit would be ideal

**Comment by hjdhjd** [comment]
Audio smart detections will be coming in the future, once I'm comfortable that Ubiquiti's solidified their capability set in the coming weeks/months. Thanks.
