### ISSUE TITLE
Is it possible to add only motion sensors from some of the devices?

### ISSUE THREAD

**Issue by jirihelmich** [hjdhjd/homebridge-unifi-protect#1068]
### Homebridge UniFi Protect Version

v6.22.0

### Homebridge Platform and OS

Hoobs Pro

### Homebridge Version

5.0.9

### Node Version

18.16.1

### UniFi OS Version

v3.2.12

### UniFi Protect Controller Version

3.0.26

### Describe the problem

For some of the devices, I'd want to add only their motion service, not audio or picture. Is that possible with current settings? I didn't find that option in the docs.

### Homebridge HBUP JSON configuration

```json
{}
```

### Relevant log output

```shell
{}
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
For cameras, no, it is not possible. I won't be adding this feature either. Thanks.
