### ISSUE TITLE
Live Streaming does not work but works with other tools

### ISSUE THREAD

**Issue by imTHAI** [hjdhjd/homebridge-unifi-protect#1071]
### Homebridge UniFi Protect Version

6.22.0

### Homebridge Platform and OS

docker

### Homebridge Version

v1.8.1

### Node Version

v20.13.1

### UniFi OS Version

3.2.12

### UniFi Protect Controller Version

3.0.26

### Describe the problem

Hello,

I’ve been using your plugin for over a year and a half, but with frustration because the live streaming was not working. I read the advices on the subject and tried what was proposed but I never managed to solve the problem. So I gave up, I was doing without.
Today, following an article published on a website whose publications I follow, I wanted to try Home Assistant. And, to my surprise, the live streaming of my UNIFI cameras works ! 
But as I found Home Assistant too complex to just be able to put cameras in my Apple Home I uninstalled Home Assistant, removed the bridge and cameras from My Home, started searching on youtube videos, and discovered Scrypted that I installed. And again, surprise ! The live streaming works!

So all this long introductory message to ask if you could revisit this bug/problem? 

Now my UDM is subscribed to the Early Access releases (it wasn't working with the stable ones anyway, and I wanted the new features of unifi), so I can't give you much informations. But anyway the other softwares (Scrypted and HA) work with those versions so it means there is nothing "blocking".

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.18.1",
            "name": "UNVR",
            "password": "xxxxxxx",
            "username": "homekit"
        }
    ],
    "name": "UniFi Protect",
    "options": [
        "Enable.Device.SyncName.xxxxxx",
        "Enable.Video.Transcode"
    ],
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
It says it starts the streaming but on the App, it never happens.
[5/11/2024, 6:51:47 PM] [UniFi Protect] G5 Pro [G5 Pro]: Streaming request from 192.168.10.98: 1280x720@30fps, 299 kbps. Using 1280x720@30fps (Medium), 2,000 kbps.
[5/11/2024, 6:51:56 PM] [UniFi Protect] G5 Pro [G5 Pro]: Stopped video streaming session.
[5/11/2024, 6:52:01 PM] [UniFi Protect] G4 Instant [G4 Instant]: Streaming request from 192.168.10.98: 1280x720@30fps, 299 kbps. Using 1280x720@30fps (Medium), 1,500 kbps.
[5/11/2024, 6:52:20 PM] [UniFi Protect] G4 Instant [G4 Instant]: Stopped video streaming session.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Sorry I can't help you here but you're welcome to try the Homebridge Discord for support. The logs you posted show that live-streaming is in fact working from HBUP's perspective. 

I don't believe your issue lies in HBUP, but it may be a Homebridge issue - the symptoms you describe are in fact referenced in the troubleshooting documentation for HBUP. I'd suggest you start there and if, after reviewing the advice in the troubleshooting section you're still struggling, please try the Discord.
