### ISSUE TITLE
Switch to disable doorbell inside HomeKit 

### ISSUE THREAD

**Issue by durosity** [hjdhjd/homebridge-unifi-protect#1072]
### Describe the feature request

I would like an option to disable ring events from being passed to HomeKit.

### Describe the proposed solution

Ideally this would work as a switch that can be toggled on or off.  When enabled (or disabled depending on your POV) it would effectively mute the ring as it wouldn’t cause notifications on phone, HomePods chiming, etc.

### Describe alternatives you have considered to the enhancement

As present I can disable each HomePod from chiming in the home app, but it’s a manual process and frankly a bit fiddly, and still doesn’t disable notifications on iPhone/ipads/watches.  

This would be useful for times when I’m napping, or suffering from anxiety related issues.

**Comment by hjdhjd** [comment]
Appreciate the request, I'll look into it in a future update. I can see how useful this might be for some folks. Thanks!
