### ISSUE TITLE
Why does UP Floodlight require full admin rights?

### ISSUE THREAD

**Issue by nielsth** [hjdhjd/homebridge-unifi-protect#1074]
### Homebridge UniFi Protect Version

6.22

### Homebridge Platform and OS

macOS Sanoma 14.4.1 (23E224)

### Homebridge Version

1.8.2

### Node Version

18.19

### UniFi OS Version

3.2.12

### UniFi Protect Controller Version

3.0.26

### Describe the problem

When using a custom role for the HBUP user on UniFi OS with full management permission enabled for the UP Floodlight, Homebridge reports the following error. 

Working: 
<img width="403" alt="Screenshot 2024-05-22 at 21 43 12" src="https://github.com/hjdhjd/homebridge-unifi-protect/assets/13969232/9f6744ea-0814-49a7-8a5f-a38952cee5f8">

Not working:
<img width="659" alt="Screenshot 2024-05-22 at 21 43 35" src="https://github.com/hjdhjd/homebridge-unifi-protect/assets/13969232/2c8e67d9-bc80-4c2e-8778-00a6227f02e6">

The floodlight can be controlled when the user is updated to the super admin role.

Shouldn't full control over just the floodlight be enough to control it? In other words, is this a bug? 

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.1.8",
            "password": "XXX",
            "username": "hb_protect"
        }
    ],
    "name": "UniFi Protect",
    "options": [
        "Enable.Device.StatusLed.6022329DDE71"
    ],
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
Floodlight Terrace [UP FloodLight]: Unable to turn the light on. Please ensure this username has the Administrator role in UniFi Protect
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
It is what it is. Take it up with Ubiquiti. :smile:

It is not a bug in HBUP.

Best of luck.
