### ISSUE TITLE
2FA SUPPORT

### ISSUE THREAD

**Issue by ericsmith66** [hjdhjd/homebridge-unifi-protect#1075]
### Describe the feature request

Since Unifi is mandating 2FA In July 22, how will authentication after that 
https://community.ui.com/questions/Upcoming-Multi-Factor-Authentication-MFA-Requirement-for-All-UI-Accounts-in-July-2024/e0d06d3c-c0ae-4af6-aa67-53c159d486a8 . I have looked for information regarding this and can't seem to find any information. 

### Describe the proposed solution

Support 2FA per Unifi's requirements 

### Describe alternatives you have considered to the enhancement

Not sure how we will continue to access after the deadline.

**Comment by ericsmith66** [comment]
Looking a little deeper it seems like local only accounts might get around the problem. Is this the approach your are taking ?

**Comment by hjdhjd** [comment]
This will not be supported nor worked on. There are multiple other issues that were opened on this, and the documentation clearly states you must use a local account only. Ubiquiti accounts are not supported and will not be supported in the future, due to the 2FA requirements.
