### ISSUE TITLE
Support for enhanced encoding 

### ISSUE THREAD

**Issue by pbush25** [hjdhjd/homebridge-unifi-protect#1077]
### Describe the feature request

UniFi protect will soon be offering support for enhanced encoding (H.265/HEVC) (this rolled out as RC today) 

will it be possible to support this from Hombridge? I know not all hardware will have what’s necessary to handle this, so may require user-education as to whether this can be turned on for their environment. 

### Describe the proposed solution

Support enhanced encoding of UniFi Protect video streams. 

### Describe alternatives you have considered to the enhancement

Continue to use the legacy video codec.

**Comment by hjdhjd** [comment]
1. I provide no comments or commitments to anything that isn’t GA.
2. It’s not relevant to HomeKit. HomeKit currently **only** supports H.264 video. Should that change in the future, I’ll certainly be looking at it.
