### ISSUE TITLE
Enhanced Video Codec not working 

### ISSUE THREAD

**Issue by Carsten0404** [hjdhjd/homebridge-unifi-protect#1078]
### Homebridge UniFi Protect Version

6.22.0

### Homebridge Platform and OS

Raspberry 

### Homebridge Version

1.8.2

### Node Version

v20.13.1

### UniFi OS Version

4.0.3

### UniFi Protect Controller Version

4.0.21

### Describe the problem

After enabling encoding enhanced under Recording Mode of the xameda, streaming is broken. 

### Homebridge HBUP JSON configuration

```json
.
```

### Relevant log output

```shell
.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
No support is given for anything that is not GA. You had to click to acknowledge that you weren't running anything that was not GA. Please be respectful of how I provide support and be polite.
