### ISSUE TITLE
Provide a seperate switch to control Status LED

### ISSUE THREAD

**Issue by agodinij** [hjdhjd/homebridge-unifi-protect#1080]
### Describe the feature request

The feature would allow you to expose the Status LED beyond having it as part of the accessory but as a separate switch.   This switch would then allow you to control that status LED.  The problem I’m trying to solve is that ability to turn on the Doorbell Status LED at dusk and turn it off at dawn.  There’s no need to have the blue light on during the day.  It get washed out anyway.

### Describe the proposed solution

Provide a separate switch to all for HomeKit automation control of the Status LED.

### Describe alternatives you have considered to the enhancement

I’ve tried via Hubitat and was unsuccessful because the switch is not exposed.

**Comment by hjdhjd** [comment]
Thanks for the request, I'll consider it for a future release.
