### ISSUE TITLE
Verify - Protect Login not working

### ISSUE THREAD

**Issue by never4ever24** [hjdhjd/homebridge-unifi-protect#1081]
### Homebridge UniFi Protect Version

Protect 4.0.21

### Homebridge Platform and OS

v6.22.0

### Homebridge Version

1.8.2

### Node Version

v6.22.0

### UniFi OS Version

Protect 4.0.21

### UniFi Protect Controller Version

Protect 4.0.21

### Describe the problem

verify sign-in request appears, but HomeBridge still can't log in and doesn't show the camera view in the HOME app

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "892.368.O.2",
            "password": "kifho4-Xokfan-xyfaaf",
            "username": "AB-CDpuh"
        }
    ],
    "name": "UniFi Protect",
    "options": [
        "Enable.Device.Standalone.68D79A8F739B",
        "Enable.Device.SyncName.68D79A8F739B",
        "Enable.Device.Standalone.68D79AE2EB53",
        "Enable.Device.SyncName.68D79AE2EB53",
        "Enable.Device.Standalone.74ACB9002C2F",
        "Enable.Device.SyncName.74ACB9002C2F",
        "Enable.Device.Standalone.D021F9999E58",
        "Enable.Device.SyncName.D021F9999E58"
    ],
    "_bridge": {
        "username": "0E:1E:C9:5B:8A:AE",
        "port": 50554
    },
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
API error: Unable to connect to the Protect controller. This is usually temporary and will occur during Protect controller reboots and firmware updates.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by never4ever24** [comment]
I'm not sure if everything was filled in correctly from my side. Sorry if I missed some information.

**Comment by jimnorrisiv** [comment]
@never4ever24 just letting you know you may have left a valid username and password in your config when you posted that here. I'd remove that! Curious if your issue is because of the new 4.0 update that was released yesterday, I've held off from upgrading until I know this plugin still works!

**Comment by hjdhjd** [comment]
@jimnorrisiv Thanks for trying to help out. As to the new release, I'd suggest going to the Discord. We're discussing it there...but yes, the plugin works fine though there are, as always, some Ubiquiti bugginess in a major firmware release. Don't enable enhanced encoding, though unless you read through the Discord or the pinned issue that's already there. Not going to cover any of that in someone else's issue. Thanks.

**Comment by hjdhjd** [comment]
> I'm not sure if everything was filled in correctly from my side. Sorry if I missed some information.

If by verify sign in you mean you're prompted for two-factor authentication, that is not supported in HBUP. You will need to create a local user on your Protect controller to use HBUP. See the [HBUP prerequisites](https://github.com/hjdhjd/homebridge-unifi-protect?tab=readme-ov-file#prerequisites) for more.

**Comment by ytaf** [comment]
Hi I have a similar issue, where I cant log in to UI Protect after this upgrade, how do we bypass UI Verify passcode?

**Comment by never4ever24** [comment]
Update - Workaround found // 2-way authentication without vacation with local user

Log in to the Homebridge app with the local user who has 2-way authentication enabled.
Then restart the Bridge.
In parallel, log in to the UDM via browser using the local IP.
Use the same user and confirm the login in the Verify popup.
This way, the login attempt of the Bridge and the one via local IP from the same IP range of the computer are confirmed, and Homebridge gained access, even though the login occurred through direct access to the UDM.

**Comment by never4ever24** [comment]
I am not sure if it is a good sign that two-factor authentication can be bypassed so easily, but it works :-)

**Comment by never4ever24** [comment]
> @never4ever24 just letting you know you may have left a valid username and password in your config when you posted that here. I'd remove that! Curious if your issue is because of the new 4.0 update that was released yesterday, I've held off from upgrading until I know this plugin still works!

**Comment by never4ever24** [comment]
@jimnorrisiv thanks for the heads up about US/PW - just change that ;-)
