### ISSUE TITLE
Enhanced Encoding in Protect 4.0 does not work

### ISSUE THREAD

**Issue by Stroell** [hjdhjd/homebridge-unifi-protect#1082]
### Homebridge UniFi Protect Version

6.22.0

### Homebridge Platform and OS

Docker on Synology

### Homebridge Version

v1.8.2

### Node Version

20.12.2

### UniFi OS Version

3.2.12

### UniFi Protect Controller Version

4.0.21

### Describe the problem

Hi,
the latest Unifi Protect Version offers a new Encoding Feature for some Cameras:
https://community.ui.com/releases/UniFi-Protect-Application-4-0-21/6890a055-2a90-4011-a3e6-18f8e290244f
_G4, G5, and AI cameras now support Enhanced Encoding for improved live streaming and recording retention efficiency._

![image](https://github.com/hjdhjd/homebridge-unifi-protect/assets/42348774/af2c8671-a438-4127-8066-490d2416d6ba)

This feature will break the Streaming of my Cameras in HomeKit:
![image](https://github.com/hjdhjd/homebridge-unifi-protect/assets/42348774/2350062f-a265-4330-9696-9267f073abb6)

If you need more logs, please let me know :-) 

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.10.1",
            "mqttUrl": "mqtt://192.168.10.10:1884",
            "password": "",
            "username": ""
        }
    ],
    "name": "UniFi Protect",
    "options": [
        "Enable.Doorbell.Trigger.AC8BA90EC1CF",
        "Enable.Motion.OccupancySensor.AC8BA90EC1CF",
        "Enable.Motion.SmartDetect.ObjectSensors.AC8BA90EC1CF",
        "Enable.Doorbell.Trigger.68D79AE527B1",
        "Disable.Device.68D79AE527B1",
        "Enable.Device.SyncName.F4E2C679401E",
        "Enable.Video.Transcode.Hardware.74ACB91C8719"
    ],
    "verboseFfmpeg": false,
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
[5/28/2024, 2:08:40 PM] [UniFi Protect] G4 Instant [G4 Instant]: The livestream API connection was unexpectedly closed by the Protect controller: this is typically due to device restarts or issues with Protect controller firmware versions, and can be safely ignored. Will retry again shortly.
[G4 Instant] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks for the report. Enhanced encoding is not currently supported.

**Comment by Stroell** [comment]
Thanks for the clarification. It's a great Plugin and with the settings enabled, it works like a charm.  👍 

Maybe something that can be enabled automatically to avoid more github issues? 
=> If enhanced encoding enabled, then transcode. 

Or just add something to the getting started guide?

Cheers from Germany,
Stefan

**Comment by hjdhjd** [comment]
For posterity: HBUP v7+ addresses this holistically. Thanks!
