### ISSUE TITLE
HomeKit Streaming - Camera Not Responding

### ISSUE THREAD

**Issue by bearattack11** [hjdhjd/homebridge-unifi-protect#109]
**Describe The Problem:**

When tapping on the thumbnail preview of the G4 doorbell, the live stream doesn't load and eventually times out with a "Camera is not responding".

**To Reproduce:**

Open the Home app and tap on the thumbnail preview for the G4 doorbell.

**Logs:**

```
[9/28/2020, 14:48:11] [UniFi Protect] [UDM-PRO] UVC G4 Doorbell [UVC G4 Doorbell]: Stopped video streaming session.
(node:891) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:998:90)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:959:16
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at ProtectStreamingDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-unifi-protect2/src/protect-stream.ts:222:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:891) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[9/28/2020, 14:49:20] [UniFi Protect] [UDM-PRO]: Connection refused.
[9/28/2020, 14:49:20] [UniFi Protect] [UDM-PRO] UVC G4 Doorbell [UVC G4 Doorbell]: Unable to retrieve snapshot.
```

**Homebridge Configuration:**

```json
"controllers": [
       		{
        		"address": "192.168.1.1",
      			"password": "[username]",
   			"username": "[password]"
      		}
        ],
            "options": [
                "Enable.StreamOnly.Low"
            ],
            "platform": "UniFi Protect"
        },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.1.1
* **Node Version:** v12.18.2
* **Homebridge-UniFi-Protect Plugin Version:** v3.6.3
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 11 Pro iOS 14
* **Operating System and OS Version:** Raspian Homebridge

**Comment by hjdhjd** [comment]
Thanks for reporting the issue. You’re running an old version of Homebridge and of this plugin. Please update to the latest version of both.

As stated in the [Changelog](https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Changelog.md#360-2020-09-04) - version 3.6.0 and beyond **require** Homebridge 1.1.3 or greater.

There are important changes in Homebridge and this plugin takes advantage of them and is incompatible with earlier versions. If you want to run an earlier version of the plugin instead, downgrade to a release before v3.6.0.

Best of luck!
