### ISSUE TITLE
Streaming video hangs frequently after plugin and protect update

### ISSUE THREAD

**Issue by danjurgens** [hjdhjd/homebridge-unifi-protect#1095]
### Homebridge UniFi Protect Version

v7.1.2

### Homebridge Platform and OS

IoS 17

### Homebridge Version

Homebridge v1.8.3 · UI v4.56.4 ·

### Node Version

v20.15.0

### UniFi OS Version

3.2.9

### UniFi Protect Controller Version

4.0.33

### Describe the problem

Frequent hangs in the streaming video in apple home app. Requires closing and reopening the camera. I see this error in the logs:
Dax Cam [G3 Instant]: The FFmpeg process ended unexpectedly due to issues with the media stream provided by the UniFi Protect livestream API. Adjusting the settings we use for FFmpeg temporarily to use safer values at the expense of some additional streaming startup latency.

Issue started after I updated the plugin, and then updated protect after the plugin said it was was required.

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.10.1",
            "password": "",
            "refreshInterval": 30,
            "username": "homebridge"
        }
    ],
    "motionDuration": 20,
    "platform": "UniFi Protect",
    "options": [
        "Disable.Audio.TwoWay.70A741AD338B",
        "Disable.Audio.TwoWay.D021F9984111",
        "Disable.Audio.TwoWay"
    ]
}
```

### Relevant log output

```shell
Dax Cam [G3 Instant]: The FFmpeg process ended unexpectedly due to issues with the media stream provided by the UniFi Protect livestream API. Adjusting the settings we use for FFmpeg temporarily to use safer values at the expense of some additional streaming startup latency.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by danjurgens** [comment]
Sorry, its the homebridge raspberry pi image on a pi4. I don't know what
exact version of the image it was, but i regularly apt upgrade.

**Comment by beslergr** [comment]
Experiencing the same, with Unifi G4 Doorbell Pro. Plugin installed via Homebridge on a Synology DS920+. Was working fine until 7.1.2.

I think this actually might be a Unifi issue, however, as restarting my Console cleared it right up. Giving info in case it's needed.

Homebridge version 1.8.3
Homebridge UI 4.56.4
Node 20.9.0
UniFi OS 3.2.12
Unifi Protect 4.0.33

JSON config
`{
    "controllers": [
        {
            "address": "###",
            "password": "###!",
            "username": "###"
        }
    ],
    "name": "UniFi Protect",
    "options": [
        "Enable.Log.HKSV.70A741934B5D",
        "Enable.Video.Transcode.Hardware.70A741934B5D",
        "Enable.Video.Stream.Only.Medium.70A741934B5D"
    ],
    "ringDelay": 0,
    "platform": "UniFi Protect",
    "_bridge": {
        "username": "0E:EF:41:57:9F:AD",
        "port": 34094
    }
}`

Warnings read as:

[7/1/2024, 10:50:20 PM] [UniFi Protect] G4 Doorbell Pro Package Camera [G4 Doorbell Pro]: Unable to retrieve a snapshot: using the most recent cached snapshot instead.
[7/1/2024, 10:50:26 PM] [UniFi Protect] G4 Doorbell Pro [G4 Doorbell Pro]: Unable to retrieve a snapshot: using the most recent cached snapshot instead.

**Comment by hjdhjd** [comment]
@beslergr If you’d like support, please open a separate issue. My policy is one person, one issue. Just because it looks similar doesn’t mean it is. :smile: This is another user’s support request. Thanks for respecting the way I prefer to provide support.

**Comment by hjdhjd** [comment]
> Sorry, its the homebridge raspberry pi image on a pi4. I don't know what exact version of the image it was, but i regularly apt upgrade.
> […](#)

Thanks for clarifying. How’s the camera’s WiFi connectivity and what’re you using for a Protect controller? Also, are you using HomeKit Secure Video as well?

**Comment by beslergr** [comment]
@hjdhjd apologies.

**Comment by danjurgens** [comment]
Camera connection is solid, everything is fine in the protect app. I’ve
using this setup for more than a year. The issue started with the update.
Enabling the experimental API seems to have solved the problem.
