### ISSUE TITLE
Update Status Light based on recording setting

### ISSUE THREAD

**Issue by kevinwestby** [hjdhjd/homebridge-unifi-protect#1096]
### Describe the feature request

Would be great if the camera status light was updated to be On if recording or live streaming is enabled.  If recording and live streaming is disabled, turn the camera status light off.

### Describe the proposed solution

Would be great if the camera status light was updated to be On if recording or live streaming is enabled.  If recording and live streaming is disabled, turn the camera status light off.

### Describe alternatives you have considered to the enhancement

I have put smart plugs on each camera (G4 Instant's) and am just powering them down when anyone arrives home.  When everyone leaves, the smart plugs are powered back on.

**Comment by hjdhjd** [comment]
This has been implemented in v7.2.0. There are two ways to do this now:

1. There’s a feature option available under the HKSV settings that will turn on/off the status indicator light when an HKSV event is being recorded.
2. There’s a feature option available under the Devices settings that activates an automation switch to let you directly control the status indicator light. If your hope is to automatically use this to show when the Protect controller itself is recording, you can further enable the camera recording automation switches (under NVR settings) and build a HomeKit automation using the state of the NVR recording mode to indicate recordings (or not).

Enjoy!
