### ISSUE TITLE
Unify 2FA creates a problem error code 499

### ISSUE THREAD

**Issue by MarceljjVonk** [hjdhjd/homebridge-unifi-protect#1097]
### Homebridge UniFi Protect Version

7.1.2

### Homebridge Platform and OS

Raspberry

### Homebridge Version

1.8.3

### Node Version

20.9.0

### UniFi OS Version

4.0.33

### UniFi Protect Controller Version

Unknown

### Describe the problem

Since Unify introduced 2FA the plugin does not work anymore

### Homebridge HBUP JSON configuration

```json
.
```

### Relevant log output

```shell
.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Please read the documentation as well as prior issues.
