### ISSUE TITLE
change buzzer sound

### ISSUE THREAD

**Issue by timmyBirds** [hjdhjd/homebridge-unifi-protect#1102]
### Describe the feature request

This plugin is great!  I was looking to see if I could change the tone of the chime buzzer button to be something shorter so I could tie the button into an automation to have the speaker alert whenever someone opens a door.

### Describe the proposed solution

ability to add custom sounds for the two buttons for the chime speaker.

### Describe alternatives you have considered to the enhancement

I could get another speaker, but was hoping to use the doorbell speaker and the existing buttons in the plugin.

**Comment by hjdhjd** [comment]
No plans to add this at this time, but might consider it for the future. Thanks.
