### ISSUE TITLE
Ambient Light Sensor

### ISSUE THREAD

**Issue by drewcovi** [hjdhjd/homebridge-unifi-protect#1105]
### Describe the feature request

Seems we may have ambient light levels provided via mqtt, any reason we couldn’t consider the same for HomeKit sensors generally? This would enable automations when light levels dip unexpectedly. 

### Describe the proposed solution

Surface an option to enable ambient light sensor for a given room based on same data fed into mqtt. 

### Describe alternatives you have considered to the enhancement

No alternatives I can think of aside from getting dedicated light sensors.

**Comment by hjdhjd** [comment]
Already a planned feature in an upcoming release.

**Comment by hjdhjd** [comment]
In v7.2.0. Enjoy.
