### ISSUE TITLE
This version of HBUP requires running UniFi Protect v4.0 or above.

### ISSUE THREAD

**Issue by Fish2** [hjdhjd/homebridge-unifi-protect#1107]
### Homebridge UniFi Protect Version

V7.12

### Homebridge Platform and OS

Unraid contaner 

### Homebridge Version

V1.8.4

### Node Version

V20.17.0

### UniFi OS Version

V4.0.19

### UniFi Protect Controller Version

V5.0.20

### Describe the problem

after updating to V5.0.20 protect I get this error 

This version of HBUP requires running UniFi Protect v4.0 or above.

### Homebridge HBUP JSON configuration

```json
{
            "controllers": [
                {
                    "address": "************",
                    "password": "************",
                    "username": "**************"
                }
            ],
            "name": "UniFi Protect",
            "options": [
                "Disable.Log.Doorbell",
                "Disable.Log.HKSV",
                "Enable.Video.Stream.UseApi",
                "Disable.Video.Transcode",
                "Disable.Video.Transcode.HighLatency",
                "Disable.Doorbell.Messages",
                "Enable.Video.HKSV.Record.Only.Medium"
            ],
            "_bridge": {
                "username": "***********",
                "port": ***********
            },
            "platform": "UniFi Protect"
        }
    ]
```

### Relevant log output

```shell
This version of HBUP requires running UniFi Protect v4.0 or above.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
You are running early release software, contrary to what you indicated in this issue. I provide no support of any kind for anything that isn't GA, as documented.

**Comment by Fish2** [comment]
I get that and don't mind if it has issues but to just not let it continue to run is a little harsh would only need an edit to run with 5. but with a warning message saying not supported don't contact for issues of even a override setting 

`if(!this.ufp.version.startsWith("4.")) {

      this.log.error("This version of HBUP requires running UniFi Protect v4.0 or above.");
      this.ufpApi.logout();

      return;
    }`

**Comment by hjdhjd** [comment]
That's because there is no support for anything that isn't GA. Please do not open issues, and thereby request support, for things that are explicitly unsupported. 😄 Please respect the rules.

Life in EA with HBUP is all on you...and I have no particular plans to make it easier as time goes by.

**Comment by madmax** [comment]
For now You can open terminal in homebridge and type

nano /var/lib/homebridge/node_modules/homebridge-unifi-protect/dist/protect-nvr.js (or you can install vim)

find this problematic line 

```
if (!this.ufp.version.startsWith("4.")) { 
```


Change 4. to 5. and it will work again. 

```
if (!this.ufp.version.startsWith("5.")) {
```
