### ISSUE TITLE
Motion Report based on "Configure Zones names" for automation

### ISSUE THREAD

**Issue by marsbars-marsbars** [hjdhjd/homebridge-unifi-protect#1108]
### Describe the feature request

Unless I have not found the configuration, the operation today only shows ' motion ' reported from a camera or device regardless of one or more motion zones are configured.   However, in UI Protect, you can define multiple ' motion zones' - multiple zones are beneficial depending on what your trying to capture and do. 

Solutions in Play:  Unifi Protect, HomeBridge w/ "Homebridge Abode Lights" & "HomeBridge Unifi Connect" - Abode Security System w/ Zwave controlled lights 

### Describe the proposed solution

Problem:  My car in the drive way gets approached frequently in the middle of the night with people tugging on the door handles to see if they can get in and swipe anything of value.   I'd like create a zone around my car that when motion is sensed by the UI camera, its passed to hombridge to pass to abode to turn on the driveway lights.  

Technically, I can do this today, IF I eliminate my other motion zones - but then I lose a lot of good meta data around people, vehicles, animals, etc.   Which is something we use a great deal. 

### Describe alternatives you have considered to the enhancement

Installing another camera w/ only one purpose, which would be to motion sense around my car and only that area.   Which would be a redundant camera, but it could be done.

**Comment by hjdhjd** [comment]
Thanks for the request. Zone names aren't communicated in the Protect API currently I'm afraid which means I can't do much with the zones, as it were. This request has come up previously as well. I'll continue to evaluate it as the API evolves.

Thanks again.
