### ISSUE TITLE
Unifi Protect v4.0 or above

### ISSUE THREAD

**Issue by herbi3** [hjdhjd/homebridge-unifi-protect#1110]
### Homebridge UniFi Protect Version

v7.1.2

### Homebridge Platform and OS

Ubuntu Focal (20.04.6 LTS)

### Homebridge Version

v1.8.4

### Node Version

v20.17.0

### UniFi OS Version

v4.0.18

### UniFi Protect Controller Version

v5.0.21

### Describe the problem

Security Recorder [UNVR4]: This version of HBUP requires running UniFi Protect v4.0 or above.

I am running Protect version v4.0 or above, the plugin doesn't attempt to start at all, despite being above the version required.

With HBUP already running, I updated unifi protect. the plugin continued to work as normal, right until a home bridge restart. so I can confirm the plugin does work on this higher version as normal. it just wont start with this higher version.

yes, it is beta. yes I understand you don't support it. but it seems a little harsh to just not allow the plugin to run if it doesnt match a version exactly (although, still meeting the requirements since I am running a version above 4.0...)

### Homebridge HBUP JSON configuration

```json
no issue with config.
```

### Relevant log output

```shell
Security Recorder [UNVR4]: This version of HBUP requires running UniFi Protect v4.0 or above.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by herbi3** [comment]
<img width="889" alt="Screenshot 2024-09-13 at 10 34 53 am" src="https://github.com/user-attachments/assets/8b28cca4-5c67-4395-acbf-02ac024d5ea1">
temp fix.

**Comment by hjdhjd** [comment]
Kindly don’t violate the rules of the road with respect to issues.
