### ISSUE TITLE
Remove Motion Sensor service for Cameras

### ISSUE THREAD

**Issue by shivanathd** [hjdhjd/homebridge-unifi-protect#1111]
### Describe the feature request

I want the ability to remove the motion sensor service. I have around 50+ cameras and my homekit home is quite busy. 

### Describe the proposed solution

i'd love the ability to remove the motion sensor service of a camera as a feature option or at the NVR option as well. This will help remove the motion sensor that is exposed to the homekit. 

### Describe alternatives you have considered to the enhancement

I checked the documentation and was not able to find this feature as by default the motion sensor is exposed per camera. There is option to add a switch to disable the motion sensor activity in the documentation, but with around 150+ devices in the home (along with FP2s, Cameras) etc it would be cleaner to remove the motion sensor service from unifi.

**Comment by hjdhjd** [comment]
Sorry, no intention of implementing this. The motion sensor is pretty fundamental and intentionally cannot be removed. Appreciate the request.
