### ISSUE TITLE
Apple Tv live stream on motion detection not working on version 7.1.2

### ISSUE THREAD

**Issue by gbieber05** [hjdhjd/homebridge-unifi-protect#1113]
### Homebridge UniFi Protect Version

7.1.2

### Homebridge Platform and OS

Ubuntu Noble (24.04.1 LTS)

### Homebridge Version

v1.8.4

### Node Version

v20.17.0

### UniFi OS Version

v4.0.6

### UniFi Protect Controller Version

v4.1.53

### Describe the problem

Once updating to this version the live streaming by motion detection to apple tv's breaks. 

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "redacted",
            "password": "redacted",
            "username": "redacted"
        }
    ],
    "name": "UniFi Protect",
    "options": [
        "Enable.Audio.Filter.Noise.E063DA86BAC8",
        "Enable.Video.Transcode.Hardware.E063DA86BAC8",
        "Enable.Motion.Duration.E063DA014A89.10",
        "Enable.Motion.Duration.E063DA86BAC8.10",
        "Disable.Doorbell.Messages.FromDoorbell.E063DA86BAC8",
        "Enable.Video.Stream.Only.High.E063DA86BAC8"
    ],
    "_bridge": {
        "username": "redacted"
    },
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
logs not showing error
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Unfortunately likely not an HBUP bug...that's just quirkiness in tvOS from time to time. You can try rebooting your ATV and see if it helps, and/or ensuring your HomeKit hub is an ATV. The new iOS release should help with some of that as well next week. TL;DR: not much to do here. I use HBUP with ATV every day...so I'm all too familiar with the quirks unfortunately.

**Comment by gbieber05** [comment]
Thank you for looking into this issue.
