### ISSUE TITLE
Crash of Protect after 7.3.0 update

### ISSUE THREAD

**Issue by VelvetMorsels** [hjdhjd/homebridge-unifi-protect#1114]
### Describe the feature request

After updating to 7.3.0 my protect plugin crashed I cannot get any accessories or hubs to respond. I try to remove the plugin and it will not let me. I have attached a screenshot of the errors.
![IMG_0658](https://github.com/user-attachments/assets/7ea6501e-3692-4be4-9476-7ed7728eb920)

### Describe the proposed solution

Na

### Describe alternatives you have considered to the enhancement

Na

**Comment by hjdhjd** [comment]
This isn’t an enhancement request…try completely uninstalling HBUP from within the Homebridge webUI and then reinstall it. Seems to be a problem on the Homebridge side, you might want to check with the team there if uninstall/reinstall doesn’t work. Not much I can do beyond point you to manually uninstalling and reinstalling the plugin I’m afraid.

Hope this helps.
