### ISSUE TITLE
Override support for EA UniFi Protect versions

### ISSUE THREAD

**Issue by Qonstrukt** [hjdhjd/homebridge-unifi-protect#1115]
### Describe the feature request

I do get that you don't want to provide support for people running EA UniFi Protect versions. (I would be in the exact same boat.) But blocking it on startup with no possible override seems a bit harsh. I build software against UniFi Protect as well, so I do upgrade to EA versions early and test stuff. I then wholeheartedly accept things not working with this plugin for example, but now you make it completely impossible to even try. 😅 

I mean, if things broke with your plugin I would quickly downgrade anyway. But now I have to, even if it works as intended. This has often been the case for me with 3.x and 4.x versions.

### Describe the proposed solution

Can you maybe add a (hidden, undocumented even) setting to override this detection and help a developer colleague out? I looked through the source to find it doesn't exist right now (or a version spoof in `unifi-protect`).

Maybe you've already tested this with version 5.x and found it broke everything... There are multiple reasons I can think of why you blocked it this way, so if you're not into this, all well and good. 😊

### Describe alternatives you have considered to the enhancement

I'll fork your plugin, or downgrade in between development, that's fine, but it'll cost me more work and time of course.
I also like to stay up to date with your plugin, given how much work you put into this quality piece of work. ❤️

**Comment by herbi3** [comment]
I raised this issue and provided a solution too, but looks like the author deleted it to prevent others from overriding it?![image](https://github.com/user-attachments/assets/62f76c23-e5cf-45ab-a1bc-e3f0c8141145)![image](https://github.com/user-attachments/assets/6f855531-648b-4cef-94f6-c02d91861560)

**Comment by herbi3** [comment]
Also @Qonstrukt, it works perfectly fine on the latest EA

**Comment by Qonstrukt** [comment]
> I raised this issue and provided a solution too, but looks like the author deleted it to prevent others from overriding it? Or maybe I just can't find it, opened the issue a few days ago.
> 
> This is what I do to get around it. Ultimately, it doesn't support version 4 and above, it only supports versions that start with 4. Little misleading for those wanting to try the beta software, fully accepting that if the plugin doesn't work, well that's on us.
> 
> Love the great work for this plugin otherwise!
> 
> ![image](https://private-user-images.githubusercontent.com/11141749/368460939-62f76c23-e5cf-45ab-a1bc-e3f0c8141145.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDY3MTUsIm5iZiI6MTcyNjY0NjQxNSwicGF0aCI6Ii8xMTE0MTc0OS8zNjg0NjA5MzktNjJmNzZjMjMtZTVjZi00NWFiLWExYmMtZTNmMGM4MTQxMTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA4MDAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNjQxODg5M2RlMTMyZGQyNDE4YjQ0MDY5NzI2OWQzNGFjNWU2M2RmYzM2YzBmZmJlZWNlMjM4YWYyMjI2MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wCQtVjphwSZ9kV7iT_w8uUTBp4bWTujLbpcuaHtK-ps)![image](https://private-user-images.githubusercontent.com/11141749/368460961-6f855531-648b-4cef-94f6-c02d91861560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDY3MTUsIm5iZiI6MTcyNjY0NjQxNSwicGF0aCI6Ii8xMTE0MTc0OS8zNjg0NjA5NjEtNmY4NTU1MzEtNjQ4Yi00Y2VmLTk0ZjYtYzAyZDkxODYxNTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA4MDAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZTMwNmNhNjM2YmVlZTM3MWYyMDQzNjcwNTdjYmY3ZjRkOTNmODkzZTQ5ODA5NzlmMzJiZWUxY2RkZDYyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.90yHzJ_ZfhVUzAF8g0TeZ757LbQCODck3_OLr-ka-0M)

Yeah I figured I could make a fork and PR a Setting in, but also that there's a big chance @hjdhjd will reject it, which is totally fine of course. But that made me choose to downgrade for now. Running my own version feels a bit counterproductive. I would only do it until v5 is GA, and then when v6 drops I would maybe have to start over again if this plugin changed a lot in the meantime.

**Comment by hjdhjd** [comment]
While I appreciate the request, I have no intentions of doing so.

Non-GA releases are explicitly unsupported - and documented as such - for a reason.
