### ISSUE TITLE
Recent 7.3.x update blocks EA-users that rely on HomeKit streams (unofficial end-user fix included)

### ISSUE THREAD

**Issue by travisnerd** [hjdhjd/homebridge-unifi-protect#1117]
### Describe the feature request

Per the 7.3.x update, developer has decided not to support non-official releases of UNVR Protect consoles, preventing HomeBridge from passing streams to HomeKit. While I concur that this plugin should only cater to official UI release channels, I also believe that hard-coding such a limitation in that the plugin self-deactivates was done hastily. (Note: it works fine under EA 5.0.32)

### Describe the proposed solution

Developer should consider implementing a bypass that can be added in the configuration for end-users to bypass at their own risk, with a clear message that developer will not address bugs encountered when this bypass is enabled.

### Describe alternatives you have considered to the enhancement

Should you, fellow end-user, find yourself in the same boat, look around line 99 in ./node_modules/homebridge-unifi-protect/dist/protect-nvr.js for IF statement block to comment out.

**Comment by herbi3** [comment]
@travisnerd I've posted a couple fixes here to also bypass this, ultimately the dev deletes the comments and images so others can't fix it themselves. This exact same issue has been raised many, many times. To which, anything with a fix is deleted and others are ignored and closed. Great plugin, great work, but overall the dev has some minor ego issues to work through.

**Comment by hjdhjd** [comment]
Duplicate that's already been addressed numerous times.
