### ISSUE TITLE
I think not yet 2.o ready

### ISSUE THREAD

**Issue by jdegouw** [hjdhjd/homebridge-unifi-protect#1119]
### Describe the feature request

Please upgrade the app so it will be Homebrdige 2.o ready.
I think the old VideoCodec is still used

### Describe the proposed solution

Replace VideoCodec with H264CodecParameters

### Describe alternatives you have considered to the enhancement

Please review all code and resolve the breaking changes. (I think only the H264CodecParameters is the problem but only a hobby programmer)

**Comment by hjdhjd** [comment]
Thanks for the request!

I’m one of the developers of Homebridge 2.0 and one of the maintainers of Homebridge. So…yes, all of my plugins will be 2.0 ready once we release Homebridge 2.0.

Please do not submit requests for support of beta software, including Homebridge, as they are explicitly unsupported by HBUP (and all of my plugins).
