### ISSUE TITLE
Getting Deprecation Warning in Homebridge

### ISSUE THREAD

**Issue by spaceg00se-r** [hjdhjd/homebridge-unifi-protect#1126]
### Homebridge UniFi Protect Version

v7.5.1

### Homebridge Platform and OS

Raspberry Pi

### Homebridge Version

v1.8.4

### Node Version

v20.17.0

### UniFi OS Version

 4.0.6

### UniFi Protect Controller Version

4.1.53

### Describe the problem

I'm getting the following warning in Homebridge. 

[homebridge-unifi-protect] (node:7477) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)

Are you aware of this? Is there a way to circumvent this?

### Homebridge HBUP JSON configuration

```json
Not required
```

### Relevant log output

```shell
[homebridge-unifi-protect] (node:7477) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Duplicate. Please review prior issues before opening new ones. #977
