### ISSUE TITLE
Same camera type with same config (HBUP and Protect) choose different streams

### ISSUE THREAD

**Issue by vfrans** [hjdhjd/homebridge-unifi-protect#1128]
### Homebridge UniFi Protect Version

v7.5.1

### Homebridge Platform and OS

Debian 12 (LXC with hwaccel running natively (no docker on top of lxc) hwaccel validated working with vainfo under the homebridge user)

### Homebridge Version

v1.8.4

### Node Version

v20.17.0

### UniFi OS Version

4.0.18

### UniFi Protect Controller Version

5.0.34

### Describe the problem

Hello,

I have two camera types; G4 Bullet and G3 Flex.

I have a camera called "Camera carport" and another one "Camera jardin haut" both are G4 Bullet configured the same (I double checked in the unifi configuration for image quality and so on, same on both)

They are are also configured the same way in HBUP.

However, when I stream those cameras behavior is very different.

Camera carport loads in under a second, flawless but the other one buffer for 2-3 seconds and starts with a grey background that only turn to image after another 2-3 seconds. Only difference I can see is the stream that HBUP chooses as source before transcode as you can see in the following logs:
```
[9/28/2024, 7:34:30 AM] [UniFi Protect] Camera carport [G4 Bullet]: Streaming request from XXXX: 1280x720@30fps, 2,000 kbps. Transcoding 1920x1080@48fps (High) [HEVC], 10,000 kbps [API].
[9/28/2024, 7:34:35 AM] [UniFi Protect] Camera carport [G4 Bullet]: Stopped video streaming session.
[9/28/2024, 7:34:35 AM] [UniFi Protect] Camera jardin haut [G4 Bullet]: Streaming request from XXXX: 1280x720@30fps, 1,500 kbps. Transcoding 1280x720@24fps (Medium) [HEVC], 1,500 kbps [API].
[9/28/2024, 7:34:43 AM] [UniFi Protect] Camera jardin haut [G4 Bullet]: Stopped video streaming session.
```

I could force the setting in the camera itself to use the High stream but I don't understand this behavior.

How is the stream chosen? How can I get to debug that issue (my issue is of course mostly that second camera load a lot slower of course :) )

Thanks a lot in advance for any help or pointer :)

### Homebridge HBUP JSON configuration

```json
{
    "name": "UniFi Protect",
    "controllers": [
        {
            "address": "XXXX",
            "username": "homebridgeprotectusername",
            "password": "thisismypassword"
        }
    ],
    "platform": "UniFi Protect",
    "options": [
        "Enable.Log.HKSV.D021F975398F",
        "Enable.Log.Motion.D021F975398F",
        "Enable.Device.Standalone.D021F975398F",
        "Enable.Video.Transcode.Hardware.D021F975398F",
        "Enable.Video.Transcode.Bitrate.D021F975398F.2000"
    ]
}
```

### Relevant log output

```shell
[9/28/2024, 7:34:30 AM] [UniFi Protect] Camera carport [G4 Bullet]: Streaming request from 192.168.139.101: 1280x720@30fps, 2,000 kbps. Transcoding 1920x1080@48fps (High) [HEVC], 10,000 kbps [API].
[9/28/2024, 7:34:35 AM] [UniFi Protect] Camera carport [G4 Bullet]: Stopped video streaming session.
[9/28/2024, 7:34:35 AM] [UniFi Protect] Camera jardin haut [G4 Bullet]: Streaming request from 192.168.139.101: 1280x720@30fps, 1,500 kbps. Transcoding 1280x720@24fps (Medium) [HEVC], 1,500 kbps [API].
[9/28/2024, 7:34:43 AM] [UniFi Protect] Camera jardin haut [G4 Bullet]: Stopped video streaming session.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
This is absolutely expected and correct behavior.

https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/Autoconfiguration.md#how-hbup-stream-quality-selectionion-works-when-transcding

**Comment by hjdhjd** [comment]
One more thing…you do not have hardware accelerated transcoding enabled as far as HBUP is concerned. If you did, you’d see a message like: 

```
Hardware accelerated transcoding 3840x2160@30fps (High) [HEVC], 16,000 kbps [API].
```

When streaming. HBUP’s very particular/specific about hardware transcoding and **only** supports macOS and Intel’s QSV. I have zero plans to support anything further.

**Comment by vfrans** [comment]
Thank you so much for the clear explanation.

I can't help but try to understand why HBUP select a different stream for that specific camera but not the others but at least I know it's normal and expected 😁

Thanks a lot also for the clear explanation on the hw acceleration, I know now that, for some reasons my gpu acceleration is not working.

However I fail to get an output or an error that explains why it does not work.

GPU acceleration works in different LXC containers on the same host with the same config (running jellyfin, Plex,...) but not with HBUP.

Sorry to ask this on a closed issue and I can certainly open a new issue for this but do you know how I can troubleshoot the gpu acceleration? I know it's not supported (or at least I think I read it somewhere) but if you would have some pointers on how to troubleshoot that issue that would be super helpful for me 😅

Just to be clear my GPU is a 13th gen QSV hardware.

Thanks a lot for your help in any case!

Best,
