### ISSUE TITLE
Volume control of the chime in the new version of protect

### ISSUE THREAD

**Issue by juhuan-nor** [hjdhjd/homebridge-unifi-protect#1129]
### Describe the feature request

Volume control changes are now controlled by doorbell.The old version of the volume control is completely broken

### Describe the proposed solution

Maybe there is a new way to control the volume of the chime?

### Describe alternatives you have considered to the enhancement

no

**Comment by hjdhjd** [comment]
I’ll look into it this weekend. Thanks for the heads up.

**Comment by hjdhjd** [comment]
Addressed in v7.6.0. Thanks!
