### ISSUE TITLE
Viewport Control Not Working

### ISSUE THREAD

**Issue by enagel** [hjdhjd/homebridge-unifi-protect#1130]
### Homebridge UniFi Protect Version

7.6.0

### Homebridge Platform and OS

Docker - Ubuntu Focal (20.04.5 LTS)

### Homebridge Version

1.8.2

### Node Version

20.13.1

### UniFi OS Version

4.0.18

### UniFi Protect Controller Version

5.0.34

### Describe the problem

Viewport control has stopped working. The error message below is displayed.

[9/29/2024, 9:54:47 PM] [homebridge-unifi-protect] Viewport Office [UP Viewport]: Unable to set the liveview to: Monitor.

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": ""redacted"",
            "password": ""redacted"",
            "username": "redacted"
        }
    ],
    "options": [
        "Enable.Doorbell.Trigger"
    ],
    "platform": "UniFi Protect",
    "_bridge": {
        "username": "0E:F5:7A:36:C6:34",
        "port": 47746
    }
}
```

### Relevant log output

```shell
[9/29/2024, 9:54:47 PM] [homebridge-unifi-protect] Viewport Office [UP Viewport]: Unable to set the liveview to: Monitor.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks for the report. Does this work currently in a prior version of HBUP?

**Comment by enagel** [comment]
> Thanks for the report. Does this work currently in a prior version of HBUP?

I believe it stopped working after upgrading UniFi protect. I upgraded HBUP to 7.6.0 to see if it would address the issue but it did not.

**Comment by hjdhjd** [comment]
I just tried the Viewport myself - works fine in HBUP. If you have a reproducible issue, happy to look into it, but from my testing, Viewports work correctly in HBUP v7.6.0.

You said "it stopped working" - that's not especially precise. Can you be very specific about what it is or isn't doing, and what the behavior is that you expected?

**Comment by enagel** [comment]
> I just tried the Viewport myself - works fine in HBUP. If you have a reproducible issue, happy to look into it, but from my testing, Viewports work correctly in HBUP v7.6.0.
> 
> You said "it stopped working" - that's not especially precise. Can you be very specific about what it is or isn't doing, and what the behavior is that you expected?

I appreciate you testing this. The error I was seeing: _[9/29/2024, 9:54:47 PM] [homebridge-unifi-protect] Viewport Office [UP Viewport]: Unable to set the liveview to: Monitor._ did not help me much so I started here. I just did some additional digging after seeing your message and it appears the user/role I have assigned to HBUP lost the appropriate permissions (no changes on my end). The user could still access and view cameras, but could not control the viewports. I assume this is as a result of one of the UniFiOS or Protect updates.

**Comment by hjdhjd** [comment]
There's always some permission issue these days it seems. You might want to try to completely delete the local user and recreate it and see if that solves the issue. If you didn't restart HBUP after changing permissions, you might want to do that prior to recreating the user, to see if you can avoid the step. In either case - I think that's the root cause here, unfortunately.
