### ISSUE TITLE
Following update to 7.8.0 ffmpeg no longer works

### ISSUE THREAD

**Issue by booshtukka** [hjdhjd/homebridge-unifi-protect#1136]
### Homebridge UniFi Protect Version

7.8.0

### Homebridge Platform and OS

macOS Sequoia

### Homebridge Version

v1.8.4

### Node Version

v20.15.0

### UniFi OS Version

4.0.20

### UniFi Protect Controller Version

5.0.34

### Describe the problem

After updating to 7.8.0 ffmpeg no longer works. It worked immediately before.

I know other have reported this issue in the past and have it marked as not reading the documentation, but the only change was the latest update.

[10/15/2024, 2:45:03 PM] [UniFi Protect] Unable to find 'ffmpeg' in path: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'.
[10/15/2024, 2:45:03 PM] [UniFi Protect] Unable to probe the capabilities of your Homebridge host without access to 'ffmpeg'. Ensure that it is available in your path and correctly working.

### Homebridge HBUP JSON configuration

```json
{
    "controllers": [
        {
            "address": "192.168.0.1",
            "defaultDoorbellMessage": "8 WILDERNESSE CLOSE",
            "password": "Jivtov-byrte0-gejdyq",
            "username": "antony@silversquid.com"
        }
    ],
    "name": "UniFi Protect",
    "options": [
        "Enable.Audio.Filter.Noise.AC8BA9636B49",
        "Enable.Audio.Filter.Noise.E438830C3700",
        "Disable.Doorbell.Messages.AC8BA9636B49",
        "Enable.Video.Transcode.Hardware.AC8BA9636B49",
        "Enable.Log.Motion.AC8BA9636B49"
    ],
    "ringDelay": 0,
    "_bridge": {
        "username": "0E:EA:96:98:A1:13",
        "port": 41855
    },
    "platform": "UniFi Protect"
}
```

### Relevant log output

```shell
[10/15/2024, 2:45:03 PM] [UniFi Protect] Unable to find 'ffmpeg' in path: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'.
[10/15/2024, 2:45:03 PM] [UniFi Protect] Unable to probe the capabilities of your Homebridge host without access to 'ffmpeg'. Ensure that it is available in your path and correctly working.
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by booshtukka** [comment]
Downgrading to v7.7.1 fixed the issue

**Comment by hjdhjd** [comment]
Retry your update to v7.8.0 - this isn't really an HBUP issue, though I understand it feels that way. The issue is in one of the HBUP dependencies that may struggle to correctly install itself if you happen to catch the Internet at a moment when it's being fickle.

**Comment by booshtukka** [comment]
I did try again, same issue. Downgrading fixed it again. Updating the machine to 15.0.1 and will restart, then report back.

**Comment by booshtukka** [comment]
That did it! Not sure if it was the reboot or the update. Thanks for the help.
