### ISSUE TITLE
No ring-message since v7.8.2 and Unifi Protect 5.0.50

### ISSUE THREAD

**Issue by makabar** [hjdhjd/homebridge-unifi-protect#1140]
### Homebridge UniFi Protect Version

7.8.2

### Homebridge Platform and OS

Ios 18.1

### Homebridge Version

1.8.5

### Node Version

22.10

### UniFi OS Version

4.1.5

### UniFi Protect Controller Version

5.0.50

### Describe the problem

Hello there, got a strange problem here. Since a couple of days I get no alarm/message while ringing my doorbell G4. Updatet to latest node and homebridge versions. Reinstalled the plugin. Configured it as childbridge and added devices again. Also configured a new local admin with local access only. But no success. Did unifi changed anything? Streaming video/audio are still working fine

### Homebridge HBUP JSON configuration

```json
In next post
```

### Relevant log output

```shell
Sorry - no log
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Thanks for the report, but as you know, I provide no support for anything other than current production releases of UniFi Protect. Please do not open issues that ignore the parameters I’ve clearly documented. It’s not cool.

**Comment by makabar** [comment]
You are absolutely right. But just for information:
Downgraded to unifi-protect 5.0.34!
Works fine again
