### ISSUE TITLE
Support for G4 Doorbell Pro Fingerprint & NFC Card automations

### ISSUE THREAD

**Issue by guysbrown** [hjdhjd/homebridge-unifi-protect#1142]
### Describe the feature request

The early access version of Protect 5.1.34 has added support for NFC and Fingerprint on the G4 Doorbell Pro. It would be great to add support for the events triggered by using fingerprints and NFC cards to run automation in HomeKit, such as unlocking HomeKit-supported locks.

### Describe the proposed solution

I believe that the integration could/would utilize the webhook feature in the Alarm Manager in Protect to fire an event when a fingerprint or NFC card is used. homebridge-unifi-protect could host the webhook and trigger events/accessories when fired by the doorbell. However, there may be a better solution. 

### Describe alternatives you have considered to the enhancement

None

**Comment by hjdhjd** [comment]
Please do not open feature requests regarding EA firmware. As always, HBUP looks to implement capabilities that I feel make sense in a HomeKit context. Beyond that, I have nothing to add.
