### ISSUE TITLE
Unifi Doorbell G4 Pro

### ISSUE THREAD

**Issue by uroopek** [hjdhjd/homebridge-unifi-protect#1147]
### Describe the feature request

Hi, Ubiquiti add fingerprint and NFC in G4 Doorbell, can you add this function ?

### Describe the proposed solution

https://community.ui.com/questions/G4-Doorbell-Pro-Enable-Fingerprint-and-NFC-for-SmartLock/6e2b8d0b-7fc7-4f3d-b720-83533a82d745

### Describe alternatives you have considered to the enhancement

Hi, Ubiquiti add fingerprint and NFC in G4 Doorbell, can you add this function ?

**Comment by hjdhjd** [comment]
It's on the roadmap. Thanks.
