### ISSUE TITLE
Package Cam Streaming Front Door Camera feed.

### ISSUE THREAD

**Issue by subeeshan** [hjdhjd/homebridge-unifi-protect#1148]
### Homebridge UniFi Protect Version

7.8.2

### Homebridge Platform and OS

Container

### Homebridge Version

v1.8.5

### Node Version

V22.11.10

### UniFi OS Version

UniFi OS 4.0.20

### UniFi Protect Controller Version

UniFi Protect Application 5.1.57

### Describe the problem

Since i updated the protect to 5.1, the package cam streams the same feed as the front door camera. 

### Homebridge HBUP JSON configuration

```json
"name": "UniFi Protect",
            "platform": "UniFi Protect",
            "_bridge": {
                "username": "",
                "port": 45083
            },
            "options": [
                "Enable.Video.HKSV.Record.Only.High.F4E2C673C781",
                "Enable.Video.HKSV.Record.Only.High.245A4CA1E375"
            ]
        }
```

### Relevant log output

```shell
NA
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Known issue - this is a Protect API bug. Hopefully Ubiquiti addresses this in a future release. Thanks for raising it. It’s been discussed at length on the Discord.
