### ISSUE TITLE
Since Updating Camera I Now Cannot Stream From It & See Error Below

### ISSUE THREAD

**Issue by Wildcat1** [hjdhjd/homebridge-unifi-protect#115]
**Describe The Problem:**
I had to re-install the G4 Doorbell today and after I did the camera no longer streamed in HomeKit and gave the error below. Worth pointing out camera can be pinged, does show up and stream in native Unifi Protect app just not in HomeKit using your plugin now. 

**To Reproduce:**
Remove old camera from network, re-install and then load into HomeKit Protect

**Logs:**

Command failed with exit code 1: /usr/local/lib/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -rtsp_transport tcp -i  -map 0:v -vcodec copy -f rawvideo -pix_fmt yuvj420p -r 30 -probesize 32 -analyzeduration 0 -fflags nobuffer -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 4027389 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -****** srtp://192.**.**.193:58838?rtcpport=58838&localrtcpport=58838&pkt_size=564 -map 0:a -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 48k -ac 1 -payload_type 110 -ssrc 1232983 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ****** srtp://192.**.**.193:55805?rtcpport=55805&localrtcpport=55805&pkt_size=188
: No such file or directory
```

**Environment:**

* **Homebridge Version:** <!-- homebridge -V --> 1.2.3
* **Node Version:** <!-- node -v --> 12.16.3
* **Homebridge-UniFi-Protect Plugin Version:** 3.7.7
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone running iOS 14
* **Operating System and OS Version:** macOS Catalina

**Comment by hjdhjd** [comment]
The error is in the log file. :smile:

Looks like for whatever reason you don’t have a proper version of FFmpeg installed any longer. I’d recommend uninstalling and reinstalling the plugin. If you use the webUI, it’s straightforward, if doing from the command line:

```
npm -g uninstall homebridge-unifi-protect
npm -g —unsafe-perm install homebridge-unifi-protect
```
Restart Homebridge and give it a whirl.

Thanks!
