### ISSUE TITLE
Alarm on smart detections

### ISSUE THREAD

**Issue by reustmd** [hjdhjd/homebridge-unifi-protect#1150]
### Describe the feature request

Unifi has decent smart detections (e.g., person detected). I would love if I could use these smart detections as a trigger for a homekit home alarm.

I think most of the DIY/off-the-shelf alarm solutions are too onerous. They have door sensors, window sensors, and much more which depending on your home design, might be a lot of devices to maintain and deal with. In my townhome for example, there's multiple windows and doors on the first floor, but instead of like 4 door sensors and 8 window sensors, I prefer having a single camera looking down the stairwell that triggers the alarm if a human is detected.

### Describe the proposed solution

1. Add an alarm switch to the protect system. I'm not sure if this would have to be associated with a device or it'd just be virtual with the bridge or something. But you need to be able to set the alarm to active or inactive.
2. Allow the user to select which cameras and/or type of smart detections (person, vehicle, etc) are relevant to trigger the alarm, if the alarm is active.
3. Actually trigger the alarm based on #2 configuration and smart detections as they come in.

I would expect to configure what happens if the alarm is triggered in homekit using automations/scenes.

### Describe alternatives you have considered to the enhancement

My current alternative is using Aqara G3 cameras for this. Basically I have one of these at each major entryway to my home and if they detect a person while the alarm is active, it sets of the alarm. This integrates well with homekit and works fine, but I'd much rather standardize on protect vs Aqara.

**Comment by hjdhjd** [comment]
Appreciate the request, but I'm unlikely to add this. You can already get person detection within HomeKit via the smart object sensors that you can enable in HBUP. How you choose to act on those is up to you. There are other plugins out there that give you a generic alarm you can tie the HBUP object sensor state to, if that's really the path you want to go down.

**Comment by reustmd** [comment]
Gotcha -- I'll poke around at that alternative path.

**Comment by hjdhjd** [comment]
In general, I'm unlikely to implement something that's bespoke to a small population of folks unless there's a very good use case and there's really no other way to do it (e.g. showing the recording status of an HKSV event via the camera status light). HBUP feature bloat is something I try hard to resist. 😄
