### ISSUE TITLE
2FA Login

### ISSUE THREAD

**Issue by jayyman3** [hjdhjd/homebridge-unifi-protect#1151]
### Describe the feature request

Well UniFi is now requiring 2FA to log into the protect controllers 

### Describe the proposed solution

Placement to enter code

### Describe alternatives you have considered to the enhancement

There are no alternatives

**Comment by hjdhjd** [comment]
Please read the documentation prior to opening requests.

https://github.com/hjdhjd/homebridge-unifi-protect?tab=readme-ov-file#prerequisites
