### ISSUE TITLE
Any chance for USP-PDU-Pro support?

### ISSUE THREAD

**Issue by gknops** [hjdhjd/homebridge-unifi-protect#1153]
### Describe the feature request

Honestly I really just want to get everything into MQTT (outlet status, per outlet power consumption for nice graphs etc) but I could also see advantages making outlets available to HomeKit.

Or separate plugin?

### Describe the proposed solution

Not sure if it fits architecturally into this plugin or if it should be a separate one.

### Describe alternatives you have considered to the enhancement

Have not found any alternatives, happy to hear about any!

**Comment by hjdhjd** [comment]
Zero chance in this plugin. This plugin is strictly for UniFi Protect. Power distribution devices are not part of the Protect ecosystem. Best of luck.

**Comment by gknops** [comment]
Fair enough. Thanks much for your work on the UniFi Protect plugin!
