### ISSUE TITLE
Enable IGPU in the plugin so it uses GPU based CPU

### ISSUE THREAD

**Issue by Barichon21** [hjdhjd/homebridge-unifi-protect#1154]
### Describe the feature request

Would love to use this amazing plugin in a docker so it uses my QNAP 253A Intel iGPU (14 nm Intel® Celeron® N3150/N3160 1.6 GHz quad-core processor)

### Describe the proposed solution

Enable the plugin to use it

### Describe alternatives you have considered to the enhancement

Work with Homebridge developer to make it happen

**Comment by hjdhjd** [comment]
Thanks!

I am one of the Homebridge developers already. :smile:

And...you can already use this plugin with the Homebridge docker image.

What you seem to be asking about is really related to hardware acceleration. You'll need to find your own version of FFmpeg that supports that, or you can hop on the Discord and the community can point you in the right direction. Best of luck!
