### ISSUE TITLE
Show 3rd party cameras from Unifi Protect

### ISSUE THREAD

**Issue by JakubSs** [hjdhjd/homebridge-unifi-protect#1155]
### Describe the feature request

As is described [here](https://help.ui.com/hc/en-us/articles/26301104828439-Third-Party-Cameras-in-UniFi-Protect), Unifi Protect allows to adopt 3rd party cameras , but I cannot see the feed in my ios homekit app. 

### Describe the proposed solution

Show feed in ios homekit app

### Describe alternatives you have considered to the enhancement

n/a

**Comment by hjdhjd** [comment]
I have no plans to do so at this time. I might revisit that in the future, but not for the moment. We'll see how Ubiquiti's support for third party cameras continues to evolve.

Thanks for the request.
