### ISSUE TITLE
Adding new topics for MQTT

### ISSUE THREAD

**Issue by uroopek** [hjdhjd/homebridge-unifi-protect#1156]
### Describe the feature request

Hi, can you add new topics in MQTT like:

Smart: animal, alrmSmoke, alrmCmonx, smokecmonx etc.
Fingerprint: authenticated and etc.

Thanks.

### Describe the proposed solution

Hi, can you add new topics in MQTT like:

Smart: animal, alrmSmoke, alrmCmonx, smokecmonx etc.
Fingerprint: authenticated and etc.

Thanks.

### Describe alternatives you have considered to the enhancement

none

**Comment by hjdhjd** [comment]
No plans to do so. You can already access all this via MQTT using the telemetry feature option. I will not be adding “custom requests” for MQTT beyond what I already provide unless I feel there’s a specific use case I’d like to address. You can already get everything you want using the telemetry feature option.
