### ISSUE TITLE
Node 18 support

### ISSUE THREAD

**Issue by gabors** [hjdhjd/homebridge-unifi-protect#1157]
### Describe the feature request

Please bring back Node 18 support

### Describe the proposed solution

Please bring back Node 18 support for those of us who are unable to use Node 20 on Synology 7.1.x

### Describe alternatives you have considered to the enhancement

Thank you

**Comment by hjdhjd** [comment]
Sorry, I have no plans to do so. Node 18 will be formally EOLed in April of 2025 everywhere in the Homebridge ecosystem, I'm just a little bit ahead of that. You should be able to install HBUP on Node 18, but I make no compatibility guarantees in newer versions. Thanks for the request.

**Comment by gabors** [comment]
That's ok.
Got rid of homebridge synology package and moved to the docker container, which has Node 22.

**Comment by hjdhjd** [comment]
Glad you’re up and running!
