### ISSUE TITLE
Live-streaming works, no recordings shown in HomeKit

### ISSUE THREAD

**Issue by camaronbenjamin** [hjdhjd/homebridge-unifi-protect#1158]
### Homebridge UniFi Protect Version

7.10.0

### Homebridge Platform and OS

Raspberry Pi 3

### Homebridge Version

1.8.4

### Node Version

20.5.1

### UniFi OS Version

v4.0.21

### UniFi Protect Controller Version

5.1.85

### Describe the problem

I managed to setup everything with the doorbell -- Messages, Livestream, etc

Only thing not working is HomeKit doesnt show recordings even though I have Stream & Allow Recordings enabled in HomeKit settings. 

### Homebridge HBUP JSON configuration

```json
not sure where to find this I am new to homebridge, using a hoobs box
```

### Relevant log output

```shell
not sure where to find this I am new to homebridge, using a hoobs box
```

### Acknowledgment that you are only running UniFi OS and UniFi Protect releases from the Ubiquiti Official release channel

- [X] I acknowledge that I am not running any early access / beta firmwares or operating systems from either Ubiquiti or Apple.

**Comment by hjdhjd** [comment]
Pi 3 isn't a supported platform for HBUP with HKSV, as [stated in the documentation](https://github.com/hjdhjd/homebridge-unifi-protect?tab=readme-ov-file#installation). Your hardware can't keep up with HomeKit's demands in that space...if you happen to be able to, that's awesome, but chances are you aren't.

Second - I do not support HOOBS I'm afraid - it's a commercial product and you can reach out to them for support. Homebridge is the only platform I support. Best of luck!
