### ISSUE TITLE
Upgrade and now having streaming issue

### ISSUE THREAD

**Issue by rpatrick2282** [hjdhjd/homebridge-unifi-protect#121]
After an upgrading to the latest version when attempting to stream from a camera I am getting No Response error in Home

**To Reproduce:**
Attempt to stream in Home App

**Logs:**
(node:8958) UnhandledPromiseRejectionWarning: Error: Command failed with ENOENT: /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -codecs
spawn /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:8958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:8958) UnhandledPromiseRejectionWarning: Error: Command failed with ENOENT: /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -codecs
spawn /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Homebridge Configuration:**

        {
            "controllers": [
                {
                    "address": "",
                    "password": "",
                    "username": ""
                }
            ],
            "options": [
                "Disable.MotionSensor",
                "Disable.MotionSwitch"
            ],
            "verboseFfmpeg": true,
            "platform": "UniFi Protect"
        },

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.2.3
* **Node Version:** 12.18.4
* **Homebridge-UniFi-Protect Plugin Version:** 3.7.7
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 11/iPad Pro iOS 14
* **Operating System and OS Version:** Docker

**Comment by hjdhjd** [comment]
There are two issues here actually:

1. Homebridge 1.2.3 has been withdrawn. There are real issues in Ubiquiti-derived platforms. Homebridge 1.1.6 is the latest working version. I’d suggest you downgrade.

2. Your error is that you don’t have ffmpeg-for-homebridge installed. The easiest way to resolve this is to uninstall and reinstall homebridge-unifi-protect.

Best of luck!

**Comment by rpatrick2282** [comment]
Perfect the downgrade and reinstall solved my issue. Thanks for your help


— Rob
