### ISSUE TITLE
Support secure iCloud recording

### ISSUE THREAD

**Issue by sebastianbk** [hjdhjd/homebridge-unifi-protect#123]
First of all, thank you so much for creating this fantastic plugin. I set it up last night and it works amazingly with my three G3 Flex cameras. I really appreciate the work you have done on this project.

I wasn't aware of secure recordings in iCloud but it seems like it's a feature offered with Apple HomeKit. I wanted to ask if there is any chance of this plugin supporting this feature. This would solve the doubt I've had about how to back up my recordings on my Cloud Key Gen2 Plus.

![image](https://user-images.githubusercontent.com/660576/95058446-d549bb80-06f7-11eb-88ef-2b26a658130e.png)

Let me know if there is a way I can help out with the development. I work as a developer in my day job and have extensive with Node.js.

**Comment by hjdhjd** [comment]
Appreciate the interest in this...it's on the radar. Stay tuned. We've got a long way to go before Homebridge can support this - HomeKit Secure Video is not a public specification, and it's unclear if non-Apple-blessed devices will work with it yet. We're (Homebridge developers) working on it. It's on the radar, but it's not coming anytime in the immediate future...but if it's doable, it will be.

Thanks...closing this one. :smile:

**Comment by emax810** [comment]
Hi!. There is a ETA for HomeKit Secure video support ?

**Comment by bondskin** [comment]
Wouldn't that break the concept of secure / trusted chain of components?

**Comment by hjdhjd** [comment]
@emax810 Not much to do at the moment until we get HKSV support into Homebridge. This is what we’re all waiting on: https://github.com/homebridge/homebridge/pull/2973

Meanwhile, I’m working on a couple of new features over the holidays, so stay tuned!
