### ISSUE TITLE
Expose a camera as a Doorbell

### ISSUE THREAD

**Issue by danielkihlgren** [hjdhjd/homebridge-unifi-protect#131]
**Is your feature request related to a problem? Please describe:**

Since the Unifi doorbell is not available world wide a lot of us are not able to purchase one. It would be nice to use another camera as a doorbell instead so that we that don't have a real Unifi doorbell can enjoy the features which a doorbell gives. This feature would make this great plugin even better.

**Describe the solution you'd like:**

If this plugin makes it possible to expose a regular camera as a doorbell and makes it possible to trigger the doorbell event in some way, that would solve the problem for many of us that can't get a real doorbell.

**Describe alternatives you've considered:**

Some other plugins has solved the problem by making it possible to trigger the doorbell event via a dummy switch in HomeKit which then can be triggered from within HomeKit by a button or similar. MQTT can also be a possible way to trigger the event but personally I would prefer the dummy switch solution since I have not started using MQTT yet.

**Comment by hjdhjd** [comment]
Thanks for taking the time to write the request. What’s unclear to me is what the use case for this is. If you have one, I’d appreciate hearing about it. I’m very reluctant to add functionality merely for the sake of adding it.

**Comment by danielkihlgren** [comment]
The use case for me is that I want the functionality that when someone presses the doorbell I want to get the camera notification on my Apple TV. I have a Unifi camera that covers the area around the door already that I want to use as a doorbell camera. The doorbell button can in my case be either a zigbee button or if connect to the old analog doorbell to get the event in some way.

**Comment by hjdhjd** [comment]
Appreciate the context. That sounds like an incredibly fragile setup to attempt something like this. I'll consider this in the future, but it isn't a priority.

Best of luck, and thanks for the suggestion.

**Comment by durosity** [comment]
The doorbell is now available in Canada.  My hope is that's a precursor to an international rollout.. I have money burning a hole in my pocket waiting for it in the UK!
