### ISSUE TITLE
Live stream freezes when motion has been detected.

### ISSUE THREAD

**Issue by MitchJackson94** [hjdhjd/homebridge-unifi-protect#140]
**Describe The Problem:**
Live stream freezes when motion has been detected.

**To Reproduce:**
Open live steam wait for motion and live stream freezes once motion has been detected.

**Environment:**

* **Homebridge Version:** 1.2.3
* **Node Version:** 11.11.0
* **Homebridge-UniFi-Protect Plugin Version:** v3.7.9
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Mac iOS
* **Operating System and OS Version:** FreeNAS (FreeBSD)

**Comment by hjdhjd** [comment]
Before looking into this any further - you’re running an unsupported version of Node, and a pulled version of homebridge. :smile: 

homebridge 1.1.6 is the current stable version.
node 12 is the current supported release.

I’ve had livestreams going for hours, **with** motion events occurring without an issue. I don’t think this is a plugin issue, but if you have a clearly reproducible test case, happy to look into it. My gut is that this has more to do with running outdated / retracted software...
