### ISSUE TITLE
Stream not working

### ISSUE THREAD

**Issue by Mr-S-D** [hjdhjd/homebridge-unifi-protect#141]
**Describe The Problem:**
All of my cameras is discovered and appears in my home app. The thumbnail image of the camera refresh's about every 10 seconds so this works fine. However, when I tap the button for a camera I only get the loading circle for a long time. I do not see a live stream. After a while it stops loading and the "video" just states no response, camera not answering.
When looking in the log of the homebridge you can see that my request has been initiated, but at the same time my iPhone/iPad gets the non response the stopped streaming occurs in the log.

I have installed the ffmpeg for homebridge as well. 

Any ideas? 

**Logs:**
```
Show the Homebridge logs here.
[10/25/2020, 11:19:22] [UniFi Protect] Cloud Key & NVR [UCK-G2-PLUS] Inngangsparti [UVC G3]: HomeKit video stream request received: 1920x1080, 30 fps, 802 kbps.
[10/25/2020, 11:19:46] [UniFi Protect] Cloud Key & NVR [UCK-G2-PLUS] Inngangsparti [UVC G3]: Stopped video streaming session.
[10/25/2020, 11:19:49] [UniFi Protect] Cloud Key & NVR [UCK-G2-PLUS] Inngangsparti [UVC G3]: Stopped video streaming session.

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge A4B4",
        "username": "0E:73:C0:9E:A4:B4",
        "port": 51580,
        "pin": "212-47-755"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "KNX",
            "platform": "KNX"
        },
        {
            "controllers": [
                {
                    "address": "XXXXXXXX",
                    "password": "XXXXXXXXX",
                    "refreshInterval": 10,
                    "username": "XXXXXXXX"
                }
            ],
            "platform": "UniFi Protect"
        }
    ],
    "accessories": []
}
```

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:** v3.7.9
* **Apple Device and iOS / iPadOS:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
Read the documentation or look through previous issues. Asked and answered more than once. 😄

Start with the troubleshooting page. Feel free to reopen if you’re still having issues.
