### ISSUE TITLE
Apple Watch Stream - Snapshot

### ISSUE THREAD

**Issue by Mr-S-D** [hjdhjd/homebridge-unifi-protect#150]
**Describe The Problem:**

**Apple Watch Streaming**
The setup is working really good, but when I try to see the stream on my Apple Watch it only says connection, and then after a while it says "not available". Is this supposed to work and this is a firewall issue, or is this not supposed to work?

**Snapshot**
I have a doorbell enabled to send http// requests. Is it possible in any way to trigger a notification with a snapshot on the home app, so if someone rings the doorbell, a request is sent and I receive a notification with a snapshot? Basically fooling the camera to belive it has a motion decided, hence sending me a notification. 

**Logs:**

When streaming from my iPhone I get this in the log when starting:
HomeKit video stream request received: 1280x720, 30 fps, 299 kbps.
When streaming from my iPhone I get this in the log when stoping:
[10/27/2020, 20:38:46] [UniFi Protect] Cloud Key & NVR [UCK-G2-PLUS] Inngangsparti [UVC G3]: Stopped video streaming session.

However when I try from my watch I get this in the log straight away:
[10/27/2020, 20:38:46] [UniFi Protect] Cloud Key & NVR [UCK-G2-PLUS] Inngangsparti [UVC G3]: Stopped video streaming session.

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge A4B4",
        "username": "0E:73:C0:9E:A4:B4",
        "port": 51580,
        "pin": "212-47-755"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "KNX",
            "platform": "KNX"
        },
        {
            "controllers": [
                {
                    "address": "XXXXXX",
                    "password": "XXXXXX",
                    "refreshInterval": 10,
                    "username": "XXXXXX"
                }
            ],
            "platform": "UniFi Protect"
        }
    ],
    "accessories": []
}
```

**Screenshots:**

**Environment:**
Raspberry Pi

* **Homebridge Version:** V1.1.6
* **Node Version:** V.12.19.0
* **Homebridge-UniFi-Protect Plugin Version:** V3.7.9
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 14.1 & WatchOS 7
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Thanks for raising the issue! See the Troubleshooting page under streaming video issues. 😄

**Comment by Mr-S-D** [comment]
Hi, 

Thanks for responding so fast. I have disabled all firewalls just to make sure this is not the issue.
Despite disabling all the firewalls the stream on the watch still not works. So I assume it is related to the latency described in the troubleshooting page.

Do you have suggestion for the snapshot "function" I would like? That would be a really nice feature :)

**Comment by hjdhjd** [comment]
No problem.

As to snapshots...the feature already exists. Read the Feature Options documentation, and look for the motion trigger feature. All sorts of goodies there.

Best of luck...closing this one.
