### ISSUE TITLE
Feature to disable wired chime

### ISSUE THREAD

**Issue by willumpie82** [hjdhjd/homebridge-unifi-protect#153]
**Is your feature request related to a problem? Please describe:**
The Unifi doorbel operates a chime that is wired via a chime adapter to the g4 doorbell itself. In the protect web gui the chime can be disabled by flipping a switch. This switch is unfortunately not available in the (ios) app.

**Describe the solution you'd like:**
During my time with the Nest hello there was an option to disable the chime for a specified amount of time. Especially handy when our son is a sleep. Getting this would unifi would require a firmware/protect update I guess. But what about a control switch from this homebridge plugin? we could handle this timing our selfs and/or by an upstream home automation software (ha, node red, homey,...)

**Describe alternatives you've considered:**
An alternative would be fiscally disabling the chime by means of additional electronics (e.g. esp8266 with a relay) or simple manual switch.

**Additional context:**
Not applicable

**Comment by hjdhjd** [comment]
Interesting problem you've got. This isn't a feature I'm likely to add, I'm afraid - first, the support in Protect for this isn't there in a meaningful way to do this. You **can.** disable it through the webUI, but it's unclear what the power draw implications or potential electrical risk might be. That's not a place I'm willing to go without a lot more information.

Personally, I wouldn't put a chime in the middle of this in the way that you have - you can use a HomePod or HomePod mini to provide that functionality and control things a bit more granularly.

Or, perhaps you look into using a digital chime with an off button or some other intelligence on when to ring?

Best of luck!

**Comment by durosity** [comment]
I'd suggest as @hjdhjd has said to physically separate out the doorbell ringer from the button device, that's the way I have mine setup at present (alas not a unifi one yet but hopefully soon). I have my existing ring doorbell wired directly to the transformer, and a 24v ac relay which shorts when the button is pressed, which in turn rings the doorbell ringer.  Between the relay and the ringer is a z-wave relay that simply allows it to complete the circuit and if I turn off the relay then all is silent.  That said I do plan to retire this once I move to a unifi doorbell and simply use homepods/HomePod minis instead.. I just wish Apple would add the ability to enable/disable the ring on them to a scene or automation, having to adjust about 8 HomePods manually each time would be a right faf!

**Comment by hjdhjd** [comment]
Closing this one.
