### ISSUE TITLE
No Video Playback in HomeKit

### ISSUE THREAD

**Issue by SemoTech** [hjdhjd/homebridge-unifi-protect#159]
**Describe The Problem:**
Brand new setup using a Raspberry Pi 4B 2GB v1.2 with 32GB uSD, connected via Gigabit Ethernet. However I am unable to get homebridge-unifi-protect video streaming to work in HomeKit.  Using all defaults except I enabled debugging in the plugin for ffmpeg. The cameras appear, but selecting any of them I get a static old image and a spinning “loading” circle.  Then it times out and says “No Response This camera is not responding”.  Would greatly appreciate some support to get this to work. 

**To Reproduce:**
Touch any of the Protect cameras in HomeKit.  This issue occurs every time.

**Logs:**
Here are the logs [OUTPUT](https://pastebin.com/CKkQ7WWP)

**Homebridge Configuration:**

Here is the [Homebridge Configuration](https://pastebin.com/u1xe5HZa)

**Screenshots:**
https://www.screencast.com/t/eAf6hXt2wUR 

**Environment:**

* **Homebridge Version:** v1.1.6
* **Node Version:** v14.15.0
* **Homebridge-UniFi-Protect Plugin Version:** v3.7.9
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 11 Pro Max v13.5 
* **Operating System and OS Version:** homebridge-raspbian-image v1.0.14

Thanks in advance!

**Comment by hjdhjd** [comment]
Thanks for reaching out, and welcome to the community!

Now...please review the [Troubleshooting](https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Troubleshooting.md#video-streaming) page. 

Asked and answered more than a few times. 😄

**Comment by SemoTech** [comment]
Thanks @hjdhjd but still no luck.  I tried both "Disable.Stream.High" and "Enable.StreamOnly.Low" feature options (one at the time with Homebridge restarts in-between) and same exact issue with playback remains. 
 
Is there anything else I can provide to help you figure out why this is happening?

**Comment by hjdhjd** [comment]
If `Enable.StreamOnly.Low` didn't do the trick, you may be out of luck, it is definitely the failsafe that always works. 

Have you also taken a close look at your network / VLAN / firewall setup to make sure you aren't blocking traffic that shouldn't be blocked?

Finally - what version of UniFi Protect are you running? No beta releases of either UniFi Protect or iOS are supported, in case you may be in one of those situations. Feel free to ping on the Discord with additional questions. Good luck.

**Comment by SemoTech** [comment]
Yeah @hjdhjd this is very strange.  The network configuration is working fine. The Protect iOS app and HomeKit work fine with everything, except the cameras live video. The Raspberry Pi is 4B v 1.2 and should be more than powerful to render video from a couple of cameras, with just one streaming at the time.

Running UniFi Protect 1.15.0 (on UDM-Pro 1.8.0) and iOS 13.5 on iPhone 11 Pro Max. No betas. 

Did you get a chance to review the debug logs I linked above?  Is anything out of the ordinary?  Thanks.

**Comment by hjdhjd** [comment]
There's nothing extraordinary in your logs...everything is working as it should. You might want to try updating to iOS 14, or rebooting your iOS device and seeing if it helps. Long shot, but you never know.

The plugin is doing what it's supposed to do...and ffmpeg is working / streaming.

**Comment by hjdhjd** [comment]
Two more things you might want to try - uninstalling and reinstalling the plugin. ffmpeg-for-homebridge occasionally has installation issues.

Once you've done that, if things aren't working, try `Enable.StreamOnly.Low` again...if it's not working, post the relevant portion of your logs and config once more and let's see.

**Comment by hjdhjd** [comment]
Closing this one. There's also a new release of homebridge-unifi-protect that you might want to try out. If you continue to encounter issues, please reopen this issue.

**Comment by SemoTech** [comment]
Thanks @hjdhjd, I followed your advice. Here are the steps and logs...

1 - Removed the _homebridge-unifi-protect_ plugin along with it's configuration from HomeBridge & restarted it. For reference aside from the Homebridge UI there are no other plugins in this fresh setup of latest HomeBridge.
2 - Installed the **new** _homebridge-unifi-protect_ plugin **v4.0.0** and restarted HomeBridge
3 - Populated the controller IP, Username and Password, and kept all other defaults.
4 - Tried the video cameras in iOS Home App - same issue!
Here are the [LOGS](https://pastebin.com/iD5h1GWB)
5 - Added the _Enable.StreamOnly.Low_ option and re-tried - same issue!
Here are the [LOGS](https://pastebin.com/JfEDTmDw)

Lastly, I also tried using the Home App on an iPad Air 2 running latest iOS 14.1, and sadly same result ("No Response, This camera is not responding"), so it is not my iPhone or iOS 13.5 that is the issue...

**Comment by hjdhjd** [comment]
@SemoTech Nope. 😄 You didn't read the fine print or updated documentation - major updates in 4.0.0 to feature options.

The correct feature option as of 4.0.0 is: `Enable.Video.Stream.Only.Low`

**Comment by SemoTech** [comment]
@hjdhjd Good point, I replaced the "Enable.StreamOnly.Low" option with "Enable.Video.Stream.Only.Low" and restarted HomeBridge, retried, and shockingly..... no effect!

**Comment by hjdhjd** [comment]
Logs please. And explain your physical setup in a bit more detail. We’ll figure this out.

Also...what type of device are you using for your UniFi Protect controller, and what controller version are you on?

**Comment by SemoTech** [comment]
Appreciate the commitment to help solve this @hjdhjd 
Setup with latest firmware for all devices as of today is as follows:

- HomeKit Hub uses an Apple TV 4K (latest version)
- Apple TV 4K connected wirelessly using UniFi U6-Mesh AP to default (untagged) "LAN" WLAN
- UniFi U6-Mesh AP connected via Ethernet to UniFi PoE Switch - Port set to "ALL" VLAN's
- UniFi Switch 8 PoE connected to UniFi UDM-Pro v1.8.0 running Protect v1.15.0 - Port set to "ALL" VLAN's/Uplink
- Raspberry Pi 4B 2GB connected via Ethernet to UDM-Pro - Port set to "IOT" VLAN
- "IOT" VLAN/WLAN is tagged and consistent.
- UniFi G4 Doorbell connected wirelessly to "IOT" WLAN & G3 Pro Camera Ethernet connected to UniFi Switch 8 PoE - Port set to "IOT" VLAN.
- "IOT" VLAN/WLAN setup as "Corporate" so there is crosstalk with "LAN" - Temporary until everything works then One-Way & Replies only Firewall Rule will be applied. 
ALL other HomeKit devices connected wirelessly to "IOT" WLAN - All work perfectly in HomeKit. 

As for logs, the Homebridge is not providing much else aside from what I already sent and since the ffmpeg debug was turned off, it's just one liner about starting the stream:

```
[02/11/2020, 12:43:14] Homebridge is running on port 51605.
[02/11/2020, 12:43:14] [UniFi Protect] SemoTech UDM-Pro [UDM-PRO]: Connected to the Protect controller API (address: 192.168.0.2 mac: 76ACB94F4B62).
[02/11/2020, 12:43:14] [UniFi Protect] SemoTech UDM-Pro [UDM-PRO]: Connected to the UniFi realtime update events API.
[02/11/2020, 12:43:14] [UniFi Protect] SemoTech UDM-Pro [UDM-PRO]: Discovered camera: Front Doorbell [UVC G4 Doorbell] (address: 172.31.200.89 mac: E063DAEFAEE3).
[02/11/2020, 12:43:14] [UniFi Protect] SemoTech UDM-Pro [UDM-PRO]: Discovered camera: UVC G3 Pro [UVC G3 Pro] (address: 172.31.200.23 mac: B4FBE4FFD729).
[02/11/2020, 12:43:14] [UniFi Protect] SemoTech UDM-Pro [UDM-PRO]: Controller refresh interval set to 10 seconds.
[02/11/2020, 12:43:14] [UniFi Protect] SemoTech UDM-Pro [UDM-PRO] Front Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: LEAVE PACKAGE AT DOOR.
[02/11/2020, 12:43:14] [UniFi Protect] SemoTech UDM-Pro [UDM-PRO] Front Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: DO NOT DISTURB.
(node:16135) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
[02/11/2020, 12:44:42] [UniFi Protect] SemoTech UDM-Pro [UDM-PRO] Front Doorbell [UVC G4 Doorbell]: HomeKit video stream request received: 1280x720@30fps, 299 kbps. Using the 480x360@15fps (Low) RTSP profile.
[02/11/2020, 12:44:53] [UniFi Protect] SemoTech UDM-Pro [UDM-PRO] Front Doorbell [UVC G4 Doorbell]: Stopped video streaming session.
```

Let me know if anything else helps....

**Comment by 4-ev3r** [comment]
> Appreciate the commitment to help with this @hjdhjd but I got it **SOLVED**!
> 
> Issue was that even tho I had setup my "IOT" VLAN as "Corporate" with the Homebridge on it, it was not able to communicate to the "LAN" VLAN properly. Since all other HomeKit devices were communicating just fine, except the cameras, I never assumed that data flow between VLAN's would be the issue. Given how the Homebridge works it aparenly needed more permissions.
> 
> I ended up creating a new Firewall Rule matching the Homebridge IP & MAC that allows it to communicate from "IOT" to "LAN". Not the cleanest solution but works for now.
> 
> ![image](https://user-images.githubusercontent.com/1452100/98152701-fa605400-1e86-11eb-9b66-a3c5fb57f36b.png)
> 
> Thanks for all your help and the awesome Unifi-protect plugin!

You can further restrict it to UDP

**Comment by SemoTech** [comment]
@4-ev3r Thanks for the UDP restriction suggestion.  
My setup worked great until Ubiquity released an update that changed something internal and undocumented related to inter VLAN routing, and the communication broke even tho I made no other changes to my configuration.  I was forced to move HomeBridge to the LAN (while keeping all IOT devices on their own VLAN) to make everything work again and ensure I can manage from the LAN.  Even opened cases with Ubiquity but no solution.
