### ISSUE TITLE
Enable.Video.Stream.X.IPADDRESS - still taking low quality stream 

### ISSUE THREAD

**Issue by m11rphy** [hjdhjd/homebridge-unifi-protect#167]
Hi, firstly thank you for such an amazing plugin

Im trying to use the new feature; Enable.Video.Stream.X.IPADDRESS

So for my Apple TV I have added Enable.Video.Stream.High.162.168.1.161, however it still seems to be get the the low quality RTSP stream from when I enabled; Enable.Video.Stream.Only.Low, as you can see from my log below;

[UniFi Protect] Dream Machine Pro [UDM-PRO] UVC G3 Pro [UVC G3 Pro]: HomeKit video stream request received from 192.168.1.161: 1920x1080@30fps, 802 kbps. Using the 640x360@15fps (Low) RTSP stream profile.

This is how may config looks; 

            "controllers": [
                {
                    "address": "xxxxx",
                    "password": "xxxxx",
                    "username": "xxxxxx"
                }
            ],
            "options": [
                "Enable.Video.Stream.Only.Low",
                "Enable.Video.Stream.High.192.168.1.161"
            ],
            "platform": "UniFi Protect"
        },

**Comment by hjdhjd** [comment]
@m11rphy Thanks for the compliment and the bug report. I'd appreciate it if you could please make sure you're completely filling out the bug report template. I don't typically check reports that are auto-closed...the template is there to streamline the process. 😄 

The error above is a typo on my part in the Changelog that's now been corrected.

Try: `Enable.Video.Stream.Only.High.192.168.1.161`

That should do the trick.

**Comment by m11rphy** [comment]
I really struggled to know what info you needed, I'm still a bit of a novice 

I tried Enable.Video.Stream.Only.High.192.168.1.161 as suggest and still the same error; 

[11/8/2020, 3:35:21 PM] [UniFi Protect] Dream Machine Pro [UDM-PRO] UVC G3 Pro [UVC G3 Pro]: HomeKit video stream request received from 192.168.1.161: 1920x1080@30fps, 802 kbps. Using the 640x360@15fps (Low) RTSP stream profile.

Config now looks like this;

"controllers": [
                {
                    "address": "xxxxx",
                    "password": "xxxxx",
                    "username": "xxxxx"
                }
            ],
            "options": [
                "Enable.Video.Stream.Only.Low",
                "Enable.Video.Stream.Only.High.192.168.1.161"
            ],
            "platform": "UniFi Protect"
        },

**Comment by hjdhjd** [comment]
Did you restart Homebridge after changing the configuration? 😄

**Comment by m11rphy** [comment]
I did. yes lol. Restarted again just to make sure tho

**Comment by hjdhjd** [comment]
Is the high streaming profile enabled on the Protect camera?

**Comment by m11rphy** [comment]
Just double checked and yes enabled on both my cameras

**Comment by hjdhjd** [comment]
Which version of the plugin are you running?

**Comment by m11rphy** [comment]
I updated this morning to homebridge-unifi-protect v4.1.0

**Comment by hjdhjd** [comment]
Remove all the feature options and just let the plugin do it's thing and see how that works.

**Comment by m11rphy** [comment]
Ok its now pulling the high quality stream to Apple TV

[11/8/2020, 4:14:10 PM] [UniFi Protect] Dream Machine Pro [UDM-PRO] UVC G3 Pro [UVC G3 Pro]: HomeKit video stream request received from 192.168.1.161: 1920x1080@30fps, 802 kbps. Using the 1920x1080@30fps (High) RTSP stream profile.

Camera wont load on my iPhone via LTE tho as expected

**Comment by hjdhjd** [comment]
One thing at a time. :smile:

Add: `Enable.Video.Stream.Only.High.192.168.1.161`

Restart. See what streams.

**Comment by m11rphy** [comment]
still getting the high quality stream on the Apple TV 

[11/8/2020, 4:19:59 PM] [UniFi Protect] Dream Machine Pro [UDM-PRO] UVC G3 Pro [UVC G3 Pro]: HomeKit video stream request received from 192.168.1.161: 1920x1080@30fps, 802 kbps. Using the 1920x1080@30fps (High) RTSP stream profile.

**Comment by hjdhjd** [comment]
Great. Now add this feature option:

`Enable.Video.Stream.Only.Low`

**Comment by m11rphy** [comment]
Now it back to low quality stream on Apple TV; 

Dream Machine Pro [UDM-PRO] UVC G3 Pro [UVC G3 Pro]: HomeKit video stream request received from 192.168.1.161: 1920x1080@30fps, 802 kbps. Using the 640x360@15fps (Low) RTSP stream profile.

**Comment by hjdhjd** [comment]
I just recreated your issue. Congrats, you found a bug. :smile: Give me a bit.

**Comment by m11rphy** [comment]
Do I win a prize? lol thanks buddy appreciate the help :)

**Comment by hjdhjd** [comment]
Fixed in v4.1.1. Give it a go.

**Comment by m11rphy** [comment]
Its working perfect buddy, Apple TV get high quality stream, iPhone over LTE gets the lower quality stream and loads in less than 5 seconds> thank you so much buddy 

Will it be ok to add more devices to Enable.Video.Stream.Only.High. or is it better to leave to one device?

**Comment by hjdhjd** [comment]
You can customize and mix and match to your heart's delight. There are no artificial limitations. 

Now...in the future - fill out the bug report completely. 😄

**Comment by m11rphy** [comment]
Thank buddy I really appreciate it, you plugin really is amazing
