### ISSUE TITLE
"Disable.Stream.High" not honored in HK streams?

### ISSUE THREAD

**Issue by patricegautier** [hjdhjd/homebridge-unifi-protect#189]
Hi.

First thanks a ton for this plugin - it really complements the Protect setup!

I was trying to restrict a G4 doorbell to medium or low RTSP qualities to see if I could improve on the startup times of the streams.

Despite my best efforts specifying

"Disable.Stream.High"
or
Enable.Video.Stream.Only.Medium

The plugin always seems to pick high as the rtsp profile..

**Logs:**

[11/29/2020, 7:23:51 PM] [UniFi Protect] 99-Video [UNVR4] 99 Doorbell [UVC G4 Doorbell]: Streaming request from 192.168.215.70: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1600x1200@24fps (High), 3400 kbps.

**Homebridge Configuration:**

```json
        {
            "debug": false,
            "options": [
                "Disable.Stream.High",
                "Disable.Stream.Medium",
                "Enable.Stream.Low"
            ],
            "controllers": [
                {
                    "address": "xxxxx",
                    "name": "NVR99",
                    "password": "xxxx",
                    "username": "xxxx"
                }
            ],
            "platform": "UniFi Protect"
        },
```

**Environment:**

* **Homebridge Version:**  1.2.3
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:** 4.2.0
* **UniFi Protect Controller Version:** 1.6.7
* **UniFi Protect Controller Type:**  UNVR4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iOS 13.1
* **Operating System and OS Version:** Docker

**Comment by hjdhjd** [comment]
Thanks!

As to your issue - please read the documentation more closely. Your feature options are incorrect. :smile:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/FeatureOptions.md#video

There were important breaking changes in 4.0, documented in the changelog related to this. :smile:

Best of luck.

**Comment by hjdhjd** [comment]
Let me know if you’re still struggling @patricegautier - it should be pretty straightforward. You only need one feature option, FYI, to do what you’re looking for: `Disable.Video.Stream.High`

Furthermore, if you have other Protect cameras and don’t want to restrict those...look at the feature option documentation on scope to better understand how you can restrict options to specific cameras or Protect controllers.

**Comment by patricegautier** [comment]
got it - Disable.Video.Stream.XX indeed does the trick, thank you for the quick response!  I guess the entries in my config were obsolete and dating prior to 4.0..

For what it's worth, it does improve startup time from 5-7s to 3-4s to use Medium on my system.

**Comment by patricegautier** [comment]
You could even consider a feature request where you start with the Low quality to get a picture quickly and then upgrade to Medium then High time/bw permitting :)

**Comment by hjdhjd** [comment]
It’s highly system-specific. For me, everything comes up in less than one second, two at the most. Every. Time. And I have an environment with 15+ cameras ranging from G4 Pros to G3 Flex’s to G4 Doorbells.

**Comment by hjdhjd** [comment]
> You could even consider a feature request where you start with the Low quality to get a picture quickly and then upgrade to Medium then High time/bw permitting :)

That’s not a feature for the plugin. First and foremost, it’s an ffmpeg limitation currently, and probably for the foreseeable future. Second...this is already built into HomeKit. If/when ffmpeg gains the technical ability to do this, it will happen. Best of luck.

**Comment by patricegautier** [comment]
Similar setup here.  What do you run homebrige and ffmpeg on?

	-P

**Comment by hjdhjd** [comment]
Six-core Xeon E5 with 256GB of RAM and a 10G Ethernet connection.

I have no network / CPU / RAM resource constraints. It’s not about the hardware per se. Your network setup matters a lot, as does all the other things you have going on in your individual setup. Troubleshooting is beyond the scope of this discussion though...best of luck. If you want to discuss individual setups...suggest you use the Discord. Take care.
