### ISSUE TITLE
Option to restrict Enable.Doorbell.Trigger to just one device

### ISSUE THREAD

**Issue by durosity** [hjdhjd/homebridge-unifi-protect#193]
**Is your feature request related to a problem? Please describe:**
I'd like the ability to limit the Enable.Doorbell.Trigger to one device, namely my G4 Doorbell.  I currently have 11 Protect devices around my house, and when I have the doorbell trigger option enabled it creates a On/Off device for every single camera which I really don't want - It'd be great if you could limit it by MAC address like you can do with the video and audio options to allow me to have it just for the Doorbell itself!  Also just curious but why was it changed from a contact sensor to a switch?  In my mind a contact sensor makes more sense as that's effectively what it is!

**Describe the solution you'd like:**
Specify by MAC address

**Describe alternatives you've considered:**
None come to mind

**Additional context:**

**Comment by hjdhjd** [comment]
This feature already exists. Please read the documentation closely on feature options. All feature options can already be scope-limited: https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/FeatureOptions.md#specifying-scope

**Comment by durosity** [comment]
Huh I coulda sworn it said it was for video and audio options only!  And I tried it out anyway but it didn't work, but I've tried it again and bingo it works.. I must've gone temporarily mad!

**Comment by hjdhjd** [comment]
> Huh I coulda sworn it said it was for video and audio options only! And I tried it out anyway but it didn't work, but I've tried it again and bingo it works.. I must've gone temporarily mad!

Hence why I said read closely. Video and audio options can be limited by both MAC address (to control options to a specific camera) and client IP address (to control what gets streamed to a particular client viewing device). It doesn’t make sense to expose a trigger to some client IPs and not others (you couldn’t do it in HomeKit even if you wanted to). :smile:

I spent a lot of time on documentation...a few minutes reading will go a long way. There’s a lot of good stuff I’m sure you’ll discover over time. Best of luck!
