### ISSUE TITLE
HomePod mini "Chime on HomePod" toggle not working.

### ISSUE THREAD

**Issue by WJKramer** [hjdhjd/homebridge-unifi-protect#194]
**Describe The Problem:**
In the iOS home.app the toggle under Camera & Doorbells for my G4 doorbell "Chime on HomePod" results in the following error: "Could not complete operation". Therefore will not ring on my test HomePod mini.

**To Reproduce:**
Enter iOS home.app Home(icon)>Home Settings>Cameras & Doorbells>G4 Doorbell>toggle "Chime on HomePod".

**Logs:**
N/A

**Homebridge Configuration:**

[
    {
        "address": "192.168.1.1",
        "username": "xxx@xxx",
        "password": "abc"
    }
]

**Screenshots:**

![IMG_2432](https://user-images.githubusercontent.com/75452447/101090464-b2674680-3584-11eb-8dde-75fdc1ac82f3.png)

**Environment:**

* **Homebridge Version:** HOOBS 3.3.1
* **Node Version:** 12.19.0
* **Homebridge-UniFi-Protect Plugin Version:** 4.2.0
* **UniFi Protect Controller Version:** 1.17.0-beta1
* **UniFi Protect Controller Type:** UDMP
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** HomePod iOS 14.2
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Thanks for the report. A few things:

1. No beta software releases of anything are supported, including (and especially!) UniFi Protect.
2. HOOBS is several versions behind of the Homebridge mainline. homebridge-unifi-protect requires a modern version of Homebridge. HOOBS is aware of these issues and is planning updates to bring them back inline at some point in the future.
3. I can’t reproduce this error on any device running production iOS / HomePod, Protect, and this plugin. If you have a method of recreating this issue running supported software configurations, I’d appreciate it if you could share it so we can troubleshoot: I (and others) reliably have HomePod-based chimes working.

I would first get yourself on production-only firmwares and OS-releases. If that doesn’t work, take a look at running a mainline Homebridge release. If neither of those work, and you have a way to reliably recreate this issue, please let me know...it’s a very nice feature and I want you to be able to enjoy it too!

**Comment by WJKramer** [comment]
Thanks you for the response and you are absolutely correct in all 3 points.

1. I reset my UDMP to the latest stable 1.8.3 which includes protect 1.16.8 and restored from back ups.

2. I installed homebridge 1.1.6 on my macOS iMac.

3. I am still getting the same error when trying to enable doorbell chimes on the HomePod mini.

**Comment by durosity** [comment]
Have you tried a reset of your HomePod?  While I didn't get that error I did have one that just didn't chime, and resetting it fixed the problem!

**Comment by WJKramer** [comment]
> Have you tried a reset of your HomePod? While I didn't get that error I did have one that just didn't chime, and resetting it fixed the problem!

I reset the HomePod this morning and it seemed to solve the issue! Thanks. I have noticed some issues with Siri's responses as well. I am chalking it up to this new HomePod mini being a bit buggy.

**Comment by hjdhjd** [comment]
Glad to hear it! Enjoy!
