### ISSUE TITLE
Upgraded to most recent homebridge / config-ui-x, doorbell throwing promise rejection errors

### ISSUE THREAD

**Issue by hanzov69** [hjdhjd/homebridge-unifi-protect#195]
**Describe The Problem:**
Upgraded the container I run homebridge + Config-UI-X in today. I now have an accessories tab, however console is spewing errors related to UUIDs, no longer have video or snapshots from doorbell. 

**To Reproduce:**
As above
**Logs:**
This repeats ad-nauseam-

```
(node:576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 30)
(node:576) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '00000112-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:281:17)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:628:16
    at Array.forEach (<anonymous>)
    at Accessory.configureController (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:626:33)
    at PlatformAccessory.configureController (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:137:34)
    at ProtectDoorbell.configureVideoStream (/homebridge/node_modules/homebridge-unifi-protect/src/protect-camera.ts:605:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 31)
```
**Homebridge Configuration:**

```json
{
            "controllers": [
                {
                    "address": "192.168.1.1",
                    "doorbellMessages": [
                        {
                            "duration": 60,
                            "message": "I'll be right there!"
                        },
                        {
                            "duration": 1800,
                            "message": "Come On In Friends!"
                        }
                    ],
                    "password": "REDACTED",
                    "username": "RE@DACT.ED"
                }
            ],
            "videoProcessor": "/usr/local/bin/ffmpeg",
            "platform": "UniFi Protect"
        }
```

**Environment:**

* **Homebridge Version:** 1.2.3
* **Node Version:** v14.15.1
* **Homebridge-UniFi-Protect Plugin Version:**  v4.2.0
* **UniFi Protect Controller Version:**  1.15.0
* **UniFi Protect Controller Type:** UDMP
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** macOS, iOS, tvOS - latest stable and beta streams
* **Operating System and OS Version:** alpine 3.12 (using 
https://hub.docker.com/r/oznu/homebridge )

**Comment by hjdhjd** [comment]
Thanks for the report. A couple of things...

Homebridge 1.2.3 is not a production version of Homebridge. v1.1.6 is the latest release. v1.2.3 was retracted for issues.

That said, this issue appears to be that you have somehow duplicated accessories or services within Homebridge. The easiest way to deal with this, unfortunately, is to simply blow away the `cachedAccessories` file under the `~/.homebridge/accessories` directory. This will effectively reset your Homebridge accessories and you’ll likely need to run through the accessory setup process again.

Best of luck.

**Comment by hanzov69** [comment]
@hjdhjd hey thanks for the heads up! I looked at the homebridge repo and saw that was the latest release- no mention of it being an issue. Didn’t think to check npm and see what was actually available. 

I reverted, problem solved. Most appreciated!

**Comment by hjdhjd** [comment]
Glad to hear it’s resolved! Enjoy!
