### ISSUE TITLE
Use Cameras with Speakers as doorbell Chimes

### ISSUE THREAD

**Issue by rasod** [hjdhjd/homebridge-unifi-protect#196]
**Is your feature request related to a problem? Please describe:**
When i’m out in the garage I sometime miss the doorbell. My Garage has a G3 Micro thought maybe it could be used as a chime for when someone rings the G4 Doorbell

**Describe the solution you'd like:**
I could pick certain cameras, which have speakers, as remote chimes for the doorbell. When someone rings the doorbell the plugin would play a pre-recorded sound over the speaker of the camera.

**Describe alternatives you've considered:**
I could just use a HomePod or remember to bring my phone with me in the garage. Also thought of using the sensors to flash the lights or other automation.

**Additional context:**
Just a “crazy enough it might work idea” I had. Feel free to ignore.

**Comment by hjdhjd** [comment]
Hi! Well...points for creativity...but I won’t be adding this to `homebridge-unifi-protect` I’m afraid. :smile:

That said, let me offer a few thoughts:

* Try a HomePod mini? They aren’t super-pricey...
* You can execute some version of this already with a little creativity...`homebridge-unifi-protect` will publish all doorbell events via MQTT. You could listen for that using another script, and send a chime / ringtone audio file and stream it directly to the G3 Micro. It’s not hard to do...and would be nearly instantaneous.

**Comment by rasod** [comment]
Yes the MQTT option was on the list of things to try. Was more of a wonder if others have a similar problem. In reality Ubiquiti should just sell a plug-in remote chime. If the can make a $30 WiFi camera they can make a remote chime.

**Comment by hjdhjd** [comment]
Well, who knows what the future holds for Ubiquiti. Wouldn’t be surprised, but you never know. Personally - if you’re willing to spend money on the Ubiquiti ecosystem, which obviously you are if you’re here, buy a HomePod mini and call it a day. It’s the easiest solution, by far.

Best of luck!
