### ISSUE TITLE
Doorbell as a action

### ISSUE THREAD

**Issue by AlbertAndersson** [hjdhjd/homebridge-unifi-protect#205]
**Is your feature request related to a problem? Please describe:**
This may be a apple HomeKit problem thats impossible to solve with a plug-in. 
When the doorbell is activated I only get a notice on my phone. It is not posible to trigger a light to come on or a sound in a speaker.

**Describe the solution you'd like:**
I would like to have the doorbell ring as an sensor in HomeKit that can trigger an action. For example it could be a motion sensor that is triggered by pressing the doorbell. Then you could make an automation in HomeKit that for example triggers a selected Hue light to turn on.

**Describe alternatives you've considered:**

**Additional context:**
No.

**Comment by hjdhjd** [comment]
This already exists. Please read the documentation. :smile:
