### ISSUE TITLE
Would love to see this integrated with homebridge-unifi-protect-camera-motion

### ISSUE THREAD

**Issue by ntableman** [hjdhjd/homebridge-unifi-protect#216]
**Is your feature request related to a problem? Please describe:**
I really would love to see the motion type into MQTT, so I can act accordingly. What I am up to is triggering something when a person appears in the doorbell and I am working...set message to something about no on is going to come to the door... or when I see a vehicle in the driveway specifically alert me so I can see if it is the UPS person, etc...

**Describe the solution you'd like:**
somehow send the type into the mqtt, I know this is in the beta versions of protect, so maybe it is about waiting until those features are there to send along to MQTT

**Describe alternatives you've considered:**
writing my own code, but while I can do C,C++, and others these "internet languages" seem to confound me :)

**Additional context:**
UDM Pro, 9 cameras, talk, etc... pro-sumer working at home techie...so happy to help tinker and test.

**Comment by hjdhjd** [comment]
When smart motion detection matures a bit more in the coming weeks and months, this, and other functionality will be added. As you correctly mentioned - non-production versions of UniFi Protect are not supported. Stay tuned. :smile:
