### ISSUE TITLE
doorbell does not revert to false

### ISSUE THREAD

**Issue by ntableman** [hjdhjd/homebridge-unifi-protect#218]
**Describe The Problem:**

the MQTT msg for doorbell ring sets to true when there is a press, but it never reverts to false

**To Reproduce:**

right the doorbell
**Logs:**

N/A
```
Show the Homebridge logs here.
Remove any sensitive information.
```
N/A
**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```
N/A
**Screenshots:**

N/A
**Environment:**

* **Homebridge Version:** 
v1.2.3
* **Node Version:** 
v14.15.3
* **Homebridge-UniFi-Protect Plugin Version:**
v0.4.2
* **UniFi Protect Controller Version:**
1.17.0.b.10
* **UniFi Protect Controller Type:** 
UDMPRO 1.8.4-3
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
N/A
* **Operating System and OS Version:** 
Docker

**Comment by hjdhjd** [comment]
This isn't a bug. It's expected - and documented - behavior.

**Comment by ntableman** [comment]
as we say in my world: working as designed is great - nuclear weapons work as designed, but still doesn't mean they are awesome.

if you won't fix it that is ok, I will, but a bummer that you spend more time justifying it vs pondering it.

it was open for all of 20 min.
