### ISSUE TITLE
v4.3.0 Issues - Running outdated UCK firmware

### ISSUE THREAD

**Issue by jimstechsupport** [hjdhjd/homebridge-unifi-protect#221]
**Describe The Problem:**
After updating to the Newest Version (4.3.0) of the Plug-in in the Home App I am getting a "No Response" from the cameras however the controller and NVR are running without issues. I haven't got back a version as there is no way to go back a version to see if this is occurring still after downgrading the plug-in version

**To Reproduce:**
Install latest version and try the Home App to see if you can see the cameras

**Logs:**
12/28/2020
10:38:32 AM Loaded plugin 'homebridge-unifi-protect'12/28/2020
10:38:32 AM [12/27/2020, 5:38:32 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect'12/28/2020
10:38:32 AM Loading 5 platforms...12/28/2020
10:38:32 AM [UniFi Protect] Initializing UniFi Protect platform...

There is no further logs

```
12/28/2020
10:38:32 AM Loaded plugin 'homebridge-unifi-protect'12/28/2020
10:38:32 AM [12/27/2020, 5:38:32 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect'12/28/2020
10:38:32 AM Loading 5 platforms...12/28/2020
10:38:32 AM [UniFi Protect] Initializing UniFi Protect platform...
```

**Homebridge Configuration:**

```json
[
    {
        "address": "10.10.1.199",
        "username": "**************",
        "password": "**************"
    }
]
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 3.3.1
* **Node Version:** 12.19.0
* **Homebridge-UniFi-Protect Plugin Version: 4.3.0
* **UniFi Protect Controller Version: 1.13.7
* **UniFi Protect Controller Type: UCKgen2+
* **Apple Device and iOS / macOS / iPadOS / tvOS Version: iOS 14.3
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Thanks for the report. Let’s troubleshoot this, shall we?

A few things:

* What’s your firmware version on the UCK?
* There is no Homebridge version 3.3.1 - what version of Homebridge are you running?

You can always revert to any version of any plugin by installing it manually. You install a specific version of any plugin with: `npm -g install packagename@version`

**Comment by jimstechsupport** [comment]
Hi, Sorry the Homebridge version is correct however I am running HOOBS not Homebridge on my RP

Firmware Ver for the UCK is 1.1.13 however there is an update to v2.0.24 which I am currently upgrading the UCK up to and I tried to roll back to v4.2.0 however I am getting an error I am looking into now as well.

hoobs@hoobs:~ $ npm -g install homebridge-unifi-protect@4.2.0
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-12-28T01_35_58_108Z-debug.log

**Comment by hjdhjd** [comment]
Suggest you review changelogs closely before updating to new versions of homebridge-unifi-protect`. :smile:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Changelog.md#430-2020-12-26

Your UCK firmware is out of date. As of v4.3.0 you’ll need to ensure you have v2.0.24 or later installed. It’s a major upgrade, so suggest you take a good look at the changelog and release notes before installing it on your UCK, because a lot will change once you install it.

Best of luck.

**Comment by jimstechsupport** [comment]
I changed the Ownership of node_modules to hoobs it seems to be running the installation now

**Comment by jimstechsupport** [comment]
Slapping forhead right now lol I was just realizing that could be the issue and since upgrading the UCK it come good again.. Thanks for the fast and prompt reply and I love the plug-in works great.

Cheers and have a Happy New Year :)

**Comment by hjdhjd** [comment]
Happy New Year to you as well. Enjoy the holiday, and appreciate the support...if you’d like to show more of your support - star the plugin repo or my username. Thanks!

**Comment by roycepope** [comment]
@hjdhjd What about UVNR4 firmware? You mention UCK but I am running the 1U rack unit with v.1.2.17 Firmware (Which is on a different firmware release path than the UCK) and your release notes don't mention it.

**Comment by hjdhjd** [comment]
I'm intimately familiar with the UNVR (have one of those too! 😄)...my release notes don't mention it for a reason: they aren't relevant to that particular note. 

The issue at hand is that Ubiquiti has updated the UCKgen2+ to use the same codebase as UDMP, UNVR, etc - UniFi OS. I've removed legacy support for the old UCK firmwares. It both enables more features for people using this plugin with UCK and simplifies my life as a developer.

The notes don't mention non-UCK devices because they are not impacted by the change.

**Comment by roycepope** [comment]
Thanks for the quick response! I'm glad you have one of these too :) The reason I ask is I was trying to figure out why all my cameras now show "No Response" (After updating to v4.3.5) in the Home app when I try to view the feed. Which led me to this issue thread. I'm thinking the best course of action then for me is to create another issue sighting for my particular issue where I can put all the relevant details of my hardware/versions. Would you agree?

Are you running the same firmware as me on your UNVR4 and its all working? v.1.2.17

Thanks!

**Comment by hjdhjd** [comment]
Please don't hijack this issue with a different one. If you'd like support for another issue, please open one. Thanks!
