### ISSUE TITLE
v4.3.0 and later - UCK: No cameras show up

### ISSUE THREAD

**Issue by commander-flatus** [hjdhjd/homebridge-unifi-protect#228]
I have a fairly vanilla installation. I have 3 protect cameras G3 dome, G3 bullet and G3 mini. All attached to a single UCK2. I have double-triple-quadruple checked the login and password and they're correct. I have ensures that the user account I'm using has admin permissions. I have ensured all RTSP feeds are enabled.

I have no cameras show up in homebridge (I'm using HOOBS on an RPi 3b.

**To Reproduce:**
Have reproduced with fresh install.

**Logs:**
1/1/2021, 6:11:10 AM [1/1/2021, 5:11:09 AM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
1/1/2021, 6:11:10 AM Loading 1 platforms...
1/1/2021, 6:11:10 AM [UniFi Protect] Initializing UniFi Protect platform...
1/1/2021, 6:11:10 AM Bridge is running on port 51826.
1/1/2021, 6:12:37 AM Got SIGINT, shutting down Bridge...
1/1/2021, 6:12:44 AM Loaded plugin 'homebridge-unifi-protect'
1/1/2021, 6:12:44 AM [1/1/2021, 5:12:44 AM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
1/1/2021, 6:12:44 AM Loading 1 platforms...
1/1/2021, 6:12:44 AM [UniFi Protect] Initializing UniFi Protect platform...
1/1/2021, 6:12:44 AM Bridge is running on port 51826.
1/1/2021, 6:13:06 AM Got SIGINT, shutting down Bridge...
1/1/2021, 6:13:13 AM Loaded plugin 'homebridge-unifi-protect'
1/1/2021, 6:13:13 AM [1/1/2021, 5:13:13 AM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
1/1/2021, 6:13:13 AM Loading 1 platforms...
1/1/2021, 6:13:13 AM [UniFi Protect] Initializing UniFi Protect platform...
1/1/2021, 6:13:13 AM Bridge is running on port 51826.
1/1/2021, 6:21:11 AM Got SIGINT, shutting down Bridge...
1/1/2021, 6:21:18 AM Loaded plugin 'homebridge-unifi-protect'
1/1/2021, 6:21:18 AM [1/1/2021, 5:21:18 AM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
1/1/2021, 6:21:18 AM Loading 1 platforms...
1/1/2021, 6:21:18 AM [UniFi Protect] Initializing UniFi Protect platform...
1/1/2021, 6:21:18 AM Bridge is running on port 51826.

**Homebridge Configuration:**

{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "xxx",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "36528"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "xxx",
        "username": "xxx"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "UniFi Protect",
            "plugin_map": {
                "plugin_name": "homebridge-unifi-protect"
            },
            "controllers": [
                {
                    "address": "192.168.11.209",
                    "username": "xxx",
                    "password": "xxx"
                }
            ],
            "options": [
                "Enable.Video.Stream.Only.Low" <----- i've tried including this, didn't change anything
            ],
            "videoProcessor": "/home/hoobs/.hoobs/node_modules/ffmpeg-for-homebridge/ffmpeg" <----- I've tried this and leaving it blank, didn't change anything
        }
    ]
}

**Screenshots:**

<img width="1434" alt="Screen Shot 2021-01-01 at 6 47 37 AM" src="https://user-images.githubusercontent.com/26506741/103438879-a0b5a500-4bfd-11eb-9695-35780dfc09c4.png">
<img width="1437" alt="Screen Shot 2021-01-01 at 6 47 50 AM" src="https://user-images.githubusercontent.com/26506741/103438881-a8754980-4bfd-11eb-85fc-4fd23435fcca.png">
<img width="1440" alt="Screen Shot 2021-01-01 at 6 48 22 AM" src="https://user-images.githubusercontent.com/26506741/103438884-ad39fd80-4bfd-11eb-95f5-793de364ff49.png">
<img width="489" alt="Screen Shot 2021-01-01 at 6 49 38 AM" src="https://user-images.githubusercontent.com/26506741/103438886-b32fde80-4bfd-11eb-884e-0599baf7ad95.png">

**Environment:**

* **Homebridge Version:** hoobs 3.3.1
* **Node Version:** 14.15.1
* **Homebridge-UniFi-Protect Plugin Version:** latest
* **UniFi Protect Controller Version:**latest
* **UniFi Protect Controller Type:** UCKgen2+
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iphone, ipad and mac latests versions
* **Operating System and OS Version:** hoobs prebuilt sd image on RPi 3b+

**Comment by hjdhjd** [comment]
Happy new year. Please read the documentation and release notes carefully:

https://github.com/hjdhjd/homebridge-unifi-protect#things-to-be-aware-of
https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Changelog.md#430-2020-12-26

You aren’t on the latest UCK firmware, which is different than the latest Protect controller.

**Comment by commander-flatus** [comment]
Ugh! That was it. Thank you and happy new year to you too!
