### ISSUE TITLE
Local user doesn't appear to login, can't see any cameras

### ISSUE THREAD

**Issue by keeniemeenie** [hjdhjd/homebridge-unifi-protect#234]
**Describe The Problem:**
I've installed and configured the package as per the instructions (using the UI) but am unable to see any cameras.  I've created a local user on the NVR and used these credentials but the Unifi UI indicates this user has never logged in. I am using the IP address of the Cloudkey Gen2+  and am able to access port 7443 from the machine homebridge.io is running on.  I've had poke about and am confident there are no network issues between the host and the protect box.  The protect system is working well and the rest of the homebridge setup works well.  I can't see anything useful in the logs I'm afraid. I'm an experienced unix developer so happy to troubleshoot!

**To Reproduce:**
Configure the the plugin with IP address, local user name and password. 

**Logs:**

The only logging appears to be the initializing message..
```
homebridge.log:[1/3/2021, 8:12:31 AM] Loaded plugin: homebridge-unifi-protect@4.3.5
homebridge.log:[1/3/2021, 8:12:31 AM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
homebridge.log:[1/3/2021, 8:12:31 AM] [UniFi Protect] Initializing UniFi Protect platform...```

**Homebridge Configuration:**

```json
{
            "controllers": [
                {
                    "address": "192.168.1.205",
                    "name": "CloudKey",
                    "password": "-------",
                    "username": "localuser"
                }
            ],
            "platform": "UniFi Protect"
        },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:**  1.2.5
* **Node Version:** 14.15.3 
* **Homebridge-UniFi-Protect Plugin Version:** 4.3.5
* **UniFi Protect Version:** WebUI: 1.22.2 Controller: 1.13.7
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** Controller 1.13.7
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPadOS 14.2 / macoS 11.1 iOS 14.2
* **Operating System and OS Version:**  Debian Buster 10

**Comment by hjdhjd** [comment]
You are running outdated UCK firmware. Please see the release notes and README:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Changelog.md#430-2020-12-26
https://github.com/hjdhjd/homebridge-unifi-protect#things-to-be-aware-of

The latest production UCK firmware is 2.0.28, I believe.

Good luck!

**Comment by keeniemeenie** [comment]
Sorry! Must have missed that update in the new Unifi UI! Thanks for pointing out my mistake - works fine now - its a great piece of work
