### ISSUE TITLE
Doorbell press exposed as a button/switch

### ISSUE THREAD

**Issue by johnlcoxjr** [hjdhjd/homebridge-unifi-protect#235]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
I would like to use a doorbell button press as a trigger to turn lights on.

**Describe alternatives you've considered:**
I looked at just using the motion capabilities.  However since some are false alarms, I would like to know when someone is really there.

**Additional context:**
None

**Comment by hjdhjd** [comment]
Happy new year!

RTFM. 😄 

This feature already exists. The plugin has extensive documentation, I’ll leave it as an exercise to the reader to discover it. 😛

**Comment by johnlcoxjr** [comment]
Sorry.  Thank you.  I must have missed it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
