### ISSUE TITLE
Plugin fails to start with "Throttling API calls..." error

### ISSUE THREAD

**Issue by joneleth** [hjdhjd/homebridge-unifi-protect#242]
**Describe The Problem:**
I have a fresh installation of Homebridge with the homebridge-unifi-protect plugin, and the plugin fails to start with a "Throttling API calls due to errors..." error. No additional info is available in the log. 

**To Reproduce:**
* Installed homebridge using the steps outlined in the documentation.
* Checked available firmware and UniFi Protect updates (everything was up to date).
* Created a local superadmin on UDM-Pro, and enabled all RTSP streams on the single G3 Flex camera I have (verified the streams with VLC).
* Installed homebridge-unifi-protect documentation and set it up with the controller address/local account etc.
* Restarted Homebridge server.

**Logs:**

```
[1/6/2021, 2:19:18 PM] [HB Supervisor] Restarting Homebridge...
[1/6/2021, 2:19:18 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[1/6/2021, 2:19:18 PM] [HB Supervisor] Started Homebridge v1.1.7 with PID: 2754
[1/6/2021, 2:19:18 PM] Loaded config.json with 0 accessories and 2 platforms.
[1/6/2021, 2:19:18 PM] ---
[1/6/2021, 2:19:18 PM] Loaded plugin: homebridge-config-ui-x@4.36.0
[1/6/2021, 2:19:18 PM] Registering platform 'homebridge-config-ui-x.config'
[1/6/2021, 2:19:18 PM] ---
[1/6/2021, 2:19:18 PM] Loaded plugin: homebridge-unifi-protect@4.3.5
[1/6/2021, 2:19:18 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[1/6/2021, 2:19:18 PM] ---
[1/6/2021, 2:19:18 PM] Loading 2 platforms...
[1/6/2021, 2:19:18 PM] [Config] Initializing config platform...
[1/6/2021, 2:19:18 PM] [Config] Running in Service Mode
[1/6/2021, 2:19:18 PM] [UniFi Protect] Initializing UniFi Protect platform...
Setup Payload:
X-HM://0024JO3XLN3MF
Enter this code with your HomeKit app on your iOS device to pair with Homebridge: <code>
[1/6/2021, 2:19:18 PM] Homebridge is running on port 51424.
[1/6/2021, 2:19:49 PM] [UniFi Protect] 192.168.1.1: Throttling API calls due to errors with the 10 previous attempts. I'll retry again in 5 minutes.
```

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge 8FC6",
        "username": <username>,
        "port": 51424,
        "pin": <pin>
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "192.168.1.1",
                    "password": <password>,
                    "username": <username>
                }
            ],
            "verboseFfmpeg": false,
            "platform": "UniFi Protect"
        }
    ]
}
```

**Screenshots:**
N/A

**Environment:**

* **Homebridge Version:** v1.1.7
* **Node Version:** v14.15.4
* **Homebridge-UniFi-Protect Plugin Version:** v4.3.5
* **UniFi Protect Version:** v1.16.9
* **UniFi Protect Controller Type:** UDM-Pro
* **UniFi Protect Controller Firmware Version:** v1.8.5
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 12 Pro Max, iOS 14.3
* **Operating System and OS Version:** Ubuntu Focal Fossa (20.04.1 LTS)

**Comment by hjdhjd** [comment]
I’ll ask the obvious one, please forgive the question...are you sure Protect is running on the UDM Pro? :smile:
Are you sure you don’t have firewall rules or subnet issues constraining connectivity back to the UDMP?
Are you sure the Ubiquiti (or local UDMP) username / password entered in the homebridge configuration?

The error you’re reporting is effectively an error communicating with the Protect controller...I’d take a closer look and make sure your UDMP -> homebridge connectivity is unencumbered.

You might also try, just for the heck of it, rebooting the UDMP as well if you think most of the above is correct.

**Comment by joneleth** [comment]
Yes, UniFi Protect status was the first thing I checked :) I've actually been looking into Homebridge because while the Protect app on iOS works just fine, but it requests 2FA authentication every time which is a little inconvenient.

The only thing in my setup that's worth noting is that the controller and the Homebridge server are on separate VLANs. However, I haven't set up any VLAN isolation rules in the UDM yet (all firewall rules are default ones at the moment), and I was able to get the same setup working with Home Assistant.

I ran some experiments, and putting the server on the same VLAN seems to resolve the issue. Putting them back to separate VLANs breaks it again. Are there any restrictions on the plugin regarding which subnet the Homebridge server is?

**Comment by hjdhjd** [comment]
Nope, beyond ensuring it can get to the Protect controller. Sounds like you have a VLAN / firewall rule issue.

If you can get the Protect controller webUI from the IP/VLAN where you have Homebridge, then `homebridge-unifi-protect` will work.

2FA is not supported in this plugin. You’ll need to either disable it, or setup a local user (which is what I would recommend doing). Instructions for doing so are beyond the scope of this plugin.

**Comment by joneleth** [comment]
Yes, I am using a local user (changed it to a limited admin with full Protect access). I'll investigate my network setup, it's pretty clear that the plugin is working fine at this point. Thanks for the help!
