### ISSUE TITLE
No connection when on cellular, everything else works

### ISSUE THREAD

**Issue by dmham187** [hjdhjd/homebridge-unifi-protect#244]
**Describe The Problem:**
Video stream isn't working on my iPhone when I'm not in the local network. I use an old iPad mini 2 as Homekit hub. Switches are working and also the still image of the camera shows up. When I click on the camera I can't even see a streaming request in the Homebridge log. I activated the "Enable.Video.Stream.Only.Low" option, but that doesn't help.

**To Reproduce:**
Access camera stream in Home-App from cellular. 

**Logs:**
Nothing shows up in the logs.

**Homebridge Configuration:**

```json
        {
            "controllers": [
                {
                    "address": "192.168.10.2",
                    "password": "***",
                    "refreshInterval": 10,
                    "username": "***"
                }
            ],
            "options": [
                "Enable.Video.Stream.Only.Low"
            ],
            "motionDuration": 7,
            "verboseFfmpeg": false,
            "platform": "UniFi Protect"
        }
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.1.7
* **Node Version:** v14.15.4 
* **Homebridge-UniFi-Protect Plugin Version:** v4.3.5 
* **UniFi Protect Version:** 1.16.9
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 2.0.24
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone X on iOS 14.2, iPad Mini 2 on iOS 12.4.9 used as hub
* **Operating System and OS Version:** Ubuntu 20.04

**Comment by hjdhjd** [comment]
Before we triage this...have you taken a close look at the documentation, particularly the Troubleshooting section? 😄

**Comment by dmham187** [comment]
Yes I did, but without success. There is no firewall between the Unifi Protect / CKgen2+ and the Wifi where the iPad is logged in. Only the cam is in a secure VLAN, but as homebridge doesn't access the cam directly, that shouldn't matter. I fear the iPad is the problem in my setup, as it is old and doesn't get newer iOS Versions. But can't check that for now.

**Comment by hjdhjd** [comment]
Okay. Walk me through what, specifically, have you tried?

**Comment by hjdhjd** [comment]
I also assume your HomeKit hub works over cellular, in general? As in you can access and control other HomeKit devices via cellular. 

If so, my first guess would be that you have a firewall issue of some sort. Give the iPad unrestricted access to wherever you have Homebridge. This isn’t a plugin issue or a streaming issue, I would wager. My guess is that this boils down to your network configuration. Start with a very permissive configuration and then progressively lock things down until something breaks and you’ll know you’ve found it.

**Comment by dmham187** [comment]
> Okay. Walk me through what, specifically, have you tried?

I read the complete troubleshooting section. This is what I did / checked:

- there is no firewall between the iPad and Homebridge, just a dumb switch and the access point
- I tried "Enable.Video.Stream.Only.Low" and "Enable.Video.Transcode", which both work while in LAN

As there is no streaming request showing up in the Homebridge log, I think it's a problem within Homekit. But I don't know how to debug that.

> I also assume your HomeKit hub works over cellular, in general? As in you can access and control other HomeKit devices via cellular.

That's right, I can switch lights without problems. Even the still image from the cam shows, only the stream isn't working.

**Comment by hjdhjd** [comment]
Problem isn’t in HomeKit. Problem is definitely in the network connection between iDevice_on_cellular -> iPad -> Homebridge. Some part of that connection equation is broken. It’s not a plugin issue. :smile:

**Comment by dmham187** [comment]
Ok, thank you for your time. Maybe I try a more recent device as hub tomorrow.

**Comment by hjdhjd** [comment]
The fact that the iPad is older is almost certainly not the issue. If you’ve got iOS 12+, you should be more than good. Good luck.
