### ISSUE TITLE
Two-Factor Authentication support for homebridge-unifi-protect Plugin 

### ISSUE THREAD

**Issue by AllanF1** [hjdhjd/homebridge-unifi-protect#248]
Video does not work in Homekit after enabling Unifi Two-Factor Authentication.

**Comment by fpuigb** [comment]
It's working for me.

**Comment by AllanF1** [comment]
Is there any additional setting in Home bridge to configure after enabling Unifi Two-Factor Authentication ?

**Comment by fpuigb** [comment]
Do you have your plug-in configured to access your NVR with a local account? not a cloud account.

**Comment by AllanF1** [comment]
I am using local account.
It was working until I restarted homebridge.

**Comment by fpuigb** [comment]
Interesting, I can confirm mine is working with 2FA.

**Comment by AllanF1** [comment]
Will retry and update.

**Comment by hjdhjd** [comment]
Literally says right there in the README that two-factor authentication is not supported. 😄

Really - right there in the README!

As a reminder: I rarely look at these if you don’t use the feature request or issue template. They exist for good reason.

**Comment by AllanF1** [comment]
Apologies, but I checked and could not find it in the readme.
I am still not able to find where it is documented.

Pointe taken on the teamplate.

**Comment by hjdhjd** [comment]
From https://github.com/hjdhjd/homebridge-unifi-protect#plugin-configuration

> You can use your Ubiquiti account credentials, though 2FA is not currently supported. That said, I strongly recommend creating a local user just for Homebridge instead of using this option.

**Comment by AllanF1** [comment]
Reconfigured local account and all works fine now.
Thank you.

**Comment by fpuigb** [comment]
> Reconfigured local account and all works fine now.
> Thank you.

I thought I asked you this [here](https://github.com/hjdhjd/homebridge-unifi-protect/issues/248#issuecomment-759865115). :-)

**Comment by AllanF1** [comment]
Agree,
But for others benefit what I was using was the local admin account.
I configured a seperate account with 'Limited Admin" role with "View" permissions for Unifi Protect.



![image](https://user-images.githubusercontent.com/40647507/104539021-f44dd700-5670-11eb-8283-a28dce9328ab.png)

**Comment by hjdhjd** [comment]
Also ill advised. The administrator role should be given for UniFi Protect if you want the best experience with this plugin.
