### ISSUE TITLE
automation per motion zone

### ISSUE THREAD

**Issue by majkelospl** [hjdhjd/homebridge-unifi-protect#251]
Hi, first - great job with plugin. I'm starting to using it and works fantastic.
Searched manual but not found any information about my case.

**Is your feature request related to a problem? Please describe:**
This is not a problem but idea.
I tried to find option to make automation to specific motion zone (and type).
I have idea that ubnt camera can be a multi zone sensor to make different automations per zones.
For example, turning on different lights depending on where the "move" appeared.
Second thought is to make different automatization for people and vehicle recognition.
I don't know that UBNT API allows for that?
I have mostly G4 cameras with new AI motion detection so it looks perfect for that job.

**Describe the solution you'd like:**
I have no solution, just question :)

**Describe alternatives you've considered:**
I have not alternatives :)

**Additional context:**
no

**Comment by hjdhjd** [comment]
Some of these things will come in future releases. 

Others are not production features in UniFi Protect currently, and this plugin **only** supports production releases of UniFi Protect. You run beta versions at your own risk and I provide zero support for it. :smile:

There will be more to come in the granularity of motion detection this year.

Stay tuned. Thanks for the input.

**Comment by tablatronix** [comment]
Can you provide any info if motion zone is exposed for events somewhere already ?
