### ISSUE TITLE
New feature added in Protect 1.17.1

### ISSUE THREAD

**Issue by FlyingGnomen** [hjdhjd/homebridge-unifi-protect#256]
**Is your feature request related to a problem? Please describe: No

**Describe the solution you'd like: implementation of the new rtsps feature in protect 1.17.1
 Add RTSPS stream support.

**Describe alternatives you've considered: no alternative 

**Additional context: Release notes for 1.17.1

**Comment by hjdhjd** [comment]
It's literally been out less than 24 hours. :smile: This is a hobby in my free time...at least wait a few days before asking for stuff! 😛 

I plan to look at everything released in the latest production version and add support for what makes sense in the near future.

Thanks!

**Comment by FlyingGnomen** [comment]
Sorry didn't mean to offend you, I respect your free time and that this is only a hobby. It obviously can wait, I'm not in a hurry. :-) Please forgive me for posting within 24 hours of the production release. I've been having a lot of use of this free plugin, and your work is very much appreciated.
Have a nice day.

**Comment by hjdhjd** [comment]
Not at all! I love the enthusiasm...I was teasing, that’s all. :smile:

Stay tuned.

**Comment by FlyingGnomen** [comment]
Well ok, I’ll stay tuned. Thank you.
