### ISSUE TITLE
options to include Unifi Protect Smart Floodlight

### ISSUE THREAD

**Issue by OfficialKaos** [hjdhjd/homebridge-unifi-protect#260]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

Please add capabilities for Unifi Protect Smart Floodlight

**Describe alternatives you've considered:**

Motion sensor and light switch

**Additional context:**

I would like to see the motion sensor as a tile and a switch for a light

**Comment by hjdhjd** [comment]
It’s not a released product yet. Early Access stuff isn’t explicitly supported by this. I won’t look into adding support until after it comes out of EA, in keeping with my long-standing practices of not support beta or pre-production releases. We’ll see what the future holds!

**Comment by OfficialKaos** [comment]
excellent and thanks for all the great work put into this

**Comment by hjdhjd** [comment]
Of course. Look forward to seeing the light released in the future. Closing this for now.
