### ISSUE TITLE
g4 doorbell mqqt back to 0 after x seconds

### ISSUE THREAD

**Issue by s31teg** [hjdhjd/homebridge-unifi-protect#264]
Is your feature request related to a problem? Please describe:

Describe the solution you'd like:

Is it possible after 1 second of the doorbell being pressed the doorbell message goes back to 0?

Describe alternatives you've considered:

comparing timestamps but this is not as easy in my home automation loxone controller

Additional context:

na

**Comment by s31teg** [comment]
I actually now see a few requests for this in the closed section.

I guess this functionality is used in homekit. Is it possible to add another message that is able to toggle between 1 and 0?

TIA!

**Comment by s31teg** [comment]
Ok I have it working.

For other loxone users:

Using loxberry and the mqtt local broker. This has an advance option to reset after a send.

**Comment by hjdhjd** [comment]
Thanks for the request, glad you resolved it!
