### ISSUE TITLE
Nothing works?

### ISSUE THREAD

**Issue by vandenbogerd** [hjdhjd/homebridge-unifi-protect#268]
**Describe The Problem:**
I installed the plugin; filled out my credentials (the same as that work with any other Unifi plugin.
I restart HB, nothing happens.

**To Reproduce:**
Several clean installs later, no difference...

**Logs:**
No specifics found in the log

**Homebridge Configuration:**

{
            "controllers": [
                {
                    "address": "192.168.1.11",
                    "password": "PASS",
                    "username": "USER"
                }
            ],
            "platform": "UniFi Protect"
        },

**Screenshots:**
NA

**Environment:**

* **Homebridge Version:** 1.1.7
* **Node Version:** 14.15.1
* **Homebridge-UniFi-Protect Plugin Version:** 4.3.5
* **UniFi Protect Version:** no idea
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 4.26.13
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPad Pro 12.9”
* **Operating System and OS Version:** Raspbian GNU/Linux Buster (10)

**Comment by hjdhjd** [comment]
Hi there! Let’s help you get up and running. So...I see a few things in the above, offhand:

* I’m willing to wager the IP address of our UniFi Protect controller is not 192.168.1.11. I’m guessing that’s the IP of your camera, but that’s not what the documentation or webUI says is needed - it’s asking for the IP address of the UniFi Protect **controller**.
* There’s no way your UniFi Protect Controller firmware version is 4.26.13 - the latest production Protect controller version is 1.17.3. I’d double check what version you are using.
* [You need to ensure your UCKgen2+ is upgraded to at least v2.0.24](https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Changelog.md#430-2020-12-26).

Best of luck.

**Comment by vandenbogerd** [comment]
Cool, I didn’t realise there was a FW update for my CC.
Updated now, and everything works! (Was still on 1.13.7)

Thanks a lot for this eye-opener!
