### ISSUE TITLE
Correct Websocket updates URL

### ISSUE THREAD

**Issue by TechMoDev** [hjdhjd/homebridge-unifi-protect#276]
**Describe The Problem:**
Hopefully you can help me out...

I'm trying to setup a custom configuration, no HomeBridge. And using this very helpfull source along the way. Thanks so far.

**To Reproduce:**
According to <a href="https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/ProtectAPI.md">ProtectAPI.md</a> the websocket updates URL should be:

```
https://protect-nvr-ip/proxy/protect/ws/update?lastUpdateId?lastUpdateId=X
```

But when I interpret <a href="https://github.com/hjdhjd/homebridge-unifi-protect/blob/1d0d28a8b020878ee8f478244bed7ec361b33779/src/protect-api.ts#L225">protect-api.ts</a> I think it should be:

```
wss://protect-nvr-ip/proxy/protect/ws/updates?lastUpdateId:X
```

But I cannot setup the websocket connection in both ways. I am able to read the lastUpdateId from the bootstrap.

What should the correct websocket updates URL be ?

Like this:
```
wss://x.x.x.x/proxy/protect/ws/updates?lastUpdateId:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

**Logs:**
No logs available

**Homebridge Configuration:**
No Homebrigde in use

**Screenshots:**
No screenshots available

**Environment:**

* **Homebridge Version:**  Custom
* **Node Version:** Custom
* **Homebridge-UniFi-Protect Plugin Version:** Current
* **UniFi Protect Version:** 1.17.3
* **UniFi Protect Controller Type:** UDM Pro
* **UniFi Protect Controller Firmware Version:** 1.8.6
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Custom
* **Operating System and OS Version:** Custom

**Comment by hjdhjd** [comment]
The documentation is correct. Your interpretation of my code isn't. 😄 

I can't really help you much further other than to point you there and to the example of my code.

You might want to play with an environment like Chrome's dev tools to get a better sense for things.

Best of luck.

**Comment by TechMoDev** [comment]
Ok. But one thing:

<a href="https://github.com/hjdhjd/homebridge-unifi-protect/blob/1d0d28a8b020878ee8f478244bed7ec361b33779/src/protect-api.ts#L242">Here</a> you create a new websocket:
```
const ws = new WebSocket(this.updatesUrl() + "?" + params.toString(), {
        rejectUnauthorized: false,
        headers: {
          Cookie: this.headers.get("Cookie") ?? ""
        }
```
Where <a href="https://github.com/hjdhjd/homebridge-unifi-protect/blob/1d0d28a8b020878ee8f478244bed7ec361b33779/src/protect-api.ts#L560">updatesUrl()</a> returns:
```
return "wss://" + this.nvrAddress + "/proxy/protect/ws/updates";
```
And the next following thing after calling the function updatesUrl() in creating the websocket is concat a question mark. How is it  then possible that the websocket URL you mention contains "update?" and not "updates?" ?

```
https://protect-nvr-ip/proxy/protect/ws/update?lastUpdateId?lastUpdateId=X
```

**Comment by hjdhjd** [comment]
As I mentioned above: the URI indicator was incorrect in the documentation, now fixed. If you're referring to the singular versus plural reference, the plural is correct, the singular is an autocorrect issue that the documentation's been updated to reflect it. Appreciate you pointing out the housekeeping item. The rest of your conjecture about the parameters attached to the URI, are incorrect. Cheers.
