### ISSUE TITLE
Add Motion Sensor History with fakegato-history

### ISSUE THREAD

**Issue by tmur11** [hjdhjd/homebridge-unifi-protect#278]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
Please add motion sensor history with fakegato characteristics

**Describe alternatives you've considered:**

**Additional context:**
homebridge-platform-wemo has incorporated motion history into wemo sensors

**Comment by hjdhjd** [comment]
Thanks for the suggestion...it’s an interesting one in some ways. I have no intention of adding this capability at this time. As a general rule, I don’t add functionality that I don’t believe is widely useful or necessary...this is way out there as a niche edge case.

If you want to do something like this, there’s MQTT support and you can roll your own with one of the other fakegato plugins.

I reserve the right to reconsider in the future...but I’ll note that non-native-Home-app support is not an area of interest for me.

PS: Genuinely appreciate the suggestion...just not one I’m likely to implement.
