### ISSUE TITLE
Something broke the Live RTSP Stream in HomeKit

### ISSUE THREAD

**Issue by wingcomm** [hjdhjd/homebridge-unifi-protect#280]
**Describe The Problem:**
I am no longer able to stream from my cameras to some iOS devices iPhones and iPads running 14.4. I get an error message that says: "No Response: This camera is not responding." It works fine on some of my computers and not others on the same local network. The iOS devices are also on the same local network. RTSP is enabled on all of the cameras.

**To Reproduce:**

Open the Home App in iOS and then tap on the camera thumbnail view to bring up the live stream.

**Logs:**

```
[2/6/2021, 3:57:42 AM] [UniFi Protect] SiteName [UCK-G2-PLUS] CameraName [UVC G3 Instant]: HomeKit video stream request received: 1280x720, 30 fps, 299 kbps.
[2/6/2021, 3:58:02 AM] [UniFi Protect] SiteName [UCK-G2-PLUS] CameraName [UVC G3 Instant]: Device appears to be inactive for over 5 seconds. Stopping stream.
[2/6/2021, 3:58:02 AM] [UniFi Protect] SiteName [UCK-G2-PLUS] CameraName [UVC G3 Instant]: Stopped video streaming session.
[2/6/2021, 3:58:17 AM] [UniFi Protect] SiteName [UCK-G2-PLUS] CameraName [UVC G3 Instant]: Device appears to be inactive for over 5 seconds. Stopping stream.
[2/6/2021, 3:58:17 AM] [UniFi Protect] SiteName [UCK-G2-PLUS] CameraName [UVC G3 Instant]: Stopped video streaming session.
```

**Homebridge Configuration:**

```json
"platforms": [
        {
            "debug": false,
            "controllers": [
                {
                    "address": "1.2.3.4",
                    "name": "SiteName",
                    "password": "password",
                    "refreshInterval": 5,
                    "username": "homebridge"
                }
            ],
            "platform": "UniFi Protect"
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
```

**Screenshots:**

![IMG_2330](https://user-images.githubusercontent.com/9159510/107114644-6d39ec00-6835-11eb-82eb-991d481ef84c.jpg)

**Environment:**

* **Homebridge Version: 1.1.7** 
* **Node Version: v12.18.2** 
* **Homebridge-UniFi-Protect Plugin Version: homebridge-unifi-protect2 v3.6.3**
* **UniFi Protect Version:1.17.3** 
* **UniFi Protect Controller Type: UCKG2+** 
* **UniFi Protect Controller Firmware Version: 2.0.27** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version: 14.4**
* **Operating System and OS Version: Docker (oznu/docker-homebridge:latest) Alpine Linux 3.12.0**

**Comment by hjdhjd** [comment]
Hi there..this one looks pretty straightforward. You’re using a now-ancient version of `homebridge-unifi-protect`. :smile:

The current version of the plugin is 4.3.5.

I’d strongly advise reading the release notes when new versions of this (or any) plugin are released. There are often important details there.

In short, you need to uninstall the plugin and install `homebridge-unifi-protect` as the name has changed.

**Comment by wingcomm** [comment]
Thank you for the excellent tech support! 😄

I nuked the old version and upgraded to 4.3.5, however the issue still persists...live streams are no longer working. I did remove and re-add HomeBridge to my Home, but it made no difference...

**Comment by hjdhjd** [comment]
Assuming everything else was working fine...when I’ve seen issues like this in the past, it typically is confusion on Homebridge’s part over which network interface to use to send streams back to a HomeKit client. How many network interfaces do you have on your docker image, and did something get added / change at some point? :smile:

**Comment by wingcomm** [comment]
That fixed it! I have had multiple NICs enabled since I installed this a while ago...for troubleshooting some issues with my server. It looks some recent changes in your code or my docker server's code made this an issue. Dropping it to one NIC seems to have resolved this issue.

**Comment by hjdhjd** [comment]
It has nothing to do with `homebridge-unifi-protect` I'm afraid...please don't ascribe fault to where there is none. :smile:

Homebridge decides which interfaces to use...I would suggest opening an issue there (or adding to an existing one if they're tracking it on a single issue), as they have been tracking this particular issue for some time.
