### ISSUE TITLE
G4 doorbell not always triggering

### ISSUE THREAD

**Issue by denniedegroot** [hjdhjd/homebridge-unifi-protect#287]
**Describe The Problem:**
The G4 doorbell is not always triggering. This is due to the following line:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/3552015940a47ed91216a741183084a9064e813a/src/protect-nvr-events.ts#L212

A payload can contain both a lastMotion and lastRing object. So the "return" needs to be deleted.

**To Reproduce:**
Dance before the G4 Doorbell and press the button.

**Logs:**
Both JSON messages when a doorbell is pressed with and without motion detected:
```
{ lastRing: 1612884026670 }
```
```
{
  lastMotion: 1612883092648,
  isMotionDetected: true,
  lastRing: 1612883093292
}
```

**Homebridge Configuration:**

**Screenshots:**

**Environment:**

* **Homebridge Version:** v4.37.0
* **Node Version:** v14.15.4
* **Homebridge-UniFi-Protect Plugin Version:** v4.3.5
* **UniFi Protect Version:** 1.17.3
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.9.0-10
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:** Debian 10.8

**Comment by durosity** [comment]
Never have I seen "Dance" as being a step to recreate an issue before!  

Just FYI the dev doesn't support beta software releases which is what I think you're running on your UDMP, but it may be a change they'll need to make when unifi publish it publicly.

**Comment by hjdhjd** [comment]
As I said [elsewhere](https://github.com/hjdhjd/homebridge-unifi-protect/issues/286#issuecomment-776032418), I’m aware and it will be addressed in a future release. Thanks.
