### ISSUE TITLE
dynamic motionDuration setting

### ISSUE THREAD

**Issue by majkelospl** [hjdhjd/homebridge-unifi-protect#288]
**Is your feature request related to a problem? Please describe:**
no

**Describe the solution you'd like:**
It would be grate if "motionDuration" was dynamic based on motion event time from Protect instead of static 10 seconds (or another static time).
Now when I’m testing Smart Motion recognizing events on Protect, I think works mostly perfect. This combo would be ideal for turning on and off lights on my the terrace.
I don’t know that API allow for that, I hope yes :)

**Describe alternatives you've considered:**
Nop.

**Additional context:**
There is no additional context.

**Comment by hjdhjd** [comment]
I might consider this in the future. There are some other things that are coming with respect to motion in the near future.

In practice - it tends to be a bad idea because it becomes very easy to spam a user with HomeKit notifications. Protect’s motion durations are not very good proxies for HomeKit, in general. So...don’t expect this to be a priority, but I’m willing to consider it in the future.

**Comment by majkelospl** [comment]
Thx for considering this. I think that new "Smart Motion" shouldn't spam like normal Motion Algorithm based on change of pixels. If it will help I can test anything You want. I have 4 x G4 cameras + 1 x G3 Flex on UDM Pro. For now I can say that Smart Motion works fine 99% of time.

**Comment by majkelospl** [comment]
I'm just thinking, that You can make some option like "MinimumMotionTime" that will prevent spamming. 
The goal is that the light shines as much as someone is within range of the lamp. I can imagine a situation that the minimum lamp lighting time will be, for example, 10 seconds, it does not bother me at all.

**Comment by hjdhjd** [comment]
It’s not just about you. 😄 

Appreciate the offer, but I’ve got a pretty robust test setup. Again...nothing is happening here for some time. I have other priorities right now. Thanks again for your feedback!
