### ISSUE TITLE
Notifications on Apple TV

### ISSUE THREAD

**Issue by jcleek** [hjdhjd/homebridge-unifi-protect#291]
**Is your feature request related to a problem? Please describe:**
Switching from Ring (also not Homekit) to Unifi Protect and trying to replicate the doorbell notifications on my Apple TV. I get them on the phone but not TV. Is that supposed to work?

**Describe the solution you'd like:**
When the doorbell rings I would like to have Apple Home show me the camera on my Apple TV.

**Describe alternatives you've considered:**
Going back to my Ring doorbell which really isn't an option I like

**Additional context:**

**Comment by hjdhjd** [comment]
This feature already exists and works by default. If you’re having issues, I suggest using the Discord or filing a detailed bug report. :smile: I’d also check the firewall rules you’re using...many of us use this feature daily.

Good luck!
