### ISSUE TITLE
Homekit Secure Video support

### ISSUE THREAD

**Issue by golbinski** [hjdhjd/homebridge-unifi-protect#300]
**Is your feature request related to a problem? Please describe:**
Apple published their own cloud based storage for the video recording with facial recognition feature of top of it. Would be great to extend the plugin to support that for Unify Protect cameras/doorbells.

**Describe the solution you'd like:**
Apple has not published any non-commercial documentation regarding the specification of the HomeKit Secure Video support, but there are unofficial reversed engineered documentation:
https://github.com/Supereg/secure-video-specification

**Describe alternatives you've considered:**
Setup a server with python face-recognition module plugged in to some RTPS stream of Unify cameras.

**Additional context:**
N/A

**Comment by hjdhjd** [comment]
This has been extensively covered in other feature requests. Please search for them to read more on this. This is on the roadmap, and yes, we (the collective Homebridge community) is working to figure it out.

There will be no timeline or commitment on this right now. Thanks.

**Comment by durosity** [comment]
@hjdhjd Could I suggest you modify the form you use to automatically close tickets that don't follow the predefined format to also search for any use of the term Secure Video and HKSV and automatically close them too? It seems like there's a request for this every single day and it must be infuriating!

**Comment by hjdhjd** [comment]
Yes, it can be...amusing.
