### ISSUE TITLE
remote access (through ATV4 or HomePod)

### ISSUE THREAD

**Issue by cleviwhite** [hjdhjd/homebridge-unifi-protect#315]
**Describe The Problem:**
I have both a HomePod and Apple TV in my home. Other HomeBridge accessories work remotely (ie, when not on local wifi network). Cameras connected through this plugin do not.

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** latest
* **Node Version:** latest
* **Homebridge-UniFi-Protect Plugin Version:** latest
* **UniFi Protect Version:** latest
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** tested on every apple device, iOS on 14.4
* **Operating System and OS Version:** Docker

**Comment by hjdhjd** [comment]
My guess is this is either related to a HomeKit permissions issue in the Home app, or a network / firewall configuration challenge. I, and hundreds of others, have these exact scenarios, so we know it works. :smile:

The key question is, why yours doesn’t. I’d suggest taking a close look at the above areas.

**Comment by cleviwhite** [comment]
Okay! Just wanting to make sure that this wasn't intended functionality (maybe that remote access for unifi in HomeKit wasn't supported).

I have done much digging, but will start combing through again!

I could technically rule out a routing/firewall issue since other appliances work remotely?

**Comment by cleviwhite** [comment]
[3/3/2021, 11:37:55 AM] [homebridge-unifi-protect] wNet [UDM-PRO] Front Door [UVC G4 Doorbell]: Streaming request from 192.168.3.126: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1600x1200@30fps (High), 6000 kbps.
[3/3/2021, 11:38:14 AM] [homebridge-unifi-protect] wNet [UDM-PRO] Front Door [UVC G4 Doorbell]: Stopped video streaming session.


So the logs show that the video is requested, and HomeKit does in fact load the current snapshot in, but will never start the video session. It finally just says device unresponsive.

**Comment by cleviwhite** [comment]
Update: I think I got it. I changed my HomeKit Hub from HomePod to Apple TV. Remote works - kinda. The video only plays for about 5 seconds and freezes, but the audio continues. Then the whole stream disconnects and I have to go back in. The log reflects the stream session closing.

**Comment by hjdhjd** [comment]
Glad you got it resolved. Closing this one.

**Comment by cleviwhite** [comment]
Any insight on the stream randomly dropping?
