### ISSUE TITLE
allow Enable.Motion.Trigger while ignoring motion events from protect itself 

### ISSUE THREAD

**Issue by justme-1968** [hjdhjd/homebridge-unifi-protect#319]
**Is your feature request related to a problem? Please describe:**
no

**Describe the solution you'd like:**
i would like to be able to use Enable.Motion.Trigger but ignore all motion events from protect itself.

**Describe alternatives you've considered:**
none

**Additional context:**
i have experienced the unifi generated motion events to be unreliable and useless. but i have very reliable doorbell and motion sensors in my home automation system. i would like to trigger a rich notification with the motion trigger whenever i detect the doorbell in my home automation system.

**Comment by hjdhjd** [comment]
Your experience doesn’t match mine. I’ve seen motion detection be quite good, actually ***if*** you put a decent amount of time into understanding how it works and tailoring it to your use case...but everyone’s experience is unique. 

If you don’t want Protect to do motion detection, then disable motion zones in UniFi Protect.

The entire point of this plugin, to a large degree, is to provide a seamless experience in connecting existing Protect capabilities to HomeKit.

If there’s something I’m missing, please feel free to elaborate...I’m disinclined to add this functionality, but open to reconsidering if there are good use cases for why this feature should exist.

**Comment by justme-1968** [comment]
yes, my experience does not match. i get events from clouds, trees, shadows, cars you name it. and i'm not the only one. if i start tuning then i can reduce false positives. but only at the cost of false negatives. which is also not good. but that is besides the point. it really depends on the surroundings.

i still use the events inside the protect ui to get a overview for potential critical things and would like continue do so. but i don't want these events to go to homekit as they are to unreliable and there are to many.

the events from my doorbell and the real motion sensors are much better and i would love to have them in a rich notification. a few iOS versions ago it was possible to just put a motion sensor from a different accessory into the same homekit room to get a rich notification. unfortunately this is no longer supported and the camera and the motion sensor have to belong to the same accessory.

so allowing Enable.Motion.Trigger even if Disable.Motion.Sensor is set would solve this problem in a very clean way. and it is the only possibility since apple has disabled the two accessory approach. it would be very much appreciated.

maybe using a third value besides Enable.Motion.Trigger and Disable.Motion.Trigger like Force.Motion.Trigger to avoid any potential side effects for existing installations.



by the way: during my testing i have noticed that the notifications i get on my iPhone will include the image if the event is triggered by the motion trigger device but will not include an image if the event is triggered directly by the camera event. but i had no time to look deeper.

**Comment by hjdhjd** [comment]
If you want to effectively make the Protect camera "just a camera" - *which is essentially what you are describing above* - lots of other plugins out there that you can use for that, most notably homebridge-camera-ffmpeg maintained by a great guy and a friend. 

Otherwise...I'll consider it, but I make no commitments, and this isn't going to be a priority anytime soon.

**Comment by justme-1968** [comment]
yes. that would be possible. but then i would miss many of the other nice features of this plugin. but thanks.

would a working patch or pull request for this feature help?

**Comment by hjdhjd** [comment]
Nope. It's not about the PR - it's half a dozen lines of code or so to implement this :smile: - it's about whether I want to add in the kitchen sink and increase technical debt over time. It's a fine line. I'm not unsympathetic to the challenge you have, I just want to be intentional in the things that are added to this plugin.

Let me noodle on this.

**Comment by hjdhjd** [comment]
Check out v4.4.0...should help in this use case. Thanks for the suggestion!

**Comment by justme-1968** [comment]
will do. thanks !
