### ISSUE TITLE
G3 Instant Support

### ISSUE THREAD

**Issue by mmmonn7** [hjdhjd/homebridge-unifi-protect#322]
**Describe The Problem:**

It doesn't seem to support the new G3 Instant.  It does not find the cam.
**To Reproduce:**

Pluged in cam.  Finds it within Protect.  Never finds in in Homebrdige
**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
It does support it. I have one. :smile:

**Comment by mmmonn7** [comment]
Really??  anything special you did?  Ive tried restarting, reconfigure the instance, stop and start the hoembridge service.

**Comment by hjdhjd** [comment]
The plugin will auto detect any and all changes to the number of cameras. I doubt it’s a plugin issue. 

I wrote the plugin with a healthy amount of logging in mind - it will tell you what cameras it sees. If the Homebridge logs show the camera is detected - you’re just not looking for it in the right place in the Home app would be my guess.

**Comment by mmmonn7** [comment]
Sorry for the continued questions.  I have 4 others that show up fine.  they are all on the same controller.  Should I remove the instance from the controller and reconfigure?  Thanks for your help.

**Comment by hjdhjd** [comment]
You didn't fill out anything of substance in the bug request. Please go back and provide the requested Homebridge logs if you'd like meaningful support. Saying "it doesn't show up" isn't a path to getting this resolved. The forms exist for a reason. :smile:
