### ISSUE TITLE
'Selected RTP Stream Configuration': characteristic was supplied illegal value: null!

### ISSUE THREAD

**Issue by sebastianbk** [hjdhjd/homebridge-unifi-protect#328]
First of all, I would like to thank you for creating this fantastic plugin. I have been extremely happy with it for the 8–9 months I have been running it so far. Your effort on this project is greatly appreciated!

**Describe The Problem:**
I recently updated to the latest version (`v4.3.5`) and, unfortunately, I could not access my camera feeds from the Apple Home app after the update. I have three G3 Flex cameras set up on my network. As you can see in the logs below, it seems as if the RTP stream configuration is not set up correctly. I'm unsure of how to resolve this, as I don't recall having to configure any RTP-related settings when I first installed the plugin.

For your reference, I am running the latest version of Homebridge (`v1.3.3`) and Homebridge Config UI X (`v4.40.0`).

**To Reproduce:**
Install the latest version of the `homebridge-unifi-protect` plugin and configure it with one or more G3 Flex cameras, following the installation guide on the front page of this GitHub repo. The error displayed in the logs below will show up.

**Logs:**
```
[3/10/2021, 8:46:56 AM] [homebridge-unifi-protect] This plugin generated a warning from the characteristic 'Selected RTP Stream Configuration': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
```

**Homebridge Configuration:**
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "manufacturer": "homebridge.io",
        "model": "homebridge",
        "port": 51826,
        "pin": "********"
    },
    "ports": {
        "start": 52100,
        "end": 52150
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": false,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "192.168.1.7",
                    "password": "********",
                    "username": "homebridge"
                }
            ],
            "options": [
                "Enable.Stream.High"
            ],
            "platform": "UniFi Protect"
        }
    ],
    "accessories": []
}
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/660576/110595856-e0a98300-817e-11eb-8a75-6586824fc22d.png)

**Environment:**
* **Homebridge Version:** 1.3.3
* **Node Version:** 12.18.4
* **Homebridge-UniFi-Protect Plugin Version:** 4.3.5
* **UniFi Protect Version:** 1.13.7
* **UniFi Protect Controller Type:** Unifi Cloud Key Gen2 Plus
* **UniFi Protect Controller Firmware Version:** 1.1.13
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Apple TV 4K 64GB (most recent version)
* **Operating System and OS Version:** Debian

**Comment by sebastianbk** [comment]
I noticed that you updated the minimum supported version of node, so I decided to update node to the latest LTS version (`v14.16.0`). However, this did not resolve the issue. Am I missing some obvious settings?

![image](https://user-images.githubusercontent.com/660576/110598941-a346f480-8182-11eb-924b-255638627524.png)

**Comment by sebastianbk** [comment]
It seems like people with Ring cameras experience a similar issue. See here: https://github.com/dgreif/ring/issues/574

However, there doesn't seem to be an obvious solution in that thread.

**Comment by sebastianbk** [comment]
Just downgraded to `v3.7.9` and now everything is working again. Please let me know if I can provide any further information that can help resolve this issue.

**Comment by sebastianbk** [comment]
Well, I just updated UniFi Protect to the latest version and, now, neither of the versions (`v3.7.9` nor `v4.3.5`) is working.

**Comment by hjdhjd** [comment]
First...thanks for the compliments, appreciate it!

A few things:

- I’d suggest downgrading to v1.3.2 of Homebridge, for the time being. 
- Downgrading between major versions of this plugin is highly inadvised. I haven’t (and really have no intention) designed this plugin to retrofit internal changes that occur across major revisions and whether things work or don’t after you downgrade and then upgrade again is definitely an untested and unsupported use case.

There are lots of changes happening with Homebridge at the moment, and it’s going through the outcome of a long beta cycle for v1.3...I would, generally speaking, proceed with caution until something that’s released is out there for a couple of weeks before upgrading. The intent is for Homebridge to force more strict compliance with various aspects of HomeKit, and there’s going to be a discovery and update cycle while many of us resolve these in plugins. 

But there are also Homebridge bugs or changes in behavior that need to be dealt with along the way...it’s a delicate dance.

I’ll take a closer look at this over the weekend.

**Comment by hjdhjd** [comment]
After further digging and discussion - these are warnings that can be mostly ignored. The plugin will continue to work just fine. Future updates will address some of these, but don’t sweat it in the meantime. Closing this one.
