### ISSUE TITLE
Motion Detection treated as Doorbell Press (Advanced Feature)

### ISSUE THREAD

**Issue by SmallwoodDR82** [hjdhjd/homebridge-unifi-protect#331]
**Is your feature request related to a problem? Please describe:**
With Homekit, Apple recently added a feature if the doorbell is pressed a live view will show up on the Apple TV (tvOS) basically a Picture in Picture which works very well with Unifi Plugin!  However if motion is detected nothing will happen on the AppleTV.

**Describe the solution you'd like:**

I'd love to ability to "Enable Motion as Doorbell Press" within the advanced features.  Basically any motion detection alert from Unifi plugin would be treated like a doorbell press, causing the PIP on AppleTV to trip.

**Describe alternatives you've considered:**

Currently I have an HTTP Requests to another plugin to trip a "switch" to trip the doorbell switch but it doesn't work very well.  I'd love to keep the solution all within this plugin and feel like it could be achieved.  

**Additional context:**

I know not many people would use this but I feel like this is a huge miss for Apple/Homekit.  They should be able to add this within AppleTV and basically add the ability for notifications on doorbell press AND motion.  But right now it's limited so figured this would be my next best shot.  Thank you so much in advance for reading this!

**Comment by hjdhjd** [comment]
This feature already exists. Simply create an automation that triggers the doorbell switch, once you enable that feature option.
