### ISSUE TITLE
Doorbell Ring does not trigger when HomeBridge is on a Docker

### ISSUE THREAD

**Issue by houshasen** [hjdhjd/homebridge-unifi-protect#337]
**Describe The Problem:**
Doorbell Ring does not trigger when HomeBridge is on a Docker

**To Reproduce:**
First everything works as expected including doorbell push and ringing to all HomePods when this plugin is used. However, when I place Homebridge on the docker (in my case Qnap NAS), video and others works fine and still very fast, but doorbell ring does not trigger on the homebridge.

The reason why I said doorbell ring does not trigger in the homebridge is because I have turned on "Enable.Doorbell.Trigger". Pushing this virtual switch from either Homebridge app or Apple Home app, HomePod mini does make sound. When I push physical doorbell, I do not see the virtual switch turns on. Hence, my conclusion is the link between Physical Doorbell (UniFi Protect) to Homebridge Plugin must be somehow bypassed/broken when Docker is used.

**Logs:**

N/A (as nothing recorded/triggered in the log).

**Homebridge Configuration:**

"controllers": [
                {
                    "address": "192.168.1.1",
                    "password": "XXXXXXX",
                    "username": "XXXXXX"
                }
            ],
            "options": [
                "Enable.Doorbell.Trigger"
            ],
            "_bridge": {
                "username": "XXXXX",
                "port": 30399
            },
            "platform": "UniFi Protect"

**Screenshots:**

N/A

**Environment:**

* **Homebridge Version: 1.3.4
* **Node Version: 14.16.0
* **Homebridge-UniFi-Protect Plugin Version: 4.3.5
* **UniFi Protect Version: 1.17.4 
* **UniFi Protect Controller Type: UDMP 
* **UniFi Protect Controller Firmware Version: 1.9.0 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version: iPhone 12 Pro (iOS 14.4.1) 
* **Operating System and OS Version: Docker (Qnap)

**Comment by hjdhjd** [comment]
This is a known issue - will be resolved in the next version. Been documented multiple times...I’ll leave it as an exercise for the search function. :smile:

UniFi Protect 1.17 introduced some new behavior that needs to be accounted for. Thanks!

**Comment by houshasen** [comment]
I apologize and thank you for yet still kind reply.

Thank you again!

iPhoneから送信

**Comment by hjdhjd** [comment]
Not at all!

**Comment by F4stFr3ddy** [comment]
Sorry to bother you, I run Homebridge (v1.3.1) inside Docker, the doorbell works and rings over my HomePods. But not always, when I press it to test it, it works flawless. But when someone visits and rings, I only get a Unifi notification. 

Is this the same issue?

**Comment by hjdhjd** [comment]
Yes.
