### ISSUE TITLE
Option for only notifying for Smart Detections

### ISSUE THREAD

**Issue by asimcard** [hjdhjd/homebridge-unifi-protect#339]
**Is your feature request related to a problem? Please describe:**
Is it possible to have a feature where you can only enable HomeKit notifications for smart detections? I have Protect setup to only send me a notification from the Protect app if a person is detected on my doorbell and I would like a feature or way to disable the regular motion notifications in homekit and only allow the "person detected" notifications that Protects sends out in Homekit. I have already enabled the Enable.Motion.SmartDetect advanced feature and it works great (even faster than the protect app for notifications).

**Describe the solution you'd like:**
Not sure if possible but have an option where if the Unifi Protect Events API states it detects a person, then Homebridge should send the notification, but if Homebridge only detects regular motion (like a car driving by) then it shouldn't. 
Another way of stating it, Protect does the detection but then Homebridge sees that person detection and sends the notification instead of the Protect app.

**Describe alternatives you've considered:**
None at the moment. I'm using a mix of Home app and Protect app but the Protect app may stay the primary.

**Comment by hjdhjd** [comment]
Please read the documentation - this feature already exists. :smile:

**Comment by asimcard** [comment]
Oh ok, I will have to do more testing since I could have sworn a car driving gave a notification too even though in Protect I have vehicle detection off and only person detection on. However, I can confirm that me walking did give a notification (and a whole second faster than Protect). Thanks for the quick response.

**Comment by hjdhjd** [comment]
No worries. There's some more goodies coming soon in this space as well...so stay tuned for more fun. :smile:

Closing this for now...
