### ISSUE TITLE
Unifi Protect doesn't work properly over OpenVPN (LTE works)

### ISSUE THREAD

**Issue by PrzemyslawKlys** [hjdhjd/homebridge-unifi-protect#346]
**Describe The Problem:**

I have a primary home with Unifi Protect and UDM PRO. I have a secondary home setup over UNIFI VPN using OpenVPN. The connection works great and I can access UDM PRO, Unifi Protect, local LAN in the primary home. 

I can access and see Unifi Protect via Apple Home App when using LTE, but whenever I connect to WIFI in 2nd home and try to access the camera it never opens up. I'm pretty sure this is not a fault of your plugin but wondering why would this be a case and what sort of checks I could do to fix it?

I've not set up any special firewall rules, just standard OpenVPN Site-2-Site.

**To Reproduce:**

Not sure it's reproducible. I can provide steps on how to configure OpenVPN but not sure it's worth the effort. 

**Logs:**

HomeApp via WIFI (doesn't work)
```
[3/29/2021, 10:08:37 AM] [UniFi Protect] EvoUDM [UDM-PRO]: Controller refresh interval set to 10 seconds.
[3/29/2021, 10:57:14 AM] [UniFi Protect] EvoUDM [UDM-PRO] UVC G3 Dome [UVC G3 Dome]: Streaming request from 192.168.241.49: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1920x1080@30fps (High), 6000 kbps.
[3/29/2021, 10:58:14 AM] [UniFi Protect] EvoUDM [UDM-PRO] UVC G3 Dome [UVC G3 Dome]: Stopped video streaming session.
```

HomeApp via LTE (works):
```
[3/29/2021, 10:58:52 AM] [UniFi Protect] EvoUDM [UDM-PRO] UVC G3 Dome [UVC G3 Dome]: Streaming request from 192.168.241.49: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1920x1080@30fps (High), 6000 kbps.
[3/29/2021, 10:59:12 AM] [UniFi Protect] EvoUDM [UDM-PRO] UVC G3 Dome [UVC G3 Dome]: Stopped video streaming session.
```

The difference is - in the first one the stop streaming session happens when it times out rather then when stream ends. 

**Homebridge Configuration:**

```json
        {
            "options": [
                "Enable.Audio.TwoWay"
            ],
            "controllers": [
                {
                    "address": "192.168.241.1",
                    "password": "",
                    "username": "homebridge"
                }
            ],
            "platform": "UniFi Protect"
        },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.3.4
* **Node Version:** v14.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 4.4 and 4.3.5
* **UniFi Protect Version:** 1.17.4
* **UniFi Protect Controller Type:** UDM PRO
* **UniFi Protect Controller Firmware Version:** 1.9.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** newest iOS
* **Operating System and OS Version:** hosted on Synology Docker

**Comment by hjdhjd** [comment]
Thanks for the report! This looks like a networking issue, though I’m not really sure where to direct you to beyond telling you to take a closer look at your routing and firewall rules.

One area to investigate - if the machine you are running Homebridge from has multiple network interfaces, check to make sure that Homebridge is using the right one to send traffic out when you are over VPN. I’d suggest you look through the [troubleshooting](https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Troubleshooting.md#network-issues) documentation and see if it helps, as well as the link to Homebridge’s network troubleshooting documentation.

**Comment by PrzemyslawKlys** [comment]
I've connected Synology with 4 x 1GB. I've also made sure to specify the home bridge interface to only one of those.  Not sure if it has any impact on your plugin. I do know it's a networking issue - just trying to figure out what sort of connectivity your plugin may be doing that it would work fine internally/thru WAN/LTE, but not via OpenVPN. Thank you.

**Comment by hjdhjd** [comment]
The plugin makes zero decisions about networking. All those decisions come from Homebridge. Best of luck!
