### ISSUE TITLE
Cameras are not showing in HomeKit (

### ISSUE THREAD

**Issue by Clickbaitcake** [hjdhjd/homebridge-unifi-protect#361]
**Describe The Problem:**
I am running this plugin on my RasberryPi 4, have configured a local account which is in the admins group but no cameras appear in the HomeKit app. There are no errors in the logs either so I am really stumped.

I am certain that the username and password are correct and the Pi can reach my controller, there are no firewalls in between they are connected via an unmanaged switch. All other HomeBridge plugins are working. 

I was also sure to install FFmpeg with the following command:
`sudo curl -Lf# https://github.com/homebridge/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-raspbian-armv6l.tar.gz | sudo tar xzf - -C / --no-same-owner
`

Am I missing a step to add the cameras to my HomeKit? Are there any verbose logs I can access?

**To Reproduce:**
- Install plugin
- Configure username/password
- Click Save
- Restart HomeBridge
- Wait for cameras to appear in HomeKit
- Cameras never appear

**Logs:**
[4/17/2021, 22:29:57] Loaded config.json with 0 accessories and 3 platforms.
[4/17/2021, 22:29:57] Loaded 0 cached accessories from cachedAccessories.
[4/17/2021, 22:29:57] ---
[4/17/2021, 22:29:58] Loaded plugin: homebridge-adb@1.4.5
[4/17/2021, 22:29:58] Registering platform 'homebridge-adb.HomebridgeADB'
[4/17/2021, 22:29:58] ---
[4/17/2021, 22:29:58] Loaded plugin: homebridge-config-ui-x@4.41.0
[4/17/2021, 22:29:58] Registering platform 'homebridge-config-ui-x.config'
[4/17/2021, 22:29:58] ---
[4/17/2021, 22:29:58] Loaded plugin: homebridge-unifi-protect@4.4.0
[4/17/2021, 22:29:58] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[4/17/2021, 22:29:58] ---
[4/17/2021, 22:29:58] Loading 3 platforms...
[4/17/2021, 22:29:58] [Config] Initializing config platform...
[4/17/2021, 22:29:58] [Config] Running in Service Mode
[4/17/2021, 22:29:58] [HomebridgeADB] Initializing HomebridgeADB platform...
[4/17/2021, 22:29:58] [UniFi Protect] Initializing UniFi Protect platform...
Preparing Advertiser for 'Homebridge C6E2 1AB7' using ciao backend!

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "192.168.0.2",
            "password": "SECRET",
            "username": "cctv"
        }
    ],
    "verboseFfmpeg": true,
    "platform": "UniFi Protect"
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.3.4
* **Node Version:** v12.18.3
* **Homebridge-UniFi-Protect Plugin Version:** v4.4.0
* **UniFi Protect Version:** Controller 1.13.7
* **UniFi Protect Controller Type:** UCKgen2+, 
* **UniFi Protect Controller Firmware Version:** 6.1.71
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 11, iOS 14.1
* **Operating System and OS Version:** Raspbian GNU/Linux Buster (10)
--

**Comment by Clickbaitcake** [comment]
Running ffmpeg command gives the following output:

`pi@homebridge:/var/lib/homebridge $ ffmpeg
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...`

**Comment by hjdhjd** [comment]
Thanks for the report. I’m guessing that you’re on an outdated UCKgen2+ firmware. What is the firmware version of the **UCK**?

**Comment by Clickbaitcake** [comment]
> Thanks for the report. I’m guessing that you’re on an outdated UCKgen2+ firmware. What is the firmware version of the **UCK**?

Hello,its running `UniFi Protect Controller Firmware Version: 6.1.71`

**Comment by hjdhjd** [comment]
That’s not the firmware I’m asking about. :smile:

The **UniFi Cloud Key** firmware version is what I’m asking about. That is **not** the same thing as the UniFi Protect controller firmware.

**Comment by Clickbaitcake** [comment]
> That’s not the firmware I’m asking about. 😄
> 
> The **UniFi Cloud Key** firmware version is what I’m asking about. That is **not** the same thing as the UniFi Protect controller firmware.

Ah sorry. I switched to new settings and struggled to find it. 

`Current Version UCKP.apq8053.v0.7.7.8abe1d4.180928.0948`

It does say upgrade available actually!

**Comment by hjdhjd** [comment]
You are running on outdated firmware. Closing this one out...upgrade your UCK firmware. :smile:
