### ISSUE TITLE
G3 Instant Streaming Issue

### ISSUE THREAD

**Issue by ScooterNC** [hjdhjd/homebridge-unifi-protect#364]
**Describe The Problem:**
I just added homebridge to my network and have added your plugin.  I followed the directions and the issue is I cannot stream in the Home app.  It can connect as it shows me a picture but not stream.  I confirm that the user is an admin and that it enabled the medium and low RSTP streams(They were disabled prior)

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**
I use this in True NAS Core and do not have its config

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.3.4
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**4.4.0
* **UniFi Protect Version:** 1.17.4
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 2.0.27
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:*14.4.2
* **Operating System and OS Version:** TrueNas Core

**Comment by hjdhjd** [comment]
I use TrueNAS Core as well, and you most certainly have a Homebridge configuration file. :smile: 

Your problem actually seems to be related to streaming - I would direct you to the Troubleshooting page. If you’re a new user - welcome to the community. I’d suggest using the Discord channel to get support...it’s going to be an easier journey than an issue on Github, if you need to walk through something with more seasoned users.

Welcome to the community!

**Comment by rzara** [comment]
The Truenas home bridge plugin does not seem to install ffmpeg, which prevents streaming.
You can install ffmpeg by connecting to your homebrigde jail and running
`pkg install ffmpeg`

**Comment by hjdhjd** [comment]
@rzara that won’t work either. You need a version of ffmpeg compiled with fdk_aac support, which the default ffmpeg on FreeBSD / TrueNAS doesn’t I’m afraid.

**Comment by rzara** [comment]
It won't allow sound, but I can confirm that it makes streaming video work

**Comment by hjdhjd** [comment]
Correct. I should be more precise….you will not get the full use of this plugin with the default ffmpeg - you will have no access to audio. I use TrueNAS every single day and this plugin is largely developed on it. :smile:
