### ISSUE TITLE
CloudKey/NVR temperature sensor

### ISSUE THREAD

**Issue by ianiv** [hjdhjd/homebridge-unifi-protect#365]
**Is your feature request related to a problem? Please describe:**

I would like to be able to create HomeKit automations based on my CloudKey's temperature. E.g. turn on a fan when temp > X

**Describe the solution you'd like:**

The temperature appears to be included in the `/api/ws/system` websocket messages, I would like to have this temperature exposed as a temperature sensor.
It is possible that other Protect NVR models do not report a temperature but I don't have any to test against.

**Describe alternatives you've considered:**

I've considered making a plugin for this myself but it's probably more efficient to have only one plugin deal with Protect.
I don't know of any alternatives that would allow me to get the temperature as a HomeKit sensor.

**Additional context:**

I know this may be a bit out of scope, but it is data provided by the device that this plugin is already connecting to.

Thanks!

**Comment by link266** [comment]
FWIW I would use this as well!  (assuming it could get the temp data from my UDM-Pro) :)

**Comment by ianiv** [comment]
I hesitated making the request because I also wasn't sure if it belongs here. But since it is related to the device running Protect, I thought I'd give it a shot :)

I hope this video I'm linking to helps explain why I would find this useful!

https://share.icloud.com/photos/00utGXk1Go36QXVqpPKffJUVQ

**Comment by fpuigb** [comment]
Hey @hjdhjd following the same line, would you ever consider making a plug-in that supports the Unifi smart plugs?

https://store.ui.com/collections/unifi-accessories/products/unifi-smart-power

**Comment by hjdhjd** [comment]
@fpuigb Sure...when I can get one. Damn things have been sold out for a while. 😄 I will likely support this in a different plugin given it’s truly outside of the UniFi Protect world.

Stay tuned on that one...but yes, I will be supporting it in the future.

**Comment by hjdhjd** [comment]
@ianiv That is the **most** compelling argument I’ve seen for this feature. Let me see what I can do in the next few weeks.

**Comment by fpuigb** [comment]
> @fpuigb Sure...when I can get one. Damn things have been sold out for a while. 😄 I will likely support this in a different plugin given it’s truly outside of the UniFi Protect world.
> 
> Stay tuned on that one...but yes, I will be supporting it in the future.

lol, yeah I have been waiting for them too. I agree it should be a different plugin. 👍🏻

**Comment by link266** [comment]
> @ianiv That is the **most** compelling argument I’ve seen for this feature. Let me see what I can do in the next few weeks.

I have a VERY similar set up.  My fan is connected to a smart outlet and is automated by a _separate_ HomeKit temp sensor (but of course, having the fan's state being automated by the UDM-Pro's temp sensor would be more much ideal).

**Comment by ianiv** [comment]
> @ianiv That is the **most** compelling argument I’ve seen for this feature. Let me see what I can do in the next few weeks.

I really appreciate you taking the time to look into adding this 🥇


And in case someone is wondering why I don't just leave the fan on all the time: behind that wall is my bed. The fan makes noise that my wife can hear. Enough said 🤣

**Comment by hjdhjd** [comment]
Closing this one. I’ll update it when I’ve got something more to share, hopefully in the coming weeks.

**Comment by hjdhjd** [comment]
I haven't forgotten about this one...it's coming. :smile:

**Comment by hjdhjd** [comment]
Implemented in v5. Enjoy!
