### ISSUE TITLE
User or Admin User Required?

### ISSUE THREAD

**Issue by ChrisChiera** [hjdhjd/homebridge-unifi-protect#371]
**Describe The Problem:**
Just a question/clarification, not an issue. Hopefully this is the right place to ask? 
The setup recommends creating a dedicated user to for Homebridge. My question is, one can create a user with "Admin" Privileges or simply "User" Permissions. If I simply use a "User" permission is that enough for all features this plugin offers, or do I need to use a user with "Admin" privileges? 

**To Reproduce:**
N/A

**Logs:**
N/A

Show the Homebridge logs here.
Remove any sensitive information.
N/A

**Homebridge Configuration:**
N/A

**Screenshots:**
N/A

**Environment:**
N/A

**Comment by hjdhjd** [comment]
RTFM. :smile: There’s a lot of documentation to help you.

Start with the best practices and troubleshooting documentation.

**Comment by ChrisChiera** [comment]
Thank you. I looked through it last night, and couldn't find the answer. But checked again after posting here, and low and behold found the page with the answer, that it does suggest using an "Admin" privileged user. Thank you so much for creating this, can't wait to try it out!
