### ISSUE TITLE
PIP on Apple TV on Motion based events

### ISSUE THREAD

**Issue by fightingmajor** [hjdhjd/homebridge-unifi-protect#372]
**Is your feature request related to a problem? Please describe:**
NO

**Describe the solution you'd like:**
It would be great to have the cameras show up on Apple TV via PIP when there is certain motion like doorbells do someone rings the doorbell.

**Describe alternatives you've considered:**
Right now I have my tv switch  inputs for my Camera feed via Unifi Viewport when there is motion on my porch so I can see the person before they ring the doorbell.  Or for when DoorDash just drops the food off on the porch and doesn't bother ringing the doorbell.

**Additional context:**
Would be great to just have a popup on my screen when using Apple TV of the camera where there is motion as apposed to my tv switch inputs to go to my Viewport.  There is a company called Arden.AI that does this with his software, but it doesn't work with Apple products as he uses Alexa for the commands.  I haven't seen this down with any other cameras as of yet and would be a great addition to your plugin.

**Comment by hjdhjd** [comment]
You can already do this through automation rules and feature options. like `Doorbell.Trigger`.  RTFM - there’s a lot of it, and lots of fun things to discover. :smile:
