### ISSUE TITLE
 data URL / base64 snapshot corrupted

### ISSUE THREAD

**Issue by SebDominguez** [hjdhjd/homebridge-unifi-protect#378]
**Describe The Problem:**

My attempts to decode the base64 string from my Unifi Doorbell are unsuccessful.

This is the image that I decode from the data URL:

![convertedFile](https://user-images.githubusercontent.com/52816569/117545411-f4118700-b025-11eb-8240-75399c78cabf.jpg)

I can see the beginning of the watermark but then the image just get corrupted. 

**To Reproduce:**
send an MQTT message `true` to `unifi/protect/[MAC]/snapshot/trigger`

receive the following response:
```
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCASwBkADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDQrC1HxZoem3Rt7zUYkmU4ZVVn2n0O0HH41tToZIJEVzGzKQHXqpI6iuIXwhonh7QdRn1PbeEozGadRuXjgL6HPfqSaYHZ2V3b31slxZzJNC/3XQ5BrGl8Y+H4rv7NJqcIlBxwGKg/7wG39a828...
```

I have the feeling that the data URL got truncated. Maybe its too large to fit inside an MQTT payload...

**Logs:**

```
[5/8/2021, 6:02:11 PM] [UniFi Protect] UniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Entrée Oest [UVC G4 Doorbell]: Snapshot triggered via MQTT.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.3.4
* **Node Version:** v14.16.0
* **Homebridge-UniFi-Protect Plugin Version:** v4.4.0
* **UniFi Protect Version:** 1.18.0
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 2.1.7
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 14.5.1 iPhone 12 Pro Max ; macOS 11.3.1 MacBookPro 13,3 
* **Operating System and OS Version:** RockPro64 armbian buster Docker

**Comment by hjdhjd** [comment]
The message is published correctly. If your MQTT broker is truncating it…not sure where to point you to beyond the documentation of your broker. I’ve used the images off of both G4 Doorbells and a G4 Pro (which has a much higher resolution picture, meaning more data) and they aren’t truncated.

Curious to see what you discover…

**Comment by SebDominguez** [comment]
Funny, I've upgraded to a UDMPRO and now the API timeout

```
[5/15/2021, 12:56:26 PM] [UniFi Protect] UDMPRO [UDM-PRO] Entrée Oest [UVC G4 Doorbell]: Snapshot triggered via MQTT.
[5/15/2021, 12:56:29 PM] [UniFi Protect] UDMPRO [UDM-PRO]: Controller API connection terminated because it was taking too long. This error can usually be safely ignored.
[5/15/2021, 12:56:29 PM] [UniFi Protect] UDMPRO [UDM-PRO] Entrée Oest [UVC G4 Doorbell]: Unable to retrieve a snapshot.
```

**Comment by hjdhjd** [comment]
Correlation is not causation. API timeouts occasionally happen in Protect, it’s normal.

**Comment by SebDominguez** [comment]
Ok but i still didn't fixed my base64 decoding issue...

**Comment by SebDominguez** [comment]
Well, since I have little hope to get this working I found a workaround by using ffmpeg

`ffmpeg -y -i rtsp://[your_RTSP_url] -vframes 1 -qscale:v 2 output.jpeg`

this will give me my snapshot.

**Comment by hjdhjd** [comment]
Glad to hear it. I will look more closely at this another time, it’s not a high priority…and it works in my test cases currently. Best of luck.

**Comment by SebDominguez** [comment]
> Glad to hear it. I will look more closely at this another time, it’s not a high priority…and it works in my test cases currently. Best of luck.

If you need me to send you logs or make some tests just tells me I'll be pleased to do so

**Comment by superjunky** [comment]
I was positively surprised to find MQTT support in this plugin! Thanks for that :)

I also was not able to decode the snapshots. It would be a great feature!

**Comment by hjdhjd** [comment]
LOL. Thanks (I think? 😀)...I'll take another look to see what might be going on, though in my prior tests, it's worked just fine.
