### ISSUE TITLE
[Homebridge UI] Failed to refresh characteristics for "abc": read ECONNRESET errors

### ISSUE THREAD

**Issue by WJKramer** [hjdhjd/homebridge-unifi-protect#389]
**Describe The Problem:**

**To Reproduce:**
No particular procedure.

**Logs:**
Any Idea why I am getting this error?

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

{
    "bridge": {
        "name": "Homebridge A560",
        "username": "x",
        "port": 51239,
        "pin": "x"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "192.168.1.9",
                    "password": "x",
                    "username": "Homebridge"
                }
            ],
            "platform": "UniFi Protect"
        },
        {
            "name": "Camera FFmpeg",
            "platform": "Camera-ffmpeg"
        },
        {
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiYzEyODEwMGIiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2MjA5MDU4NjAsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6MTE4MDU1OCwicm5kIjoiTWRENVdMbVdIVmMzLWciLCJzZXNzaW9uX2lkIjoiZTMxYTRmOGEtMzc4Zi00ZDhkLTljYjMtNjAxNWM5OTQ5Njc3IiwidHlwZSI6InJlZnJlc2gtdG9rZW4ifQ.krSzR7QZvY-1mjscdYnEx7B_e1BnuJ6zfbX6uWkUbjQuPpsvoWUtF18vgdFFq9w6mV3aOQ0-3RFO-Ee-W3m79g",
            "hideLightGroups": true,
            "hideUnsupportedServices": true,
            "platform": "Ring"
        }
    ]
}

**Screenshots:**
![Screen Shot 2021-05-13 at 07 35 50](https://user-images.githubusercontent.com/75452447/118120571-1a387d80-b3be-11eb-85e5-fa29f6dee362.png)

**Environment:**

* **Homebridge Version:** v1.3.4
* **Node Version:** v14.16.1
* **Homebridge-UniFi-Protect Plugin Version:** v4.4.0
* **UniFi Protect Version:** 1.18.0
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** iPhone/iPad/tvOS
* **Operating System and OS Version:** macOS

**Comment by hjdhjd** [comment]
Looks like network reset errors…these aren’t plugin errors per se. Your network connections are being reset. Might want to try rebooting the UNVR/UDM-Pro/UCK as a starting point. Best of luck.
