### ISSUE TITLE
UniFi Cameras in a seperate VLAN

### ISSUE THREAD

**Issue by kjmcfall** [hjdhjd/homebridge-unifi-protect#396]
HI,
I am attempting to move my UniFi Cameras into a separate VLAN.  In this case my IoT VLAN 107.
I have moved these cameras and have created firewall rules to allow the cameras to communicate with the CloudKey UCK-G2+ with Protect on it.
This is all working well, and the Protect App works fine.
HomeBridge has been moved to this VLAN as have my apple TV's etc.
All is working well except I can no get the video to stream from HomeKit on my iPhone
Are there any special ports for this scenario that need to be allowed?
The Plugin seems to connect to Protect Fine and finds the cameras.
**To Reproduce:**

**Logs:**
There are no log entries related to this issue

```

**Homebridge Configuration:**

{
    "controllers": [
        {
            "address": "10.1.1.1",
            "name": "nvr.local.net",
            "password": "XXXXXXXXXX",
            "username": "homebridge"
        }
    ],
    "options": [
        "Enable.MotionSensor",
        "Enable.MotionSwitch"
    ],
    "platform": "UniFi Protect"
}

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Homebridge Version:** 1.3.4
* **Node Version:** 12.18.3
* **Homebridge-UniFi-Protect Plugin Version:** 3.6.3
* **UniFi Protect Version:** 1.18
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 2.1.7
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 14.5.1
* **Operating System and OS Version:** "Raspbian GNU/Linux 10 (buster) 5.10.17 -v7l+

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by hjdhjd** [comment]
There are no special settings other than understanding the appropriate firewall rules that you will need and accounting for them. I would suggest beginning with an open scenario where you allow all traffic through both sides and progressively lock things down until you can trace down your issue. Firewall configuration is beyond the scope of this plugin, but I would suggest trying the Discord…the community is quite helpful.

Best of luck!

**Comment by kjmcfall** [comment]
OK,
Thank You.  Appreciate the response.

Cheers
Kevin
