### ISSUE TITLE
Privacy Zones

### ISSUE THREAD

**Issue by durosity** [hjdhjd/homebridge-unifi-protect#418]
**Is your feature request related to a problem? Please describe:**

I'd like to be able to set and remove privacy zones via HomeKit.
**Describe the solution you'd like:**

Ideally this could work as a config requesting the points that the zone would cover as a grid, or an option to blank all of the feed.  This could be show as a switch that can be turned on or off via triggers. 
**Describe alternatives you've considered:**

I can't think of any short of using the unifi protect app which is a bit cumbersome as even they don't have the ability to save zones and just turn them on/off, you have to redefine the mask every single time.
**Additional context:**

I'm not sure if this is even plausible.  The reason I want it is I have a couple of indoor cameras that I want to mask when someone is in the house but then show the feed when we're out, or if something happens like a smoke detector is triggered, etc.

**Comment by hjdhjd** [comment]
I appreciate the idea…but this isn’t going to be implemented. At best, once we get HomeKit Secure Video going (whenever that happens), you can use those capabilities, potentially. These capabilities are best left to the native Protect app, in general.

Thanks for the suggestion!

**Comment by durosity** [comment]
Yeah I figured that'd be the response, thought I'd try anyway.  Alas this is definitely one area where the Protect app is pretty shoddy in its implementation, so hopefully HKSV does roll around at some point!  

Thanks for the reply!
