### ISSUE TITLE
FFMPEG errors after installing plugin through Homebridge UI

### ISSUE THREAD

**Issue by carson-autocicd** [hjdhjd/homebridge-unifi-protect#423]
**Describe The Problem:**
Originally referenced here: https://github.com/hjdhjd/homebridge-unifi-protect/issues/422

I realized that I did not explicitly state how I installed the application (this might be good information to include in the template or if it's there sorry I missed it!). I did install the application through the HomeBridge UI by simply searching for and installing the plugin and setting the NVR settings.

Because I was not clear on how I installed the application, it was incorrectly assumed I installed the application through an improper means and the fix suggestion was simply uninstall and install the application correctly. I uninstalled, and followed the same installation process as I did the first time, which was the process recommended by the author. 

The result is the same however, but I had no means to re-open the ticket. I'm not sure what the next troubleshooting step might be but the issue persists.

**To Reproduce:**
Access any camera directly either by clicking on the tile for any Unifi camera or by clicking on an alert (such as the doorbell ringing).

**Logs:**
Note: I removed the MAC Addresses

```
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4]: Connected to the Protect controller API (address: 10.10.10.166 mac:).
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4]: Connected to the UniFi realtime update events API.
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4]: Discovered camera: Driveway [UVC G4 Pro] (address: 10.10.10.92 mac:).
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4]: Discovered camera: Backyard [UVC G4 Pro] (address: 10.10.10.10 mac:).
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4]: Discovered camera: Side stairs [UVC G4 Pro] (address: 10.10.10.86 mac:).
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4]: Discovered camera: Garage [UVC G3 Flex] (address: 10.10.10.106 mac:).
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4]: Discovered camera: Doorbell [UVC G4 Doorbell] (address: 10.10.10.183 mac:).
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4]: Controller refresh interval set to 10 seconds.
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4] Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: LEAVE PACKAGE AT DOOR.
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4] Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: DO NOT DISTURB.
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4] Doorbell [UVC G4 Doorbell]: Discovered doorbell message switch: PRESS TO SUMMON DOG..
[6/12/2021, 12:53:28 PM] [UniFi Protect] UNVR [UNVR4] Doorbell [UVC G4 Doorbell]: Doorbell message set: PRESS TO SUMMON DOG..

node:99976) UnhandledPromiseRejectionWarning: Error: Command failed with ENOENT: ffmpeg -codecs
spawn ffmpeg ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
at onErrorNT (internal/child_process.js:469:16)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:99976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:99976) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "10.10.10.166",
            "password": "<hidden>",
            "username": "homebridge"
        }
    ],
    "platform": "UniFi Protect"
}.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:**  1.3.4
* **Node Version:** 12.18.4
* **Homebridge-UniFi-Protect Plugin Version:** 4.4.0
* **UniFi Protect Version:** 1.18.1
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** 1.4.9
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** <iOS 14.6 (iPhone & iPAD) & MacOS 11.4
* **Operating System and OS Version:** MacOS 10.3.16

**Note:**
My HomeBridge host is a Mac mini (late 2012) with 16gb of ram, 2.5ghz i5 and Intel HD Graphics 4000. It's running macOS High Sierra (nervous about updating it because of its age and what it may or may not do to HomeBridge).

**Comment by carson-autocicd** [comment]
Ok I installed this on a PC rather than my old Mac Sierra and it worked fine on the PC. Watching the installation logs I could see it downloading/installing FFMPEG on the PC, but I did not see this on my particular Mac version. While trying to install FFMPEG using brew on MacOS High Sierra, after quite some time it failed due to certain components no longer being supported.

So it could well by that that older version of MacOS is not supported.

**Comment by hjdhjd** [comment]
That’s not exactly the case - all operating systems are supported by this plugin, provided you have a version of ffmpeg compiled with AAC support, and the [installation-related documentation references the requirements as well](https://github.com/hjdhjd/homebridge-unifi-protect#installation). If ffmpeg-for-homebridge doesn’t support your system, you’re on your own to provide a working ffmpeg with the right support compiled in, which should be pretty straightforward on High Sierra and I’ll leave it to your favorite search engine to find instructions for how to do it.

Best of luck!

**Comment by hjdhjd** [comment]
v4.4.1 should resolve this. Thanks!

**Comment by Arcxk** [comment]
Sorry to bring up a closed issue, but I'm currently seeing this same issue on v4.4.1

> Error: Command failed with ENOENT: /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -codecs
spawn /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg',
  path: '/homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg',
  spawnargs: [ '-codecs' ],
  originalMessage: 'spawn /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT',
  shortMessage: 'Command failed with ENOENT: /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -codecs\n' +
    'spawn /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg ENOENT',
  command: '/homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -codecs',
  escapedCommand: '"/homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg" -codecs',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

- Homebridge Version: 1.3.4
- Node Version: 14.17.0
- Homebridge-UniFi-Protect Plugin Version: 4.4.1
- UniFi Protect Version: 1.18.1
- UniFi Protect Controller Type: UNVR and UDMP
- UniFi Protect Controller Firmware Version: 1.9.3
- Apple Device and iOS / macOS / iPadOS / tvOS Version: <iOS 14.6 (iPhone & iPAD) & MacOS 11.4
- Operating System and OS Version: Debian Buster Host running Homebridge in a docker container (Alpine Linux - 3.12.7)

**Comment by hjdhjd** [comment]
You don’t have a version of ffmpeg installed with the appropriate codec support. Please read the installation documentation I referenced above. Good luck.

**Comment by Arcxk** [comment]
Thank you sir. I got it working.

 I had to manually specify "ffmpeg" in the video processor option field under "additional settings" in the homebridge ui configuration window. This seems strange since I haven't had to do that in the past and I would assume that it would use the ffmpeg in the PATH by default. Either way all is working. Thanks again!
