### ISSUE TITLE
How to trigger doorbell function to homekit via HomeSeer automation

### ISSUE THREAD

**Issue by PrimaryInc** [hjdhjd/homebridge-unifi-protect#430]
**Describe The Problem:**

Hi, I use HomeSeer for automation, and HomeBridge to connect to homekit. All connected via the HomeSeer plugin for HomeBridge.
Sins i have a Unifi Dream Machine Pro, I also use Unifi Protect.
Now i used to use Homebridge Camera FFmpeg plugin,  but for al possible reasons using the Unifi plugin made mye world alot easier.

So with Homebridge Camera FFmpeg i could from HomeSeer trigger an action event, that calls a url. 
This url then triggers the doorbell function in homekit, giving me a live view of whom ever was at the door.
Under the action url used to trigger doorbell:
&hs.URLAction("http://IP:8888/doorbell?Gardsplass","GET","","")
Reason for me to do it this way, doorbell is a 433Mhz device calling a device in HomeSeer. 
And when this device is triggered, it calls event that send url to HomeBridge and view appears on my apple tv.

I have enabled doorbell function with Enable.Doorbell.Trigger under feature options.
So the question is, is there a url that i can use to trigger doorbell function in your plugin?
I have 7 cameras, and I only need to trigger one by the door.
Is it possible? Any ideas? 

Thank you very much :)

**Homebridge Configuration:**

   {
            "controllers": [
                {
                    "address": "IP",
                    "password": "Something",
                    "username": "User"
                }
            ],
            "options": [
                "Enable.Doorbell.NvrEvents",
                "Enable.Doorbell.Trigger"
            ],
            "platform": "UniFi Protect"

**Environment:**

* **Homebridge Version:** 1.3.4
* **Node Version:** 14.17.1
* **Homebridge-UniFi-Protect Plugin Version: 4.4.1
* **UniFi Protect Version:**  1.19.0-beta.10
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.10.0-13
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**Apple TV tvOS15 (beta)
* **Operating System and OS Version:** Windows 2019 Standard server

**Comment by hjdhjd** [comment]
No, there isn’t a way to do it through a URL, and I have no plans to create such a mechanism. In the future, you’ll be able to trigger a doorbell ring through MQTT, however. No timeframe, but in the coming months I hope.

**Comment by PrimaryInc** [comment]
Hi, 

Thats to bad, great plugin and would be useful function for any home automation platform.

**Comment by PrimaryInc** [comment]
By the way what other functions can trigger the doorbell? Only internally in homekit/homebridge?

**Comment by hjdhjd** [comment]
RTFM or Discord. 😄
