### ISSUE TITLE
Camera doesn’t respond behind VPN in the same network 

### ISSUE THREAD

**Issue by Taxyovio** [hjdhjd/homebridge-unifi-protect#442]
**Describe The Problem:**
When iOS devices are connected in the same home network with VPN enabled, cameras won’t respond. 

In fact this also happens for local proxy tools (like [Surge](https://apps.apple.com/gb/app/surge-4/id1442620678)) that use a VPN profile on iOS. 

I have talked to the developer, who confirmed that it was a bug on iOS. The issue is due to iOS sends the IP address of the VPN instead of the real IP to the cameras, resulting in failure for cameras to stream rtsp data back correctly. So it happens for all homekit cameras.

This issue has been reported to Apple for 2 years but it’s still not fixed. So I’m thinking if it’s possible to have some workaround as a new feature option. Thanks.

**To Reproduce:**
1. Turn on some VPN, say Surge (Free version is enough).
2. View camera stream.

**Logs:**

**Homebridge Configuration:**

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.3.4
* **Node Version:**
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 14-15
* **Operating System and OS Version:** raspbiam

**Comment by hjdhjd** [comment]
Sorry, I won’t be working on this one…this is an iOS issue and quite a specific use case. Happy to accept a PR though. Best of luck.
