### ISSUE TITLE
Smart event not being sent to MQTT during detection delay after motion event

### ISSUE THREAD

**Issue by AndAy224** [hjdhjd/homebridge-unifi-protect#444]
**Describe The Problem:**

If a smart event occurs after a motion event, during the event duration delay, the smart alert is not sent to MQTT

**To Reproduce:**

Set the motion zone larger than the smart detection zone. If a person/vehicle is moving on the street and triggers a motion event, a person walking into the smart detection area will not trigger a smart event that is sent to MQTT. Deleting the motion zone will allow for dependable smart detection, or making the motion event zone smaller than the smart detection zone.

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.

{
    "controllers": [
        {
            "address": "10.0.0.22",
            "mqttUrl": "mqtt://10.0.0.150",
            "password": "REMOVED",
            "refreshInterval": 2,
            "username": "homebridge"
        }
    ],
    "motionDuration": 5,
    "platform": "UniFi Protect"
}
```

**Environment:**

* **Homebridge Version:**  v1.3.4
* **Node Version:**  v14.17.1
* **Homebridge-UniFi-Protect Plugin Version:** v4.4.1
* **UniFi Protect Version:**   v1.18.1
* **UniFi Protect Controller Type:**  UNVR
* **UniFi Protect Controller Firmware Version:**  v1.4.9
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** N/A
* **Operating System and OS Version:**  Docker

**Comment by hjdhjd** [comment]
Thanks…I’ll take a look at this one when I get a few. Appreciate the report!
