### ISSUE TITLE
Add a new option to reverse the status of the Motion Switch

### ISSUE THREAD

**Issue by jcg3** [hjdhjd/homebridge-unifi-protect#457]
**Is your feature request related to a problem? Please describe:**
The "Enable.Motion.Switch" option is fantastic! It gives me the ability to turn off notifications when there's something going on at the front door - e.g., if I'm talking with someone outside and don't want to repeatedly get motion alerts, I should be able to turn off the motion alerts while I'm out there.

The only downside is the way the Home app shows the switch. When it's turned on (which is 99% of the time) it shows in the main tab as a "Switch On". If I turned it off, it disappears from the main tab's status, even though that is when I'd want to see it most prominently - as a reminder to turn the motion detection back on.

I'd like it to behave more like my smart door lock. When the door is locked, it doesn't show in status. When it's unlocked, it does show.

**Describe the solution you'd like:**
I'd like a config option to reverse the switch's status in Home - e.g., when motion detection is on, the switch's status is off, and vice versa.

**Describe alternatives you've considered:**
I can turn off the setting for "Include in Home Status" which will remove it from showing in the main tab in the Home app, but then I don't get the in-your-face reminder to turn it back on.

I tried to set up an Automation in HomeKit to turn the motion sensor back on after 15 minutes, but couldn't figure out how to do that - not sure if it is possible. I may try a shortcut, but haven't done that yet.

**Additional context:**
Obviously not urgent, but I think it would be nice to have.

**Comment by hjdhjd** [comment]
Sorry, won't be adding this one. I'm very cautious about feature bloat and this is definitely in the cosmetic-not-functional category to cater to a niche use case. Thanks for the suggestion!

**Comment by jcg3** [comment]
Bummer but fair, thanks for considering it.
