### ISSUE TITLE
Face Detection?

### ISSUE THREAD

**Issue by ChrisChiera** [hjdhjd/homebridge-unifi-protect#471]
**Describe The Problem:**

Apple's Secure Video support Face Detection in Home App, but I'm not seeing the option for it on my Unifi Protect Cameras setup through Homebridge and don't see it mentioned on this GitHub. Am I missing something? As coming from Nest where I only got notified of people and cars, and read that Homekit supported that too, but without it, get frequently notifications of motion when the wind blows trees etc.
**To Reproduce:**

N/A - Can't figure out how to enable it, unless it's not currently supported and don't see anywhere else to ask.
**Logs:**

N/A
```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

N/A
**Environment:**

* **Homebridge Version:** Latest Stable
* **Node Version:**  Latest Stable
* **Homebridge-UniFi-Protect Plugin Version:**  Latest Stable
* **UniFi Protect Version:** Latest Stable 
* **UniFi Protect Controller Type:** UNVR 
* **UniFi Protect Controller Firmware Version:** Latest Stable 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Latest MBP, Latest iPhone 12
* **Operating System and OS Version:** 
Docker on Synology

**Comment by hjdhjd** [comment]
Please search through other issues. Been asked and answered several times. 😀

Thanks for the suggestion just the same!

**Comment by ChrisChiera** [comment]
Yes, first thing I did was search on here, alas didn't come up with any results and nothing comes up when searching for "face detection" when searching the documentation, which is the official term for the feature in homekit. Hopefully if as you noted its a common question the answer can be added to the documentation, but I'll keep searching in the meantime and hopefully someone has the answer. Thanks!
![image](https://user-images.githubusercontent.com/270079/125143271-2a33bb80-e0e8-11eb-926c-a215d4afefbf.png)

**Comment by hjdhjd** [comment]
It’s not called “Apple Secure Video”…it’s HomeKit Secure Video. Lots of references to it when you search the issue. Here’s a good summary: https://github.com/hjdhjd/homebridge-unifi-protect/issues/226#issuecomment-752728445
