### ISSUE TITLE
Doorbell with Alexa plugin support.

### ISSUE THREAD

**Issue by EminezArtus** [hjdhjd/homebridge-unifi-protect#481]
**Is your feature request related to a problem? Please describe:**

When using the verified Alexa Plugin the doorbell shows up but doesn't detect the button being pushed. However, the Doorbell trigger accessory does work but that appears in Alexa as a switch. Alexa can't use switches to trigger events or routines so maybe with a few conditions we can make it behave differently if you are using Alexa.

**Describe the solution you'd like:**

First check and see if it's just a bug or if this feature isn't available add a condition that would allow the user to specify if they are using Alexa to have it behave differently.

**Describe alternatives you've considered:**

The motion detection also works great with Alexa to trigger a routine maybe we can trick the doorbell trigger to be a motion sensor. I prefer just to make the doorbell work because Alexa has an awesome built in menu if the device is a doorbell.

**Additional context:**

Thanks in advanced.

**Comment by hjdhjd** [comment]
Alexa isn’t supported by this plugin and I have no plans to offer any direct support for it I’m afraid.

**Comment by EminezArtus** [comment]
Would you except some code contributions or do you rather not support it at all? I know a having this support would draw a good amount of people over to Homebridge.

**Comment by hjdhjd** [comment]
Homebridge exists to support HomeKit. :smile: For Alexa support, take a look at some existing projects that try to bridge the worlds. Best of luck!

**Comment by EminezArtus** [comment]
I hear ya thanks.
