### ISSUE TITLE
Ability to Create Sound Sensor/Trigger?

### ISSUE THREAD

**Issue by chrisdudek** [hjdhjd/homebridge-unifi-protect#493]
**Is your feature request related to a problem? Please describe:**
No.

**Describe the solution you'd like:**
I would like to be able to have a Sound Sensor/Trigger for the Cameras. This trigger would alert me when the Camera detects noise. 

**Describe alternatives you've considered:**
I don't believe there are other alternatives except for: also carrying a noise monitor, using a different Camera (such as Nest).

**Additional context:**
 In the plugin's configuration, I think it would be beneficial to include toggles/ranges in the Audio Options/Settings to help reduce false positives (i.e. noise from sound machine for baby).

**Comment by chrisdudek** [comment]
Bumping your keep active. If the developer feels like this isn’t worth keeping open, please feel free to close.

**Comment by hjdhjd** [comment]
This is intriguing, though supporting it cleanly, meaning without the need to build a lot of internal infrastructure ourselves, requires Protect API support…I’ll look into this one for the future. Great suggestion and lots of potential utility, thanks!

**Comment by georgeboot** [comment]
Perhaps this can be done using ffmpeg, like homeassistent does it: https://www.home-assistant.io/integrations/ffmpeg_noise/

This plugin is just so much better than HA’s one, so it would be awesome if the audio triggers could be added here too.

Use case for me is cry detection on my “baby monitor” (G3 flex).

**Comment by georgeboot** [comment]
@hjdhjd will the above be possible?
