### ISSUE TITLE
Audio Issues (Beta Testing: iOS 15 + macOS Monterey)

### ISSUE THREAD

**Issue by nickvanimschoot** [hjdhjd/homebridge-unifi-protect#496]
**Describe The Problem:**

- There’s no flow-less audio anymore, audio is “in pieces” - you are not able to recognise what people are saying.
- Two-Way Audio won’t work anymore, my iPhone’s microphone takes a tape but the camera won’t play any sound.

Please note, that the issues don't occur on macOS Monterey 12 Beta 2, they do occur on iOS 15 Beta 3. Probably Apple is causing the issue (altho there's a small chance that the Homebridge Plugin Update caused this issue), just a kindly notification in advance (if relevant).

**To Reproduce:**

- I tried to enable / disable Audio.Filter.Noise, but that doesn’t work out.
- I tried to go back one version earlier, but my HOOBS Core won’t restart after the downgrade. This forces me to keep the plugin updated to the latest version.

**Environment:**

* **Homebridge Version:** Up to Date (V3.3.12)
* **Homebridge-UniFi-Protect Plugin Version:** Up to Date (V4.4.2)
* **UniFi Protect Version:** Version 1.19.0-Beta.16
* **UniFi Protect Controller Type:** UDMP (UniFi OS UDM Pro V1.10.0)
* **UniFi Protect Controller Firmware Version:** Up to Date
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 15 Beta 3, issues do not occur on macOS Monterey 12 Beta 2
* **Operating System and OS Version:** Raspbian (HOOBS IN A BOX)

**Comment by pelowj** [comment]
Can confirm this issue also affecting me on iPad OS 15.0 Beta 3 (19A5297e). No issue on previous betas.

**Comment by hjdhjd** [comment]
To reiterate what is stated in numerous places in this project:  **no beta versions of iOS or UniFi Protect are supported.** Please don’t open or file bug reports against them - you are on your own here I’m afraid. I get the desire to test the new hotness…but I won’t even look at a bug report if it’s against a beta version. The only supported versions are the current production releases of both Protect and iOS/iPadOS/macOS.

Best of luck!
