### ISSUE TITLE
Add ability to toggle Night Vision LEDs as a Switch

### ISSUE THREAD

**Issue by owine** [hjdhjd/homebridge-unifi-protect#499]
**Is your feature request related to a problem? Please describe:**
There is no way to toggle the night vision features (Auto, On, Off, LED Off) via the Home app.

**Describe the solution you'd like:**
The ability to configure a Switch device in the Home app which would toggle night vision for a specific camera. Ideally a picker since there is more than just On/Off but I am not sure if this is possible. If not possible, the ability to specify what exactly the On/Off states translate to would be great.

**Describe alternatives you've considered:**
Only alternative I am aware of requires doing deep into the UniFi Protect app to make this change and that cannot be done as a part of any automation.

**Additional context:**
I use a camera as a baby monitor and sometimes the night vision LEDs are distracting to baby. I would prefer to leave the LEDs off, but it is clunky to toggle them back on. The ability to quickly toggle the LEDs on and off via a switch device in the same room would be very easy to use for this case.

**Comment by hjdhjd** [comment]
Thanks for the suggestion - I’ve got something  on my radar along these lines in my backlog. Conceptually straightforward. Thanks!
