### ISSUE TITLE
Support for UI Smart Plug

### ISSUE THREAD

**Issue by fpuigb** [hjdhjd/homebridge-unifi-protect#503]
Can be possible to add support for the UI Smart Plugs?

**Is your feature request related to a problem? Please describe:**
Current version of the plug-in does not support the UI Smart Plugs family.

**Describe the solution you'd like:**
Add support for the UI Smart Plugs inside the plug-in.

**Describe alternatives you've considered:**
N/A

**Additional context:**
N/A

**Comment by hjdhjd** [comment]
The only smart plug I’m aware of that Ubiquiti produces is the SmartPower Plug and it’s not a Protect device…so no. :smile:

**Comment by fpuigb** [comment]
> The only smart plug I’m aware of that Ubiquiti produces is the SmartPower Plug and it’s not a Protect device…so no. 😄

You right! would you create another awesome plug-in like the Protect one that support the plugs? 😂
