### ISSUE TITLE
Two bugs found

### ISSUE THREAD

**Issue by vagifzeynalov** [hjdhjd/homebridge-unifi-protect#509]
Hi!
At first, thank you for your work!
I found two bugs
1. typo in `fps=fps=` https://github.com/hjdhjd/homebridge-unifi-protect/blob/3f96e00773bd5dee83342bd2b1a18c55a3d94908/src/protect-stream.ts#L334
2. HK is asking for specific resolution, for example this is for Apple Watch `320x240@15fps`, but those values are not used for transcoding. Could you please to add `"-s", request.video.width + "x" + request.video.height,` into https://github.com/hjdhjd/homebridge-unifi-protect/blob/3f96e00773bd5dee83342bd2b1a18c55a3d94908/src/protect-stream.ts#L326

Also, perhaps you would consider to add these options into default `ffmpegArgs`?
```
-hwaccel auto
-movflags
+faststart
-tune zerolatency
```

Thank you,
Vagif

**Comment by hjdhjd** [comment]
Nope and nope. These aren’t bugs, they are correct and intended, despite the strange appearance to some. And no…won’t be adding those options by default - the ffmpeg options that exist are there for a reason, and the ones that do not are also not there for a reason. If you choose to venture off on your own, that’s certainly your prerogative, but it’s highly unlikely I will be adding them in. I have spent months tweaking the options…they exist as they do for very good reason. :smile:

Best of luck, and thanks for the well-intentioned feedback.
