### ISSUE TITLE
Two bugs were found

### ISSUE THREAD

**Issue by vagifzeynalov** [hjdhjd/homebridge-unifi-protect#510]
Hi!
At first, thank you for your work!

**Describe The Problem:**
I found two bugs
1. typo in `fps=fps=` https://github.com/hjdhjd/homebridge-unifi-protect/blob/3f96e00773bd5dee83342bd2b1a18c55a3d94908/src/protect-stream.ts#L334
2. HK is asking for specific resolution, for example this is for Apple Watch `320x240@15fps`, but those values are not used for transcoding. Could you please to add `"-s", request.video.width + "x" + request.video.height,` into https://github.com/hjdhjd/homebridge-unifi-protect/blob/3f96e00773bd5dee83342bd2b1a18c55a3d94908/src/protect-stream.ts#L326

**To Reproduce:**
Look at the code.

**Logs:**
```
skip
```

**Homebridge Configuration:**
```
skip
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* * **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:** 

Also, perhaps you would consider to add these options into default `ffmpegArgs`?
```
-hwaccel auto
-movflags
+faststart
-tune zerolatency
```

Thank you,
Vagif

**Comment by hjdhjd** [comment]
Duplicate. https://github.com/hjdhjd/homebridge-unifi-protect/issues/509#issuecomment-890048641

Not bugs. Intentional design choices. There are no typos.
