### ISSUE TITLE
Creating Liveview for HomeKit

### ISSUE THREAD

**Issue by richtong** [hjdhjd/homebridge-unifi-protect#535]
**Describe The Problem:**

I don't really understand what a "Homebridge specific liveview is, I see there is a default liveview in Https://controller/protect/liveview, note that the url has changed since the documentation. 

So I created a new live view, but how does you plugin know which is a "homekit specific liveview"
**To Reproduce:**

Installed the homebridge and the connedction works, but I don't see the security widget added to Homekit
**Logs:**

```
No logs
```

**Homebridge Configuration:**

```json
None relevant
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.3.4
* **Node Version:** v14.17.1
* **Homebridge-UniFi-Protect Plugin Version:** homebridge-unifi-protect v4.4.2
* **UniFi Protect Version:** Protect 1.18.1
* **UniFi Protect Controller Type:**  UDMP
* **UniFi Protect Controller Firmware Version:**  homebridge-unifi-protect v4.4.2
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 12 Pro Max
* **Operating System and OS Version:**  MacOS Big Sur 11.4

**Comment by hjdhjd** [comment]
The documentation at https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Liveviews.md explains:

> Creating plugin-specific liveviews are as simple as ensuring they are named:

The table that comes after, explains the mapping. The left column represents security system state, the right column represents the liveview name it maps to. So the `Home` security system state would map to a liveview named `Protect-Home`. Enjoy.
