### ISSUE TITLE
I'm unable to get person or vehicle detection alerts.

### ISSUE THREAD

**Issue by hankinsoft** [hjdhjd/homebridge-unifi-protect#547]
**Describe The Problem:**
I'm unable to get person or vehicle detection alerts. I am able to get motion alerts.

**To Reproduce:**
I have added the following three features:
Enable.Motion.SmartDetect
Enable.Motion.SmartDetect.Person
Enable.Motion.SmartDetect.Vehicle

My understanding from the documentation is that `Enable.Motion.SmartDetect` is disabled by default, but adding theses, should enable it. (I do see the smart detection via the `Protect` UniFi app push notification).

**Logs:**
[30/08/2021, 09:58:49] [UniFi Protect] UDMPRO [UDM-PRO]: Connected to the Protect controller API (address: 192.168.1.1 mac: XXXXXXXXXX).
[30/08/2021, 09:58:49] [UniFi Protect] UDMPRO [UDM-PRO]: The user 'homebridge' requires the Administrator role in order to automatically configure camera RTSP streams.
[30/08/2021, 09:58:49] [UniFi Protect] UDMPRO [UDM-PRO]: Connected to the UniFi realtime update events API.
[30/08/2021, 09:58:49] [UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Backyard [UVC G4 Pro] (address: 192.168.1.144 mac: XXXXXXXXXX).
[30/08/2021, 09:58:49] [UniFi Protect] UDMPRO [UDM-PRO]: Discovered camera: Front door [UVC G4 Doorbell] (address: 192.168.1.31 mac: XXXXXXXXXX).
[30/08/2021, 09:58:49] [UniFi Protect] UDMPRO [UDM-PRO]: Controller refresh interval set to 10 seconds.
[30/08/2021, 09:58:49] [UniFi Protect] UDMPRO [UDM-PRO] Backyard [UVC G4 Pro]: Smart motion detection enabled: person, vehicle.

**Environment:**

* **Homebridge Version:** 1.4.3
* **Node Version:** v14.17.4
* **Homebridge-UniFi-Protect Plugin Version:** homebridge-unifi-protect v4.4.2
* **UniFi Protect Version:** 1.19.0
* **UniFi Protect Controller Type:** UDMPro
* **UniFi Protect Controller Firmware Version:** 6.2.26
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 14 and macOS 10.16
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Not sure what to do with this one...the logs clearly show they are enabled. What is it that you think isn't working? Everything appears correct.

**Comment by hankinsoft** [comment]
Hi.

> What is it that you think isn't working?

I’m not getting alerts via the ‘home’ app. I was thinking enabling those options would give me the alerts.

**Comment by edelmaca** [comment]
Did you enable the notifications in the home app for this Camera?

**Comment by hjdhjd** [comment]
@edelmaca Thanks for asking the question I was about to, so I didn't have to. :)

**Comment by hjdhjd** [comment]
And have you read the [Best Practices documentation](https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/BestPractices.md)?

**Comment by hankinsoft** [comment]
![EF370A2C-3F3E-4AF3-9BCF-481CD665DED1](https://user-images.githubusercontent.com/3160528/131397008-0fa53f40-2a76-4dbb-94f5-667b681b7c06.png)
![756EDC7D-FB0F-4434-B613-DE0F56EE3CE5](https://user-images.githubusercontent.com/3160528/131397012-c6dc95bc-fc10-4bcf-a649-f4cd9b8f214e.png)

Hi. I do have notifications enabled and I receive both doorbell and motion notifications via the home app and protect app. Person/vehicle notifications I am only receiving via the protect app (my goal is to disable motion and remove the protect app once I have person/vehicle detection working via the home app).

**Comment by hjdhjd** [comment]
It's working correctly, as designed. You will NOT see a notification that says "vehicle detected" on the iPhone. It's working exactly as designed.

Notifications are only generated and sent to the iOS device when a **smart notification** is generated (aka vehicle, etc.). But the only alert you will see on your iOS device is that motion is detected...you won't get the additional context.

There's not a way to deliver a notification that _says_ "A vehicle was detected" without HomeKit Secure Video, which Homebridge hasn't implemented yet, though it's being worked on and at some point in the coming months, we hope becomes available.

**Comment by hankinsoft** [comment]
Ohhh that makes a ton of sense. Sorry about me causing any confusion and
thanks for the clarification. Also, thanks a ton for making this plugin.
