### ISSUE TITLE
HKSV Support

### ISSUE THREAD

**Issue by sundar2012** [hjdhjd/homebridge-unifi-protect#559]
Hi, any chance you can integrate with the approach here:

https://github.com/koush/scrypted

to add HKSV to this plugin?

**Comment by hjdhjd** [comment]
Kindly do not open issues that have already been addressed in prior issues and discussed. I'm aware of the work that's being done on HKSV, and when support is ready, we'll support it, but not before. I get the excitement, but please don't clutter up issues with topics that are asked, answered, and addressed. :)

**Comment by sundar2012** [comment]
Apologies

**Comment by skhavari** [comment]
where has thees been addressed and discussed. I might be able to help.
