### ISSUE TITLE
Two way audio not working in HomeKit

### ISSUE THREAD

**Issue by flobernd** [hjdhjd/homebridge-unifi-protect#563]
**Describe The Problem:**

Hi there, 

two way audio does not seem to work for me in HomeKit. I'm testing with an UVC G3 Instant. If I try it from the Protect mobile app, I first hear a sound from the camera and after that I can speak without any problems. Trying the same in HomeKit does neither cause the camera to play the initial sound nor can I hear my voice.

**To Reproduce:**

In HomeKit, select the camera, press "speak" and say a few words.

**Logs:**

Nothing related in the output/logs (default verbosity).

**Homebridge Configuration:**

Standard config with a single UNVR. I created a dedicated Homebridge user on my UNVR and assigned the "view only" role. As well tried after additionally assigning the "administrator" role, without any noticeable change.

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** v14.17.6
* **Homebridge-UniFi-Protect Plugin Version:** v4.4.3
* **UniFi Protect Version:** 1.19.0
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** 2.2.7
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 15 on iPhone XS Max
* **Operating System and OS Version:** Windows 10

**Comment by hjdhjd** [comment]
I can confirm that it does indeed work. :smile:

First and foremost - you are running beta iOS releases, none of which are supported. If you are on beta anything - iOS, Protect, etc. - you’re on your own and that is an unsupported configuration, as stated in the documentation. The betas are notorious for issues, particularly when it comes to HomeKit. 

I’d suggest trying with production-only releases and give it a whirl.

**Comment by flobernd** [comment]
@hjdhjd iOS 15 final has been released yesterday 😋

**Comment by flobernd** [comment]
Does not seem to work on iPadOS 4.8 for me as well.

**Comment by hjdhjd** [comment]
Read the detailed troubleshooting documentation if you haven't yet. :smile:

I can confirm it works fine with the latest production configurations of both iOS and iPadOS, on the current production releases of UNVR and Protect controller firmware - same as what you outlined. This functionality isn't new...it's been well-tested, and used by a lot of folks including me. :smile:

Don't have much more to point you to unless you're running in a VLAN/firewalled environment, in which case, I would simplify the network and run it all on a single segment / VLAN to eliminate that dimension.

Good luck.

**Comment by flobernd** [comment]
The troubleshooting guide sadly does not contain any helpful information for me.

I indeed run a segmented network (VLANs), but firewall rules are not a problem here. Checked that already. As well the native UniFi Protect app works fine (including the voice out).

Could you maybe tell me some technical details about how the audio is sent? Is it sent to the UNVR or directly to the cam? Which protocol is used?

**Comment by hjdhjd** [comment]
It's sent directly to the camera as an encoded AAC stream. The native Protect app isn't a good barometer in this instance, since it uses WebRTC to communicate. 

I'm still wagering your issues are related to your network configuration. Simplify the network configuration and put everything on the same segment first. Everything means: Protect camera, UNVR, Homebridge, and your iOS client. That will either confirm or eliminate the network / firewall configuration as part of your issue.

**Comment by flobernd** [comment]
Thanks, that was very helpful. I feel ashamed for double checking all firewall rules from Homebridge -> UNVR, but not actually checking the Homebridge -> CAM cases. I forgot to configure the "Mirco Talkback" (port 7004) route for UDP instead of TCP.

**Comment by hjdhjd** [comment]
Overly aggressive firewall rules are the bane of home network setups. :smile: Best of luck.

**Comment by flobernd** [comment]
Haha, right! Sadly they are required if you have to setup home- and business-networks/infrastructure at the same place. Thanks again for the useful hint!

**Comment by hjdhjd** [comment]
I know the challenge well. :smile:
