### ISSUE TITLE
Add Support for SmartPower Plug

### ISSUE THREAD

**Issue by aveach** [hjdhjd/homebridge-unifi-protect#564]
**Is your feature request related to a problem? Please describe:**
I am frustrated with all the other smart plugs on the market, especially those that have to go through some cloud service. It would be great if this plugin added support for the UniFi SmartPower Plug so that it can be used with HomeKit and Siri.

**Describe the solution you'd like:**
I would like the SmartPower Plug to be supported so that it can be used with HomeKit and Siri.

**Describe alternatives you've considered:**
I've used a lot of the smart plugs on the market. They all suck for one reason or another. 

**Additional context:**
UniFi SmartPower Plug: https://store.ui.com/collections/unifi-accessories/products/unifi-smart-power

**Comment by hjdhjd** [comment]
LOL. Not in Protect, because this doesn't belong here, but in another plugin I'm working on when I get time. It's in the backlog. :smile:

**Comment by aveach** [comment]
Nice! Can't come soon enough! Thanks for all the hard work!

**Comment by cjsfj** [comment]
@aveach FYI I've just installed this one and it works pretty well. https://github.com/derek-miller/homebridge-unifi-smartpower

Then there's also this one if you're interested in using Unifi POE ports as switches. https://github.com/Kienz/homebridge-unifi-poe-control
