### ISSUE TITLE
The ability to connect to offsite Unifi NVR controllers via the homebridge plugin.

### ISSUE THREAD

**Issue by StephenShamakian** [hjdhjd/homebridge-unifi-protect#566]
**Is your feature request related to a problem? Please describe:**
The plugin supports adding additional NVR controllers. In fact I was able to add my NVR to an offsite homebridge install fine after configuring port forwarding rules (so only that one WAN IP address can access it via the Internet). Everything worked. Even camera snapshots. But the RTSP stream failed. I believe this is due to the fact its trying to use the local IP the NVR provides when the homebridge plugins requests the RTSP stream.

I had to resort to using the standard ffmpeg plugin to get the camera feed from a remote NVR.

**Describe the solution you'd like:**
What would be great is if the plugin would use the IP of the NVR that is configured in the homebridge config file (minus any custom ports added to it). For the RTSP stream as well. Maybe add the feature behind a advanced feature flag that way it doesn't create any backwards compatibility issues with other users?

**Describe alternatives you've considered:**
I've considered VPN but I have no way of configuring the VPN at the remote site. Plus I rather not give full access to the local network via the VPN.

**Comment by hjdhjd** [comment]
Appreciate the request. What you’re really describing is an edge case that I can’t see warranting adding support for. This plugin is most definitely not intended to operate across a WAN environment, and though it may work, it’s not a supported configuration and isn’t likely to be in the future.

Best of luck!
