### ISSUE TITLE
Add smart flood light

### ISSUE THREAD

**Issue by mterhar** [hjdhjd/homebridge-unifi-protect#567]
**Is your feature request related to a problem? Please describe:**

I’d like to be able to control the flood light from HomeKit.

**Describe the solution you'd like:**

the smart flood light is quite simple.

- 1 on/off button, 
- 1 motion sensor, 
- a brightness setting that goes from very bright to ever-so-slightly-brighter. 

**Describe alternatives you've considered:**

Opening the unifi protect app is annoying. 

**Additional context:**

If you need the device, let me know.

**Comment by hjdhjd** [comment]
Thanks for the suggestion. As I’ve said elsewhere…it’s on the backlog. Stay tuned. Thanks.
