### ISSUE TITLE
Livestream not working

### ISSUE THREAD

**Issue by DeathBlade** [hjdhjd/homebridge-unifi-protect#576]
Yes I've gone through documentation 

**Describe The Problem:**

Previews update normally but when I open a camera it does not stream. I have setup Protect-Home, etc and there has been no change. Tried changing video processors.

**To Reproduce:**

Open a camera

**Logs:**

No logs when attempting open a camera

**Homebridge Configuration:**

            "controllers": [
                {
                    "address": "Redacted",
                    "password": "Redacted",
                    "username": "Redacted"
                }
            ],
            "options": [
                "Enable.StreamOnly.Low"
            ],
            "verboseFfmpeg": false,
            "platform": "UniFi Protect"
        }

**Screenshots:**

**Environment:**

* **Homebridge Version:**  v1.3.5
* **Node Version:** 16.2.0
* **Homebridge-UniFi-Protect Plugin Version:** v4.4.3
* **UniFi Protect Version:** 1.19.2
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:**  2.1.11
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 13 pro max / ios 15.0.1
* **Operating System and OS Version:** Docker on FreeNAS

**Comment by DeathBlade** [comment]
I moved homebridge to another server not on docker and got this error to show. This homebridge was install on Centos 7 using the official installation process/steps

`(node:14213) UnhandledPromiseRejectionWarning: Error: Command failed with ENOENT: builtin -codecs
spawn builtin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14213) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14213) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

The same happens with ffmpeg

**Comment by hjdhjd** [comment]
You don’t have a working version of ffmpeg installed with the right codecs. Please see the documentation for the plugin for more details. Good luck.
