### ISSUE TITLE
Livestream not compatible with iOS 15?

### ISSUE THREAD

**Issue by ThomasWeiss** [hjdhjd/homebridge-unifi-protect#580]
**Describe The Problem:**
I've recently realized that the livestream, which used to work, doesn't anymore. The screenshots that are taken every 10s still work. The only recent change on my end is that I updated my phone from iOS 14.x to 15.1. Same problem on my spouse's new phone, iOS 15.1 too.

**To Reproduce:**
Click on a specific camera from the Home app. The spinning icon is displayed for a while, then the app says "No response - The camera is not responding".

**Logs:**
Logs aren't showing any error:
```
[31/10/2021, 18:13:40] [UniFi Protect] Cloud Key [UCK-G2-PLUS] Front porch [UVC G4 Bullet]: Streaming request from xxx.xxx.xxx.xxx: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1280x720@24fps (Medium), 2000 kbps.
[31/10/2021, 18:14:10] [UniFi Protect] Cloud Key [UCK-G2-PLUS] Front porch [UVC G4 Bullet]: Stopped video streaming session.
```

**Homebridge Configuration:**
```json
{
    "controllers": [
        {
            "address": "192.168.1.xxx",
            "password": "<password>",
            "username": "homebridge"
        }
    ],
    "platform": "UniFi Protect"
}
```

**Screenshots:**
N/A

**Environment:**

* **Homebridge Version:** 1.3.5
* **Node Version:** 14.15.1
* **Homebridge-UniFi-Protect Plugin Version:** 4.4.3
* **UniFi Protect Version:** 1.19.2
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 2.2.10
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 15.1
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Thanks for the report. That said...it's working just fine on iOS 15.1. Something else may be going on in your setup...but given it's working for the vast majority, myself included, I doubt it's the plugin.

Just going off the minimal symptoms you notes, it might be an mDNS issue on your network, potentially, if I were to hazard a guess. Typically those resolve themselves in a bit of time or with a couple of reboots of the affected network gear.

Good luck.

**Comment by durosity** [comment]
I had an intermittent issue with this and I switched homebridge from ciao to the old HAP option and that appears to have fixed it, although I still get the occasional one that won't connect.. but certainly worth trying
