### ISSUE TITLE
iCloud+ Feature/s 

### ISSUE THREAD

**Issue by DefenestrateIT** [hjdhjd/homebridge-unifi-protect#581]
Hi really like your plug-in so far (keep up the great work), but it would be awesome if I/you/everyone could use iCloud+ features for storing video off-site, in apples icloud+ service (perhaps even the facial recognition features as well).

**Is your feature request related to a problem? Please describe:**

Since Ubiquiti Unifi Protect has no way of natively storing content off site currently, & I have already been broken into once where they took my Ubiquiti UNVR UniFi 4 Bay Network Video Recorder & didn't have notifications set up at the time so I didn't even get photo's. 

**Describe the solution you'd like:**

Triggered video activity in Unifi Protect is record/stored in iCloud+ or some other off-site cloud service.

**Describe alternatives you've considered:**

RTSP feed processed & stored by a NAS or PC then uploaded/rsync'd to off-site storage.

**Additional context:**

https://support.apple.com/en-au/guide/icloud/mme054c72692/icloud
https://support.apple.com/en-au/guide/iphone/iph7bc5df9d9/ios

Once again, Awesome plugin...

**Comment by hjdhjd** [comment]
Appreciate the creative request...I won't be adding this though...it's too kludgy for my liking and a very niche feature set that likely isn't worth the maintenance overhead. 

What I will be adding is HomeKit Secure Video support which provides most of the above and some other things, once homebridge support is there to support it.

Thanks!
