### ISSUE TITLE
Notification for Smart Detection by Zone

### ISSUE THREAD

**Issue by cyrusauyeungc** [hjdhjd/homebridge-unifi-protect#583]
**Is your feature request related to a problem? Please describe:**
I have set up multiple Smart Detection zone in Unifi Protect, say for instance there are two zones, Driveway and Street. Currently, when there are vehicles going across the street or coming into the driveway, I will get notified from both of them.

**Describe the solution you'd like:**
I'd like to see if the notification can be split by zone. 
e.g. if someone is coming into my zone Driveway, I'd like to received a notification in Home.
While in the zone Street, I'd rather have no notification but have it recorded in Unifi Protect only.

**Describe alternatives you've considered:**
Haven't thought of any alternatives at the moment. 
Will keep updating the thread once I come up with any. Thanks!

**Comment by hjdhjd** [comment]
Very much on the roadmap when I get a bit of time. :smile: Appreciate the suggestion!
