### ISSUE TITLE
issue with Enable.Doorbell.Trigger

### ISSUE THREAD

**Issue by marcobastianon** [hjdhjd/homebridge-unifi-protect#589]
**Describe The Problem:**

i've enabled "Enable.Doorbell.Trigger" to trigger a chime rappresented by a homekit switch.
when i try the automation it works and chime rang, and was thinking was all ok.
when i press the doorbell button no action is triggered, m'I wrong someware?

**To Reproduce:**

enabling "Enable.Doorbell.Trigger" option and test linked automation

**Logs:**

```
[27/11/2021, 14:48:39] [UniFi Protect] Domus [UDM-PRO] Campanello [UVC G4 Doorbell]: Doorbell ring event triggered.

and nothing more
```

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "x.x.x.x",
            "password": "xxx",
            "username": "xx.xx@xx.com"
        }
    ],
    "options": [
        "Enable.Doorbell.Trigger"
    ],
    "platform": "UniFi Protect"
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.3.8
* **Node Version:** v16.1.0
* **Homebridge-UniFi-Protect Plugin Version:** v4.4.3
* **UniFi Protect Version:** 1.20.0
* **UniFi Protect Controller Type:** UDMPro
* **UniFi Protect Controller Firmware Version:** v1.10.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone iOS 15
* **Operating System and OS Version:** Raspbian

**Comment by ucdscott** [comment]
I believe I may be having the same issue.

I've created an Automation in the iOS Home app that turns on a vDoorbell switch when the 'G4 Doorbell Doorbell Trigger' turns on and 'Test This Automation' works perfectly but If I turn on 'G4 Doorbell Doorbell Trigger' via the Homebridge UI, the vDoorbell does not turn on.

**Comment by hjdhjd** [comment]
@marcobastianon Thanks for the report. Can you elaborate a bit on what you’re trying to do so I can better understand where the issue might be?

**Comment by marcobastianon** [comment]
hi, thx for you time.. i have G4 Doorebell and when i press the button i have notification on my telephone.. this is ok, but some time i not have my telephone with me.. so i add a chine connected on a relay on homekit.
my goals is: when i press the G4 Doorebell button trigger the switch to enable the chime.
