### ISSUE TITLE
Trigger Doorbell out of MQTT

### ISSUE THREAD

**Issue by Ahrenfelde** [hjdhjd/homebridge-unifi-protect#593]
**Describe The Problem:**
 Is there a Way to trigger the Doorbell out of MQTT? I want to trigger the Doorbell Switch external per an mqtt Message.

**To Reproduce:**
 nothing 

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** Ickgen2 plus
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by dosordie** [comment]
Hello, I am also trying to activate the doorbell from MQTT. Unfortunately does not work.

The Homepods ring with the doorbell button in the Home app.

Am I doing something wrong, or is it just not possible via MQTT?

Greetings
Dominik
