### ISSUE TITLE
Support Request: Disable/enable camera notifications via automation

### ISSUE THREAD

**Issue by Ghazgkull** [hjdhjd/homebridge-unifi-protect#601]
**Describe The Problem:**
I have a Unifi G4 Dome camera integrated with Homekit through this Homebridge plugin and it's working great (thank you!). Now that I have the basic setup working, I'm hoping to reproduce an automation that I previously had set up for my Eufy cameras through that corresponding Homebridge plugin... where I was able to disable motion detection whenever I unlocked a door. And then "re-arm" detection when the door was locked.

Is something like this possible with the homebridge-unifi-protect plugin? Is there a way to automate enabling/disabling motion detection? Or just enable/disable the notifications? The end goal user experience I'm looking for is that when a homeowner unlocks their door and walks out onto their back porch they don't get notifications about their own activity. But when they go back inside and lock the door, motion detection is enabled.

**To Reproduce:**
This is a request for information, not really a problem report. No steps other than "use this plugin". :)

**Logs:**
No logs.

```
No logs but I'm nervous about the automation on this project which closes Issues.
```

**Homebridge Configuration:**
If there's configuration to enable this kind of workflow, that would be great.
```json
{}
```

**Screenshots:**
Not applicable

**Environment:**

* **Homebridge Version:** 1.3.8
* **Node Version:** v16.13.1
* **Homebridge-UniFi-Protect Plugin Version:** v4.4.3
* **UniFi Protect Version:** 1.19.2
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 4.41.16
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Apple TV 4K hub.
* **Operating System and OS Version:** Raspbian 10 (buster)

**Comment by hjdhjd** [comment]
RTFM. :smile:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/FeatureOptions.md#motion-feature-options

See the Motion.Switch feature option.
