### ISSUE TITLE
Support for UP-Sense

### ISSUE THREAD

**Issue by pbush25** [hjdhjd/homebridge-unifi-protect#607]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
Add support for the new UP-Sense and associated sensors to show up in HomeKit.

**Describe alternatives you've considered:**
There aren't any -- this is a new product I'd like to see supported.

**Additional context:**
Should support: motion, door open/closed, accelerometer, temperature, humidity, ambient light, and alarm sound sensors/notifications

**Comment by hjdhjd** [comment]
As stated in numerous places in the documentation - beta hardware and software are unsupported. When it’s no longer beta…yes, I’ll be providing support for it. :smile: The sensor is still beta, currently.

**Comment by hjdhjd** [comment]
Spoke too soon…I see it’s now GA. Support will be coming in the not distant future. :smile:

**Comment by pbush25** [comment]
I only came here bagaje it came out of EA this morning, no need to get snippy. 😊

**Comment by hjdhjd** [comment]
Ha! Not even giving me 24 hours…that’s just mean. Hey, remember this is a passion project! :smile: Now go do something else like celebrate NYE and reflect on the awesomeness of this plugin! 😜

**Comment by pbush25** [comment]
Id be happy to help with the implementation if you want to point me in a direction. I'm an iOS dev by day but I know enough js to be dangerous.

**Comment by hjdhjd** [comment]
Appreciated it…but I’m good. It’s on my roadmap and there are some other things I’d like to do as well. Thanks though!
