### ISSUE TITLE
Snapshots not updating or are blank.

### ISSUE THREAD

**Issue by michaelyork** [hjdhjd/homebridge-unifi-protect#608]
**Describe The Problem:**
As of the last day or so, none of my cameras return snapshots. They're just blank, and all Home apps (macOS, iOS, iPadOS) just show "now" perpetually in the snapshot timestamp field. All cameras still stream perfectly. Potentially related to UNVR Pro 2.3.10 firmware update? I believe it happened around the same time, but can't be sure.

**To Reproduce:**
- Open Home app
- Observe cameras

**Logs:**

```
[12/29/2021, 4:14:45 PM] [homebridge-unifi-protect] <REDACTED> NVR [UNVR-PRO]: Connected to the Protect controller API (REDACTED).
[12/29/2021, 4:14:45 PM] [homebridge-unifi-protect] <REDACTED> NVR [UNVR-PRO]: Connected to the UniFi realtime update events API.
[12/29/2021, 4:14:45 PM] [homebridge-unifi-protect] <REDACTED> NVR [UNVR-PRO]: Discovered camera: Office [UVC G3 Flex] (REDACTED).
[12/29/2021, 4:14:45 PM] [homebridge-unifi-protect] <REDACTED> NVR [UNVR-PRO]: Discovered camera: Family Room [UVC G4 Instant] (REDACTED).
[12/29/2021, 4:14:45 PM] [homebridge-unifi-protect] <REDACTED> NVR [UNVR-PRO]: Discovered camera: Garage [UVC G4 Pro] (REDACTED).
...
[12/29/2021, 4:14:45 PM] [homebridge-unifi-protect] <REDACTED> NVR [UNVR-PRO]: Controller refresh interval set to 15 seconds.
[12/29/2021, 4:14:45 PM] [homebridge-unifi-protect] <REDACTED> NVR [UNVR-PRO] Office [UVC G3 Flex]: Disabling motion sensor.
[12/29/2021, 4:14:45 PM] [homebridge-unifi-protect] <REDACTED> NVR [UNVR-PRO] Family Room [UVC G4 Instant]: Disabling motion sensor.
[12/29/2021, 4:14:45 PM] [homebridge-unifi-protect] <REDACTED> NVR [UNVR-PRO] Garage [UVC G4 Pro]: Disabling motion sensor.
...
```

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "...",
            "name": "UNVR Pro",
            "password": "...",
            "refreshInterval": 15,
            "username": "homebridge"
        }
    ],
    "options": [
        "Disable.Motion.Sensor",
        "Enable.Video.Stream.Only.High.10.1.1.3",
        "Enable.Video.Stream.Only.High.10.1.1.4",
        "Enable.Video.Stream.Only.High.10.1.1.5",
        "Enable.Video.Stream.Only.High.10.1.1.6",
        "Enable.Video.Stream.Only.High.10.1.1.7"
    ],
    "verboseFfmpeg": false,
    "_bridge": {
        "username": "...",
        "port": 36809
    },
    "platform": "UniFi Protect"
},
```

**Screenshots:**

![IMG_0946](https://user-images.githubusercontent.com/3916693/147712189-a65e82bd-726a-4e5d-8ba4-e09b718d31d5.PNG)

**Environment:**

* **Homebridge Version:** 1.3.9
* **Node Version:** 14.18.0
* **Homebridge-UniFi-Protect Plugin Version:** 4.4.3
* **UniFi Protect Version:** 1.20.3
* **UniFi Protect Controller Type:** UNVR-Pro
* **UniFi Protect Controller Firmware Version:** UNVR Pro 2.3.10
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 15.2
* **Operating System and OS Version:** Ubuntu Server 20.04.3 LTS

**Comment by michaelyork** [comment]
Worth mentioning (to rule out potential bug with Home app clients), camera snapshots from other homebridge plugins (like [homebridge-videodoorbell](https://github.com/Samfox2/homebridge-videodoorbell#readme)) are working fine.

**Comment by brianmedia** [comment]
I had the same issue after the Protect upgrade/update... a reboot of Homebridge fixed it for me.

**Comment by michaelyork** [comment]
@brianmedia Unfortunately that didn’t resolve for me. Had tried several times. :(

**Comment by hjdhjd** [comment]
I’ve noticed the behavior in the last couple of days…chalking it up to a bug in Protect at the moment, and not the plugin or Homebridge…but I’ll be watching. Bear with it guys…while I look into it a bit further. Deeply annoying to all of us (me included!). As with most updates…I suspect this is a Protect bug that’ll be resolved in a future firmware update on the Ubiquiti end…but I’ll rule out the other stuff in the next day or so.

**Comment by michaelyork** [comment]
Thanks for taking a look @hjdhjd! I'm just not sure why the Home app would suddenly start failing for us without an iOS/macOS update.

Don't have a native HK camera to test with - will leave that to someone else.

**Comment by hjdhjd** [comment]
I agree. That said, there **was** an iOS update on 12/13. Given the holidays, many of us - me included - have been looking at our phones less often and problems like this are less obvious. Or it’s another issue entirely.

The key point here is: **this problem isn’t restricted to this plugin.** Another data point: https://www.reddit.com/r/HomeKit/comments/rpwcww/camera_snapshots_stuck_showing_now_but_image_is/

**Unless there’s compelling information to show otherwise, this is a HomeKit / Apple / iOS issue that needs to be resolved, not a plugin issue.**

**Comment by ydnar** [comment]
Can confirm this happens with iOS 15.3. I see stale (not black) snapshots for all UniFi Protect cameras in the Home app.

**Comment by michaelyork** [comment]
Oh wow, that Reddit thread is pretty definitive. Thanks @hjdhjd !

**Comment by brianmedia** [comment]
> @brianmedia Unfortunately that didn’t resolve for me. Had tried several times. :(

Ah! I got fooled by the stale image vs black screen. Definitely not working for me either.

**Comment by codesleeper** [comment]
@hjdhjd Just wanted to confirm that this does seem to be an issue with Home app. When I open Home+ the snapshots load as expected.

**Comment by MitchJackson94** [comment]
Looks like signing out and back in of iCloud works but not sure how long it’ll last

**Comment by hjdhjd** [comment]
Seems to be mysteriously back to working again across all HomeKit devices. Maybe someone at Apple flipped the wrong switch last week. :smile:

**Comment by michaelyork** [comment]
Interesting. Still very much broken on my end across all devices (even post-reboot). :(

**Comment by ufkel** [comment]
Strange. A minute ago, it switched back to working on my iPad. On my iPhone, the problem still persists. On my Mac, the problem never came up at all. Kind of a mixed bag experience.

**Comment by jnanes** [comment]
The solution for me was to sign out and back into iCloud. It is now working.

**Comment by speedingcheetah** [comment]
> The solution for me was to sign out and back into iCloud. It is now working.

How do you do that in the home app?

**Comment by jnanes** [comment]
You need to sign out of iCloud under settings on your iPhone. You’re not just signing out of the Home app.

Thanks,
Jesse

**Comment by speedingcheetah** [comment]
> You need to sign out of iCloud under settings on your iPhone. You’re not just signing out of the Home app. Thanks, Jesse
> […](#)
> On Jan 9, 2022, 12:56 PM -0500, speedingcheetah ***@***.***>, wrote: > The solution for me was to sign out and back into iCloud. It is now working. How do you do that in the home app? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

That says it signs out of find my iphone

**Comment by speedingcheetah** [comment]
Signing out of the full phone is NOT a solution or possible. It erases data. Like all your Wallet cards and other things it removes from the phone. Do NOT do it..

**Comment by jnanes** [comment]
whaaaaaaa? I have lost 0 data. I added my credit cards back to home app in about 45 seconds. I now have working screenshots. Good luck to you sir.

**Comment by jnanes** [comment]
Find my iphone re-enables the moment you sign in :)

**Comment by speedingcheetah** [comment]
Not a fix or solution or the issue, since it works fine on a iphone that has not been done to.
The issues is somewhere else and needs to be fixed.
I can not add cards back, the Apple card for one lives on the phone and have no way to add it back.

**Comment by jnanes** [comment]
Call @apple and let them know then! :) it is not an issue with this plugin.

**Comment by speedingcheetah** [comment]
> Call @apple and let them know then! :) it is not an issue with this plugin.

its the dev job to report bugs with ios, since they program app for it.

**Comment by jnanes** [comment]
This is not something supported by apple. you are using a 3rd party unsupported plugin.

**Comment by speedingcheetah** [comment]
> This is not something supported by apple. you are using a 3rd party unsupported plugin.

But still you say its an Apple issue not plugin issue? make up your mind.

**Comment by hjdhjd** [comment]
Locking this issue. :smile: Suggest this gets taken up on Discord. This is not an issue with the plugin...please see the https://github.com/hjdhjd/homebridge-unifi-protect/issues/608#issuecomment-1003039347 or the Discord for more information.
