### ISSUE TITLE
Streams work from Home app on iOS devices but not from Home app on Mac

### ISSUE THREAD

**Issue by jimmyz80** [hjdhjd/homebridge-unifi-protect#611]
**Describe The Problem:**
I am new to using this plugin with Homebridge, but it seems to be working perfectly fine from the Home app on all of my iOS devices. However, when I try to use the Home app on my Mac, I can see all of the camera thumbnails but clicking on them never starts a stream. It tries to load but just fails after waiting a bit.

**To Reproduce:**
Try loading a stream from the Home app on a Mac. I am on MacOS Monterey 12.1.

**Logs:**
All logs appear to be normal, even though this streaming session did not load successfully from the Home app on my Mac.

[12/31/2021, 3:44:37 PM] [UniFi Protect] UDM-Pro [UDM-PRO] Back Yard Lawn Side [UVC G4 Bullet]: Streaming request from 192.168.1.101: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1280x720@24fps (Medium), 2000 kbps.
[12/31/2021, 3:45:02 PM] [UniFi Protect] UDM-Pro [UDM-PRO] Back Yard Lawn Side [UVC G4 Bullet]: Stopped video streaming session.

**Homebridge Configuration:**
NA

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.3.9
* **Node Version:** 16.13.1
* **Homebridge-UniFi-Protect Plugin Version:** 4.4.3
* **UniFi Protect Version:** Protect 1.20.3
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** UniFi OS UDM Pro 1.11.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Mac 12.1
* **Operating System and OS Version:** Docker on Synology DSM7

**Comment by simplytoast1** [comment]
I have the same issue, however the stream does work with Scrypted

**Comment by EricSabe** [comment]
Same issue - trying to load the stream from the Home app on my iPhone.  Started a few days back.

**Comment by hjdhjd** [comment]
Thanks for the reports...I use my plugin daily on a Mac, running the latest Monterey as well. :smile:

This is typically a configuration or firewall issue on your network and not a plugin issue. Have you run through all the troubleshooting steps in the documentation? If not, I'd start there. The logs above indicate that everything on the plugin end is working as it should.

**Comment by simplytoast1** [comment]
It's on a local network and my machines firewall is off (serving it on a Mac as well).

But I'll start inspecting traffic to see any hints.

**Comment by hjdhjd** [comment]
If you haven't run through the troubleshooting steps, I'd start there. If the logs show a stream has started, it's clear there's communication to the plugin. Curious to see what you discover...thanks!

**Comment by EricSabe** [comment]
> Same issue - trying to load the stream from the Home app on my iPhone. Started a few days back.

Fwiw, my issue seems to be triggered by the combination of a two things:  (A) being on the same subnet as either the Home hub (Apple TV) and/or the docker container running HomeBridge (both of those are on the same subnet - 192.168.x.x) AND (B) Microsoft Defender for Endpoint's Web Protection feature - it uses a loopback VPN to scan URLs.

When A and B are true, the HomeBridge log shows that the streaming request comes from IP 10.10.10.10, which happens to be the IP address my phone uses within the MDE VPN.  There is no route between HomeBridge and that IP, so the log shows that it's sending packets but the phone sees nothing.  If I move the phone to a different wireless network (and subnet) but leave the VPN active, it seems that the requesting IP changes to the Home Hub (Apple TV) and the relay between the Apple TV and my phone works as expected, streams coming through fine.  If I leave the phone on that first wireless network and disable the VPN, it works fine and the requesting IP changes to the phone's IP on that network. 

I've had MDE on my phone for a few months now and this seems to have changed on 12/30/2021, so not sure what happened.

**Comment by hjdhjd** [comment]
Thanks for tracking it down further @EricSabe. Non-straight-forward network configurations can wreak havoc in Homebridge, and then you throw Docker into the mix and it gets even dicier. There's a forthcoming update to the plugin that will default the streams to use the same address as provided by the user in the plugin configuration versus using what the Protect NVR gives us. That should resolve issues for **some** of these types of issues / quirks.

Docker introduces a whole other class of issues in Homebridge. If you haven't had a chance to, read:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Troubleshooting.md#network-issues

There's a pointer on how to force the network interface for Homebridge traffic if needed.

Really the underlying question I think is the last one asked: what changed for folks at the end of the calendar year?

**Comment by stevesinchak** [comment]
Same issue as others reported.  Works fine on iPhone but not Mac. I also have a different setup than @EricSabe so I'm not sure the factors he mentioned are related. 

In my environment the iPhone and Mac are on the same subnet so same FW rules/network conditions apply.  When I connect from iPhone everything works as expected.  But does not work from the Home app on the Mac and I see this in the home bridge logs:

[1/6/2022, 10:13:02 PM] [UniFi Protect] UNVR [UNVR4] Basement [UVC G3]: Streaming request from X.X.X.X: 1280x720@30fps, 299 kbps. Using RTSP stream profile: 1920x1080@30fps (High), 6000 kbps.
[1/6/2022, 10:13:03 PM] [UniFi Protect] UNVR [UNVR4] Basement [UVC G3]: Stopped video streaming session.

So you can see it is able to communicate but then immediately stops.  The Mac is running Monterey 12.1.  Thumbnails do work fine on Mac generally.  Just unable to jump to live stream.

**Comment by hjdhjd** [comment]
@stevesinchak Thanks...that's a clean setup network-wise, so we can eliminate that class of issues and continue to troubleshoot. Out of curiosity, can you try a couple of things:

1.  Disable iCloud Private Relay if enabled and see if that helps.
2. Enable transcoding in the plugin configuration and see if that helps.

I've got an identical setup to yours, but I can't replicate this issue and it's both fascinating and frustrating.

**Comment by stevesinchak** [comment]
No iCloud Private Relay, I'll have to read the docs to setup transcoding.  But another interesting observation, I pulled out a macbook running 11.5.2, again same network and everything works as expected.  I'm going to upgrade that macbook to 12.1 now and see if that has an impact.

**Comment by hjdhjd** [comment]
Enabling transcoding is straightforward...add this feature flag: `Enable.Video.Transcode`.

I am starting to suspect this is a bug in the latest Monterey.

**Comment by simplytoast1** [comment]
I think it’s a problem with the video stream.  On my side forcing encoding works.  No encoding doesn’t.

The oddest thing is the stream works non encoded from Scrypted which is using the same direct stream you are.

**Comment by hjdhjd** [comment]
It's not a problem with the video stream, but thanks. :smile: I've think I've tracked down the issue...will be dealt with in an upcoming update the weekend.

**Comment by simplytoast1** [comment]
Wow!  Great work!!!

**Comment by stevesinchak** [comment]
Likely unnecessary at this point, but reporting that transcoding did not help.  Same experience.  We'll see if it breaks upon 12.1 upgrade on macbook when that finishes in a while. 

[1/6/2022, 10:36:00 PM] [UniFi Protect] UNVR [UNVR4] Basement [UVC G3]: Streaming request from X.X.X.X: 1280x720@30fps, 299 kbps. Transcoding RTSP stream profile: 1920x1080@30fps (High), 6000 kbps.

[1/6/2022, 10:36:01 PM] [UniFi Protect] UNVR [UNVR4] Basement [UVC G3]: Stopped video streaming session.

**Comment by hjdhjd** [comment]
@stevesinchak Please keep going...just because I think I know the problem doesn't mean it's the actual problem you're experiencing, especially given that I'm not seeing this issue myself. :smile:

My money is on a Monterey bug.

**Comment by stevesinchak** [comment]
So the Macbook that I upgraded to 12.1 continues to work fine. Same network as mac mini also on 12.1 that does not work.  

So network does not seem to play a role, OS version does not, specific devices?

**Comment by hjdhjd** [comment]
Are you able to downgrade the mini? 12.1 only came out over the holidays...

**Comment by stevesinchak** [comment]
Mac mini is my daily driver so that is a difficult ask.  Any other takers first?

**Comment by hjdhjd** [comment]
Not worth it...I'm going to lock this issue shortly...I feel good that it's likely a bug, and between that and an update I'm going to be pushing, I suspect we'll be in good shape. Thanks for taking the time to test!

**Comment by simplytoast1** [comment]
Its odd... I still have the issue.  My network is family simple.  No VLANs, no firewall rules.  Using the medium steam from the camera. Bulletproof on iOS in and out of the house.  MacOS its touch and go.

**Comment by stevesinchak** [comment]
> Following up on this @stevesinchak - can you see how v5 works for you?

Same issue on new version.  iOS awesome, mac mini 12.1 shows thumbs but can't do live video. Also tried signing out ad back into my iCloud account. Removed and re-added the bridge and also flattened my network so similar setup to @simplytoast1.

**Comment by hjdhjd** [comment]
Kind of stumped here I’m afraid. Have a similar setup to everyone here and yet everything works just fine. Do you have genuine HomeKit cameras in your setup and do they work well? Trying to figure out what’s different here and how to chase this. Clearly a connection is made and responded to…so something else is amiss.

I assume you’ve also tried enabling transcoding? Add this feature option: `Enable.Video.Transcode`…that should definitely eliminate any video stream weirdness, should there be any.

**Comment by stevesinchak** [comment]
Tried transcoding again as well but no change.  This feels more like an Apple bug because it is working on 12.1 on my Macbook but not on my Mac Mini.  Unfortunately, I do not have any legit HomeKit cameras.

**Comment by hjdhjd** [comment]
Inclined to agree that it’s an Apple-ism. Sorry folks…hopefully in 12.2 which should come out soon?

**Comment by simplytoast1** [comment]
I’m leaning more to the plugin because the same cameras work perfectly with Scrypted on the Mac

**Comment by jimmyz80** [comment]
My ring doorbell stream loads fine, but none of my UniFi cameras do. Same behavior with and without transcoding enabled.

**Comment by simplytoast1** [comment]
Low Works.

Transcoding in any form doesn’t.

I’m going to look at the ScryptedApp docs and see how Koush does it for a hint.  I think with HKSV coming to HB coming soon that would be helpful.

**Comment by hjdhjd** [comment]
It's no different than any of us do it...there's no magic there. HKSV is the variable...and I view this as an Apple bug until proven otherwise. The above also proved that there is a specific difference once macOS was upgraded to the latest Monterey for a user...again, points to an Apple issue. Also...I'm running on the same setup, and I know others who are as well, without an issue.

Closing this issue - until someone proves to me this is a plugin issue, it's an Apple one in my book that's being masked by HKSV. Sorry folks.

**Comment by stevesinchak** [comment]
Low didn't help me.  But I also tried a different plugin (Homebridge Camera FFmpeg) and I have the same behavior on my mac mini so I don't think this is plugin specific.  Maybe all plugins that are not using HKSV are impacted.

**Comment by hjdhjd** [comment]
@stevesinchak Exactly my suspicion at this point. Thanks so much for leaning in to help test BTW!

**Comment by simplytoast1** [comment]
That can be the case!  Until the next OS release!  Thanks all!
