### ISSUE TITLE
Plugin Crashes Due to Missing FFmpeg.

### ISSUE THREAD

**Issue by simplytoast1** [hjdhjd/homebridge-unifi-protect#612]
**Describe The Problem:**
On update to 4.4.4 when attempting to start a stream the plugin crashes the child bridge.

**To Reproduce:**
Start a steam on any iOS or MacOS device

**Logs:**

[1/2/2022, 6:21:36 PM] [Homebridge UI] Running Command: npm install -g homebridge-unifi-protect@latest
Error: Command failed with ENOENT: ffmpeg -codecs
spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[1/2/2022, 6:22:27 PM] [homebridge-unifi-protect] Child bridge process ended
[1/2/2022, 6:22:27 PM] [homebridge-unifi-protect] Process Ended. Code: 1, Signal: null

**Environment:**

* **Homebridge Version:** 1.3.9
* **Node Version:** 16.13.1
* **Homebridge-UniFi-Protect Plugin Version:** 4.4.4
* **UniFi Protect Version:** 1.20.3
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.11.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 15.2
* **Operating System and OS Version:**  macOS

**Comment by hjdhjd** [comment]
You don't have an accessible version of FFmpeg. :smile:

Plugin shouldn't just crash, but that's the underlying issue.

**Comment by simplytoast1** [comment]
Odd, It worked perfectly in the last versions.  Was FFMPEG changed in 4.4.4?

**Comment by hjdhjd** [comment]
Nope. The plugin has nothing directly to do with FFmpeg, though it does leverage ffmpeg-for-homebridge. Suggest you look there, or specify a path to a working FFmpeg. See the plugin documentation for details.

**Comment by simplytoast1** [comment]
I just reinstalled FFMPEG-For-Homebridge and that did the trick!  Guess in my update cycle something broke from here to there.  Thanks for the prompt responses... Closing the issue.

**Comment by tablatronix** [comment]
Homebridge crashes from this, is that normal ?

![Screen Shot 2022-01-06 at 10 35 11 AM](https://user-images.githubusercontent.com/807787/148417216-551d5bae-8294-4fa4-bb03-711b39983dfb.png)

**Comment by hjdhjd** [comment]
Nope...it'll be fixed in an upcoming version..an unfortunate regression. That said, without a working FFmpeg the plugin is pretty much useless anyway, so there's that. :smile:

**Comment by tablatronix** [comment]
How can I fix in docker ? Do i need to install this inside the container maybe or add a volume map ?

**Comment by hjdhjd** [comment]
Uninstall and reinstall the plugin...it's a bug in ffmpeg-for-homebridge. You won't lose any configuration information.

If that doesn't work try: https://github.com/hjdhjd/homebridge-unifi-protect/issues/612#issuecomment-1003807305 above.

**Comment by tablatronix** [comment]
Fixed, thanks!
