### ISSUE TITLE
No preview images in iOS Home app.

### ISSUE THREAD

**Issue by speedingcheetah** [hjdhjd/homebridge-unifi-protect#613]
Noticed not getting preview images in Home App anymore. clicking on it it will stream. logs show this.
[03/01/2022, 18:53:18] [UniFi Protect] UniFi-CKG2+ [UCK-G2-PLUS] G3wifi [UVC G3 Instant]: Unable to retrieve a snapshot: the camera is offline or unavailable.

Which i not true, cause like i said, i tap the cam and it loads the stream fine. am fully up to date on plugin and HB version, rebooted phone and HB.
there was a recent Unifi Cloud key update to 2.3.10. maybe that broke something?

homebridge-unifi-protect v4.4.4
homebridge-config-ui-x v4.41.5
Node.js Version | v14.18.2

**Comment by hjdhjd** [comment]
Please don’t duplicate issues. There’s already an open issue on this.
