### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by theomuys** [hjdhjd/homebridge-unifi-protect#614]
**Describe The Problem:**
This plugin seems to give the DeprecationWarning:
(node:18088) [node-fetch#buffer] DeprecationWarning: Please use 'response.arrayBuffer()' instead of 'response.buffer()'
(Use `node --trace-deprecation ...` to show where the warning was created)

**To Reproduce:**
Enable the UniFi-Protect plugin. I have disabled and restarted (cleared cache) of my other plugins (only 2 other plugins) one by one. If the UniFi-Protect plugin is enabled, I get this message.

**Logs:**

```
(node:18088) [node-fetch#buffer] DeprecationWarning: Please use 'response.arrayBuffer()' instead of 'response.buffer()'
(Use `node --trace-deprecation ...` to show where the warning was created).
```

**Homebridge Configuration:**

```json
   {
            "controllers": [
                {
                    "address": "192.xxxxxx",
                    "password": "xxxxxxxx",
                    "refreshInterval": 5,
                    "username": "xxxxx"
                }
            ],
            "options": [
                "Enable.Doorbell.Trigger.XXXXXXXXXX"
            ],
            "platform": "UniFi Protect"
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.3.9
* **Node Version:** v16.3.1
* **Homebridge-UniFi-Protect Plugin Version:** v4.4.4
* **UniFi Protect Version:** 1.20.3
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** v2.3.10
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** macOS 12.1 Monterey
* **Operating System and OS Version:** Raspbian Buster

**Comment by hjdhjd** [comment]
Known issue...it's harmless and will be addressed in a future update. Thanks for the report!
