### ISSUE TITLE
Camera Image Thumbnails No Longer Updating

### ISSUE THREAD

**Issue by wingcomm** [hjdhjd/homebridge-unifi-protect#618]
**Describe The Problem:**
Thumbnails are no longer loading in the Home App on iOS. We are using iOS 15.2 on 4 different devices (iPhone/iPad). I can load the live streams on all the cameras just fine, but the thumbnails have not updated since 12/26/21. Home App on iOS shows that thumbnails were updated "Now". Genuine HomeKit/HKSV cameras with another home load thumbnails as expected.

Further testing reveals that this issue appears to be the opposite of #611 ... I seem to be able to see thumbnails on all my macOS devices running 10.15, 11.6.2. However, they will not load on my M1 Mac running 12.1.

One camera is temporarily offline, but this has not affected thumbnail display in the past.

**To Reproduce:**
Open Home App and look at the thumbnails.

**Logs:**

```
[1/10/2022, 8:03:10 AM] [UniFi Protect] HomeName [UCK-G2-PLUS] CameraName [UVC G3 Micro]: Unable to retrieve a snapshot: the camera is offline or unavailable.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.3.9
* **Node Version:** v12.18.2
* **Homebridge-UniFi-Protect Plugin Version:** 0.5.0
* **UniFi Protect Version:** 1.20.3
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 2.3.10
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 15.2
* **Operating System and OS Version:** Docker

**Comment by burkusmax** [comment]
I had this happen. I just needed to log out of iCloud and back in and everything started working again.

**Comment by wingcomm** [comment]
That’s not really an option since a lot of my walllet items would be removed and I’d have to re-add them.

**Comment by hjdhjd** [comment]
Duplicate. This isn't a plugin issue. See: https://github.com/hjdhjd/homebridge-unifi-protect/issues/608#issuecomment-1003039347
