### ISSUE TITLE
Support G4 Doorbell Pro Package Camera

### ISSUE THREAD

**Issue by nickelser** [hjdhjd/homebridge-unifi-protect#621]
**Is your feature request related to a problem? Please describe:**

I would like to be able to view the package camera for my Doorbell Pro.

**Describe the solution you'd like:**

A second HomeKit camera of the package camera (it is available as a separate RTSP stream).

**Describe alternatives you've considered:**

The package stream isn't actually supported in the iOS app so I can only view it on web right now.

**Additional context:**

Product page is here:

https://store.ui.com/collections/unifi-protect-cameras/products/g4-doorbell-pro-ea

**Comment by hjdhjd** [comment]
Please RTFM. :smile: We explicitly do not support beta or EA releases of anything software nor hardware-wise from Protect.

**Comment by nickelser** [comment]
Hm, I did see the note about beta/EA software but did not see a note about EA hardware - maybe it can be called out more clearly in the README? For an upcoming product like this, would you accept a draft PR to support the functionality, if it's officially released?

**Comment by hjdhjd** [comment]
Your assumption is that it isn’t already supported…which it will almost certainly be when it’s released, and happy to review any PRs people submit. Please do not discuss unreleased products here. This is not the place for them. Thanks.

**Comment by nickelser** [comment]
Sounds good; my only ask would be to make clear that policy around EA products (both discussion around and support of) so that others don't open spurious issues like me 😅

Thank you for your hard work on this project!

**Comment by hjdhjd** [comment]
Thanks…and you can’t run EA stuff without running beta firmware. :smile: One requires the other, generally speaking. But I will make it even more explicit.

**Comment by hjdhjd** [comment]
I am. 😄 It will be in an upcoming release. Thanks. 😄
