### ISSUE TITLE
Feature Request: HomeKit Secure Video 

### ISSUE THREAD

**Issue by randomranran** [hjdhjd/homebridge-unifi-protect#625]
**Is your feature request related to a problem? Please describe:**

Feature Request 

**Describe the solution you'd like:**

HomeKit Secure Video support

With the release of HomeBridge 1.4.0 beta 4 homebridge now supports secure video. Are there any plans to implement this into this already great plugin?

**Describe alternatives you've considered:**

I know the devs of Camera Ui already have a beta out for HSV and the also the devs of Homebridge Camera FFMPEG also have stated they are working on implementing HSV

**Additional context:**

n/a

**Comment by hjdhjd** [comment]
Please do not open issues or feature requests without looking through prior issues. This has been asked and answered many times, including most recently in the latest release notes.
