### ISSUE TITLE
5.0.5 upgrade error

### ISSUE THREAD

**Issue by aferrar** [hjdhjd/homebridge-unifi-protect#627]
Hi, thanks for the plugin.

When trying to upgrade my plugin I get the following error (running homebridge in a docker container, all previous upgrades had no issue). Thank you.

USER: root
DIR: /homebridge
CMD: npm install --save homebridge-unifi-protect@latest

npm ERR! code EROFS
npm ERR! syscall open
npm ERR! path /root/.npm/_cacache/tmp/1203ff43
npm ERR! errno EROFS
npm ERR! rofs Invalid response body while trying to fetch https://registry.npmjs.org/homebridge-unifi-protect: EROFS: read-only file system, open '/root/.npm/_cacache/tmp/1203ff43'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

Command failed. Please review log for details.

**Comment by hjdhjd** [comment]
This isn't a plugin issue...it's a docker / system issue...your filesystem is readonly. Your issue is elsewhere I'm afraid.
