### ISSUE TITLE
Support for G4 Doorbell Pro

### ISSUE THREAD

**Issue by jonathanbardo** [hjdhjd/homebridge-unifi-protect#629]
Hi!

I got an EAP unit for the GA Doorbell Pro (UVC G4 Doorbell Pro) and setup the unit in the unifi console. The camera works great but the Ring and actually doorbells option are not being recognized. I tried to look at the source code but I can't put my finger on where I would need to make the modification to enable it. Do we need to add some sort of identifier to a config somewhere?

**Is your feature request related to a problem? Please describe:**
The[ G4 Doorbell Pro](https://store.ui.com/collections/early-access/products/g4-doorbell-pro-ea) is not being recognize as a doorbell. 

**Describe the solution you'd like:**
Trying to understand how doorbell are being recognize. Either by config or something else.

**Describe alternatives you've considered:**
I looked at the source code and saw that doorbell has a feature flag called hasChime but I don't quite know how to debug why the new doorbell pro doesn't work.

**Additional context:**

**Comment by hjdhjd** [comment]
No EA hardware is supported, nor will be, by this plugin. If it's GA, expect support to be forthcoming. Please don't open issues without reading the documentation ahead of time that specifically enumerates this. :smile:

https://github.com/hjdhjd/homebridge-unifi-protect#things-to-be-aware-of

**Comment by jonathanbardo** [comment]
That's totally fine. Was just looking for pointers to be able to contribute something once it hit GA in a few months.

**Comment by hjdhjd** [comment]
Appreciated, but I'll be adding support once it is. :smile:

**Comment by jonathanbardo** [comment]
Really a head scratcher! The feature flag on that accessory does say hasChime and following the code it should work out of the box.

**Comment by hjdhjd** [comment]
Locking and deleting this. Please do not discuss EA products here. They are, at best, ambiguous topics of discussion given Ubiquiti’s EA terms of use. Thanks. Redacting and deleting as well.
