### ISSUE TITLE
Picture / Live Stream is not shown outside LAN / WIFI

### ISSUE THREAD

**Issue by fritte87** [hjdhjd/homebridge-unifi-protect#631]
**Describe The Problem:**
When I leave my House and Phone switch to LTE, the Livestream is not working anymore, Snapshots all 10 s are working done

**To Reproduce:**
Switch off Wifi on my iPhone / iPad - Livestream is broken 

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** newest Version 1.3.9
* **Node Version:** v12.18.3
* **Homebridge-UniFi-Protect Plugin Version:** newest 
* **UniFi Protect Version: 1.20.3
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** newest
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iPhone / iPad
* **Operating System and OS Version:** Installed on Raspberry Homebridge

**Comment by hjdhjd** [comment]
Thanks for the report. This isn't really an actionable bug report, and it's almost certainly not an issue with the plugin. Please read through the documentation (it is extensive!) including the troubleshooting docs. My suggestion for this type of issue is to try the Discord...this looks like a network configuration issue in your setup, not a plugin one. Happy to help you over there. Thanks!

**Comment by fritte87** [comment]
Hi,
Thanks...I read the Docu again and set the "Enable.Video.Stream.Only.Low" - now everything works fine!!

Thanks...
But: I dont find the donate Button where I can spend some Money...
