### ISSUE TITLE
HomeKit secure video support

### ISSUE THREAD

**Issue by MikeO7** [hjdhjd/homebridge-unifi-protect#634]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
Support for HomeKit secure video 

**Describe alternatives you've considered:**
NA

**Additional context:**
Homebridge recently released version 1.4 which supports HKSV.
Release notes: https://github.com/homebridge/homebridge/releases/tag/v1.4.0

**Comment by hjdhjd** [comment]
RTFM…asked and answered in multiple places including the most recent release notes and change log. Please don’t open issues without taking the time to read the documentation and prior issues.
