### ISSUE TITLE
A GH Issue or PR to track Progress on HomeKit Secure Video Support

### ISSUE THREAD

**Issue by francisschmaltz** [hjdhjd/homebridge-unifi-protect#635]
**Is your feature request related to a problem? Please describe:**
No

**Describe the solution you'd like:**
A link to release notes, changelog, PR, or issue where HKSV is tracked

**Describe alternatives you've considered:**
N/A

**Additional context:**
After diving through other GH Issues related to HomeKit Secure Video – the latest update seems to say there will be "noise" when HK upstream supports it, but there is no recent updates – PR's that mention [HKSV](https://github.com/hjdhjd/homebridge-unifi-protect/pulls?q=HomeKit+Secure+Video) or [HomeKit Secure Video](https://github.com/hjdhjd/homebridge-unifi-protect/pulls?q=HomeKit+Secure+Video), reading the changelog, viewing the only commit that references "Secure Video" https://github.com/hjdhjd/homebridge-unifi-protect/commit/16bf7d07a5b6e100ae78ee784021b7a854e1bcc0 . Can you provide an issue that you don't immediately lock to track HK Video support.

It's frustrating that every HKSV issue is immediately, or recently, locked. Pinning an open issue would solve the two-sided frustration of not having a place to track updates, and you having to close issues frequently asking the same thing. Keeping a place open for people to `+1` and follow status would be immensely helpful. A lot of people, myself included, are excited about this feature and it would be helpful for you to keep an issue open for us to follow updates when the come.

**Comment by hjdhjd** [comment]
Fair enough. I will lock it though to prevent the bevy of "I'm excited too". Yes, it's coming. Soon. We just released support for it in Homebridge a couple of days ago. :smile: It won't be much longer.

**Comment by hjdhjd** [comment]
Locked and pinned. Support will be forthcoming shortly.

**Comment by hjdhjd** [comment]
HKSV is fully implemented as of `homebridge-unifi-protect` v5.1.1. Enjoy!
