### ISSUE TITLE
Still images of cameras do not update

### ISSUE THREAD

**Issue by ameoz** [hjdhjd/homebridge-unifi-protect#638]
**Describe The Problem:**

The camera images do not update when viewing them in the Cameras section of a room or in the favorite section of Home.

**To Reproduce:**

On iPad with iPad OS 15.2.1:
1. Go to home screen
2. Click on Home app
3. Click on a room with a UniFi Protect camera
4. Scroll to the cameras
5. The cameras update the still images and begin to incrementally count in seconds in the lower right-hand corner of the images.
6. Click on the images for video and audio streaming to begin as expected.
7. This functions as expected.

On iPhone with iOS 15.2.1:
1. Go to home screen
2. Click on Home app
3. Click on a room with a UniFi Protect camera
4. Scroll to the cameras
5. The cameras do not update the still images. They show images from December 2021 per the timestamp on the image. The bottom right-hand corner of the image says "now" and does not incrementally count.
6. Click on the images for video and audio streaming to begin as expected.
7. Step 5 does not function as expected.
I have tried force closing and reopening the Home app and rebooting the phone and the still images do not update.

Both the iPad and iPhone are on the same WiFi SSID. 
**Logs:**

```
The Homebridge log does not show updates of the still image(s) on either the iPad or the iPhone.
```

**Homebridge Configuration:**

```json
        {
            "controllers": [
                {
                    "address": "192.168.x.1",
                    "password": "password",
                    "username": "admin"
                }
            ],
            "platform": "UniFi Protect"
        }
```

**Screenshots:**

iPhone 13 Pro - still image is from December 2021 and does not update
![D94FC415-A7C4-494F-A8F4-372ACA1C12C6_1_201_a](https://user-images.githubusercontent.com/98376927/150921154-9fd81871-7168-42a8-9f18-9344fe051179.jpeg)

**Environment:**

* **Homebridge Version:** 1.4.0
* **Node Version:** v14.18.3
* **Homebridge-UniFi-Protect Plugin Version:** 5.0.6
* **UniFi Protect Version:** 1.20.3
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.11.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 13 Pro iOS 15.2.1
* **Operating System and OS Version:**  Ubuntu 20.04.3 LTS

**Comment by hjdhjd** [comment]
This is a known, ongoing for some, Apple bug that has nothing to do with this plugin in particular I'm afraid. It impacts all HomeKit cameras. Link to a prior issue on this...you may want to try some of those things. Sorry, not much to do here from the plugin end.

https://github.com/hjdhjd/homebridge-unifi-protect/issues/608#issuecomment-1003039347

**Comment by ameoz** [comment]
Ahh, thank you for the link to the previous issue, @hjdhjd. It's strange to me how the cameras update correctly on some devices and not at all on others.
