### ISSUE TITLE
setting to disable verbose settings in log

### ISSUE THREAD

**Issue by benpoe** [hjdhjd/homebridge-unifi-protect#641]
since the update my homebridge log is bombarded with protect-variables json.

IE:

`[1/30/2022, 2:43:06 PM] [UniFi Protect] {
  accessKey: '1----',
  authUserId: '=====',
  bridges: [],
  cameras: [
    {
      anonymousDeviceId: 'oooo4f',
      apMac: null,
      apRssi: null,
      audioBitrate: 64000,
      canAdopt: false,
      canManage: false,
      channels: [
        {
          bitrate: 3000000,
          enabled: true,
          fps: 30,
          fpsValues: [
             1,  2,  3,  4,  5,  6,  8,
             9, 10, 12, 15, 16, 18, 20,
            24, 25, 30
          ],
          height: 1200,
          id: 0,
          idrInterval: 5,
          isRtspEnabled: true,
          maxBitrate: 6000000,
          minBitrate: 32000,
          minClientAdaptiveBitRate: 0,
          minMotionAdaptiveBitRate: 750000,
          name: 'High',`

this continues on and on. is it possible to disable this as it fills the log really fast and make it hard to debug.

**Comment by hjdhjd** [comment]
This is user error I’m afraid. :smile: You have debugging enabled either for the plugin or for Homebridge overall. Disable debugging and the log spam goes away. :smile:
