### ISSUE TITLE
Missing variable in HKSV logs

### ISSUE THREAD

**Issue by michaelyork** [hjdhjd/homebridge-unifi-protect#646]
An easy fix :)

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/3916693/153730249-46e3bfb2-5fe1-4553-b81e-3240e998a81f.png">

https://github.com/hjdhjd/homebridge-unifi-protect/blob/05f25a08a18122c5170ef66204d5bdf5c95953ff/src/protect-camera.ts#L652

**Comment by hjdhjd** [comment]
Thanks...will be in the next release.

**Comment by michaelyork** [comment]
Thanks for the HKSV support! :)

**Comment by hjdhjd** [comment]
Much more coming...
