### ISSUE TITLE
G3 Instant Camera Status/Record LED is turning on after Homebridge reboot. Both 5.1.1 and 5.1.2

### ISSUE THREAD

**Issue by lp1977** [hjdhjd/homebridge-unifi-protect#652]
**Describe The Problem:**
G3 Instant Camera Status/Record LED is turning on after Homebridge reboot. Both 5.1.1 and 5.1.2.

**To Reproduce:**
Running homebridge-unifi-protect 5.1.1 or 5.1.2, turn off status/record LED on Unifi Protect camera in UniFi settings.
Reboot homebridge.

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.4.0
* **Node Version:** 16.14.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.1.1 or 5.1.2
* **UniFi Protect Version:** 1.21.0
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.11.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iOS 15.3.1
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
RTFM. Known behavior and a bug in the Home app.

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/HomeKitSecureVideo.md#camera-properties-exposed-in-homekit-secure-video
