### ISSUE TITLE
HKSV: Repeating errors in console since activating.

### ISSUE THREAD

**Issue by jakesteele** [hjdhjd/homebridge-unifi-protect#654]
**Describe The Problem:**
Since enabling the HKSV functionality errors are regularly showing up in the logs on my HomeBridge. 

Raspberry Pi 4
Up to date
Ffmpeg version 4.3.1 

**To Reproduce:**
Update to the latest version and enable HKSV in the Apple Home app. 

Errors just repeat.

**Logs:**

```
Posted one of each, they just repeat over and over.

[HDS ::ffff:192.168.1.230] Delegate finished streaming for 1 without setting RecordingPacket.isLast.         Can't notify Controller about endOfStream!
[HDS ::ffff:192.168.1.230] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.

Delegate finished streaming for 1 without setting RecordingPacket.isLast.         Can't notify Controller about endOfStream!

[13/02/2022, 18:27:17] [UniFi Protect] UNVR [UNVR4] Backyard [UVC G4 Pro]: HomeKit Secure Video event recording ended abnormally: HomeKit canceled the request.

```

**Homebridge Configuration:**

```

{
    "controllers": [
        {
            "address": "192.168.1.xxx",
            "password": "",
            "refreshInterval": 10,
            "username": ""
        }
    ],
    "options": [
        "Enable.Doorbell.NvrEvents",
        "Enable.Doorbell.Trigger",
        "Enable.Motion.SmartDetect"
    ],
    "motionDuration": 10,
    "platform": "UniFi Protect"
}

```

**Screenshots:**

**Environment:**

* **Homebridge Version:**1.4.0
* **Node Version:** 16.13.1 - 8.5.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.1.2
* **UniFi Protect Version:**2.3.14
* **UniFi Protect Controller Type:**UNVR
* **UniFi Protect Controller Firmware Version:** 2.3.14
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 15.3
* **Operating System and OS Version:** Raspian Pi 4

**Comment by hjdhjd** [comment]
This is to be expected...please read the documentation. RPi is a pretty low-powered device. Please read through the documentation on [HKSV and low-powered devices](https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/HomeKitSecureVideo.md#performance-considerations). There's also a support area on the Discord for RPi users.
