### ISSUE TITLE
ffmpeg HKSV high cpu usage

### ISSUE THREAD

**Issue by cemilbrowne** [hjdhjd/homebridge-unifi-protect#655]
**Describe The Problem:**
I'm seeing high CPU usage from ffmpeg and long running processes, without an active video session - I assume HKSV recording is the root cause.  4x Unifi Protect cameras - 2x G4 Pros, 1x G3 instant, 1x G4 Doorbell.  

Maybe ffmpeg keeps running after 'homekit canceled the request'?  If I check timestamps below, I see a start of ffmpeg at 11:36 (aligning with restart + start of buffer).  

```
cemil      22656  216 13.9 3240580 2240388 ?     Sl   11:36  12:01 /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -f mp4 -i pipe:0 -map 0:v -vcodec libx264 -pix_fmt yuvj420p -profile:v main -level:v 4.0 -preset veryfast -b:v 2000k -bufsize 4000k -maxrate 2000k -force_key_frames expr:gte(t, n_forced * 4) -fflags +genpts -reset_timestamps 1 -movflags frag_keyframe+empty_moov+default_base_moof -map 0:a -acodec copy -f mp4 pipe:1
cemil      22657  339 14.0 3240404 2268164 ?     Rl   11:36  18:53 /homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -f mp4 -i pipe:0 -map 0:v -vcodec libx264 -pix_fmt yuvj420p -profile:v main -level:v 4.0 -preset veryfast -b:v 2000k -bufsize 4000k -maxrate 2000k -force_key_frames expr:gte(t, n_forced * 4) -fflags +genpts -reset_timestamps 1 -movflags frag_keyframe+empty_moov+default_base_moof -map 0:a -acodec copy -f mp4 pipe:1

```
<img width="595" alt="Screen Shot 2022-02-14 at 11 43 59 am" src="https://user-images.githubusercontent.com/834596/153782970-b245a218-7bd5-458e-b5bf-7e04389d0ff6.png">

This is on a fairly robust (i5-12400) system, homebridge hosted via Docker (alpine linux).  

**To Reproduce:**
Unknown root cause - happens upon restart of homebridge, can't replicate what starts/stops these processes.  

**Logs:**

```
[2/14/2022, 11:36:40 AM] [UniFi Protect] UDM-Pro [UDM-PRO] Garage Doorbell [UVC G4 Doorbell]: Enabling HomeKit Secure Video event recording: 1920x1080@30fps, 2000 kbps with a 4 second timeshift buffer.
[2/14/2022, 11:36:40 AM] [UniFi Protect] UDM-Pro [UDM-PRO] North Lawn Cam [UVC G4 Pro]: Enabling HomeKit Secure Video event recording: 1920x1080@30fps, 2000 kbps with a 4 second timeshift buffer.
[2/14/2022, 11:36:40 AM] [UniFi Protect] UDM-Pro [UDM-PRO] South Lawn Cam [UVC G4 Pro]: Enabling HomeKit Secure Video event recording: 1920x1080@30fps, 2000 kbps with a 4 second timeshift buffer.
[2/14/2022, 11:37:14 AM] [UniFi Protect] UDM-Pro [UDM-PRO] Garage Doorbell [UVC G4 Doorbell]: HomeKit Secure Video has recorded a 29 second motion event.
[2/14/2022, 11:37:14 AM] [UniFi Protect] UDM-Pro [UDM-PRO] Garage Doorbell [UVC G4 Doorbell]: HomeKit Secure Video event recording ended abnormally: HomeKit canceled the request.
```

**Homebridge Configuration:**

```json
{
            "controllers": [
                {
                    "address": "0.0.x.x",
                    "password": "xxx,
                    "username": "yyy"
                }
            ],
            "motionDuration": 7,
            "platform": "UniFi Protect"
        },
```

**Screenshots:**
provided

**Environment:**

* **Homebridge Version:** Homebridge v1.4.0
* **Node Version:** v16.14.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.3.0
* **UniFi Protect Version:** 1.21.0
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.11.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** N/A - but using iPhone 13 Pro on latest firmware, in general.
* **Operating System and OS Version:** Alpine Linux Docker container on Linux Mint host.

**Comment by hjdhjd** [comment]
High CPU usage isn't a bug in and of itself. :smile: You're correct that you seem to have long-running processes...please RTFM. You need to set an upward limit on how much you want HomeKit to record rather than allowing it to do as it pleases. Again - it's in the documentation.

**Comment by cemilbrowne** [comment]
I definitely understand & respect the position.  I made sure I went back and re-read the manual; however (and maybe this is HKSV weirdness rather than plugin) - right now, there is no motion occurring on any cameras, but I'm still seeing 2 processes that have been running for 5 mins each.  This doesn't quite seem like expected behaviour, or is it? 

I've defined motion zones....

**Comment by hjdhjd** [comment]
I understand the issue you're raising...but...

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/HomeKitSecureVideo.md#how-homekit-secure-video-works

Whether or not there is or isn't a motion event any longer doesn't matter. HomeKit decides when it's had enough, not you. Unless you choose to enforce an upward limit. Again...please read, and re-read the documentation. Don't skim this one. :smile:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/HomeKitSecureVideo.md#configuring-hksv-for-unifi-protect

**Comment by cemilbrowne** [comment]
Fair enough; I guess I'll ascribe a lot of it to HKSV weirdness. 

My long term plan will be (once linux support for Alder Lake is up to snuff) enabling hw accelerated encoding on the CPU, that should help a lot.  I note your point about lack of support, which makes sense. 

Thanks for engaging constructively; let me see what setting some limits does to this.

**Comment by hjdhjd** [comment]
Totally happy to engage and discuss. Definitely want to get this right for everyone...and it's early days with HKSV, so there's going to be a lot of learning for everyone. :smile:

One observation I've already had...the G4 Doorbell video stream seems to motivate HKSV to keep recording for far longer than it should. Perhaps it's some artifact in the video stream, or lens-related issues...who knows. What I **do** know is that I've seen the G4 Doorbell and HKSV behave similarly for a bit. Good news is...you can impose a sane limitation via the above links.

As a reminder, should someone else lookup this issue later, you can apply feature options either globally or to an individual camera...read the feature option documentation for details. :smile:

Closing for now...also feel free to find me on Discord in the #unifi-protect channel.

**Comment by cemilbrowne** [comment]
As an update to this issue: setting a time limit had a significant impact (as expected).  No more 'runaway' ffmpeg processes.  One concept here - I wonder if the 'default' should be time limited.  

I wonder if the predominant use case is using HKSV as the NVR or Unifi Protect.  I, for example, don't mind having a 60-90 second clip time, because if someone broke in or I really needed video, I could go check Protect. 

It might provide a better 'default' experience - but I can understand why we might not want to.  

For others, I added this block:

`"options": [
                "Enable.Video.HKSV.Recording.MaxDuration.60"
            ],`

**Comment by hjdhjd** [comment]
@cemilbrowne I might, I might not. Time will tell...it's still early days and I'm still playing with what I think are sane defaults. At the end of the day it's a judgment call...the beauty of it is, you can tailor to your own preferences.

I tend to err strongly on the side of give Apple what it wants, when it wants it. It tends to work out better over time. That said - for others who come across this - please don't directly edit your config JSON. You're asking for more pain and suffering than just using the webUI. Some folks love to edit the JSON directly...knock yourself out...but don't go opening an issue when it breaks because you forgot a comma. Put on your seat belts and use the webUI...it's almost always a better answer for most folks. 😄 

Finally...if you choose to run something like HBUP with HKSV on a low-power device like an RPi, you're really asking to suffer if you have more than a camera or two. It's going to immediately or eventually be unpleasant.
