### ISSUE TITLE
FFmpeg process ended unexpectedly with an exit code of 1.

### ISSUE THREAD

**Issue by b-ill-y** [hjdhjd/homebridge-unifi-protect#660]
First of all -- amazing work to get this functionality in. Some things I'm noticing but didn't want these to slip away.

**Describe The Problem:**

FFmpeg process unexpectedly ends when motion event outside activity zone is recorded. 

The vehicle videos recorded are also not showing up as an option to view home application (but available in Unifi Protect app)

**To Reproduce:**

Not 100% of the cause, but checking the Unifi Protect camera events showed that a vehicle driving by was recorded during that exact time. 

I've got an activity zone setup in iOS Home and a motion zone in protect to exclude the recording area where the vehicle passed by. 

Recording Options - Specific Motion is Detected w/ people, animals, vehicles, packages & record audio.
Notification Option - Specific Motion is Detected w/ people, animals, packages. 

**Logs:**

```
[2/14/2022, 1:41:19 PM] [homebridge-unifi-protect] UCK-G2-Plus [UCK-G2-PLUS] UVC G4 Doorbell [UVC G4 Doorbell]: FFmpeg process ended unexpectedly with an exit code of 1.
[2/14/2022, 1:41:20 PM] [homebridge-unifi-protect] UCK-G2-Plus [UCK-G2-PLUS] UVC G4 Doorbell [UVC G4 Doorbell]: HomeKit Secure Video has recorded a 5 second motion event.
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/56973378/153948338-dca92161-8466-4464-8387-005216e92bf8.png)

**Environment:**

* **Homebridge Version:** 1.4.0
* **Node Version:** 16.13.1
* **Homebridge-UniFi-Protect Plugin Version:** 5.3.1
* **UniFi Protect Version:** 1.20.3
* **UniFi Protect Controller Type:** UCKgen2
* **UniFi Protect Controller Firmware Version:** 2.3.14 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**15.3
* **Operating System and OS Version:** Docker / Synology DS920+

**Comment by hjdhjd** [comment]
You're at least one version behind...can you give v5.3.2 a shot? And did things work well in v5.3.0?

You also left out what platform you're running on. Docker isn't sufficient. 😄 If you're running Docker on an RPi...you're going to have occasional problems on low-powered devices...it's par for the course at the moment I'm afraid.

**Comment by b-ill-y** [comment]
@hjdhjd I've upgraded to 5.3.2 and the problem still persists. Updated w/ platform info. 

I just upgraded to 5.3.1 today so it's hard to say if things worked well, overall it's been really good. I do notice that some video recordings of vehicles don't show an error associated with it and that this seems to be a bit more sporadic.

**Comment by hjdhjd** [comment]
Known issues...I'm on the case. You can revert to 5.3.0 for now and it should work well until I get this fixed. It's my top priority right now for this plugin. Thanks and appreciate you taking the time!

**Comment by hjdhjd** [comment]
I completely misread the question / issue. Now that I understand it a bit more...

Vehicle and object detection in UniFi Protect and detection in HKSV are two different and completely separate systems. They may **look** like they relate, but they don't, other than to say they are both smart motion detection systems.

Please read the HKSV-related documentation for this plugin and it will provide you a bit more context. As I re-read this, it's not a bug. It's working as designed.

**Comment by badgertastic** [comment]
Seeing some success after setting the following:

```
      "Disable.Video.Stream.High",
      "Enable.Video.Dynamic.Bitrates"
```

**Comment by badgertastic** [comment]
Spoke too soon. Got one recording, then subsequently same error. So now trying Low (disabled Medium).

Unless I'm mistaken, the Disable.Video.Stream setting is only impacting playback, and not recording.  Even on Low I still see 1920x1080:

```
[15/02/2022, 12:04:00] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Patio - G3 Flex [UVC G3 Flex]: Enabling HomeKit Secure Video event recording: 1920x1080@30fps, 2000 kbps with a 4 second timeshift buffer.
[15/02/2022, 12:04:00] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Driveway - G4 Bullet [UVC G4 Bullet]: Enabling HomeKit Secure Video event recording: 1920x1080@30fps, 2000 kbps with a 4 second timeshift buffer.
[15/02/2022, 12:04:00] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Garden Rear - G4 Pro [UVC G4 Pro]: Enabling HomeKit Secure Video event recording: 1920x1080@30fps, 2000 kbps with a 4 second timeshift buffer.
[15/02/2022, 12:04:00] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Garden Side - G3 Flex [UVC G3 Flex]: Enabling HomeKit Secure Video event recording: 1920x1080@30fps, 2000 kbps with a 4 second timeshift buffer.
[15/02/2022, 12:04:00] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Porch - G3 Instant [UVC G3 Instant]: Enabling HomeKit Secure Video event recording: 1920x1080@30fps, 2000 kbps with a 4 second timeshift buffer.
```

**Comment by badgertastic** [comment]
Swapped out options for just:

`Enable.Video.Stream.Only.Medium`

Same error:

`[15/02/2022, 13:04:46] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Driveway - G4 Bullet [UVC G4 Bullet]: Enabling HomeKit Secure Video event recording: 1280x720@30fps, 2000 kbps with a 4 second timeshift buffer.`

```
[15/02/2022, 13:05:58] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Driveway - G4 Bullet [UVC G4 Bullet]: FFmpeg process ended unexpectedly with an exit code of 1.
[15/02/2022, 13:05:59] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Driveway - G4 Bullet [UVC G4 Bullet]: HomeKit Secure Video has recorded a 5 second motion event.
```

—

Down to Low

`Enable.Video.Stream.Only.Low`

No error so far:

` [15/02/2022, 13:08:23] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Driveway - G4 Bullet [UVC G4 Bullet]: Enabling HomeKit Secure Video event recording: 640x360@24fps, 2000 kbps with a 4 second timeshift buffer.`

`[15/02/2022, 13:11:08] [homebridge-unifi-protect] UDM-Pro [UDM-PRO] Driveway - G4 Bullet [UVC G4 Bullet]: HomeKit Secure Video has recorded a 21 second motion event.`

Where to go from here, to get Home viewing stream back to High, HKSV recording working, and no degradation in resolution for Homebridge please?  Thanks

**Comment by hjdhjd** [comment]
@badgertastic Please do not hijack another person’s issue, even if it’s similar to yours. If you would like support, open a new issue, or use the Discord. Thanks. One person, one issue. 😄

**Comment by badgertastic** [comment]
Thought you didn't like new issues for same issue (see the title). Just trying to help.  ps. Low also errors now. So done all troubleshooting and will give up on this until later release. Thanks.

**Comment by hjdhjd** [comment]
@badgertastic That’s absolutely right, and I appreciate the confusion and the irony. 😄 This person’s core issue as I understand it is actually that there’s confusion between Protect’s own smart object detection and HKSV’s. That’s not your issue.

Second…you’re running on an RPi, this person is running on a Synology.

Third…you posted more messages in this person’s support request than they did with the original question! That’s not helpful and will cause confusion for folks who go searching for this later.

Your issue may not be their issue. There may be overlaps, undoubtedly, but that’s not identical.

Seeing 10 issues opened up asking for HKSV as a feature request, for instance…yeah, those are identical and will be closed without comment.

Finally: Discord is your best bet if you’d like to get timely and more complete support. Lots of folks there, and lots of troubleshooting and information. Thanks!
