### ISSUE TITLE
The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'G3 Instant' was slow to respond!

### ISSUE THREAD

**Issue by shivanathd** [hjdhjd/homebridge-unifi-protect#663]
Describe The Problem:

After the 5.3.3 update I'm getting this Writehandler too slow to respond error. Hopefully its not an RTFM :) I didn't decrease the quality as my hardware should be able to support it 

To Reproduce:

Enable HKSV on cameras, I have G3 Instants, G4 Doorbell, G3 Pro, Flex etc..
Open the Camera in HomeKit to live view it

Logs:

[HOOBS Whitehouse 8AF7@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'G3 Instant' was slow to respond!

Homebridge Configuration:

Since the last issue I've upgraded from an HOOBS RPI to Hoops on a MAC book air with m1 (brand spanking new) 

Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
{
"platform": "UniFi Protect",
"controllers": [
{
"address": "192.168.X.XXX",
"name": "UNVR",
"password": "duh",
"username": "username hidden"
}
]
}

Screenshots:

<img width="1240" alt="Screenshot 2022-02-15 at 3 03 36 PM" src="https://user-images.githubusercontent.com/1937549/154033925-67a971ba-ca61-489a-b605-c7448d29f896.png">

Homebridge Version: 1.3.9 i use HOOBS4
Node Version: 16.13.1
Homebridge-UniFi-Protect Plugin Version: 5.3.0
UniFi Protect Version: 1.21.0
UniFi Protect Controller Type: UNVR
UniFi Protect Controller Firmware Version: 2.3.14
Environment:
**Apple Device and iOS / macOS / iPadOS / tvOS Version
:**iphone 12 pro max 15.3.1

Operating System and OS Version: HOOBS 4 on a Mac air m1 Catalina 
<img width="431" alt="Screenshot 2022-02-15 at 3 05 34 PM" src="https://user-images.githubusercontent.com/1937549/154034284-1c1eb424-3670-4d11-a5a0-2fd6cbc245a3.png">

**Comment by hjdhjd** [comment]
I do not support nor use HOOBS. Sorry…Homebridge only please, or take it up with the HOOBS folks. 😄 Give Homebridge a try…it’s the only thing I test and use on, and the only thing I can really provide support against. Can you give it a go? I’d also take a look ensuring you’re running HBUP in a child bridge…it’s a critical performance element. Thanks!
