### ISSUE TITLE
Doorbell G4 crackling audio

### ISSUE THREAD

**Issue by zargan2** [hjdhjd/homebridge-unifi-protect#667]
**Describe The Problem:**

Hey, 
I'm really not sure if this issue is by the plugin or by the doorbell itself.
The audio is crackling all the time. It gets more when talking to each other.

When it cant  come from the plugin or homekit itself, maybe my doorbell is broken?! =/

When watching the records of the tests, its most of the time clean. Sometimes its crackling too but im not sure if this is coming from the missing Acoustic Echo Cancellation because the crackling output will come back to the speaker?!

**To Reproduce:**
Using Audio and Mic

**Logs:**
Dont know which logs could be helpful and where to get it =/

**Homebridge Configuration:**

{
    "controllers": [
        {
            "address": "123.123.123.123",
            "password": "_password_",
            "username": "_username_"
        }
    ],
    "options": [
        "Enable.Video.Stream.Only.Low" <- Without any options its the same behavior.
    ],
    "_bridge": {
        "username": "AB:CD:EF:GH:IJ:KL",
        "port": 30713
    },
    "platform": "UniFi Protect"
}

**Environment:**

* **Homebridge Version:**  v1.4.0
* **Node Version:** v14.19.0
* **Homebridge-UniFi-Protect Plugin Version:** v5.3.4
* **UniFi Protect Version:** 1.21.0
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 2.3.14
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS_15.3.1
* **Operating System and OS Version:** Raspbian GNU/Linux Stretch (9)

**Comment by hjdhjd** [comment]
It’s unlikely to be AEC…not having AEC just means you hear an echo coming back…unsure of what the source of your issue is, but it doesn’t feel like it’s plugin-related. Perhaps try rebooting the doorbell and seeing if it helps?

**Comment by zargan2** [comment]
Naahh. I mean.. from the recorded videos which are safed on the cloud key, it seems like the mic is crackling only and the home app user only hear the "crackling echo". Maybe its just the speaker on the doorbell. Mhmmmmmm...

I'll try a reboot, reset and when nothing helps I will make a case at Ubiquiti. Will update you =)

Thanks for the super quick response!

PS: Do have the "video options" any influence on the audio? The new "dynamic" options sounds interesting for getting a faster upshowing stream but im a bit scared about using "new functions". xD

**Comment by hjdhjd** [comment]
Good luck...I wouldn't get hung up on audio quality of the two-way microphone/speaker setup. It's almost always going to sound better from the Protect app given it's more native setup. Closing this issue for now. Thanks!
