### ISSUE TITLE
Feature Request: Refresh snapshot image

### ISSUE THREAD

**Issue by rjblake** [hjdhjd/homebridge-unifi-protect#67]
Firstly, many thanks for this awesome piece of work! Much simpler than managing through other plugins. I was wondering if there was a way to set a refresh of the still image? On another setup, I have a Raspberry Pi where it updates this every 10seconds - would be great if there was a way to do similar with UniFi Protect.

**Comment by shard87** [comment]
Mine refreshes every 10 seconds using this plugin when I’m in the home app. Maybe somethings not quite right?

**Comment by rjblake** [comment]
@shard87 - does this happen when you are connecting remotely? I'm connecting to this from a remote location over 4G

**Comment by shard87** [comment]
Just checked, it doesn’t update remotely; just the first time I go into the app.

**Comment by hjdhjd** [comment]
Thanks for using the plugin!

As others have said above - this isn't a plugin-related issue. Snapshot refreshes are requested by HomeKit, not this plugin. There is zero control over requesting a snapshot refresh in HomeKit.

If you're running a beta version of iOS, you may be running into issues with the beta. This isn't a bug, or a feature request, for this plugin. :smile:

You may also have an issue with your HomeKit home hub (Apple TV, HomePod)...you might want to try rebooting those devices. Good luck!

**Comment by hjdhjd** [comment]
Closing.
