### ISSUE TITLE
Doesn't work when upgrading to V5.3.0

### ISSUE THREAD

**Issue by rhy5davie5** [hjdhjd/homebridge-unifi-protect#672]
**Describe The Problem:**
When upgrading from v4.4.3 to V5.3.0, whole setup stops working. Camera previews don't update on home app and clicking any cameras shows 'camera not responding' Downgrading back to v4.4.3 and it starts working again when HB rebooted.

**To Reproduce:**
See hardware list below

**Logs:**
Says 'starting plug-in' when HB rebooted but no further logs from plug-in at all

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**
Homebridge Version: 1.4.0
Node Version: v12.11.1
Homebridge-UniFi-Protect Plugin Version: v5.3.0
UniFi Protect Version: v1.9.0
UniFi Protect Controller Type: UCKgen2+
UniFi Protect Controller Firmware Version: 6.2.26
Apple Device and iOS / macOS / iPadOS / tvOS Version: Various Mac devices affected
Operating System and OS Version: Raspberry Pi - Unknown

**Comment by rhy5davie5** [comment]
Updated plug-in from v4.4.3 to V5.3.4 and now not working

HB Log when restarting on V5.3.4:![image](https://user-images.githubusercontent.com/57730638/154334016-078ddedc-6065-4811-8b3b-80dacd68bd70.jpeg)

No other log events after this....

**Comment by hjdhjd** [comment]
Off the top of my head: you're running an ancient version of Node that's about to go out of support in less than 60 days. You're also running an unknown / old version of Protect on the controller. I'd suggest updating both of those first to the latest production releases. Your screenshots aren't particularly helpful either. My suggestion is to ensure you're on appropriately recent releases of all your software stack: Protect controller, Node version, Homebridge, and this plugin.

Best of luck.

**Comment by rhy5davie5** [comment]
Downgrading back to v4.4.3 and logs showing discovered cameras:

[2/16/2022, 18:45: 02] [UniFi Protect] xxxxxxxxx [UCK-G2-PLUS]: Connected to
the Protect controller API
(address: xxx.xxx.xxx.xxx mac: xxxxxxxxxxx)
[2/16/2022,
18:45: 021 [UniFi Protect] 
xxxxxxxxx [UCK-G2-PLUS]: Connected to the UniFi realtime update events API.
[2/16/2022, 18:45: 02] [UniFi Protect] xxxxxxxxxxx [UCK-G2-PLUS]: Discovered camera: Back Garden [UVC G3] ( address: xxx.xxx.xxx.xxx mac: xxxxxxxxxxx).

**Comment by rhy5davie5** [comment]
> Off the top of my head: you're running an ancient version of Node that's about to go out of support in less than 60 days. You're also running an unknown / old version of Protect on the controller. I'd suggest updating both of those first to the latest production releases. Your screenshots aren't particularly helpful either. My suggestion is to ensure you're on appropriately recent releases of all your software stack: Protect controller, Node version, Homebridge, and this plugin.
> 
> 
> 
> Best of luck.

Hi bud, thanks for reaching out. I've updated the project software and issue still exists.
Would an old node version cause this as the plugin v4.4.3 is working??

**Comment by rhy5davie5** [comment]
Happy days.
Nodejs and NPM updated and plug-in now working as expected.

Updating wasn't as straight forward as one command but had to update and upgrade apt first.
