### ISSUE TITLE
Events not recording/timeline not visible in AHK

### ISSUE THREAD

**Issue by jackc94** [hjdhjd/homebridge-unifi-protect#673]
So appreciate your efforts with this plugin... very slick!

I have a problem with motion detection not being recorded and therefore the timeline in the Home app not displaying, just the LIVE tag in the bottom left corner. I have already tried adding the Enable.Video.Stream.Only.Low option which prevents the cancelled requests as you'll see below... still no timeline in the Home App.

I am able to reproduce this by triggering a motion event and although a notification is delivered no recording is.

### Logs:
Before adding any options:
```
[16/02/2022, 08:53:57] [UniFi Protect] 3 Kiln Lane | UniFi [UCK-G2-PLUS] Cam 3 | House Rear [UVC G3]: HomeKit Secure Video has recorded a 16 second motion event.
[16/02/2022, 08:53:57] [UniFi Protect] 3 Kiln Lane | UniFi [UCK-G2-PLUS] Cam 3 | House Rear [UVC G3]: HomeKit Secure Video event recording ended abnormally: HomeKit canceled the request.
[16/02/2022, 08:54:21] [UniFi Protect] 3 Kiln Lane | UniFi [UCK-G2-PLUS] Cam 3 | House Rear [UVC G3]: HomeKit Secure Video has recorded a 13 second motion event.
[16/02/2022, 08:54:21] [UniFi Protect] 3 Kiln Lane | UniFi [UCK-G2-PLUS] Cam 3 | House Rear [UVC G3]: HomeKit Secure Video event recording ended abnormally: HomeKit canceled the request.
```

After adding Enable.Video.Stream.Only.Low option:
```
[16/02/2022, 19:27:13] [UniFi Protect] 3 Kiln Lane | UniFi [UCK-G2-PLUS] Cam 3 | House Rear [UVC G3]: HomeKit Secure Video has recorded a 20 second motion event.
[16/02/2022, 19:29:34] [UniFi Protect] 3 Kiln Lane | UniFi [UCK-G2-PLUS] Cam 3 | House Rear [UVC G3]: HomeKit Secure Video has recorded a 20 second motion event.
```

### Homebridge Configuration:
```
 {
              "controllers": [
                  {
                      "address": "10.165.11.2",
                      "name": "3 Kiln Lane | Protect",
                      "password": "[removed]",
                      "username": "[removed]"
                  }
              ],
              "options": [
                  "Enable.Video.Stream.Only.Low"
              ],
              "platform": "UniFi Protect"
          }
```

### Screenshots:
Home app settings:
![IMG_1858](https://user-images.githubusercontent.com/74192229/154350174-af4ffe7d-8f38-4627-8b9f-05b25b789a90.PNG)
![IMG_1859](https://user-images.githubusercontent.com/74192229/154350196-ebe8fd33-c339-4e36-b3dd-6abc819b9d2e.PNG)
![IMG_1860](https://user-images.githubusercontent.com/74192229/154350212-1ff7183c-8f01-4ac9-9ce7-54bf316b511f.PNG)

Video playback without timeline:
![IMG_1861](https://user-images.githubusercontent.com/74192229/154350322-385d947f-5748-4852-a0f9-65520fa53f08.jpg)

### Environment:

Homebridge Version: 1.4.0
Node.js Version: 16.14.0
Npm Version: 8.5.0
Homebridge-UniFi-Protect Plugin Version: 5.3.4
UniFi Protect Version: 1.21.0
UniFi Protect Controller Type: UCKG2+
UniFi Protect Controller Firmware Version: 2.3.15
Apple Device and iOS / macOS / iPadOS / tvOS Version: iOS 15.3.1, tvOS 15.3
Operating System and OS Version: Raspbian GNU/Linux Buster (10)

**Comment by hjdhjd** [comment]
Try disabling recording and re-enabling it in the Home app?

**Comment by jackc94** [comment]
I have done a fair bit of fault finding like removing the plugin from Homebridge and re-adding, resetting both Apple TV’s to factory and setting up from scratch but still no change. Happy to try any other fault finding…

**Comment by hjdhjd** [comment]
Wish there was more I could tell you here beyond that my best guess is that you're using a pretty underpowered device and there might be just enough of a delay that HKSV is throwing out what's recorded, or some other weird HKSV issue is going on. There's nothing that I can tell you that's not going to be the digital equivalent of "jiggle the key in the lock until it works for you" I'm afraid. Things I would try to see if it helps:

* Rebooting everything in the chain at some point including Apple Home hubs.
* Ensuring you're only using the low stream to decrease latency on low-power devices like RPi.
* Making sure all your software is up to date.

At the end of the day, HBUP is recording what is being asked of it and transmitting it to HKSV, but for whatever reason HKSV isn't thrilled. When I've seen this before it's been typically related to either being an underpowered device like RPi, or Home hubs can (on rare occasion) get stuck and not want to process an HKSV client and need to be reset or unplugged.

Wish there was more troubleshooting I could point you to.

**Comment by jackc94** [comment]
So… randomly, it’s just started working… was getting ready to reboot things, checked and there it was! Thanks again for all your hard work, it’s great to have this functionality, crazy it isn’t offered natively.

**Comment by hjdhjd** [comment]
Your welcome...and some days, you just take the win. 😄
