### ISSUE TITLE
Allow for alternative Default Welcome message on G4 Doorbell

### ISSUE THREAD

**Issue by squircle12** [hjdhjd/homebridge-unifi-protect#679]
**Is your feature request related to a problem? Please describe:**
No

**Problem**
We use the doorbell in a bilingual part of Wales, So I've changed the default greeting from WELCOME to CROESO/WELCOME to display always on the screen. When switching to another message (eg "Leave Package at Door") for 30 seconds, the doorbell reverts to the Welcome message rather than the preferred default that was set.

**Describe the solution you'd like:**
Allow the option to set a default message to revert on the message screen back to after the timeout period has completed on selection

**Describe alternatives you've considered:**
Unable to set a new default message in the protect app other than just reset the custom message and set to always once again.

**Additional context:**

**Comment by hjdhjd** [comment]
Thanks for the suggestion - I'll have to think about this one...I think there's value in having a different default message if you want one. Appreciate the suggestion.

**Comment by hjdhjd** [comment]
Thank you! I use it every single day…it’s key to our household!

**Comment by zargan2** [comment]
Very nice suggetion. For me it would be awesome for translations. I live in germany and can't change "Welcome" to "Willkommen" what looks a bit strange for some visitor. xD

**Comment by AngellusMortis** [comment]
To implement this, it is just a PATCH request to `nvr.doorbellSettings.defaultMessageText`. Same rules apply for custom messages (30 char limit, ASCII only).

https://github.com/briis/pyunifiprotect/blob/master/pyunifiprotect/data/nvr.py#L705

**Comment by hjdhjd** [comment]
@squircle12 This will be in the next release of HBUP in the coming days / weeks. Enjoy!

**Comment by squircle12** [comment]
Amazing! thanks @hjdhjd !!!

**Comment by brettaweston** [comment]
How can this be set? I couldn’t find any reference in the HBUP doorbell documentation.

**Comment by hjdhjd** [comment]
Implemented in v6.0.0 and above. Sorry for the long wait on this one. It's been a journey. 😄

**Comment by squircle12** [comment]
Installed immediately- works perfect thanks so much!!
