### ISSUE TITLE
Streaming in HOME app is not always successful after upgrading to 5.4.4(with hksv)

### ISSUE THREAD

**Issue by cyrusauyeungc** [hjdhjd/homebridge-unifi-protect#682]
**Describe The Problem:**

After upgrading to 5.4.4, the streaming in Home app is not always successful.

**To Reproduce:**

If I rebooted the RPI (which runs the homebridge), usually the first few times will have a successful streaming.
However, after numerous connection, it would stuck in the loading page, 
while the log in Homebridge only shows "requested streaming" / and show "stopped streaming" after a while,
which the steaming never occurred. 
As seen from the log below, there is no successful loading in between the 1 min time.
The camera would be displayed as no response in Home app
However, the snapshot is still working fine while streaming is not.

**Logs:**

[2/23/2022, 7:07:49 PM] [UniFi Protect] UDM-Pro [UDM-PRO] Driveway [UVC G4 Pro]: Streaming request from 192.168.1.164: 1280x720@30fps, 299 kbps. Using 1280x720@24fps (Medium), 2000 kbps.
[2/23/2022, 7:07:59 PM] [UniFi Protect] UDM-Pro [UDM-PRO] Driveway [UVC G4 Pro]: Stopped video streaming session.

**Screenshots:**
<img width="710" alt="image" src="https://user-images.githubusercontent.com/69232468/155310032-e33532c0-1315-467d-a4b0-8d9d327d1d8f.png">

**Environment:**
OS | Raspbian GNU/Linux Bullseye (11)
Node.js Version | v16.14.0
Npm Version | v8.3.1
Homebridge-UniFi-Protect Plugin Version | v5.5.0
UniFi Protect Version | 1.21.0
UNIFI OS | 1.11.0

Thanks.

**Comment by hjdhjd** [comment]
Please ensure you’re running the latest version of the plugin - you’re several releases behind. 😄

**Comment by cyrusauyeungc** [comment]
thanks for your prompt reply!
I mean I have been seeing the issue since 5.4.4 and I am on 5.5.0 now.
but then is there any chance that  I can disable HKSV just for the G4 pro as I've still got two g3 flex with HKSV?

**Comment by cyrusauyeungc** [comment]
just read through your documentation again and found that I should be able to control each of the device properly.
I have extracted the MAC address from my unifi page and removed all the ":"

<img width="317" alt="image" src="https://user-images.githubusercontent.com/69232468/155356900-b76d3c16-d995-437c-a623-ee8438c58620.png">

**Comment by cyrusauyeungc** [comment]
I've now added the above specification and I'll see if the performance could be improved!

**Comment by hjdhjd** [comment]
You don’t need to disable HKSV in the plugin. Simply tell the Home app not to enable recording for that camera…it’s a better approach. 😄 Best of luck!
