### ISSUE TITLE
Camera status switch on after connect through homekit.

### ISSUE THREAD

**Issue by 40federico** [hjdhjd/homebridge-unifi-protect#689]
**Describe The Problem:**
<Camera status switch on after connect through homekit.>

**To Reproduce:**
<I switch off each camera in Unifi app. After that if you try to see the cameras through homeket, automatically status lights turn on.>

**Logs:**
<No applicable. -->

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
I have no options in the json configuration of the pluggin.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/HomeKitSecureVideo.md#camera-properties-exposed-in-homekit-secure-video
