### ISSUE TITLE
Unable to stream video over cellular

### ISSUE THREAD

**Issue by tronny87** [hjdhjd/homebridge-unifi-protect#69]
Hi there,

I know we discourage the use of beta software, and you don't fully support beta software, but I'm in a bit of a pickle since there's no way to downgrade my Apple TV 4K from tvOS 14. It is my main HomeKit hub and I really don't have any alternative at this time. 

I'm not able to stream video from any of my cameras in the Home app, but only via cellular. Everything over my WLAN works perfectly fine. I'm able to reproduce this issue from my main iPhone using iOS 14 but also from an iPad cellular model using iOS 13. 

I am almost certain it's the Apple TV that is somehow causing a problem, but I was wondering if anyone else is having similar issues or if there's anything else I can try.

**Comment by tronny87** [comment]
Fixed my own problem by reading a previously closed issue. Enable.StreamOnly.Low did the trick.

**Comment by hjdhjd** [comment]
LOL. I don’t discourage the use of it...the world needs lots of beta testers!

I’m just saying, don’t expect much from a support perspective if you choose to be on the ultra-bleeding edge. :smile:

You can also read more here if you want to better understand what’s going on:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Troubleshooting.md#video-streaming-issues

On another note...have you tried two-way audio? :smile:

**Comment by tronny87** [comment]
> LOL. I don’t discourage the use of it...the world needs lots of beta testers!
> 
> I’m just saying, don’t expect much from a support perspective if you choose to be on the ultra-bleeding edge. 😄
> 
> You can also read more here if you want to better understand what’s going on:
> 
> https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Troubleshooting.md#video-streaming-issues
> 
> On another note...have you tried two-way audio? 😄

I use two-way audio almost daily! I'm so happy you finally had it implemented. It did take some time to adjust to hearing my own voice coming out of the speaker but I've actually been training myself to stop hearing it lol. But I'm sure it's only a matter of time before you figure that one out too!

**Comment by hjdhjd** [comment]
Glad to hear it's working well for you. We'll solve echo cancellation soon enough. As you can see, there's a lot of active development here.

Out of curiosity, what're you using for two-way audio? The G4 Doorbell or the G3 Micro?

**Comment by tronny87** [comment]
> Glad to hear it's working well for you. We'll solve echo cancellation soon enough. As you can see, there's a lot of active development here.
> 
> Out of curiosity, what're you using for two-way audio? The G4 Doorbell or the G3 Micro?

I use it more on the G3 Micro than with the doorbell. I use it as sort of a baby monitor for our small dog who is quite the yapper when we're not home.

**Comment by fpuigb** [comment]
> Glad to hear it's working well for you. We'll solve echo cancellation soon enough. As you can see, there's a lot of active development here.
> 
> Out of curiosity, what're you using for two-way audio? The G4 Doorbell or the G3 Micro?

This is not only about fixing BUGs but adding new features :-) nice development....

**Comment by hjdhjd** [comment]
Spread the word, share the love, and do some good in the world.
