### ISSUE TITLE
Record light/LED of camera will be enabled random.

### ISSUE THREAD

**Issue by Kevin-Kusters** [hjdhjd/homebridge-unifi-protect#690]
**Describe The Problem:**
The blue LED(aka record light) will be enabled automatically by this plugin .

**To Reproduce:**
Just install the plugin and set it up and wait.

I have installed the latest version of UniFi Protect plugin, but the issue also occurs with previous versions
The latest version of Homebridge is installed
Also the latest versions on all of my UniFi products
** I **DON’T** HAVE ANY BETA/EARLY ACCESS SOFTWARE INSTALLED

**Comment by hjdhjd** [comment]
https://github.com/hjdhjd/homebridge-unifi-protect/issues/689#issuecomment-1053773490
