### ISSUE TITLE
Support native camera zoom

### ISSUE THREAD

**Issue by MSchmidt** [hjdhjd/homebridge-unifi-protect#696]
**Is your feature request related to a problem? Please describe:**
My camera supports a native, optical zoom. I use it for birds and squirrel watching on Apple TV. I need to zoom in via unifi protect app though. 

**Describe the solution you'd like:**
I presume there is no zoom feature in HomeKit yet. But not sure. If not I thought the zoom could present itself like a light bulb or shutter. So the brightness percentage is used as zoom level.

**Describe alternatives you've considered:**
Just doing it via Unifi Protect App.

**Additional context:**
If supported, it would allow zoom via Siri as well.

**Comment by hjdhjd** [comment]
It's a great question. I will add this one to the backlog. Stay tuned.
