### ISSUE TITLE
Massive Lines of Logs

### ISSUE THREAD

**Issue by fratinize** [hjdhjd/homebridge-unifi-protect#698]
I have Looked, but I am Not finding a Way to Turn off the Logs, or lessen the Lines it produces. 

**Is your feature request related to a problem? Please describe:**
This plug in really Hogs the logs :P,  can't even roll back to look at the last device to register a Log. 

**Describe the solution you'd like:**

Am I missing Something? I there a Way to Minimize this. 

**Describe alternatives you've considered:**

Other than that Love this plug in Nice Work.

**Comment by hjdhjd** [comment]
You are running Homebridge in debug mode. The logs are intentional. Don't run Homebridge in debug mode if you don't want debugging information. :smile:

**Comment by fratinize** [comment]
Ok :P Thank You for teaching this ID10T I thought I would loose all the Logs by turning of Debug :(

U R The Man, TY

**Comment by hjdhjd** [comment]
No worries. Small suggestion: when there's a plugin that's as mature and used as widely as this one is in the Homebridge world, chances are usually pretty good that if you're new to it the problem isn't in the plugin. :smile:
