### ISSUE TITLE
Notifications not working on UCK-Gen2+ controllers in v3.6.3.

### ISSUE THREAD

**Issue by henkied** [hjdhjd/homebridge-unifi-protect#70]
After update after the latest version, no more notifications for movements. In the log is below!

[9/8/2020, 8:51:12 PM] [UniFi Protect] Unifi Henk [UCK-G2-PLUS]: Protect-Away -> Hall: Motion detection enabled.
[9/8/2020, 8:51:12 PM] [UniFi Protect] Unifi Henk [UCK-G2-PLUS]: Protect-Away -> Garage: Motion detection enabled.

Movements are not indicated in the log. So are not registered

In the feature settings it says: Enable.MotionSensor

The settings on my iPhone are correct.

**Comment by hjdhjd** [comment]
Thanks for the report. Let me take a look on my end and run a couple of tests. Stay tuned.

**Comment by henkied** [comment]
@hjdhjd thx!!

**Comment by hjdhjd** [comment]
It's a bug. Thank you for finding it so we can get this regression fixed.

I'll push an update shortly to fix it. Please note, I'll only be pushing updates to `homebridge-unifi-protect` from now on. Have you made the switch yet?

**Comment by henkied** [comment]
Have you made the switch yet?

Yes i made the switch!

**Comment by hjdhjd** [comment]
Fixed in v3.6.4. Enjoy.

**Comment by henkied** [comment]
WOW super what a quick fix many thx!!
