### ISSUE TITLE
Homebridge turns Record light on when reset

### ISSUE THREAD

**Issue by tbird1706** [hjdhjd/homebridge-unifi-protect#705]
I have 3 G3 Flex cameras in my Unifi setup and whenever I have to restart my Homebridge the record light gets turned back on. It is only a minor inconvenience since I can easily turn them off but we use 2 of the G3 Instant. I didn't see anything in the logs that would indicate what is causing the lights to turn on.

```
None
```

**Homebridge Configuration:**

```json
None
```

**Screenshots:**
Not Applicable

**Environment:**

* **Homebridge Version:** 1.4.0
* **Node Version:** v16.13.2
* **Homebridge-UniFi-Protect Plugin Version:** v5.5.0
* **UniFi Protect Version:** 1.21.0
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.10.4
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 12 on iOS 15.3 and Apple TV 4K 1st gen on 15.3
* **Operating System and OS Version:** Raspbian V10

**Comment by hjdhjd** [comment]
Documented behavior.

https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/HomeKitSecureVideo.md#camera-properties-exposed-in-homekit-secure-video
