### ISSUE TITLE
QUESTION:  Is the HKSV implementation in homebridge-unifi-protect as fast or better than Scrypted?

### ISSUE THREAD

**Issue by SemoTech** [hjdhjd/homebridge-unifi-protect#708]
Hello,

I saw a lot of comments about how fast and responsive Scrypted is with HKSV for most non-homekit native cameras, and was wondering if anyone is using it and can compare the performance with the HKSV implementation in this plugin.

I am running **homebridge-unifi-protect** as a child bridge in homebridge (docker) and was wondering if it makes sense to install Scrypted in Docker and switch my 7 UniFi cameras from this plugin to it?

Thank you.

**Comment by link266** [comment]
Sometimes I see these types of posts and I just wish I could see @hjdhjd's response before they are auto-closed (as they should be!)
