### ISSUE TITLE
Status Lights

### ISSUE THREAD

**Issue by tminnow** [hjdhjd/homebridge-unifi-protect#712]
**Is your feature request related to a problem? Please describe:**

Whenever Homebridge restarts, the plugin automatically turns on the status lights for all cameras. 
I like to keep the camera status lights off for certain cameras that are in line of sight most of the time.

**Describe the solution you'd like:**

Would it be possible to add a configuration override? ("Disable.Status.Lights")

**Describe alternatives you've considered:**

I have to login to Unifi and turn some of camera status lights off.

**Additional context:**

Thanks for building this. It's a great integration for Homebridge/HomeKit.

**Comment by hjdhjd** [comment]
Thanks for the request...that said, this request has come up a few times. Please read the documentation here to address your issue:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/HomeKitSecureVideo.md#camera-properties-exposed-in-homekit-secure-video
