### ISSUE TITLE
 No Connection Requests HomeCam

### ISSUE THREAD

**Issue by fishcharlie** [hjdhjd/homebridge-unifi-protect#715]
**Describe The Problem:**

When using the iOS app [HomeCam](https://apps.apple.com/us/app/homecam-for-homekit/id1292995895) sometimes (most of the time), one or more of my cameras fails to load, and gets stuck on `Connecting`. Sometimes it goes to the image still snapshot for that camera.

I have 3 UniFi Protect cameras.

I'm unsure exactly when this started, but I believe it was after I upgraded to the version that introduced HomeKit Secure Video. However, I hadn't updated in a while before that.

So my first thought was that it was related to HomeKit Secure Video, so I tried to disable that, but the problem persists.

Then I thought it could be related to my system not being powerful enough. But the CPU load is 9%, and the memory available is 5.41 GB. So that doesn't make sense. Lots of free resources.

Additionally, the camera that doesn't get a streaming request, seems to change as well. It's not a constant thing with a single camera. It's random which camera the issue happens with.

I wouldn't be surprised if this is an issue with HomeCam or iOS/HomeKit. However, since all of my other cameras (Logitech Circle View, Eve Cam, etc) are not experiencing this issue, I figure this would be a good starting place to post about this.

I'd be happy to run tests or gather more debugging information if I could get some information about how to do so.

**To Reproduce:**

1. Have 3+ cameras in UniFi
2. Open the HomeCam application
3. Notice that **sometimes** no connection request is sent for some cameras

**Logs:**

```
[4/8/2022, 2:01:00 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Laundry Room Server Rack Camera [UVC G3 Flex]: Streaming request from 10.0.0.241: 1280x720@30fps, 299 kbps. Using 1920x1080@25fps (High), 6000 kbps.
[4/8/2022, 2:01:00 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Office Server Room Camera [UVC G4 Dome]: Streaming request from 10.0.0.241: 1280x720@30fps, 299 kbps. Using 1280x720@24fps (Medium), 2000 kbps.
[4/8/2022, 2:01:00 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Patio West Camera [UVC G3 Flex]: Streaming request from 10.0.0.241: 1280x720@30fps, 299 kbps. Using 1920x1080@25fps (High), 6000 kbps.
[4/8/2022, 2:01:06 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Office Server Room Camera [UVC G4 Dome]: Stopped video streaming session.
[4/8/2022, 2:01:06 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Patio West Camera [UVC G3 Flex]: Stopped video streaming session.
[4/8/2022, 2:01:06 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Laundry Room Server Rack Camera [UVC G3 Flex]: Stopped video streaming session.

...

[4/8/2022, 2:12:53 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Patio West Camera [UVC G3 Flex]: Streaming request from 10.0.0.16: 1280x720@30fps, 299 kbps. Using 1920x1080@25fps (High), 6000 kbps.
[4/8/2022, 2:12:53 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Laundry Room Server Rack Camera [UVC G3 Flex]: Streaming request from 10.0.0.16: 1280x720@30fps, 299 kbps. Using 1920x1080@25fps (High), 6000 kbps.
[4/8/2022, 2:15:03 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Patio West Camera [UVC G3 Flex]: Stopped video streaming session.
[4/8/2022, 2:15:03 PM] [UniFi Protect] CFNetwork [UCK-G2-PLUS] Laundry Room Server Rack Camera [UVC G3 Flex]: Stopped video streaming session.
```

As you can see in the first section, all cameras connect successfully (this was right after I restarted Homebridge). In the second section (even tho my steps to reproduce were the same), only 2 of the 3 cameras got a streaming request.

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge ....",
        "username": "..:..:..:..:..:..",
        "port": .....,
        "pin": "...-..-...."
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": ....,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "10.0.0....",
                    "password": "...",
                    "username": "..."
                }
            ],
            "platform": "UniFi Protect",
            "options": [
                "Disable.Video.HKSV"
            ]
        }
    ]
}
```

**Screenshots:**

I'd be happy to share screenshots, but due to the sensitivity of showing cameras, I'd prefer to do this privately. I'm also not sure how relevant this is as well.

**Environment:**

* **Homebridge Version:** v1.4.0
* **Node Version:** v16.14.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.0
* **UniFi Protect Version:** 1.21.4
* **UniFi Protect Controller Type:** UniFi OS UCK G2 Plus 2.3.15
* **UniFi Protect Controller Firmware Version:** 2.3.15
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 13 Pro Max iOS 15.4.1
* **Operating System and OS Version:** macOS Monterey 12.2.1

**Comment by fishcharlie** [comment]
I also just tested adding these cameras to HomeKit using [Home Assistant](https://www.home-assistant.io). The Home Assistant cameras seem to work good, and don't have this same issue. The problem is the audio when using Home Assistant seems to cut in and out every few seconds or so, and it doesn't have as much functionality as this plugin does.

I'd be happy to help investigate the code and debug further to help get this resolved. But need some pointers and directions into how to best debug this and pointers here.

**Comment by simplytoast1** [comment]
I am having the same issue.  It seems related to the API of Unifi Protect per @hjdhjd 

We just have to hope that Ubiquiti fixes the issue in future releases.  Also disabling the TimeShift buffer can help.

But I am there and with you.

**Comment by fishcharlie** [comment]
@simplytoast1 

> It seems related to the API of Unifi Protect

Do we know what part of the API is failing? I'd be happy to contact Ubiquiti and try to encourage them to prioritize this.

> Also disabling the TimeShift buffer can help

Does this completely fix it or? I'd prefer not to deal with temporary solutions. So just trying to gauge the pros and cons of this.

---

It's also weird that it works on [Home Assistant](https://www.home-assistant.io/), especially if it's an issue with the UniFi API.

**Comment by simplytoast1** [comment]
@fishcharlie No worries, you will find us a very helpful community.

I am unsure what part of the API is being inconsistent but that is direct from the developer.  Trust me I am right there with wanting a fix considering Ubiquit is starting to beta the 2.0 branch.

Regarding the TimeShiftBuffer its is not a total fix at all - it is a lot better but scattershot at best.

Also, with the other plugins they may NOT be using the API and just the SRTSP streams.  I am unsure of their methods. What I have learned is that @hjdhjd says that most of the other apps use his code (or some fork of it) but he only focuses on his plugin.  I choose to keep it all in all in HB instead of running two (or more) solutions.

We are having a discussion in the discord about it - but all roads lead to an inconsistent API and only @hjdhjd can add to the commentary on that.

**Comment by fishcharlie** [comment]
I'm actually not sure this is an issue with this plugin anymore. The `handleStreamRequest` method in `protect-stream.ts` isn't even getting called for me. Which indicates to me that it's an issue higher up in the stack (HomeBridge, hap-nodejs, HomeCam, or HomeKit itself).

**Comment by hjdhjd** [comment]
Thanks for the thorough report, but this isn't a bug in the plugin. There are issues in the latest iOS and UniFi Protect releases...separate ones to be sure. 

The issue you are calling out related to streaming requests taking a long time to start  is a HomeKit one, not a Homebridge nor HBUP one. Apple's been having HomeKit challenges, particularly related to video, in most of the 15.4 branch. Calls to stream video in particular can be all over the place and unreliable at the moment, particularly when using HomePods as home hubs...no, it shouldn't be the case, but yes, it is right now. Frustrating and without a good pattern of cause.

Separately and addressed elsewhere, the latest Protect production firmwares break a few things...stick to the 1.20.x series until they sort that mess out.

Finally - in my experience, HomeCam has been pretty buggy over the years, though the developer tries to work within the constraints he has. I don't support it, so please report your issues to HomeCam's creator and support infrastructure - I provide no support for anything beyond HBUP and whether HBUP works (or not) with HomeCam is out of my scope. :smile: 

I use HomeCam as well, with dozens of Protect cameras...it's never been particularly reliable. It works well with one or two cameras, but it struggles to scale has been my experience, and I imagine some of it is constrained by HomeKit quirks as well.

**Comment by fishcharlie** [comment]
@hjdhjd I do think it is a HomeKit issue after investigating further.

Just out of curiosity, have you reported any of these issues to Apple? I'm thinking about reporting it, but it'd be helpful if you have any thoughts about how to explain it well. There are a lot of different components here, and it's tough to know how to describe it in a clear and concise way. Also having a feedback number to also mention as a duplicate might be helpful.

If not that is ok, thought it'd be worth asking tho.

**Comment by hjdhjd** [comment]
Feel free to join the chorus if you'd like to file another report - others have. Best of luck.
