### ISSUE TITLE
Invalid login credentials given. Please check your login and password.

### ISSUE THREAD

**Issue by henkied** [hjdhjd/homebridge-unifi-protect#716]
**Describe The Problem:**
Since a few days the login no longer works. I am very sure that I have correct login details

**To Reproduce:**
I am using homebridge via docker on synology NAS. All other plugins are working okay! I have the same problem running homebridge on another synology NAS. I have checked login name and password 100 times. If I with kopy/paste login in unifi environment no problem if I log in with the same kopy paste via homebridge plugin then error message

**Logs:**
[UniFi Protect] Invalid login credentials given. Please check your login and password.

**Homebridge Configuration:**

"controllers": [
                {
                    "address": "xxxxxxxx",
                    "password": "xxxxxxxx!",
                    "username": "xxxxxxx"
                }
            ],
            "platform": "UniFi Protect"

**Environment:**

* **Homebridge Version:** 1.4.0
* **Node Version:** 16.14.2
* **Homebridge-UniFi-Protect Plugin Version: 5.5.0
* **UniFi Protect Version:** UniFi OS UCK G2 Plus 2.3.15
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:**2.3.15
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**ALL IOS Macos Ipados tvOS
* **Operating System and OS Version:** Docker

**Comment by ydnar** [comment]
I have this issue now as well. @henkied what was your fix?

**Comment by ydnar** [comment]
> I have this issue now as well. @henkied what was your fix?

I deleted and recreated the local user with no effect. Restarting the UDM-Pro addressed the issue.
