### ISSUE TITLE
Problem when trying to view a camera in Home app

### ISSUE THREAD

**Issue by jfmoots** [hjdhjd/homebridge-unifi-protect#72]
When clicking on a camera in the home app, the camera is giving a no response message. In the Hoobs log it reads:

9/9/2020, 1:14:08 PM Front Door is running on port 41065.
9/9/2020, 1:14:47 PM (node:672) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
9/9/2020, 1:14:47 PM at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/camera/RTPStreamManagement.js:675:98)
9/9/2020, 1:14:47 PM at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/camera/RTPStreamManagement.js:644:27
9/9/2020, 1:14:47 PM at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:15:25
9/9/2020, 1:14:47 PM at ProtectStreamingDelegate.prepareStream (/home/hoobs/.hoobs/node_modules/homebridge-unifi-protect/dist/protect-stream.js:143:9)
9/9/2020, 1:14:47 PM at runMicrotasks (<anonymous>)
9/9/2020, 1:14:47 PM at processTicksAndRejections (internal/process/task_queues.js:93:5)
9/9/2020, 1:14:47 PM (node:672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
9/9/2020, 1:14:47 PM (node:672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
9/9/2020, 1:14:57 PM [UniFi Protect] MootsNVR [UCK-G2-PLUS] Fire Pit [UVC G3 Dome]: Stopped video streaming session

I'm thinking it's a FFMPEG issue but this was working on the old Protect2 npm.

**Comment by regnierz** [comment]
I had that exact issue. I manually updated Node.js and it worked, but then Hoobs would start to glitch out and not work. I just switched to Homebridge from Hoobs to see if this was any better. Thankfully, Homebridge uses the updated version of Node, so none of the errors are happening that you mentioned above.. unfortunately.. it takes upwards of 30 seconds to establish a connection every time you click on it.. and sometimes it doesn't work at all - with the same configuration that took 3-ish seconds on Hoobs. I'm not sure what to do at this point.

**Comment by hjdhjd** [comment]
HOOBS needs to be updated to support the latest homebridge. I believe that support is coming in the next few days.

**homebridge-unifi-protect required Homebridge 1.1.3 or later as of v3.6.0.**

Until HOOBS is updated, I suggest you install homebridge-unifi-protect2@3.5.1

FYI - this change was documented in the Changelog.

This is not a Node issue. It's a HOOBS issue really - namely that HOOBS needs to incorporate the important changes that were in Homebridge 1.1.3 and later for video-related plugins like this one.

I believe Ovi is working on an update to HOOBS to address it.

Alternatively, you can install the latest version of the plugin and don't try to start video streams. All the other functionality will continue to work correctly.

Good luck.

**Comment by jfmoots** [comment]
You're awesome! I'll watch for the Hoobs update! Thanks!

**Comment by hjdhjd** [comment]
@jfmoots Thanks! Star the repo to show your support. I'm just sorry things broke on the HOOBS front...it's unfortunate, but it's a difficult decision when you want to move things forward to take advantage of new capabilities that help eliminate problems for users in other ways...sometimes it just takes a while for HOOBS and Homebridge to sync up.

To reemphasize - you can still use v3.6.0 and beyond on HOOBS. Streaming is just broken for now.

**Comment by hjdhjd** [comment]
@regnierz Curious about your 30-seconds-until-I-can-stream issue. Can you elaborate? On my homebridge setup, I get a stream off of one of my G3 Flexes in less than 3 seconds every time, for example.

How exact is your setup duplication? :smile:

**Comment by regnierz** [comment]
I would love some help. I've been switching installs from Hoobs and Homebridge desperately trying to get this to work again (as I have many smart devices that aren't usable from the constant reconfiguration). I've been limiting my installs to just Unifi-Protect to try to get that to work, as I know the rest of them do.

On Hoobs, I had:

        "address": "192.168.1.1",
        "username": "username",
        "password": "password"

and for the options:

    "Enable.StreamOnly.Quality",
-preset ultrafast -tune zerolatency,
    "Enable.MAC.{mac address}"

I tried to copy these settings to Homebridge, which work 5-6 times out of 10 (when I click on the stream on Homekit, it doesn't connect for like 30 seconds, or not at all).

I then tried to just input the ip address, username, and password, but that doesn't connect at all. I'm unsure of what i'm doing wrong, as i'm very new to Hoobs and Homebridge. I had everything working on Hoobs, until I received the same error as the OP, which then I updated (on the advice of MANY forums I searched):

sudo npm install -g n
sudo n stable

which fixed the issue on Hoobs, but then quickly crashed my entire setup and nothing works (I can still SSH but the service won't start, even when manually telling the service to)

Any advice? I have a UDM-Pro, G4 Doorbell, and a Raspberry Pi 4 - 4GB if any of those details help.

**Comment by regnierz** [comment]
Of note, the static images that poll every 10 seconds on Homekit does update like clockwork, i'm only having issues with the streaming bit.

**Comment by fpuigb** [comment]
> On Hoobs, I had:
> 
> ```
>     "address": "192.168.1.1",
>     "username": "username",
>     "password": "password"
> ```
> 
> and for the options:
> 
> ```
> "Enable.StreamOnly.Quality",
> ```

Not sure if this apply for the Hoobs but in the hombridge Unifi Protect plug-in you can try "Enable.StreamOnly.Low". Not sure if you have defined "Enable.StreamOnly.Quality" instead of "Enable.StreamOnly.Low".

**Comment by regnierz** [comment]
Oh, wow. That did it. "Enable.StreamOnly.Low" allowed it to connect to the video every time and rather quick. The log states it is still the same resolution, frame rate, and bitrate as when the high worked. What does this setting "do" then?

either way, Thank you!!

p.s. I had "quality" as high, not "quality", sorry for any confusion

**Comment by regnierz** [comment]
@fpuigb Just tried to change it back to "High" and it failed to connect several times and was experiencing the same 30-ish second delay. Swapped back to your suggestion, "Low" and it works within 3 seconds again.

**Comment by fpuigb** [comment]
> Oh, wow. That did it. "Enable.StreamOnly.Low" allowed it to connect to the video every time and rather quick. The log states it is still the same resolution, frame rate, and bitrate as when the high worked. What does this setting "do" then?
> 
> either way, Thank you!!
> 
> p.s. I had "quality" as high, not "quality", sorry for any confusion

@hjdhjd will probably chime in and say it's in the documentation lol, but AFAIK it basically use the low quality stream from the cameras / NVR to HB.

**Comment by fpuigb** [comment]
> @fpuigb Just tried to change it back to "High" and it failed to connect several times and was experiencing the same 30-ish second delay. Swapped back to your suggestion, "Low" and it works within 3 seconds again.

Yep, there is a bottleneck in some place that I don't understand yet. But happened to me too.

**Comment by hjdhjd** [comment]
It is. :)

See https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Troubleshooting.md#video-streaming-issues

**Comment by hjdhjd** [comment]
If you don't understand what the options mean I suggest you look closely at the feature options documentation too. 😀

**Comment by regnierz** [comment]
> > @fpuigb Just tried to change it back to "High" and it failed to connect several times and was experiencing the same 30-ish second delay. Swapped back to your suggestion, "Low" and it works within 3 seconds again.
> 
> Yep, there is a bottleneck in some place that I don't understand yet. But happened to me too.

Well, at least i'm not insane. "Low" takes about 2-3 seconds to load, "Medium" takes 5-7 seconds to load, "High" times out or takes around 30 seconds. I know the RTSP streams have low, medium, and high from the Unifi settings, so that setting must just enforce it (makes sense as we don't have to input the encoded RTSP-link, so this setting likely just says what stream to use.

**Comment by fpuigb** [comment]
@regnierz - did you have issues with high quality stream even when connected via Wi-Fi?

**Comment by regnierz** [comment]
Thanks for your help everyone. I really do appreciate it. I have a lot to read regarding the settings about the various plugins I use, I was mainly just trying to verify this worked before continuing to re-add my others. Some smart folks here!

**Comment by regnierz** [comment]
> @regnierz - did you have issues with high quality stream even when connected via Wi-Fi?

Wi-Fi on the Pi? I have it hardlined. Would you like me to try Wi-Fi?

**Comment by hjdhjd** [comment]
Read the documentation link I put above. You don't **need** "high quality"...it's largely a waste of time. Read why before proceeding. :smile:

**Comment by regnierz** [comment]
> Read the documentation link I put above. You don't **need** "high quality"...it's largely a waste of time. Read why before proceeding. 😄

Excellent! Will do, I did not know that. Thank you so much {insert endearing gender neutral term here}!

**Comment by fpuigb** [comment]
> > @regnierz - did you have issues with high quality stream even when connected via Wi-Fi?
> 
> Wi-Fi on the Pi? I have it hardlined. Would you like me to try Wi-Fi?

Umm, Wi-Fi in your client side. (iPhone, iPad, Mac,.....)

**Comment by regnierz** [comment]
> > > @regnierz - did you have issues with high quality stream even when connected via Wi-Fi?
> > 
> > 
> > Wi-Fi on the Pi? I have it hardlined. Would you like me to try Wi-Fi?
> 
> Umm, Wi-Fi in your client side. (iPhone, iPad, Mac,.....)

On, my apologies. Yes, i'm using an iPhone and an iPad to monitor Homekit (as those are the only Apple devices I have). I used "High" quality with minimal delay on the Hoobs side prior to 3.6x with minimal delay (3-ish seconds), but past 3.6x (even with the janky manual update that broke Hoobs I did), it would still delay 30-ish seconds and timeout. This is relatively new, which is why I even commented on the OP, as I was going through the same frustrating discovery. All with the same wireless client devices (and the wireless G4-Doorbell, as it currently doesn't have an Ethernet option).

**Comment by fpuigb** [comment]
Cool, ok so "Enable.StreamOnly.Low" its your best friend. It works pretty good and BTW; helps you so save some bandwidth in the LAN, WLAN and/or Cellular network....

**Comment by regnierz** [comment]
> Cool, ok so "Enable.StreamOnly.Low" its your best friend. It works pretty good and BTW; helps you so save some bandwidth in the LAN, WLAN and/or Cellular network....

Excellent. Thank you so much for your help. Thank you @hjdhjd for putting this in the documentation you linked above, too. I apologize for not finding this first and testing it before commenting about it. I really appreciate both of your help and guidance.

**Comment by hjdhjd** [comment]
No worries. You're just spurring me to create an issue template and try to encourage people to read the documentation beforehand. I spent a lot of time on it. :smile:
