### ISSUE TITLE
Protect 2.0 Support using Opus?

### ISSUE THREAD

**Issue by randomranran** [hjdhjd/homebridge-unifi-protect#724]
Hi mate, will this plug-in support Protect 2.0 when released? I have the beta installed so wasn’t anticipation this plug-in working with 2.0 until officially released. I think they have changed the audio codec to opus?

**Is your feature request related to a problem? Please describe:**
 
Plug-in not currently working with Protect 2.0

**Describe the solution you'd like:**

Support for Protect 2.0

**Describe alternatives you've considered:**
N/a

**Additional context:**
 N/a

**Comment by hjdhjd** [comment]
Thanks for the request. I’ll start with the usual: please read the documentation - it clearly explains what is and is not supported. 

To reiterate it again: I support, and will support the latest **production / GA** releases of UniFi Protect. I don’t comment, discuss, nor speculate regarding anything beta in the UniFi Protect ecosystem other than to reiterate what is already documented: **this plugin supports the latest production / GA Protect releases, and will always do so**.
