### ISSUE TITLE
Insufficient privileges for this user.

### ISSUE THREAD

**Issue by Maxoududu** [hjdhjd/homebridge-unifi-protect#739]
**Describe The Problem:**

Hello all,

I'm getting the following error after installing and configuring the plugin:
`[UniFi Protect] Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges.`

I am not sure if it is my UniFi user created that do not have permission or if a file or command is trying to be accessed and my Homebridge user doesn't have permission.

**To Reproduce:**

I'm running Homebridge on Synology DSM  (using [this](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Synology-DSM)), installed ffmpeg with [this](https://github.com/oznu/homebridge-syno-spk/wiki/DSM-7:-ffmpeg-with-libfdk_aac)

installed the plug-in and entered configuration (see bellow for configuration and environment)

Some more useful info:
```bash
bash-4.4$ whoami
homebridge
bash-4.4$ which ffmpeg
/var/packages/ffmpeg/target/bin/ffmpeg
bash-4.4$ ls -l /var/packages/ffmpeg/target/bin/ffmpeg
-rwxr-xr-x 1 sc-ffmpeg synocommunity 271304 Apr 30 12:51 /var/packages/ffmpeg/target/bin/ffmpeg
```

**Logs:**

```
[UniFi Protect] Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges.
```

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxxx",
        "port": 51802,
        "pin": "xxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode-purple",
            "tempUnits": "c",
            "lang": "auto",
            "accessoryControl": {
                "debug": false
            },
            "platform": "config"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "xxxx",
                "cookies": "xxxx"
            },
            "platform": "Nest"
        },
        {
            "name": "Elgato Key Lights",
            "powerOnBehavior": 2,
            "powerOnBrightness": 10,
            "powerOnTemperature": 3911,
            "switchOnDurationMs": 100,
            "useIP": true,
            "platform": "ElgatoKeyLights"
        },
        {
            "controllers": [
                {
                    "address": "xxxx",
                    "password": "xxxx",
                    "username": "xxxx"
                }
            ],
            "verboseFfmpeg": true,
            "platform": "UniFi Protect"
        }
    ],
    "disabledPlugins": [ ]
}
```

**Environment:**

* **Homebridge Version:** v1.4.1
* **Node Version:** v16.14.2
* **Homebridge-UniFi-Protect Plugin Version:** v5.5.0
* **UniFi Protect Version:** Protect 1.21.6
* **UniFi Protect Controller Type:** DreamRouter
* **UniFi Protect Controller Firmware Version:** 1.21.6
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 15.4.1
* **Operating System and OS Version:**  Synology DSM

**Comment by hjdhjd** [comment]
Setting up the right permissions can be confusing, and UniFi doesn’t always make it easy.

Homebridge isn’t the issue - the issue is the user you created on the **Protect controller** not having administrative privileges. You need to modify the permissions for the username you are using for Homebridge on the Protect controller to include administrative privileges.

Best of luck!

**Comment by Maxoududu** [comment]
That was it. The issue was resolved after setting it to "Viewer" instead of "Member" (which now seems pretty logical)
