### ISSUE TITLE
Support for UDM-Pro (FQ Email Required Now) - Protect Version 1.14.11

### ISSUE THREAD

**Issue by jwebbstevens** [hjdhjd/homebridge-unifi-protect#74]
**Is your feature request related to a problem? Please describe:**
UDM-Pro is increasing in adoption. With Protect native to that device the mechanism to create a local user no longer exists in that version of Protect (Version 1.14.11). The only acceptable username is a full qualified email address.  The email must be confirmed and account setup at UI must be used which includes a public facing username (which I presume is only for UI forum purposes).

**Describe the solution you'd like:**
Documentation needs to be updated to reflect this new email, non local user environment. Specifically the UI interface that refers too. "UniFi Protect username for this controller. Creating a homebridge-specific local user is strongly encouraged for security and sanity."

**Describe alternatives you've considered:**
Not sure any exist since Ubiquiti controls Protects environment.

**Additional context:**
 Image for context

<img width="764" alt="Screen Shot 2020-09-11 at 1 25 45 PM" src="https://user-images.githubusercontent.com/7277574/92955058-7cf20780-f432-11ea-8836-1fccdac80383.png">

**Comment by hjdhjd** [comment]
This isn't the case. You can create local users in Protect, on a UDM-Pro.

**Comment by hjdhjd** [comment]
https://community.ui.com/questions/UDM-Pro-Adding-Users-from-local-portal-page/458d0297-029c-4e57-b7e5-74664f9125ed

For those who run into this question in the future.

Thanks for the suggestion, best of luck.

**Comment by brianmedia** [comment]
@hjdhjd is correct. I use UDMPro with a local login for Protect plugin

**Comment by hjdhjd** [comment]
Thanks @brianmedia :smile:

**Comment by jwebbstevens** [comment]
My bad.  I'm still getting used to the UI/UX of UDM-PRO.  Silly me thought the user add/remove would be in Protect, which it is. But in that page it's only for cloud users.  I didn't know I had to go to the UDM-PRO users page which includes both cloud and local user functionality.  

Thanks for the heads up.

**Comment by hjdhjd** [comment]
Happens to the best of us. Good luck.
