### ISSUE TITLE
Support for G4 Doorbell Pro

### ISSUE THREAD

**Issue by discorev** [hjdhjd/homebridge-unifi-protect#750]
**Is your feature request related to a problem? Please describe:**
The G4 Doorbell Pro has now been released and it would be good to see what support can be added for the additional package camera.

**Describe the solution you'd like:**
To add a stream for the package camera, or, if HomeKit has a way to have this exposed as part of the doorbell as a secondary camera to do that.

**Describe alternatives you've considered:**
As this is a new feature, I do not see any alternatives.

**Additional context:**
[Unifi doorbell page](https://ui.com/camera-security/doorbell)

**Comment by discorev** [comment]
<img width="358" alt="RTSPS" src="https://user-images.githubusercontent.com/8238834/171034166-89cd469b-6259-4379-aa37-09aed96bd994.png">

The package camera appears to be exposed as an additioanl RTSPS stream

**Comment by hjdhjd** [comment]
Asked and answered elsewhere. Support will be forthcoming.
