### ISSUE TITLE
plugin keeps enabling status light

### ISSUE THREAD

**Issue by shazport** [hjdhjd/homebridge-unifi-protect#753]
Hi - is all working however it continues to re-enable the status light after I turn it off? Is there a code to disable this fucntion?
Thanks

![image](https://user-images.githubusercontent.com/107011332/172726548-3bfaa09e-71aa-4552-bd78-ef53b3b4bf5e.png)

**Comment by simplytoast1** [comment]
Hey @shazport !

The status light control when using HBUP is managed by HomeKit.

To turn off the status light in the Home app (on iOS or MacOS) click on the camera in question to start the stream.

Click the gear icon.

Scroll until you see the option to turn off the camera status light.

![75A9CCC9-3457-4359-B2F4-72A2D801C425](https://user-images.githubusercontent.com/4954230/172729701-38e140a2-7668-4bf1-b03e-42e317df111b.jpeg)

**Comment by shazport** [comment]
Hey  - will it only work with an admin account? I set up a local user and HB complained about needing admin access?
Thanks
John

**Comment by simplytoast1** [comment]
John - 

This has expanded beyond an issue and is more troubleshooting.  An admin user is required for HBUP.  I strongly suggest reading the (very well) written documentation about proper setup.

https://github.com/hjdhjd/homebridge-unifi-protect#plugin-configuration

**Comment by ryanschmidt** [comment]
I've been using the plugin for awhile without this issue but with one of the recent builds it cropped up. Admin user, all functionality works, but when disabling the status light the light is automatically re-enabled no matter if you disable from UniFi or HomeKit. I've tried all combinations of these settings but the status light always comes on again (even though the settings show they are off).

**Comment by eaglexeye69** [comment]
Just come across this too. G4 Pro status light keeps re-enabling itself from within Homekit.
