### ISSUE TITLE
Support standalone UniFi cameras 

### ISSUE THREAD

**Issue by bcyng** [hjdhjd/homebridge-unifi-protect#755]
**Is your feature request related to a problem? Please describe:**
Cant add standalone UniFi cameras

**Describe the solution you'd like:**
The ability to add standalone UniFi cameras that don’t use UniFi protect. 

With hsv support now working, it doesn’t make sense to record both on the UniFi protect controller and in the cloud with hsv. Would like to lose the UniFi protect controller (mine dies every few years), put the cameras in standalone mode and use this plugin to record using the hsv functionality.

**Describe alternatives you've considered:**
Tried setting the standalone camera as the UniFi protect controller in this plug-in. It doesn’t work. 

Tried using the camera ui homebridge plug-in - hsv recording is broken on that plug-in.

tried the camera-ffmpeg homebridge plugin. Doesn’t support hsv.

**Additional context:**
Nil

**Comment by hjdhjd** [comment]
I appreciate the dilemma - this won’t be worked on. This plugin is explicitly for support within the Protect ecosystem. I won’t be providing this support.

If you’d like to use a camera as a standalone one, you can use plugins like the excellent homebridge-camera-ffmpeg.

Thanks for the suggestion!
