### ISSUE TITLE
Erratic HomeKit Notifications

### ISSUE THREAD

**Issue by ibogost** [hjdhjd/homebridge-unifi-protect#757]
**Describe The Problem:**
HomeKit notifications for camera motion and ring events are not being delivered as expected. Some cameras never send notifications, others do erratically. 

**To Reproduce:**
Unclear. I have confirmed that Homebridge and my Unifi Protect controller are set to the same time, as per plugin troubleshooting documentation.

**Logs:**

No relevant logs; please let me know if there is a verbose logging option that would provide relevant detail.

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "192.168.1.236",
            "password": "[removed]",
            "username": "[removed]"
        }
    ],
    "options": [
        "Enable.Doorbell.Trigger",
        "Enable.Motion.SmartDetect"
    ],
    "platform": "UniFi Protect"
}
```

**Screenshots:**
N/A

**Environment:**

* **Homebridge Version:** 1.4.1
* **Node Version:** 14.17.4
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.0.1
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** 2.4.10
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 12 Pro iOS 15.5
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Thanks for the report - please review the feature option documentation (see the README on the project homepage) for logging options. Feel free to open a new issue if needed but what you're describing sounds like a HomeKit hub-related quirk than anything else.

Best of luck.
