### ISSUE TITLE
G3 Instant won’t work on UDR

### ISSUE THREAD

**Issue by scooter306** [hjdhjd/homebridge-unifi-protect#759]
**Describe The Problem:**

Added Protect to homebridge. Only have a g3 instant atm. Screenshots work, the timestamp renews every 30’seconds. Livestream won’t work as camera seems to not respond. 
**To Reproduce:**

Select the camera in HomeApp
**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.5
* **Node Version:** 16.15.1
* **Homebridge-UniFi-Protect Plugin Version:**5.5.4
* **UniFi Protect Version:** 2.0.1
* **UniFi Protect Controller Type:** UDR
* **UniFi Protect Controller Firmware Version:** 2.4.10
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iOS, iPadOS
* **Operating System and OS Version:** homebridge in docker

**Comment by ryanschmidt** [comment]
Same issue here.
