### ISSUE TITLE
Doorbell button activates camera

### ISSUE THREAD

**Issue by shazport** [hjdhjd/homebridge-unifi-protect#760]
**Is your feature request related to a problem? Please describe:** 
<Would be great if the doorbell trigger could be used to activate the camera live stream. the standard unify activation is slow to respond  -->

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by hjdhjd** [comment]
As I interpret your request, you’re asking about a HomeKit capability that Apple would need to provide in the Home app. There’s nothing the plugin can do about that. The plugin cannot force a livestream to be instantiated - the Home app does that. Thanks.
