### ISSUE TITLE
Homebridge in Debug mode, controlling plugin logging level

### ISSUE THREAD

**Issue by exsilium** [hjdhjd/homebridge-unifi-protect#776]
Hi, thank you for this awesome project. 👏 🙇 I've been a long time user of this plugin and haven't had any issues yet, and I still don't :) But... I just upgraded to `v5.5.4` and noticed that I get a long json struct logged to my overall homebridge.log file whenever controller refresh happens. Granted, I'm running my homebridge in Debug mode to get verbose logging from other plugins, but Protect plugin seems to drown all other messages due to (at least what feels to me) excessive logging. 

```
[8/7/2022, 6:30:50 AM] [UniFi Protect] {
  accessKey: '...',
  authUserId: '...',
  bridges: [
    {
  ...
  viewers: []
}
```
For me and my setup, this is a 2700+ line object that gets logged on every refresh. I extended the refresh time so I get less of it but is there an option that I can use to suppress this object logging without turning the overall homebridge debug mode off? If not, I think there should be. I see the value of this output when debugging Protect plugin, but when focusing elsewhere it drowns everything else. Thanks, and Cheers! 🍻

**Comment by exsilium** [comment]
Note to self: @exsilium - Right, I'll rewrite/open an issue and transform this request to a proper template as per process dictates. 👍

**Comment by hjdhjd** [comment]
Live by debug mode, die by debug mode. 😄 There will be changes in an upcoming major release, but you really shouldn't rely on that when it comes to debug logging information. Debug mode is intended for debugging, not for use in production environments...I've historically enjoyed a verbose debugging environment. 😄 

I'm sure there's a reason you've decided to run Homebridge in debug mode, and that's your choice, but the "fix" here is don't run in an explcit debug mode, not changing that I provide a robust debugging experience for the plugin. 😉

Thanks and keep enjoying the plugin!

**Comment by exsilium** [comment]
Hi @hjdhjd , and thank you for your comments. Being the "HomeKit for the impatient" implementation I find the debug mode a great way to get the most verbose output from my own plugins (XBee/Zigbee) as well as others - so you have a point, debug is and should be as verbose as it can get :) Just in case there are other people who find the object dumps too much for their taste when working against live environment and focusing on other plugins, there's a quick workaround to disable the debug prints from within the `unifi-protect` library. Cheers! 🍻 

```
--- protect-api.js.orig	2022-08-08 11:42:53.408490388 +0000
+++ protect-api.js	2022-08-08 11:43:25.280282943 +0000
@@ -194,7 +194,7 @@
             this.log.info("%s: Connected to the UniFi Protect controller API (address: %s mac: %s).", this.getNvrName(), data.nvr.host, data.nvr.mac);
         }
         // Capture the bootstrap if we're debugging.
-        this.log.debug(util_1.default.inspect(this.bootstrap, { colors: true, depth: null, sorted: true }));
+        // this.log.debug(util_1.default.inspect(this.bootstrap, { colors: true, depth: null, sorted: true }));
         // Check for admin user privileges or role changes.
         this.checkAdminUserStatus(firstRun);
         // We're good. Now connect to the event listener API.
@@ -287,7 +287,7 @@
         if (!(await this.bootstrapProtect())) {
             return false;
         }
-        this.log.debug(util_1.default.inspect(this.bootstrap, { colors: true, depth: null, sorted: true }));
+        // this.log.debug(util_1.default.inspect(this.bootstrap, { colors: true, depth: null, sorted: true }));
         // We currently know about the following device classes:
         //   - cameras (including doorbells)
         //   - lights
```

**Comment by hjdhjd** [comment]
Best of luck! Another approach, and a preferred one, would be not to modify the developer’s code that can (and in my case definitely will) change on you and instead separate your world into production and non-production Homebridge instances. Run the plugins you want to debug in their own Homebridge instances. You can do so on the same machine with relatively little fuss - instructions are on the Homebridge site.

Closing this out and archiving. Cheers.
