### ISSUE TITLE
Camera Status Light activates each time HomeKit pulls a preview (and disabling in Accessory Details doesn't actually disable).

### ISSUE THREAD

**Issue by kristiandg** [hjdhjd/homebridge-unifi-protect#780]
**Describe The Problem:**
I have repeatedly found a camera's Status Light activated (which is a dangerous thing, as it shows people when it's offline). I have been repeatedly deactivating it, only to see it turned back on again. Since this problem didn't start until I loaded this plugin, I believed something was happening with the HomeKit tie-in.

**To Reproduce:**
Although the Status Light has been set to disabled on each camera in Protect many times (both from within the Protect app, and within the Accessory Details section of HomeKit), it doesn't stay that way.

There are two parts to this. First, if you disable the Status Light on the Protect App (and confirm it's disabled), then go into HomeKit, even loading the preview image causes the status light to be re-enabled. It seems, whenever HomeKit accesses the camera, it makes this setting change.

Second, disabling the status light in Accessory Details within HomeKit, doesn't actually disable it.

So, the process would be:
1: Disabled camera status light within Protect app
2: Launch HomeKit and let it pull a preview, or access the camera's feed within HomeKit
3: In Protect app, view camera settings
(You should now see that Status Light has re-enabled itself)

**Logs:**
The main log display didn't seem to have any odd errors. If there's a more detailed log specifically for the plugin, I can provide - I would just need to know where it is.

**Homebridge Configuration:**

```
{
    "bridge": {
        "name": "HomeBridge",
        "username": "<NotReallyRelevant>",
        "port": 51032,
        "pin": "<NotReallyRelevant>",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "<IP ADDY>",
                    "name": "UDM-Pro",
                    "password": "<SuperSecretPassword",
                    "refreshInterval": 10,
                    "username": "<SuperSecretUsername"
                }
            ],
            "options": [
                "Disable.Doorbell.Messages.FromDoorbell"
            ],
            "platform": "UniFi Protect"
        },
        {
            "zoneTypes": [
                {
                    "zoneNumber": 1,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 2,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 3,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 4,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 5,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 6,
                    "zoneType": "motion"
                },
                {
                    "zoneNumber": 7,
                    "zoneType": "motion"
                },
                {
                    "zoneNumber": 8,
                    "zoneType": "motion"
                },
                {
                    "zoneNumber": 9
                },
                {
                    "zoneNumber": 10,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 11,
                    "zoneType": "motion"
                },
                {
                    "zoneNumber": 12,
                    "zoneType": "noContact"
                },
                {
                    "zoneNumber": 13,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 14,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 15,
                    "zoneType": "garage"
                },
                {
                    "zoneNumber": 16,
                    "zoneType": "motion"
                },
                {
                    "zoneNumber": 17,
                    "zoneType": "noContact"
                },
                {
                    "zoneNumber": 18,
                    "zoneType": "noContact"
                },
                {
                    "zoneNumber": 19
                },
                {
                    "zoneNumber": 20
                },
                {
                    "zoneNumber": 21
                },
                {
                    "zoneNumber": 22
                },
                {
                    "zoneNumber": 23
                },
                {
                    "zoneNumber": 24,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 25,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 26,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 27,
                    "zoneType": "motion"
                },
                {
                    "zoneNumber": 28,
                    "zoneType": "garage"
                },
                {
                    "zoneNumber": 29,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 30,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 31,
                    "zoneType": "contact"
                },
                {
                    "zoneNumber": 32,
                    "zoneType": "contact"
                }
            ],
            "name": "M1Gold",
            "elkAddress": "10.0.101.5",
            "elkPort": 2101,
            "secure": false,
            "area": 1,
            "keypadCode": 1701,
            "garageDoors": [
                {
                    "name": "Garage Overhead Door - Exterior",
                    "stateZone": 15,
                    "openOutput": 7,
                    "closeOutput": 7
                },
                {
                    "name": "Garage Overhead Door - Interior",
                    "stateZone": 28,
                    "openOutput": 8,
                    "closeOutput": 8
                }
            ],
            "includedOutputs": [
                65
            ],
            "platform": "ElkM1"
        }
    ],
    "disabledPlugins": []
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.5.0
* **Node Version:** 16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.1.2
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.12.22
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** IOS 15 and 16beta
* **Operating System and OS Version:** Raspbian v11 (Bullseye)

**Comment by hjdhjd** [comment]
This is documented behavior, and how to address it is also been documented and asked, and answered, more than a few times in the past. [Please refer to the documentation](https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/HomeKitSecureVideo.md#camera-properties-exposed-in-homekit-secure-video). Or you can search  issues that were opened in the past on this topic.

There will be a future update to allow a bit more customization here. Thanks.

**Comment by kristiandg** [comment]
Unfortunately, I tried the option to disable within HomeKit, as the documentation suggested, and it didn't sustain the setting, which is why I had opened the ticket and noted that. So is the thought that HomeKit right now isn't even honoring that setting currently?  If so, is there a Options string that could be used to disable extending that setting into HomeKit?

**Comment by hjdhjd** [comment]
As mentioned above - there will be additional options in a future update. Your alternative is to disable HomeKit Secure Video on a given camera. Cheers.

**Comment by thegreatco** [comment]
@hjdhjd any chance you could expose a feature flag to just prohibit HomeKit from changing this value? I keep toggling the value off in HomeKit but it keeps getting set back to "on" and I haven't figured out how to prevent it.

**Comment by hjdhjd** [comment]
https://github.com/hjdhjd/homebridge-unifi-protect/issues/780#issuecomment-1217005524

Coming soon, among other things. Thanks!
