### ISSUE TITLE
Status Light gets enabled by plugin automatically

### ISSUE THREAD

**Issue by hammerofthor8** [hjdhjd/homebridge-unifi-protect#784]
**Describe The Problem:**
With the Status Light disabled (or enable), the plugin will automatically turn it on. If you turn off the status light through the Protect app, the plugin will re-enable it, sometimes it takes 10 minutes, other times it will re-enable it within a minute. 

**To Reproduce:**
Turn off the status light in protect app
Wait
Status light will be enabled again

**Logs:**
N/A

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "192.168.1.1",
            "password": "Yaypassword!",
            "username": "unifi@gmail.com"
        }
    ],
    "_bridge": {
        "username": "",
        "port":
    },
    "platform": "UniFi Protect"
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** homebridge-config-ui-x v4.50.1
* **Node Version:** v16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** v5.5.4
* **UniFi Protect Version:**  v2.1.2
* **UniFi Protect Controller Type:** UDM-Pro
* **UniFi Protect Controller Firmware Version:** v1.12.22
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 14-16, macOS 15-16
* **Operating System and OS Version:** MacOS
*

**Comment by brianmedia** [comment]
There's a ton of tickets on this in the 'closed' section. Have you read those? TL;DR it's not this plugin causing the issue.

**Comment by hammerofthor8** [comment]
I have not sorry, I am completely new to this GitHub thing. I will look for them.

**Comment by hammerofthor8** [comment]
'''In the case of UniFi Protect, one of those settings is the Camera Status Light setting in the Home app. It allows you to turn on or off the Camera Status Light setting for a HomeKit-enabled camera. In the UniFi Protect world, that means the ability to turn on or off the status LED on a camera. That's great functionality, but there's also a bug in the Home app itself related to this. Specifically, the camera status light setting is initially forced on by the Home app. There is no way to actually force this to default to what is currently set on the UniFi Protect controller, and sync accordingly. We are left with a situation where, if I want to provide access to this feature - which I do - you are forced into having to turn off the camera status light, in the Home app in order to have a setting that sticks. '''

**Comment by hjdhjd** [comment]
> There's a ton of tickets on this in the 'closed' section. Have you read those? TL;DR it's not this plugin causing the issue.

Thank you! Appreciate you leaning in. ❤️

**Comment by hjdhjd** [comment]
> There's a ton of tickets on this in the 'closed' section. Have you read those? TL;DR it's not this plugin causing the issue.

Thank you @brianmedia! Appreciate you leaning in. ❤️
