### ISSUE TITLE
Turning off and on specific cameras on demand

### ISSUE THREAD

**Issue by PrzemyslawKlys** [hjdhjd/homebridge-unifi-protect#785]
I was wondering if it's something that would be doable. Essentially I have cameras at home and outside. While I don't care for the outside cameras to work day and night, I prefer to have cameras at home only enabled when I leave. While I can remove specific cameras from HomeKit using some options you provide, what I am looking for is to disable the camera totally maybe via POE port control on UDM/switch via SWITCH in HomeKit. Of course that means controlling network and I saw you have placeholder for network plugin that is not started yet.

Worst case scenario, I would like to be able to disable/enable cameras or enable/disable audio only in HomeKit but using a HomeKit switch or multiple state buttons or something, so I could control on demand which cameras are on and which aren't and when they do record stuff. 

Unifi system itself doesn't provide scheduling or anything.

**Is your feature request related to a problem? Please describe:**

Described above

**Describe the solution you'd like:**

Described above

**Describe alternatives you've considered:**

Described above

**Additional context:**

**Comment by hjdhjd** [comment]
There’s already a feature to enable or disable recording on specific cameras. Disabling a camera entirely is something I might consider for the future, though this isn’t a high priority feature. In general, I don’t think features like this really belong here…but I can be convinced.

Take a look at the `Enable.Nvr.Recording.Switch` feature option. Thanks for the suggestions.

**Comment by PrzemyslawKlys** [comment]
For me, this is a fantastic and most wanted feature. I don't need recordings or, even better, running cameras when I am at home unless I want them. To be honest, I bought all my cameras inside and outside to watch my dog and be aware of where he is or what he is doing so I don't run around like a madman. Everything else is a bonus.  It feels weird having to record all my conversations or my guests or whatever. I would like to shut it down and, when I go out, enable it all so I can look at what my dog is doing or, if anything happens, know about it.

So for me, there should be three options to pick from:

- Enable.Nvr.Recording.Switch
- Enable.Nvr.Audio.Switch
- Enable.Nvr.Camera.Switch

I just tested the first switch, and it's awesome. The other two would make it superb and complete. I am now thinking that while Audio should be easy to achieve, the disabling of the camera would be a bit harder because most likely would require POE to be turned off. Or maybe there's some other setting that could be used. I was even thinking that maybe one could mess up colors of the camera to make it totally black or something if doing this via POE would require some huge work.

**Comment by hjdhjd** [comment]
Thanks but unlikely to implement something like that to deal with specific edge cases anytime soon, if ever. There is a high bar for me to add exceptional capabilities that go beyond the scope of this plugin: to provide the best HomeKit native experience for UniFi Protect.

Thanks for the suggestion.
