### ISSUE TITLE
Allow Status Light Functionality to be Disabled in the Plugin Without Disabling HKSV

### ISSUE THREAD

**Issue by Garywoo** [hjdhjd/homebridge-unifi-protect#789]
**Is your feature request related to a problem? Please describe:**
This plugin's feature of exposing the camera's status light within the Home app is preventing me from conditionally turning on and off the status light from other platforms. 

My intended use case is using Home Assistant to turn on or off the camera's status light to indicate whether or not the camera is recording. The state of the camera's status light and recording status is being set within Home Assistant using the controls available within that platform. This is working correctly, however the state of the camera's status light will be overridden by the state of the status light switch within the camera's setting in the Home app soon afterwards. For example, if the status light is turned off in the Home app, and the status light is turned on by Home Assistant, the status light will be turned on for a while, but will eventually become turned off again to match the Home app's status light setting.

**Describe the solution you'd like:**
I understand that there is a bug in the Home app which affects the ability to sync the state of the status light within the Home app with the actual state of the cameras status light, therefore I would like to be able to prevent HomeKit from overriding the state of the camera's status light, by preventing the status light from being exposed to HomeKit entirely. This could be achieved by introducing some additional feature options in the plugin. I believe this would be an acceptable workaround, besides a resolution to the Home app bug. 

**Describe alternatives you've considered:**
I have considered disabling HomeKit Secure Video for the affected cameras, which does resolve the issue, however the HKSV feature has other benefits that I would prefer not to lose (such as offsite video recording).

**Additional context:**
I know there have been numerous issues raised about the status light behaviour in this plugin already, but I felt that they were all focused on simply turning on or off the status light permanently, and I wanted to make my case for how I beleive the plugin could be improved given the context of my use case, where the status light is being externally controlled.

**Comment by hjdhjd** [comment]
Thanks for the suggestion, as I have mentioned elsewhere, there will be a future update to address this Cheers.
