### ISSUE TITLE
Doorbell ring event doesn't include a name

### ISSUE THREAD

**Issue by mterhar** [hjdhjd/homebridge-unifi-protect#793]
**Is your feature request related to a problem? Please describe:**

When someone rings the doorbell, the HomeKit notification is just "someone rang some doorbell". It properly identifies the people ringing the bell, but doesn't say which door. I have to wait for the video preview to load and check behind them to see where I need to go.

**Describe the solution you'd like:**

Wondering if adding the doorbell's name is an easy fix or something innate to HomeKit.

**Describe alternatives you've considered:**

Not sure what else can be done here. Open to suggestions. 

**Additional context:**

**Comment by hjdhjd** [comment]
Thanks for the suggestion, but we have no control over this. That’s all controlled by HomeKit. Fun fact: if you have HKSV enabled, AND photo access enabled, HomeKit will recognize names it knows…again, all this is the HomeKit black box. The plugin has no influence or control over those bits.
