### ISSUE TITLE
snapshots load but stream doesn’t 

### ISSUE THREAD

**Issue by mac067783** [hjdhjd/homebridge-unifi-protect#795]
**Describe The Problem:**

If I click on a camera and then click close (ios16) it updates the snapshot right away. However if I click on a camera the stream never loads, just get a spinning icon…

**To Reproduce:**

Open home on iOS 16, click on a camera, sits and spins
**Logs:**

None applicable, logs show same process as prior to iOS 16.  

```
Show the Homebridge logs here.
Remove any sensitive information.
```
None available. 
**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```
Again,  robing changed. 
**Screenshots:**

Screen shot will just show spinning wheel waiting for camera to load. 
**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by Amarog** [comment]
Got the exact same problem, after adding the bridge (As a Child) everything works perfect. After 5 minutes however I get the spinning wheel. Tried the low stream option, same thing. As with OP, the snapshot keeps updating every 10s. No problems there.

**Comment by hjdhjd** [comment]
@Amarog If you have an issue, please open a new one if you want support, or use the Discord. Given neither of us know the exact setup in question, whether it’s the **exact** same issue or something else is far from clear. That’s why I insist that users keep their issues separate. Thanks.

@mac067783 There’s nothing to be done with the above given the lack of information. Please open a new issue and provide **all* of the information requested in the issue template if you’d like support. Thanks.
