### ISSUE TITLE
G4 Doorbell Pro Welcome Light

### ISSUE THREAD

**Issue by Hazza42** [hjdhjd/homebridge-unifi-protect#796]
**Is your feature request related to a problem? Please describe:**

I’m not even sure if this is exposed in the API since I can’t find any manual controls for it in the Protect app, but I’d love to have some manual control over this via HomeKit 

**Describe the solution you'd like:**

A simple light switch inside the doorbell camera would be great since it would allow me to use the package cam (which I assume will get support soon) at night since it has no infrared capabilities and wouldn’t otherwise not be able to see anything.

**Describe alternatives you've considered:**

No alternatives that I can find currently as the Welcome Light seems to be tied to motion events and isn’t configurable.

**Additional context:**

I would also tie this Welcome Light to my other outside lights to activate more reliably as it seems pretty sporadic as it is.

**Comment by hjdhjd** [comment]
It’s on the roadmap. Thanks for the suggestion. 😄
