### ISSUE TITLE
"STREAMING DISABLED ACTIVE" message in logs

### ISSUE THREAD

**Issue by x-magic** [hjdhjd/homebridge-unifi-protect#804]
**Describe The Problem:**

When cameras are set to "Detect Activity" (assume the same in "Off" mode), `STREAMING DISABLED ACTIVE` message will be generated constantly and polluting the Homebridge logs. 

**To Reproduce:**

1. Confirm Unifi Protect camera is active and streaming in Home app
2. Go to one of the camera's settings in Home app, change the recording options (either) to "Detect Activity"
3. Monitor the Homebridge log, and "STREAMING DISABLED ACTIVE" message should show up and repeat (too) many times

**Logs:**

```
See screenshot below
```

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "[REDACTED]",
            "mqttTopic": "unifi/protect",
            "mqttUrl": "mqtt://[REDACTED]@[REDACTED]:1883",
            "password": "[REDACTED]",
            "username": "[REDACTED]"
        }
    ],
    "options": [
        "Disable.Video.Stream.High.[REDACTED]",
        "Disable.Video.Stream.High.[REDACTED]",
        "Disable.Video.Stream.High.[REDACTED]",
        "Disable.Video.Stream.High.[REDACTED]",
        "Disable.Video.Stream.High.[REDACTED]",
        "Disable.Video.Stream.High.[REDACTED]",
        "Disable.Video.Stream.High.[REDACTED]",
        "Disable.Video.Stream.High.[REDACTED]",
        "Disable.Video.Stream.High.[REDACTED]",
        "Disable.Video.HKSV.[REDACTED]",
        "Disable.Video.HKSV.[REDACTED]",
        "Disable.Video.HKSV.[REDACTED]",
        "Disable.Video.HKSV.[REDACTED]",
        "Disable.Doorbell.Messages"
    ],
    "platform": "UniFi Protect",
    "_bridge": {
        "username": "[REDACTED]",
        "port": 41565
    }
}
```

**Screenshots:**

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/3180639/193403169-bd13456f-9c79-4145-8a21-0f3e969d2e35.png">

**Environment:**

* **Homebridge Version:** 1.5.0
* **Node Version:** v16.17.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.2
* **UniFi Protect Controller Type:** UCKG2+
* **UniFi Protect Controller Firmware Version:** Unifi OS 2.5.11
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Latest release of devices (tested on iPhone/iPad and Macs)
* **Operating System and OS Version:**  Homebridge host: Debian 11 Bullseye (stable)

**Comment by x-magic** [comment]
Only a cosmetic issue, won't affect the functionality of the plugin. However this message consumes the majority of the logs, which can be a problem in the long term (logs analytical or such).

**Comment by hjdhjd** [comment]
I don't believe that's a message generated by the plugin actually.

**Comment by x-magic** [comment]
That's my guess, too. Surprisingly the only valid Google search is on the Blink plugin for Homebridge, but that issue is not really about the message. Where do you think the message is actually generated? Unlike other logs in Homebridge that are always marked with timestamp and source, this one doesn't.

**Comment by hjdhjd** [comment]
Sorry can't help there. If I come across something I will provide an update here and would appreciate the same if you track it down. I take pride in my logging. 😀
