### ISSUE TITLE
Support for Unifi Connect.

### ISSUE THREAD

**Issue by gheydon** [hjdhjd/homebridge-unifi-protect#805]
**Is your feature request related to a problem? Please describe:**

No this would be a new feature.

**Describe the solution you'd like:**

ATM Unifi Protect is exposing all the devices that are available to the Unifi protect controller. With the addition of Unifi Connect controller (Replacing the Unifi LED controller but still in EA) so that it will expose the devices in Unifi Connect as well.

**Describe alternatives you've considered:**

I have considered writing a new module for Unifi connect. But I am assuming that most of the function provided by the Unifi Protect home bridge plugin would be replicated. Also I have not been able to find any documentation on the unifi connect API.

**Additional context:**

I have Unifi LED panels and switches. I would like to have these accessible via homekit.

I am a developer and would be happy/excited to assist developing and testing the addition of the Unifi Connect devices.

**Comment by hjdhjd** [comment]
Thanks for the request. If and when Connect leaves EA, I’ll be looking to add support for it. As a rule, I provide no support for any EA / unreleased product whatsoever. Thanks!
