### ISSUE TITLE
Different types of motion sensors

### ISSUE THREAD

**Issue by MichaelVdheeren** [hjdhjd/homebridge-unifi-protect#811]
**Is your feature request related to a problem? Please describe:**
I have a G4 Pro camera where I defined multiple motion areas and a trespassing line. I am unable to make any distinction between the motion events triggered by the different areas or the line. I would like the porch light to turn on only when someone passed the line configured in Unifi Protect while I would always like to record all the other motions still.

**Describe the solution you'd like:**
Provide different motion sensors, or a contact sensor, for trespassing lines and different motion sensors for each zone or area configured.

**Describe alternatives you've considered:**
Removing all the other areas, but that is not really an option because I will then miss events happening around the house.

**Additional context:**
N/A

**Comment by hjdhjd** [comment]
Thanks for the suggestion, but I’m unlikely to implement this anytime soon, but will consider it for the future. Appreciated!

**Comment by hjdhjd** [comment]
Implemented in v6.3.0 and beyond - enjoy!
