### ISSUE TITLE
No camera livestream with homebridge-unifi-protect

### ISSUE THREAD

**Issue by Mikka20** [hjdhjd/homebridge-unifi-protect#815]
**Describe The Problem:**
Hi,
i am using the following setup:
Raspberry Pi 4, Raspberry Pi OS Lite (64-bit) + Debian 11 (bullseye) + Docker containers:
    - Homebridge v1.5.0
    - unifi-protect-arm64 [https://github.com/markdegrootnl/unifi-protect-arm64](url) (UNVR 2.3.10 & Protect 1.20.3)
Camera G3 Instant (Firmware Version - Up to Date)

I know that beta software is not supported by this project, but I could not find out if that counts for Unifi Protect Software in an Docker environment.
The installation of all components is successful and without error messages. I can see a livestream in Unifi Protect (PC Browser & iOS Unifi Protect App) and also a livestream in Homebridege with the Homebridge Camera FFmpeg
(homebridge-camera-ffmpeg v3.1.4) plugin. Unfortunately, there is no livestream available in the Homebridge UniFi Protect (homebridge-unifi-protect v5.5.4) plugin.

**To Reproduce:**
Install Homebride + Unifi Protect in Docker.

**Logs:**
[10/24/2022, 1:58:55 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[10/24/2022, 1:58:55 PM] [HB Supervisor] Started Homebridge v1.5.0 with PID: 1494
[10/24/2022, 1:58:56 PM] Loaded config.json with 0 accessories and 3 platforms.
[10/24/2022, 1:58:56 PM] Loaded 1 cached accessories from cachedAccessories.
[10/24/2022, 1:58:56 PM] ---
[10/24/2022, 1:58:56 PM] Loaded plugin: homebridge-camera-ffmpeg@3.1.4
[10/24/2022, 1:58:56 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[10/24/2022, 1:58:56 PM] ---
[10/24/2022, 1:58:57 PM] Loaded plugin: homebridge-unifi-protect@5.5.4
[10/24/2022, 1:58:57 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[10/24/2022, 1:58:57 PM] ---
[10/24/2022, 1:58:57 PM] Loading 3 platforms...
[10/24/2022, 1:58:57 PM] [UniFi Protect] Initializing UniFi Protect platform...
[10/24/2022, 1:58:57 PM] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[10/24/2022, 1:58:57 PM] [Camera FFmpeg] [G3] Configuring cached bridged accessory...
Setup Payload:
X-HM://0012A3BCDEFG4
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXX-XX-XXX │     
    └────────────┘     
                       
[10/24/2022, 1:58:57 PM] Homebridge v1.5.0 (HAP v0.10.4) (Homebridge D901) is running on port 51653.

**Homebridge Configuration:**
{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51653,
        "pin": "XXX-XX-XXX",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "192.168.1.100",
                    "password": "password",
                    "username": "user"
                }
            ],
            "platform": "UniFi Protect"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "G3",
                    "videoConfig": {
                        "source": "-i rtsps://192.168.1.100:7441/aBBBB12b34cDEfgH5?enableSrtp"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}

**Environment:**

* **Homebridge Version:** v1.5.0 (HAP v0.10.4)
* **Node Version:** v16.18.0
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 1.20.3
* **UniFi Protect Controller Type:** unifi-protect-arm64 [https://github.com/markdegrootnl/unifi-protect-arm64](url) (UNVR 2.3.10 & Protect 1.20.3)
* **Apple Device iOS Version:** iPhone 7 + iOS 15.7 & iPhone X + iOS 16.0.3
* **Operating System and OS Version:** Raspberry Pi 4, Raspberry Pi OS Lite (64-bit) + Debian 11 (bullseye) + Docker  5:20.10.18~3-0~debian-bullseye arm64

Thx
Mikka

**Comment by hjdhjd** [comment]
Setting aside that you're running an entirely unsupported configuration...this isn't a plugin issue. 

Please read the documentation related to docker and homebridge...you have an interface-specificity issue with Homebridge...and it's been covered many times in prior closed issues.

https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/Troubleshooting.md#network-issues
https://github.com/homebridge/homebridge/wiki/mDNS-Options#how-to-select-advertised-network-interfaces

Best of luck.

**Comment by thezepter** [comment]
> **Describe The Problem:** Hi, i am using the following setup: Raspberry Pi 4, Raspberry Pi OS Lite (64-bit) + Debian 11 (bullseye) + Docker containers: - Homebridge v1.5.0 - unifi-protect-arm64 [https://github.com/markdegrootnl/unifi-protect-arm64](url) (UNVR 2.3.10 & Protect 1.20.3) Camera G3 Instant (Firmware Version - Up to Date)
> 
> I know that beta software is not supported by this project, but I could not find out if that counts for Unifi Protect Software in an Docker environment. The installation of all components is successful and without error messages. I can see a livestream in Unifi Protect (PC Browser & iOS Unifi Protect App) and also a livestream in Homebridege with the Homebridge Camera FFmpeg (homebridge-camera-ffmpeg v3.1.4) plugin. Unfortunately, there is no livestream available in the Homebridge UniFi Protect (homebridge-unifi-protect v5.5.4) plugin.
> 
> **To Reproduce:** Install Homebride + Unifi Protect in Docker.
> 
> **Logs:** [10/24/2022, 1:58:55 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution [10/24/2022, 1:58:55 PM] [HB Supervisor] Started Homebridge v1.5.0 with PID: 1494 [10/24/2022, 1:58:56 PM] Loaded config.json with 0 accessories and 3 platforms. [10/24/2022, 1:58:56 PM] Loaded 1 cached accessories from cachedAccessories. [10/24/2022, 1:58:56 PM] --- [10/24/2022, 1:58:56 PM] Loaded plugin: homebridge-camera-ffmpeg@3.1.4 [10/24/2022, 1:58:56 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg' [10/24/2022, 1:58:56 PM] --- [10/24/2022, 1:58:57 PM] Loaded plugin: homebridge-unifi-protect@5.5.4 [10/24/2022, 1:58:57 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect' [10/24/2022, 1:58:57 PM] --- [10/24/2022, 1:58:57 PM] Loading 3 platforms... [10/24/2022, 1:58:57 PM] [UniFi Protect] Initializing UniFi Protect platform... [10/24/2022, 1:58:57 PM] [Camera FFmpeg] Initializing Camera-ffmpeg platform... [10/24/2022, 1:58:57 PM] [Camera FFmpeg] [G3] Configuring cached bridged accessory... Setup Payload: X-HM://0012A3BCDEFG4 Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
> 
> ```
> ┌────────────┐     
> │ XXX-XX-XXX │     
> └────────────┘     
> ```
> 
> [10/24/2022, 1:58:57 PM] Homebridge v1.5.0 (HAP v0.10.4) (Homebridge D901) is running on port 51653.
> 
> **Homebridge Configuration:** { "bridge": { "name": "Homebridge XXXX", "username": "XX:XX:XX:XX:XX:XX", "port": 51653, "pin": "XXX-XX-XXX", "advertiser": "bonjour-hap" }, "accessories": [], "platforms": [ { "name": "Config", "port": 8581, "platform": "config" }, { "controllers": [ { "address": "192.168.1.100", "password": "password", "username": "user" } ], "platform": "UniFi Protect" }, { "name": "Camera FFmpeg", "cameras": [ { "name": "G3", "videoConfig": { "source": "-i rtsps://192.168.1.100:7441/aBBBB12b34cDEfgH5?enableSrtp" } } ], "platform": "Camera-ffmpeg" } ] }
> 
> **Environment:**
> 
> * **Homebridge Version:** v1.5.0 (HAP v0.10.4)
> * **Node Version:** v16.18.0
> * **Homebridge-UniFi-Protect Plugin Version:**
> * **UniFi Protect Version:** 1.20.3
> * **UniFi Protect Controller Type:** unifi-protect-arm64 [https://github.com/markdegrootnl/unifi-protect-arm64](url) (UNVR 2.3.10 & Protect 1.20.3)
> * **Apple Device iOS Version:** iPhone 7 + iOS 15.7 & iPhone X + iOS 16.0.3
> * **Operating System and OS Version:** Raspberry Pi 4, Raspberry Pi OS Lite (64-bit) + Debian 11 (bullseye) + Docker  5:20.10.18~3-0~debian-bullseye arm64
> 
> Thx Mikka

Hey Mikka,

have you solved your Problem ? I did not get it solved. Until recently everything was going great and suddenly not anymore. I have already checked the interfaces under Settings and also tried all 3 mDNS advertisers. Nothing helps.

**Comment by Mikka20** [comment]
> [thezepter]have you solved your Problem ? I did not get it solved. Until recently everything was going great and suddenly not anymore. I have already checked the interfaces under Settings and also tried all 3 mDNS advertisers. Nothing helps.(/thezepter)

Hey thezepter,

yes, I was able to solve the problem.
My raspbarry pi has 3 ip addresses:
eth0 = 192.168.1.X
docker0 = 172.17.0.1/16 
vethxxxxx = X.X.X.X/16

The tips from [hjdhjd](https://github.com/hjdhjd) gave me the idea to use the ip address (Controller Address: 172.17.0.1) of docker [(look SCREENSHOT)](https://ibb.co/djBk3yg) the Homebridge-UniFi-Protect plugin.
After entering the docker ip address everything is automatically available.

Mikka

**Comment by thezepter** [comment]
I can not get the problem solved. Have already tried old HB versions. These also do not bring any remedy. What is also very strange is that the preview image of the cameras are displayed in Homekit. Only the livestream does not work.
