### ISSUE TITLE
API limits & high usage

### ISSUE THREAD

**Issue by shivanathd** [hjdhjd/homebridge-unifi-protect#816]
**Describe The Problem:**
I have 31 cameras and 7 Floodlights, and run my protect in a UNVR. I've been getting these errors in homebridge plugin for a while and thought it might resolve it self over few updates, but its now at a point where the plugin is getting these errors very often and I end up restarting it often as well. Granted, i do believe this particular error is something on the Unifi UNVR balckbox but wanted to bring this issue up to notice. 

I have run into this issue when i had the homebridge running on a macbook air M1 and now on the synolgy DSM as well. I have a separate local admin user for homebridge on unifi 
 
**To Reproduce:**
No specific steps as such. I have the system configured as per the Manual and only thing i can think of is the number of cameras and floodlights might be more than a typical homebridge user at home. 

**Logs:**

10/24/2022, 7:12:25 PM] [homebridge-unifi-protect] UNVR [UNVR4] Lift Cam [UVC G3 Instant]: The Protect livestream API has closed unexpectedly and will retry again shortly. This is usually due to a controller or camera restart and can be safely ignored.
[10/24/2022, 7:12:43 PM] [homebridge-unifi-protect] UNVR [UNVR4] Sitting area [UVC G3 Instant]: HomeKit Secure Video has recorded a 16 second motion event.
[10/24/2022, 7:12:43 PM] [homebridge-unifi-protect] UNVR [UNVR4] Sitting area [UVC G3 Instant]: HomeKit Secure Video event recording ended abnormally: The request timed out.

**Homebridge Configuration:**

{
    "controllers": [
        {
            "address": "192.168.1.142",
            "name": "UNVR",
            "password": "******",
            "refreshInterval": 60,
            "username": "homebridge"
        }
    ],
    "options": [
        "Enable.Audio.Filter.Noise",
        "Disable.Video.Stream.High",
        "Enable.Video.DynamicBitrate",
        "Enable.Video.Transcode"
    ],
    "_bridge": {
        "username": "0E:0D:4A:BB:DD:2E",
        "port": 41329
    },
    "platform": "UniFi Protect"
}

**Screenshots:**
![Screenshot 2022-10-24 at 7 20 36 PM](https://user-images.githubusercontent.com/1937549/197541847-ad227269-13b7-4b06-8c5b-aea12cd96b2f.png)

**Environment:**

* **Homebridge Version:**[v1.5.0]
* **Node Version:** 16.18.0
* **Homebridge-UniFi-Protect Plugin Version:** homebridge-unifi-protect v5.5.4
* **UniFi Protect Version:** Protect 2.2.6
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** UniFi OS UNVR 2.5.11
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iOS 16
* **Operating System and OS Version:** DSM 7.1.1-42962 Update 1

**Comment by shivanathd** [comment]
Always been a fan of yours .. i love the work you've put in and appreciate the response. 

Quick questions if I may

1. I can try and turn off HKSV and see if that helps 
2. I used to run it on a Macbook AIR M1 with 8 GB ram and it didnt peak memory / CPU but had still got the same issue hence tried moving to Synology 
3. I have 9 Homepod Minis, 2 Apple TV 4Ks (not the 2022 ones) , but if that might solve it i'm happy to get them, network wise i have Unifi AP AC Pros for each room and channel optimized so it shouldnt have an issue.. i tried even interference optimization. 
4. iOS 16 has been much better. I had also move to CiaO and even tried Avahi it was much better than Bonjour but the API limit reached issue was still there for me 

If i may ask, what is the system you're running ? have you come across any API limits for Unifi Protect 

Thank you so much for the swift response as always

**Comment by shivanathd** [comment]
<img width="703" alt="Screenshot 2022-10-24 at 10 11 01 PM" src="https://user-images.githubusercontent.com/1937549/197579830-c14b18ea-f22b-43f2-a0e5-fbbad2d7de9b.png">
Here's a quick snapshot of the network activity .. ( i don't know if it helps in addressing the bandwidth consumption angle)

**Comment by hjdhjd** [comment]
Thanks!

1. If you turn off HKSV...pretty sure that will fix things rather quickly I imagine. Then turn on HKSV one at a time and see when you reach the limit of what you're working with.
2. ...
3. Maybe? HomeKit is a black box I'm afraid...timeout messages like that are coming **from** the HomeKit hubs...and usually it's because they aren't being given data fast enough...put another way, it could be that the Synology is underpowered for what you're asking it to encode.
4. Ciao is definitely a better route to go these days.

There is no API limit error or issue in what you've mentioned above nor the log entries you shared...and there aren't API limits on the Ubiquiti end beyond not spamming the controller so it can't keep up, but that's not really an issue.

I run Homebridge on a 6-processor Xeon server...I wouldn't recommend it for most people, it's a monster of a power hog and very loud. I am eventually going to move it to an M2 Mac mini or Studio (when it's released) with a 10G network connection.

**Comment by shivanathd** [comment]
Thank you Boss.. i'll update the thread after i turn off HKSV and Turn them on one by one ...
