### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by the1maximus** [hjdhjd/homebridge-unifi-protect#818]
**Is your feature request related to a problem? Please describe:** NO

**Describe the solution you'd like:**
Support for USP-Plug and USP-Strip

**Describe alternatives you've considered:**
There is an alternative Plug-In but it is not verified. 

**Additional context:**
I would like to be able to control the UI Power devices such as the Smart Plug and Power Strip

**Comment by cjsfj** [comment]
I just logged in to see if there was support for this. +1

**Comment by the1maximus** [comment]
The other plug-in works well enough, but it’s
not verified.  I’d love to see it incorporated directly within this plug-in as an add on.

**Comment by hjdhjd** [comment]
As @cjsfj said, they aren’t part of Protect, and they’re out of scope of this plugin. I’ve got something else in the works for UniFi Network…but that’s for another day. Thanks for the request…best of luck. This will not be implemented in this plugin.
