### ISSUE TITLE
Audio files played through 2-way audio enabled cameras

### ISSUE THREAD

**Issue by bls8486** [hjdhjd/homebridge-unifi-protect#82]
Just a thought, and if it isn't of interest, please disregard.

While the AEC is being worked out and even after its figured out, I thought that it would be interesting to be able to play pre-recorded audio messages.  The workflow that I dreamed up would be similar to the switches exposed for text window messages.  I have noticed that the screen doesn't always get attention from those ringing the doorbell.  I hope that was clear and concise.

**Comment by hjdhjd** [comment]
Appreciate the feedback. I’ve got something similar on the backlog downstream. There are a few HomeKit-specific challenges to be worked out first. Stay tuned and thanks for taking the time to make a suggestion. 😄
