### ISSUE TITLE
Some motion events are not recorded

### ISSUE THREAD

**Issue by jhnvz** [hjdhjd/homebridge-unifi-protect#820]
**Describe The Problem:**
Thanks for writing this great plugin! Regarding the problem, some motion events are not recorded (with the default quality settings). When setting the quality to medium, everything is stable. I do, however, like to record in high quality since face recognition works way better this way. I did notice that when a motion event is detected with high-quality settings, I see CPU spikes of 97% utilization. When opening multiple streams (On Apple TV high, iPad medium) CPU utilization peaks at 7%. I'm trying to understand what's going wrong here:
1. What is so heavy about motion detection recording vs. opening streams?
2. Is my NAS underpowered to perform high quality recordings?
3. I also don't have the newest Apple TV (2020 model) could it be timing out on high-quality recordings?

**Network**
```
Cameras (GbE) => USW-Pro-24-POE Gen2 (10GbE) => UDMP (GbE) => NAS
                                                     (Gbe) => Apple TV
```

**To Reproduce:**
Jump in front of the camera, so motion gets detected.

**Logs:**
When jumping in front of the camera to trigger a motion event, I sometimes get this in the logs, I also notice high CPU spikes (97%) when recording a motion event:
```
[10/31/2022, 11:38:03 AM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: HomeKit Secure Video event recording ended abnormally: The request timed out.
```

When opening multiple streams from multiple devices CPU utilization peaks at 7%:
```
[10/31/2022, 12:07:55 PM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: Streaming request from 192.168.1.243: 1920x1080@30fps, 802 kbps. Using 3840x2160@24fps (High), 16000 kbps.
[10/31/2022, 12:08:02 PM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: Streaming request from 192.168.1.21: 1920x1080@30fps, 802 kbps. Using 3840x2160@24fps (High), 16000 kbps.
[10/31/2022, 12:08:11 PM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: Streaming parameters adjustment requested by HomeKit: 1280x720, 30 fps, 299 kbps.
[10/31/2022, 12:08:13 PM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: Streaming request from 192.168.1.243: 1280x720@30fps, 299 kbps. Using 1280x720@24fps (Medium), 4000 kbps.
[10/31/2022, 12:08:15 PM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: Streaming parameters adjustment requested by HomeKit: 640x360, 30 fps, 132 kbps.
[10/31/2022, 12:08:19 PM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: Streaming parameters adjustment requested by HomeKit: 640x360, 30 fps, 132 kbps.
```

**Homebridge Configuration:**

```json
{
  "bridge": {
      "name": "Homebridge BC33",
      ...
      "bind": [
          "eth1"
      ]
  },
  "accessories:" [
    ...
  ],
  "platforms": [
      {
          "name": "Config",
          "port": ****,
          "platform": "config"
      },
      {
        "controllers": [
            {
                "address": "*.*.*.*",
                "password": "**********",
                "refreshInterval": 5,
                "username": "**********"
            }
        ],
        "motionDuration": 5,
        "platform": "UniFi Protect",
        "_bridge": {
            "username": "**:**:**:**:**:**",
            "port": ****
        }
    },
    ...
  ]
}
```

**Environment:**

* **Homebridge Version:** 1.5.0
* **Node Version:** 14.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.12.30
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Apple TV 4K (A1842), tvOS 16.0
* **Operating System and OS Version:** Docker on Synology NAS (DS1019+)

**Comment by jhnvz** [comment]
Sometimes I'm also getting this error: `[10/31/2022, 2:53:57 PM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: HomeKit Secure Video event recording ended abnormally: An unexpected protocol failure has occured.`

**Comment by hjdhjd** [comment]
@jhnvz Your welcome, appreciate the feedback!

1. Nothing is heavy about motion detection in and of itself. However, when you are using HomeKit Secure Video, which you seem to be above...video will be transcoded before it's sent to HKSV. There's no avoiding this requirement due to the specific requirements Apple has for HKSV streams. You can read more in the [documentation under the HomeKit Secure Video section](https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/HomeKitSecureVideo.md).
2. Yes. Especially if you want to start with a higher quality stream. But the quality of the stream is somewhat less relevant if you're using HKSV...HKSV streams are lower quality - this isn't a user-configurable item...it's a black box, like many Apple things. 😄 Medium is a good compromise if you're on underpowered systems as a starting point...though I use high quality starting streams and have 20+ HKSV-enabled cameras...but running on a pretty beefy server.
3. Nope. **Streaming** video isn't the same as processing motion events in an HKSV context. Streaming video isn't transcoded, and should be zippy. If you're seeing a reduction in performance, it's likely due to your use of HKSV on an underpowered system that's struggling to keep up.
4. Occasional HKSV errors are par for the course...nothing to worry about.

Best of luck.

**Comment by jhnvz** [comment]
Thanks for the quick response @hjdhjd! Got it, so the transcoding for HKSV is really CPU intensive. My high-quality streams are snappy and don't create much CPU load when requested. Weird that if I set the stream quality to Medium, I don't see those spikes when an HKSV motion event occurs. Just out of curiosity, what kind of hardware are you using?

> Occasional HKSV errors are par for the course...nothing to worry about.

So I don't need to worry about errors like this:
```
[10/31/2022, 2:53:57 PM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: HomeKit Secure Video event recording ended abnormally: An unexpected protocol failure has occurred.
[10/31/2022, 11:38:03 AM] [homebridge-unifi-protect] Home [UDM-PRO] Front door [UVC G4 Pro]: HomeKit Secure Video event recording ended abnormally: The request timed out.
```

If that's the case, feel free to close this issue :)

**Comment by jhnvz** [comment]
Also good to know that the quality settings don't impact recording and face recognition, thanks for explaining

**Comment by hjdhjd** [comment]
Think multi-CPU Xeon server, in my case...but I have different needs than most. 20+ G4 Pros is a lot of data to crunch.

The difference in size/complexity/quality from a UniFi camera between medium and high, especially for devices like the G4 Pro is quite substantial. A high quality stream from a G4 Pro is 4K, essentially. A medium quality one is 1080p...that's a 4x delta in data to be crunched/transcoded. Suffice it to say, that's likely the reason for the differential in CPU utilization.

You'll see fewer HKSV-related errors, in general, if you have a server that can keep up with demand when HKSV requests a video stream...they can be safely ignored. 😄 

Cheers.
