### ISSUE TITLE
Cams work on Wifi but no stream over ethernet

### ISSUE THREAD

**Issue by MiOrt** [hjdhjd/homebridge-unifi-protect#823]
**Describe The Problem:**
All cams work as expected using Wifi or LTE connection (on all iOS devices and on MacBook). However on my stationary Mac mini and my ATV I only see the preview in the home app and when trying to connect to cam for stream it says "No answer - cam is not responding". When closing the stream-window the little previews of the not jet clicked cams update every 10 seconds. The previews of the clicked cams stay with the crossed cam icon and "no answer".

**To Reproduce:**
Start home app while using WiFi/LTE everything works. Start home app on devices using ethernet to connect to cam for stream it says "No answer - cam is not responding" 

**Logs:**
-

**Homebridge Configuration:**

{
            "controllers": [
                {
                    "address": "192.168.0.1",
                    "password": "...",
                    "username": "..."
                }
            ],
            "options": [
                "Enable.Motion.SmartDetect",
                "Enable.Doorbell.Trigger"
            ],
            "_bridge": {
                "username": "0E:77:82:65:D5:24",
                "port": 36559
            },
            "platform": "UniFi Protect"
        }

**Screenshots:**
![Screenshot 02 11 2022 um 16 41 54 PM](https://user-images.githubusercontent.com/31467468/199534599-40f483de-fbfb-4e98-b8a2-649e34418559.png)

**Environment:**

* **Homebridge Version:** 1.5.1
* **Node Version:** 16.18.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** UniFi OS UDM Pro 1.12.30
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPadOS 16, iOS 16.1, MacOS 13.0, tvOS 16.0
* **Operating System and OS Version:** Docker on Synology DSM 7.1

**Comment by hjdhjd** [comment]
Homebridge issue, not a plugin issue. 😄 You haven’t told Homebridge which interface to use.

Please review the troubleshooting documentation:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/Troubleshooting.md#network-issues
https://github.com/homebridge/homebridge/wiki/mDNS-Options#how-to-select-advertised-network-interfaces

**Comment by MiOrt** [comment]
Thanks for you answer. However I reviewed the settings (indeed overlooked this interface thing since everything worked for years without problems), changed to the docker-interface 192.168.0.19, copied this setting from HB-bridge config to child bridge, changed to all other interfaces, tried all advertiser... same behaviour (except that the cams are not reachable at all if I don't select the bond0-docker-interface 192.168.0.19. Every device (iPad, iPhone, Mac, aTV, HomePods) is on the same network.

**Comment by hjdhjd** [comment]
I know it’s an unsatisfying answer but this really is not a plugin issue, and what you’re describing closely follows a Homebridge quirk (although it’s not really their fault either…) that’s well-known when dealing with multiple interfaces. Try running things outside of Docker to start eliminating variables…I don’t run Docker, so this is as far as I can help you I’m afraid.

In my experience, things don’t just stop working…if you had a working setup previously, something, perhaps seemingly innocuous, changed…a setting, WiFi enabled/disabled somewhere, a software update. Things don’t just mysteriously stop working…now as to what changed…can’t help you there. 😄

Best of luck.

**Comment by MiOrt** [comment]
Hi, just a follow up... nothing "just stopped working", I just setup the plugin and the problem occurred right away. I moved Homebridge from Synology Docker to a Raspberry Pi4 already running for other things and took a backup to transfer everything. Problem persisted. I then deleted the Protect-Plugin, cleared the protect devices fron the cache and started over. I also restarted the ATv. Now the cams work as expected everywhere except my Mac Mini, and two-way-audio to doorbell also now works (wasn't before, only working through Unifi-app). I have no idea what prevents the stream from working on the Mac since all other devices accept it without a problem. I discovered these lines in the ffmpeg verbose log... having no idea what is stopping the stream:

`...
Stopped video streaming session.
...
Exiting normally, received signal 15.` 

This is happening when I try to start the stream from my Mac Home app. The moment the "stopped" log is generated the Home app shows the "no answer" line.

**Comment by MiOrt** [comment]
Thanks for your replay. Not sure if I get it right... do I have to do this on the mac trying unsuccessfully to access the stream or the pi running Homebridge? I'm asking because my iPad is also a M1 version and the stream runs perfectly.

In any way could you be so kind and please specify where to put in the path (especially if it has toi be done on the mac)?
