### ISSUE TITLE
Home App Status LED revert on Homebridge restart

### ISSUE THREAD

**Issue by whardy15** [hjdhjd/homebridge-unifi-protect#824]
**Describe The Problem:**
The camera status LED light resets to on in the Home app after each restart of Homebridge.  While I've read this is expected behavior because of a bug in the Home app, I was hoping there might be a disable option in the Homebridge Unifi Plugin that would disable passing through the status LED feature - so it could be controlled reliably through the Protect app.

**To Reproduce:**
Open Home app, turn off the Status LED light.  Restart the Homebridge app through UI.  Open Home app the Status LED light will be turned back on.

**Environment:**

* **Homebridge Version:** 1.5.1
* **Node Version:** v16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** v5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** 2.5.11
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 14 Pro, 16.0.2
* **Operating System and OS Version:** Synology Package

**Comment by hjdhjd** [comment]
There will be an upcoming release this year (I hope) related to this. Thanks.

**Comment by whardy15** [comment]
Thanks!
