### ISSUE TITLE
All cams get doorbell trigger, not just the doorbell

### ISSUE THREAD

**Issue by MiOrt** [hjdhjd/homebridge-unifi-protect#825]
**Describe The Problem:**
Having a Doorbell G4 I set the feature switch "Enable.Doorbell.Trigger". After HB restart ALL cams within Home app get the doorbell trigger (can also see them in "devices" at the HB UI).

This somehow prevented my ATv from automatically show who is on the door once it rings. On all cams except the G4 Doorbell I had to turn off "Notification upon ring" to get this to work as expected.

**To Reproduce:**
Set the feature switch "Enable.Doorbell.Trigger"

**Logs:**
-

**Homebridge Configuration:**
-

**Screenshots:**
-

**Environment:**

* **Homebridge Version:** 1.5.1
* **Node Version:** 16.18.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** UniFi OS UDM Pro 1.12.30
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPadOS 16, iOS 16.1, MacOS 13.0, tvOS 16.0
* **Operating System and OS Version:** Docker on Synology DSM 7.1

**Comment by hjdhjd** [comment]
Please read the documentation on feature options. You can selectively choose which camera gets a trigger. Thanks.

**Comment by MiOrt** [comment]
Sorry for bothering... was unable to fully understand how to set it up by reading the docs (not a native speaker) and did not get the mac-address-part right. Kept on trying and now it seems to be working as expected. Thanks!
