### ISSUE TITLE
G4 Pro Blue Status Light Keeps re-enabling even after turning it off in the Home App & Ubiquiti Protect in iOS 16

### ISSUE THREAD

**Issue by MikeParkinWits** [hjdhjd/homebridge-unifi-protect#831]
**Describe The Problem:**
I have read through the documentation, and troubleshooting tab, and continue to have the blue status light re-enabled itself after a couple of hours. When disabling the status light in the Home App, it reflects that it is disabled in Protect but then re-enables itself soon thereafter. The only remedy is disconnecting the plugin all together. I presume this might have something to do with iOS 16 and the redesigned HomeKit framework.

**To Reproduce:**
1) Using a device running iOS 16, for the new HomeKit framework, disable the status light on a G4 Pro camera in the Home App.
2) Confirm that it is disabled in Protect and physically
3) Wait a couple hours (sometimes it happens in less than an hour, and sometimes only a full 24 hours later) and check whether the status light has turned itself back on.

**Logs:**
N/A for this issue

**Homebridge Configuration:**
N/A for this issue

**Screenshots:**
N/A for this issue

**Environment:**

* **Homebridge Version:**  v1.5.1
* **Node Version:**  v16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** v5.5.4
* **UniFi Protect Version:**  Protect 2.2.6
* **UniFi Protect Controller Type:**  UNVR
* **UniFi Protect Controller Firmware Version:**  UniFi OS 2.5.11
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone's & iPad's on iPadOS/iOS 16.1
* **Operating System and OS Version:**  Raspbian

**Comment by hjdhjd** [comment]
Asked and answered elsewhere. Thanks!

#829
