### ISSUE TITLE
Help for different notification settings

### ISSUE THREAD

**Issue by MiOrt** [hjdhjd/homebridge-unifi-protect#833]
**Describe The Problem:**
I need some advice concerning the notification settings in HomeKit. I can set up notifications for motion or for certain motion types (and have several choices here). I am unsure what notifications get triggered by Protect and what are notification triggers by HomeKit? I already enabled the smart detection feature in the plugin but am a bit confused here... i. e. I only use smart detections on my g4 cams and already set them up on the UDMP, is it correct that only setting the notifications to "motion" is correct here. So I don't have to duplicate the "smart choices" like people and vehicle by choosing "certain motions"?

**To Reproduce:**
-

**Logs:**
-

**Homebridge Configuration:**
-

**Screenshots:**
-

**Environment:**

* **Homebridge Version:** 1.5.1
* **Node Version:** 16.18.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** UniFi OS UDM Pro 1.12.30
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPadOS 16, iOS 16.1, MacOS 13.0, tvOS 16.0
* **Operating System and OS Version:** Debian GNU/Linux Bullseye (11) on Raspberry Pi 4

**Comment by hjdhjd** [comment]
The defaults are correct for most users...things should "just work". Using the additional feature options available to you is an advanced activity and I'd refer you to the documentation for more details.

If you're trying to use the more sophisticated settings in HomeKit for object notification (animals, people, vehicles, etc.)...that's a completely independent system wherein HomeKit analyzes and decides what's worthy of notification and completely bypasses anything from the Protect controller.

Read through the documentation on HomeKit Secure Video, which elaborates how notifications work between the two:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/HomeKitSecureVideo.md#interactions-with-unifi-protect-smart-motion-detection

Read through the best practices documentation for additional tuning considerations:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/BestPractices.md

Hope this helps and best of luck. There's a lot of good documentation to go through that will help you get up and running.
