### ISSUE TITLE
Be more verbose for MQTT?

### ISSUE THREAD

**Issue by alexdie** [hjdhjd/homebridge-unifi-protect#834]
**Is your feature request related to a problem? Please describe:**
When having both normal motion zones and smart detection zones configured on a camera, [this line](https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/src/protect-nvr-events.ts#L528) prevents MQTT events from being published for smart detections most of the time, as a normal motion event usually is already inflight when a smart detection happens.

The safeguards against spamming motion events that are likely caused by the same thing make perfect sense for HomeKit integration.

However, when using MQTT, I'm interested in every event. If I don't want both the motion and the smart detection event I either don't subscribe to both or filter them further down the line.

In my specific use case I want to turn on porch lights on smart detections of persons or vehicles. This prevents spiders in front of the camera from turning on the porch lights in the middle of the night, which is great. I still have motion zones configured on the same camera for other recording purposes, but those currently break the MQTT notifications for smart detections.

**Describe the solution you'd like:**
Publish MQTT events earlier, without consideration for potential duplicate events. 
In the "worst case", both motion and smart detection are set to true at the same time. Even though this is a behavior change, considering that smart detections currently only work properly if there are no normal motion zones configured, this change is unlikely to break existing setups. What do you think?

**Describe alternatives you've considered:**
Check Motion and Smart Detection events or duplicates separately. Same as above, it's not like you can use both right now. Although this might spam things on the HomeKit side, I'm not sure.

**Additional context:**
I'm only using the plugin for it's MQTT functionality. I don't have homebridge registered in HomeKit, but this doesn't seem to cause any issues or behavior change.

Thank you for the plugin, it's already very useful 👍

**Comment by hjdhjd** [comment]
Thanks for the suggestion and explaining the use case...I'll consider it for the future.

**Comment by hjdhjd** [comment]
You’ve now got access to the complete telemetry that the Protect controller produces through MQTT, published under the `telemetry` topic, so you can do stuff like this to your heart’s content. You need to explicitly enable the feature option for it, and be warned, it’s a lot of data…but you can do this now in v6. Enjoy!

**Comment by hjdhjd** [comment]
@alexdie One more followup to this one - as of v6.13, the modernized motion event delivery I've had in testing for quite some time is now live, and the behavior should default to delivering motion events with more granularity (e.g. more verbosely) over MQTT. Cheers.
