### ISSUE TITLE
FFmpeg not found

### ISSUE THREAD

**Issue by lanyar** [hjdhjd/homebridge-unifi-protect#841]
**Describe The Problem:**
Nothing has changed recently by myself. Not sure what may have changed in the environment with regards to firmware releases or updates but recently streaming from HomeKit has stopped working. Now seeing

`[UniFi Protect] Unable to find FFmpeg at: '/homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg'. Please make sure that you have a working version of FFmpeg installed.`

**To Reproduce:**
Nothing done to change behaviour that I am aware of

**Logs:**

```
[UniFi Protect] Unable to find FFmpeg at: '/homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg'. Please make sure that you have a working version of FFmpeg installed.
```

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge EDB3",
        "username": "username",
        "port": 53832,
        "pin": "thepin"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "ipaddress",
                    "password": "password",
                    "username": "user"
                }
            ],
            "options": [
                "Disable.Video.HKSV"
            ],
            "platform": "UniFi Protect"
        },
        {
            "name": "Flo-by-Moen",
            "auth": {
                "username": "username",
                "password": "password"
            },
            "disableCache": false,
            "showTemperatureAndHumidity": true,
            "enableValveControl": false,
            "showHealthTestSwitch": false,
            "treatWarningAsCritical": false,
            "deviceRefresh": 90,
            "sleepRevertMinutes": 120,
            "platform": "Flo-by-Moen"
        }
    ],
    "disabledPlugins": []
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.5.1
* **Node Version:** 18.12.1
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 1.12.33
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 16.1.1
* **Operating System and OS Version:** 13.0.1

**Comment by hjdhjd** [comment]
Try uninstalling and reinstalling the plugin. The error is indicating that the prebundled FFmpeg that Homebridge plugins can use isn’t installed correctly for some reason. No idea why…but there you have it. Reinstalling the plugin should force all the dependencies to refresh.

Best of luck!

**Comment by lanyar** [comment]
Problem resolved - thank you!
