### ISSUE TITLE
Camera Motion Not Reporting to HomeKit Motion Sensors Reliably

### ISSUE THREAD

**Issue by e-pilot** [hjdhjd/homebridge-unifi-protect#842]
**Describe The Problem:**
Motion from G3/G4 cameras not being reflected in HomeKit reliably, works approximately 25-50% of the time, all motion events are being logged as expected by the UCKgen2+

**To Reproduce:**
observe motion sensors in homekit app when they should be triggered by motion

**Homebridge Configuration:**

```json
            "controllers": [
                {
                    "address": "*removed*",
                    "doorbellMessages": [
                        {
                            "duration": 0,
                            "message": "HELLO THERE"
                        }
                    ],
                    "password": "*removed*",
                    "refreshInterval": 5,
                    "username": "*removed*"
                }
            ],
            "motionDuration": 10,
            "ringDuration": 3,
            "_bridge": {
                "username": "0E:7A:CB:70:69:B4",
                "port": 57215
            },
            "platform": "UniFi Protect"
```

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** 18.12.1
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 2.5.11
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 16.1.1 HomePod 16.1
* **Operating System and OS Version:** Ubuntu 20.04.5 LTS

**Comment by hjdhjd** [comment]
If you’re using G4 cameras, they will default to using the smart motion detection capabilities in the G4 series. If your intention is to get **all** motion events, see the feature option documentation around explicitly disabling smart motion detection. ‘

On G3 cameras, given their lack of smart motion detection, the defaults are to capture all motion. This is all documented, and I’d encourage you to spend some time in the plugin documentation if you haven’t already. There’s a lot you can configure, if you choose to do so.

Beyond that, if you have a specific, reproducible issues, then please provide the details. Just opening a report with “things sometimes don’t work the way I expect” isn’t a good path to helping you troubleshoot what’s going on. 😄
