### ISSUE TITLE
Liveview Camera View

### ISSUE THREAD

**Issue by CochiseFugue** [hjdhjd/homebridge-unifi-protect#843]
If there is any way to accomplish it, it would be insanely beneficial to actually get saved Liveview grids to be visible as a 'camera'  in HomeKit. 

The current AI 360 cameras are fantastic, but truly benefit from the Liveview grids since you can save multiple dewarped 'angles' from a single camera. 

As it currently stands, the video feed from an AI 360 works perfect, but since it is not being viewed via Liveview in dewarped grips, it only shows as the warped 360 degree fisheye 'bubble'.

Finding a way to get a feed from saved Liveview grids via homebridge-unifi-protect to HomeKit, even if using an intermediary process, would be a huge feature enhancement.

**Comment by swilalaa** [comment]
bump - this feature would be great to have!
