### ISSUE TITLE
Secure Video only records when stream is set to low

### ISSUE THREAD

**Issue by mtvan** [hjdhjd/homebridge-unifi-protect#845]
**Describe The Problem:**
Secure video only records when Enable.Video.Stream.Only.Low is enabled.  Medium and high result in no recordings but it streams just fine

**To Reproduce:**
Connect camera, enable everything and see if it records on high

**Logs:**
n/a

**Homebridge Configuration:**
n/a

**Screenshots:**
n/a

**Environment:**

* **Homebridge Version:** v1.6.0
* **Node Version:** v16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.6.17
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** v3.0.13
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 16.1
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Thanks for the report. Please read the documentation related to HKSV - you’re running on a massively underpowered device if you’re trying to do HKSV.

Best of luck.
