### ISSUE TITLE
Turning off status light in Home app does not persist

### ISSUE THREAD

**Issue by scclemens** [hjdhjd/homebridge-unifi-protect#849]
The documentation states `you are forced into having to turn off the camera status light, in the Home app in order to have a setting that sticks.`

This does not work. I have turned off the status light _in both the Home app and in Unifi Protect_ and the status lights all get turned back on again less than 12 hours later.

**Comment by disruptivepatternmaterial** [comment]
Yes I'd like to see this reopened as it is still an issue.

**Describe The Problem:**
see the initial issue

**To Reproduce:**
open a camera in HomeKit and try to disable the light, it doesnt "stick"

**Logs:**

nothing appears in the homebridge logs when I turn the light on and off in home app

**Homebridge Configuration:**

Nothing unusual at all - very vanilla config

**Screenshots:**

There is nothing here to share

**Environment:**

* **Homebridge Version:** v1.6.0
* **Node Version:** [v18.13.0](https://homebridge.io/w/JTKEF)
* **Homebridge-UniFi-Protect Plugin Version:** homebridge-unifi-protect v5.5.4
* **UniFi Protect Version:** Protect 2.7.15
* **UniFi Protect Controller Type:** UNVR
* **UniFi Protect Controller Firmware Version:** UNVR v3.0.13
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**13.0.1 (22A400)
* **Operating System and OS Version:** 13.0.1 (22A400)
