### ISSUE TITLE
Question: eliminate Microphone accessories

### ISSUE THREAD

**Issue by jasonlboggs** [hjdhjd/homebridge-unifi-protect#851]
**Describe The Problem:**
I have a wide array of ubiquity cameras and each camera in Homebridge creates both Microphone and Motion Sensor accessories.  Each device receives the same name, for example, "Garage".  I want to pass the Motion Sensor to Alexa using `homebridge-alexa`.  If I set up the `hombridge-alexa` plugin to allow it to send "Garage" to Alexa, it passes both the Microphone and Motion Sensor, since they have the same name.  There seems to be no way to differentiate between the Garage Motion Sensor and the Garage Microphone.

My quesion is this: Is it possible to either
A) Eliminate the "Microphone" accessory for cameras
B) Rename the accessories so their names are "Garage Microphone" and "Garage Motion Sensor"

Either of these solutions would be acceptable, but my preference would be to eliminate the Microphone accessories across the entire protect plugin.  Is there a `Disable.*` option I can use?  Renaming them on these screens has no impact.

![image](https://user-images.githubusercontent.com/38923495/207209372-5acf0be7-8c2a-407e-a82f-541919139885.png)

![image](https://user-images.githubusercontent.com/38923495/207209435-8ebc1467-e48b-4e1d-840f-10a4e832d9fd.png)

**To Reproduce:**
Setup the plugin and add one camera

**Logs:**
N/A

```

```

**Homebridge Configuration:**

```json
{
            "controllers": [
                {
                    "address": "IP",
                    "password": "password",
                    "username": "username"
                }
            ],
            "options": [
                "Disable.Doorbell.Messages",
                "Disable.Audio.TwoWay",
                "Disable.Video.HKSV",
                "Disable.Doorbell.Messages.FromDoorbell"
            ],
            "_bridge": {
                "username": "username",
                "port": port
            },
            "platform": "UniFi Protect"
        }
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** `1.6.0` 
* **Node Version:** `v16.18.1` 
* **Homebridge-UniFi-Protect Plugin Version:** `v5.5.4`
* **UniFi Protect Version:** `2.6.17` 
* **UniFi Protect Controller Type:** UNVR 
* **UniFi Protect Controller Firmware Version:** `UNVR v3.0.13` 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** `iOS 16.1.1` 
* **Operating System and OS Version:**  Ubuntu 20.04

**Comment by hjdhjd** [comment]
Sorry I don't provide support for someone else's plugins. As to the accessory names - you can always change the names to whatever you'd like in the Home app. There's certainly no restriction there.

Beyond that there's not much more I can say here. Thanks!
