### ISSUE TITLE
Disable chime via HomeKit  

### ISSUE THREAD

**Issue by koaxfr** [hjdhjd/homebridge-unifi-protect#854]
**Is your feature request related to a problem? Please describe:**
 No

**Describe the solution you'd like:**
Hi,

First off, great plugin, honestly everything went so smoothly it’s really nice for a change. 

I’m wondering if there’s any way to disable the chime via HomeKit, a little bit like a do not disturb type of option. 

For now I simply toggle between no chime and mechanical chime to do so but would be nice to automate the process via HomeKit. 

Your help is greatly appreciated!

**Describe alternatives you've considered:**
Making a little controller or “smart relay” to control the chime separately via HomeKit only. 

**Additional context:**

**Comment by hjdhjd** [comment]
Appreciate the feedback. Will consider this for a future update…appreciate the suggestion, I just need to clear a few other things off the backlog first.

**Comment by leppert** [comment]
Just wanted to add a +1 to this feature and also thank you for ann amazing plugin.

**Comment by hjdhjd** [comment]
Implemented in v6.2.0. Enjoy.
