### ISSUE TITLE
Reply to Doorbell Push / Motion with Pre Recorded Message

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [hjdhjd/homebridge-unifi-protect#855]
**Is your feature request related to a problem? Please describe:**
I am surprised how many people do not realize the unifi doorbells are doorbells. I see video of people looking at them, talking to them, and other curious behavior. Or they just keep pushing the button even though I put a message on the doorbell stating I am busy. As someone who works from home, I am often busy and just need the person to wait or comeback.

**Describe the solution you'd like:**
What would be very useful is a way to put some mp3's on my home bridge setup that I can push a button in HomeKit and play or even setup to play automatically when a human is detected or when someone pushes the ring button. I would just push a button while on a call that says "I'll be right down!" This would also be an interesting security feature because I could trigger a message if someone is in my backyard when they shouldn't be.

**Describe alternatives you've considered:**
Putting up a sign that says I work from home, that doesnt mean I can come to the door, please ring the doorbell to your left, yes that is a doorbell"

**Additional context:**
none

**Comment by hjdhjd** [comment]
This is well beyond the scope of this plugin…sorry, this won’t be worked on. Thanks for the suggestion, just the same!
