### ISSUE TITLE
HomeKit Camera Active: 0

### ISSUE THREAD

**Issue by skosow** [hjdhjd/homebridge-unifi-protect#857]
**Describe The Problem:**
I installed a G4 Instant, I have 5 other cameras working through home bridge. It shows up in Homebridge but shows HomeKit Camera Active = 0 in the operating mode accessory.

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 1.6.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** Cloud Key Plus 3.0.13
* **UniFi Protect Controller Type:** Cloud Key Gen2 Plus
* **UniFi Protect Controller Firmware Version:** Cloud Key Plus 3.0.13
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**16.2
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
Thanks for the report, but I have no idea what you’re trying to report. 

“HomeKit Camera Active: 0” doesn’t really mean anything to me. If you’ve got a specific bug or issue to report, please provide the relevant details and specifics.

**Comment by cjsfj** [comment]
This sounds like the bug I just reported #858
