### ISSUE TITLE
Exposing Connect Panel On/Off at Switches

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [hjdhjd/homebridge-unifi-protect#862]
**Is your feature request related to a problem? Please describe:**

Connect related, but I use my connect panels to display protect cameras in my home: there is no easy way to turn the panels off at night and on in the morning. It would also be wonderful if I could get them to go to a camera on motion or camera set (view) on startup (which are obvious features that unifi should implement, but here we are...)

**Describe the solution you'd like:**

I'd like to see switches in HomeKit for the panels to be turned on and off.

**Describe alternatives you've considered:**
MQTT path for each panel, exposed as a switch using MQTTThing, that when a 1/0 is received I then PATCH to /proxy/connect/api/v2/devices/***SOME ID***/status with the body of

{"id":"***SOME OTHER ID***","name":"display_on","args":{}}

To be clear the SOME ID seems to be some internal it of the panel, while the SOME OTHER ID is something else all together and is different than the SOME ID and is different for each panel (I have 3).

I snooped all this in Firefox and used the urls and bodies; and it worked. Off is display_off in name. I'd be happy to send more detailed exact examples and logs if it would be helpful.

Something I haven't figured out is how to get the state of the panel, I am working on that, but all I have to do is flip the HomeKit switch a couple times just in case right now, but it works. I did this in node-red, but was going to then do it in python at some point.

**Additional context:**
/proxy/network/wss/s/default/events is how I snooped some of this and is likely the key to finding out the status.

**Comment by hjdhjd** [comment]
Thanks for the suggestion - stay tuned.
