### ISSUE TITLE
HTTP stream out of the HomeKit plugin?

### ISSUE THREAD

**Issue by beef76** [hjdhjd/homebridge-unifi-protect#871]
**Describe The Problem:**

Plug-in working smoothly with HomeKit! Great work and many thanks. 
but I’m also looking for a solution to get a non rtsp stream opened via browser. Would it be possible to call up any Liveview from the plug-in using a browser? 

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
That's out of scope for the plugin and isn't supported by Protect. You can pull individual camera streams from HBUP.
