### ISSUE TITLE
Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges.

### ISSUE THREAD

**Issue by etcook** [hjdhjd/homebridge-unifi-protect#875]
**Describe The Problem:**

After migrating to a UDM SE (on Unifi OS 3.0) from UDM, I now get the following error message with a locally created user:

Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges.

**To Reproduce:**

- create new user on Unifi US 3.0
- utilize the user and password in the homebridge config

**Logs:**

```
[2/2/2023, 8:22:17 PM] [homebridge-unifi-protect] Insufficient privileges for this user. Please check the roles assigned to this user and ensure it has sufficient privileges.
```

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge 43CE",
        "username": "xx",
        "port": xx,
        "pin": "xx",
        "advertiser": "bonjour-hap",
        "bind": [
            "ovs_bond0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": xx,
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "xx",
                    "password": "xx",
                    "username": "xx"
                }
            ],
            "_bridge": {
                "username": "xx",
                "port": xx
            },
            "platform": "UniFi Protect"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.6.0
* **Node Version:** v16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** v5.5.4
* **UniFi Protect Version:** 2.7.25
* **UniFi Protect Controller Type:** UDM SE
* **UniFi Protect Controller Firmware Version:** v3.0.13
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 16.3
* **Operating System and OS Version:** Homebridge on Synology

**Comment by hjdhjd** [comment]
You need to ensure you provide administrative privileges for the local user you created. You can do that by changing the role assigned to the local user under the Admins tab on your UniFi console.

Best of luck!

**Comment by etcook** [comment]
@hjdhjd Hi there! I did, indeed, already have admin privileges on the user, but it was still giving the error. However, it seems to have worked itself out over time, though, and now works. Not sure why there was a delay or why it didn't work initially. Thanks for your work!

**Comment by hjdhjd** [comment]
Thanks for the data point...truly odd. Appreciated and stay tuned for more goodness coming from HBUP.

**Comment by eleventhaus** [comment]
Getting this same error despite making sure that the local user has full management privileges. Guess I will just have to wait until unifi magically works itself out.

**Comment by hjdhjd** [comment]
One person, one issue please @eleventhaus. If you’d like support, open a new issue or feel free to use the support channel on Discord.
