### ISSUE TITLE
Unifi Protect BridgeUniFi ProtectNo UniFi Protect login credentials have been configured.

### ISSUE THREAD

**Issue by stig44** [hjdhjd/homebridge-unifi-protect#878]
**Describe The Problem:**
Unable to Configure the Hoobs for Unifi Protect because I am getting the error of no login credentials have been configured. 
I have tried connecting to the IP address without 7443 and I get the same results. I am able to connect to the IP address from a PC with the same login credentials as in the configuration. 

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
![image](https://user-images.githubusercontent.com/124536891/216854332-577dd191-da0b-4b36-a550-8bdcc3897a0a.png)

```

**Homebridge Configuration:**
![image](https://user-images.githubusercontent.com/124536891/216853213-7aef939a-ff3d-4124-a8c6-bdd8ec18510e.png)

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/124536891/216854357-139e50d4-f4a7-4ca3-9db4-ee00f25576b3.png)

**Environment:**

* **Homebridge Version:** 1.5.0
* **Node Version:** 16.19.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:**  UDMP
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 16.3
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/AdvancedOptions.md

You specified a port along with an IP address. Please review the documentation for the correct way to specify it, if you have a question.
