### ISSUE TITLE
Unifi Protect BridgeUniFi Protect No UniFi Protect login credentials have been configured.

### ISSUE THREAD

**Issue by stig44** [hjdhjd/homebridge-unifi-protect#880]
**Describe The Problem:**
Unable to Configure the Hoobs for Unifi Protect because I am getting the error of no login credentials have been configured.
I am able to connect to the IP address from a PC with the same login credentials as in the configuration.

**To Reproduce:**

**Logs:**

![image](https://user-images.githubusercontent.com/124536891/216993170-b99e69e5-445b-4177-872a-22d3109c54ae.png)

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**
![image](https://user-images.githubusercontent.com/124536891/216993480-a36aa7d2-ae64-44e1-9820-5f438994893d.png)

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/124536891/216993187-d68cd861-8325-4b79-9bb6-e2a1c35dcfc4.png)

**Environment:**

* **Homebridge Version:** 1.5.0
* **Node Version:** 16.19.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**16.3
* **Operating System and OS Version:**  Raspbian

**Comment by hjdhjd** [comment]
**Again - please read the documentation. Your options are incorrect. Please do not open issues without thoroughly reading through the documentation.**

You do not have a username specified.
