### ISSUE TITLE
Status light on g4 instant being turned on by plug-in 

### ISSUE THREAD

**Issue by Claywd** [hjdhjd/homebridge-unifi-protect#884]
**Describe The Problem:**

I got a new g4 instant that I started using as a baby monitor and I’m having this recurring issue where I turn off the status light in UniFi protect but the logs on your plug-in say it’s turning it back on.

I checked the optional features documentation and didn’t see anything about the status light. Can you provide some guidance?

**To Reproduce:**
no idea. Get a g4 instant, hook it up the plug-in , turn off the status light in protect and wait 24-72 hours and watch the plug-in turn it back on and log the action. 

**Logs:**

```
I had none yet… they erase too quickly. 
```

**Homebridge Configuration:**

```json

{
            "controllers": [
                {
                    "address": "10.0.1.1",
                    "doorbellMessages": [
                        {
                            "duration": 60,
                            "message": "Leave pkg and ring"
                        },
                        {
                            "message": "Welcome Home!"
                        }
                    ],
                    "password": "",
                    "username": ""
                }
            ],
            "platform": "UniFi Protect"
        },

```

**Screenshots:**

**Environment:**
Prod? 
* **Homebridge Version:** 1.6.0
* **Node Version:** 16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 2.2.6 
* **UniFi Protect Controller Type:** uDMP
* **UniFi Protect Controller Firmware Version:** 2.2.27 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**ios
* **Operating System and OS Version:** free bsd 13.1-release-p2

**Comment by Claywd** [comment]
It’s also worth noting, that the plug-in isn’t adding this camera to HomeKit either. No idea why.

**Comment by Claywd** [comment]
Nevermind. I finally got the camera added to HomeKit and turned off the status light which is enabled by default. Apparently, it has to be turned off in HomeKit and if it is not, the plug-in will just turn it back on. 

Also, fyi, names are not syncing from protect to HomeKit. Seems like synchronization of meta data is off a tad.

**Comment by hjdhjd** [comment]
Glad you got it solved. FYI, related to the status light questions - all this is in the documentation as well as in previous issues.

https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/HomeKitSecureVideo.md

There are no metadata sync issues - nor sync at all for that matter - between Protect and HomeKit names. Once you change names in Protect, they won't flow through to HomeKit. That's an intentional design decision by Apple - HomeKit won't allow devices to arbitrarily change their names programmatically once they've been added to HomeKit.
