### ISSUE TITLE
Protect on Apple TV

### ISSUE THREAD

**Issue by fratinize** [hjdhjd/homebridge-unifi-protect#887]
**Describe The Problem:**

**Is your feature request related to a problem? Please describe:**
First have to Say this Plug in is great on many levels and I do not believe my issue is caused by the plug in. Just looking for some guidance and maybe some other users experiencing the same.

**To Reproduce:**
This Plug in loads fine, I can See my 5 Protect Cameras on My iPhone 16.3.1 (This Issue goes back much further). When I try on my Apple TV TVOS (Current, but Goes Back) The Protect Cameras are Not Responding. I have Seen the Protect Cameras Three Times in the Past TVOS Updates. The First time I show the Cameras on a New TVOS Update, I can See All 14 Cameras. ( The Second Time I connect, the protect only, Show Not Responding... and will not connect reboot Apple TV, reboot hb, same issues, even rebooted Router (udm pro)

**Homebridge Configuration:**

My Current Set up is
homebridge (Current, again, has Occurred on previous versions) Node 18.14.2 Runs on a pi4.
I also have HB running on a MacBook Pro, which handles 8 Wyze v2 RTSP cameras. using Homebridge Camera FFmpeg
homebridge-camera-ffmpeg v3.1.4. All these show up fine. I had move to Them to their Own server since I have so many Cameras. The wyze cameras all Show Fine on my Apple TV, always, albeit 5-7 second load time. My Ring Door bell cam is on the pi with the Protect Plug in and the ring is Solid and always the First Camera to Show live on the Apple TV with in seconds.

8 Wyze on the MacBook Pro
1 Ring on the pi4
5 Unifi Protect Cameras on the pi4

Again, I do not believe this is a plug in specific issue and obviously something there may be something between hb and/or network and Apple TV.

Thoughts? Direction?
Thank you for your great plug in and any support

**Comment by fratinize** [comment]
really?

**Comment by hjdhjd** [comment]
Yes, really. 😄 

Appreciate the detailed explanation of your issues. As you suspected, this likely isn't really a plugin issue.

Based on my experience, this issue tends to fall into two categories: either UniFi Network-related, or Homebridge-related.

Specifically - mDNS and multicasting in general.

The Apple TV isn't, for some reason, "seeing" Homebridge on the network and isn't connecting to it. Why it isn't seeing it is what leads you to the above. There are two different mDNS engines baked into Homebridge. You can switch between them and see if that helps: https://github.com/homebridge/homebridge/wiki/mDNS-Options. Ciao is the new hotness and is pretty solid, but HAP-Bonjour is the old reliable for some folks. HAP-Bonjour didn't comply with standards nearly as well as Ciao does...but weirdly, some networks prefer the more loud/noisy HAP-Bonjour.

Second thing is, given you're running this on a Mac - make sure you're broadcasting traffic on the right interface, if you have more than one live network interface (e.g. you've got WiFi configured and running and have an Ethernet cable plugged into the Mac at the same time). Same link as above, but look under **How To Select Advertised Network Interfaces**. You might want to try this one first before changing mDNS options.

You can try the old reboot everything Apple TV, HomePods (if you have them), Homebridge, and possibly the UniFi network devices themselves.

Finally - I found simplifying my network setup greatly reduced the issues that happen on occasion in the UniFi world. It's great hardware, but the software can be quite buggy. If you're running Homebridge on a different VLAN than the Apple TV, for instance, UniFi relies on an mDNS reflector to move mDNS traffic between segments. IGMP snooping, if enabled, can be buggy at times and cause issues with multicast applications (heck the [most recent production release for UDM firmware](https://community.ui.com/releases/UniFi-OS-Dream-Machine-SE-3-0-18/5ab556f7-da59-4e88-bc6b-90654b37abb2) has yet another fix for IGMP, something that should have been stable for years. Keep the network setup and options selected as close to the defaults as possible and that tends to be the happy path in UniFi Network.

To be fair, the software quality has ticked markedly upward in the past year...but it's still not anywhere near where it needs to be.

Hope these point you in the right direction.

**Comment by fratinize** [comment]
Its all good, I get it, Things must be managed...

Thank You for you reply. I definitely appreciate it and the education is invaluable.
Will look into this

Have a Great day

**Comment by hjdhjd** [comment]
Anytime! If you solve it for yourself, I'd appreciate it if you could post the solution to this thread so others can learn from your experience. Thanks and good luck!

**Comment by fratinize** [comment]
Will doSent from my iPhoneOn Mar 5, 2023, at 10:20 AM, hjdhjd ***@***.***> wrote:﻿
Anytime! If you solve it for yourself, I'd appreciate it if you could post the solution to this thread so others can learn from your experience. Thanks and good luck!
