### ISSUE TITLE
Can’t download from Hoobs Library

### ISSUE THREAD

**Issue by foxtrotoscar104** [hjdhjd/homebridge-unifi-protect#892]
**Describe The Problem:**
 When attempting to download from Hoobs Library a message stating “WARNING plugin site unavailable” 

**To Reproduce:**
 Attempt fresh install of plug in in Hoobs
![IMG_1081](https://user-images.githubusercontent.com/127637328/224518489-20c2c509-3ec9-4d6f-b4d8-b99f5121aa52.png)

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:**  1.5.0
* **Node Version:** 16.17.1
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
This is a HOOBS issue, not a plugin issue. Please reach out to the HOOBS team for support.

Best of luck!
