### ISSUE TITLE
Notification cooldown

### ISSUE THREAD

**Issue by dbinit** [hjdhjd/homebridge-unifi-protect#897]
**Is your feature request related to a problem? Please describe:**
I have 9 cameras covering all sides of my house (2 per corner + doorbell). When anyone is outside, particularly when I get a delivery, I get back to back repeated notifications from each camera as the person walks around to the front door and back to the driveway.

**Describe the solution you'd like:**
I would like the option to have a per-camera notification cooldown and/or a global notification cooldown. Bonus points if I can have it be per smart notification type (e.g. person vs car).

**Describe alternatives you've considered:**
I haven't discovered any alternatives. If mowers are outside, I will usually mute notifications for an hour (built-in Apple Home feature).

**Additional context:**
![IMG_3DB979AEC0D0-1](https://user-images.githubusercontent.com/77516/227590864-d4e9192a-ad5a-4d0c-adad-437a1a2cf628.png)

**Comment by hjdhjd** [comment]
Thanks for the suggestion - but I'm unlikely to add anything further than what already exists for this use case. You can already control the duration between motion events in the settings for the plugin. Take a look at the advanced settings.

There's no way to distinguish what objects are detected by HomeKit from the perspective of the plugin - it's a black box.

There are two ways to achieve what you want to do:

1. Adjust the duration of each motion event within HBUP. This is available under advanced settings and will dictate how long HBUP should wait between acknowledging motion events that come from Protect
2. Adjust the duration / sensitivity of each motion event within Protect.

Best of luck, and appreciate the challenge - I have a similar one and it's pretty well managed with a combination of the above. 😄
