### ISSUE TITLE
500 error ad infinitum

### ISSUE THREAD

**Issue by turtle2472** [hjdhjd/homebridge-unifi-protect#899]
**Describe The Problem:**

Cameras and thumbnails for them no longer update in the Home app. When attempting to view them a "no response" error is provided.  In Homebridge the logs are filled with 500 errors.

**To Reproduce:**

Restart child bridge for homebridge-unifi-protect or the rPi running the Homebridge instance.
**Logs:**

```
[24/03/2023, 14:51:30] [homebridge-unifi-protect] Restarting Process...
[24/03/2023, 14:51:31] [homebridge-unifi-protect] Launched child bridge with PID XXXXX
[24/03/2023, 14:51:32] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[24/03/2023, 14:51:32] [homebridge-unifi-protect] Loaded homebridge-unifi-protect v5.5.4 child bridge successfully
[24/03/2023, 14:51:32] Loaded 9 cached accessories from cachedAccessories.XXXXXXXXXXX.
[24/03/2023, 14:51:33] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-unifi-protect) is running on port XXXXX.
[24/03/2023, 14:51:33] [homebridge-unifi-protect] API access error: 500 - Internal Server Error
[24/03/2023, 14:51:33] [homebridge-unifi-protect] 192.168.x.x: Unable to retrieve NVR configuration information from UniFi Protect. Will retry again later.
[24/03/2023, 14:51:33] [homebridge-unifi-protect] API access error: 500 - Internal Server Error
[24/03/2023, 14:51:33] [homebridge-unifi-protect] 192.168.x.x: Unable to retrieve NVR configuration information from UniFi Protect. Will retry again later.
[24/03/2023, 14:51:33] [homebridge-unifi-protect] API access error: 500 - Internal Server Error
[24/03/2023, 14:51:33] [homebridge-unifi-protect] 192.168.x.x: Unable to retrieve NVR configuration information from UniFi Protect. Will retry again later.
```

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "192.168.x.x",
            "name": "DMP",
            "password": "password1234",
            "username": "homebridgeuser"
        }
    ],
    "videoProcessor": "/usr/local/bin/ffmpeg",
    "platform": "UniFi Protect",
    "_bridge": {
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX
    }
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.6.0 (HAP v0.11.0)
* **Node Version:** v16.19.0
* **Homebridge-UniFi-Protect Plugin Version:** v5.5.4 (running as child bridge)
* **UniFi Protect Version:** 2.2.11
* **UniFi Protect Controller Type:** UDMP 
* **UniFi Protect Controller Firmware Version:** 2.5.17
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPadOS 16.3.1 
* **Operating System and OS Version:** Raspbian GNU/Linux Buster (10) 

I've restarted the child bridge, the rPi the homebridge parent is running on as well as just the Protect app on the Dream Machine Pro. Finally I shutdown (cold) the DMP, unplugged and plugged back in. Nothing changes the error and, of course, the cameras video/thumbnails do not populate in the Home app.

**Comment by hjdhjd** [comment]
Let's see what we can do. First, the protect controller firmware version I'm going to assume is incorrect. 2.5.17 isn't a valid current Protect controller software revision. I'm going to presume you mean 2.2.6 is the version you're on, and the UDMP is running 2.5.17.

Second - was this configuration working previously?

You might want to try the Discord community for this one as well.

**Comment by turtle2472** [comment]
For Protect controller firmware I assumed it was the Dream Machine Pro firmware since there isn't a specific controller for Protect on it (that I'm aware of) so yes, that is the UDMP firmware version. 2.2.11 is the Protect version.  Please let me know if I'm just not looking in the right place.
![udmpVersion](https://user-images.githubusercontent.com/5554624/227620664-510bf542-d2ba-4733-9515-0d21797f8171.png)
It was working until recently.  Generally flawlessly actually.  Given my devices show the last update to the thumbnails is 5 days ago, I would assume it was around then that the DMP did and update of some kind.

**Comment by cbbg** [comment]
Same issue here with UniFi Protect 2.7.34

**Comment by hjdhjd** [comment]
@cbbg Please don't surf onto other people's issues. One person, one issue.

**Comment by hjdhjd** [comment]
@turtle2472 Your Protect revision is 2.2.11. The UDMP itself is essentially a platform for apps (think of it as iOS versions)...but that's not the same thing as the Protect revision.

All that said...I'll take a closer look, but I'm running on an identical setup without an issue. Ubiquiti updates are notorious for creating issues like this unfortunately, not that it's much of a consolation.

If you're willing to try something more extreme...you could backup your Protect controller configuration, stop and uninstall the Protect service / app on the UDMP, and reinstall / restore your config and see if that helps.

Crappy all around, no doubt, but it's a last resort.

Before that - does the Protect iOS app work?

**Comment by turtle2472** [comment]
I'm willing to uninstall, reinstall and restore if needed.  Obviously I would prefer not to do so.

Yes, it has been working on my Protect App without issue.  That is why I didn't even notice it actually.  My family used the Home App for everything where I don't look at the cameras on it and just scroll past them when going to whatever I'm looking to control.

**Comment by garetheowen** [comment]
I had a very similar issue to the one that turtle2472 is describing.  In the end I found that it had arisen as Unifi version upgrades have slowly changed the way that local users for Protect are set up.  The steps I would recommend checking are:  1) ensure your protect user is set up in unifi.com as a cloud user and the account is verified (2FA is not essential).  2) ensure the user has a local accreditation on the unifi DM or CloudKey.  3) ensure the user has a role which at least gives view rights for Protect.

**Comment by turtle2472** [comment]
Hmm... that could be it.  My homebridge users are local only. I've not verified them for the cloud or anything because they are custom and single purpose. :/  Guess I'll look into that today.

**Comment by garetheowen** [comment]
Give it a go for sure.  Mine *were* working as local users only, but as of last year (can't recall which new unifi version) my protect stopped working - and (thanks to your ticket prompting me to look again) now in retrospect i've realised it was when the cloudkey/UDM controller changed the way it worked with users.   If you look at this old unifi ticket, you'll see that many of the buttons/menu items for users have now changed..... https://community.ui.com/questions/Protect-Local-User/db71a09e-25c8-45ae-96b6-55f0c8d024bf

**Comment by turtle2472** [comment]
That was it!  Yay!
```
...
[27/03/2023, 10:52:13] [homebridge-unifi-protect] API access error: 500 - Internal Server Error
[27/03/2023, 10:52:13] [homebridge-unifi-protect] 192.168.x.x: Unable to retrieve NVR configuration information from UniFi Protect. Will retry again later.
[27/03/2023, 10:52:14] [homebridge-unifi-protect] DMP [UDM-PRO]: Connected to the UniFi Protect controller API (address: 192.168.x.x mac: XXXXXXXXXXX).
[27/03/2023, 10:52:14] [homebridge-unifi-protect] DMP [UDM-PRO]: Connected to the UniFi Protect realtime update events API.
[27/03/2023, 10:52:14] [homebridge-unifi-protect] DMP [UDM-PRO]: Discovered camera: G3 Front Yard [UVC G3 Instant] (address: 192.168.x.x mac: XXXXXXXXXXX).
...
```
As soon as the account was verified in the cloud it just started working.

Perhaps the docs for this plugin can specify cloud users now?

**Comment by hjdhjd** [comment]
> I had a very similar issue to the one that turtle2472 is describing. In the end I found that it had arisen as Unifi version upgrades have slowly changed the way that local users for Protect are set up. The steps I would recommend checking are: 1) ensure your protect user is set up in unifi.com as a cloud user and the account is verified (2FA is not essential). 2) ensure the user has a local accreditation on the unifi DM or CloudKey. 3) ensure the user has a role which at least gives view rights for Protect.

Thanks so much for this @garetheowen. Super helpful. Really appreciate the insightful response and glad things got working for folks.
