### ISSUE TITLE
Streams/snapshots don't work in 3.7.3 when camera offline

### ISSUE THREAD

**Issue by s1rc** [hjdhjd/homebridge-unifi-protect#90]
**Describe The Problem:**

Updating to 3.7.3 noticing a change in the log format when I've got at least one camera disconnected. Reverting to 3.6.5 streams work fine. The issue in 3.7.3 also causes other Homebridge plugins to be unresponsive.

**To Reproduce:**

* Update to 3.7.3
**Logs:**

* 3.7.3
```
[9/16/2020, 17:08:53] [UniFi Protect] [UDM-PRO] Backyard [UVC G4 Pro]: Unable to retrieve snapshot: %s.
```

* 3.6.5
```
9/16/2020, 17:12:57] [UniFi Protect]  [UDM-PRO] Backyard [UVC G4 Pro]: Unable to retrieve snapshot.
```
**Homebridge Configuration:**

**Screenshots:**

**Environment:**

* **Homebridge Version**:  1.2.2
* **Homebridge UniFi Protect Version**: 3.7.3
* **Operating System and OS Version**:  Homebridge Raspbian v1.0.4 - Raspberry Pi 4 Model B Rev 1.1

**Comment by hjdhjd** [comment]
Thanks for reporting this. I'm aware of the problem. Fix upcoming in 3.7.4.

**Comment by hjdhjd** [comment]
3.7.4 is available.

**Comment by s1rc** [comment]
Thank you!

I updated and now the error in the logs is gone. All the streams seem to be working except for my doorbell, so I'll have to diagnose why that is. 

There seems to be a delay in starting the stream and when the Homebridge logs show the stream request of about 60 seconds. There's a good chance this is on my end.

```
[9/17/2020, 08:36:45] [UniFi Protect] [UDM-PRO] Doorbell [UVC G4 Doorbell]: HomeKit video stream request received: 1280x720, 30 fps, 299 kbps.
[9/17/2020, 08:37:15] [UniFi Protect] [UDM-PRO] Doorbell [UVC G4 Doorbell]: Stopped video streaming session.
```
