### ISSUE TITLE
Support for G4 Doorbell Pro (secondary/package camera)

### ISSUE THREAD

**Issue by hoivikaj** [hjdhjd/homebridge-unifi-protect#900]
**Is your feature request related to a problem? Please describe:**
The G4 Doorbell Pro has 2 included cameras. The traditional forward facing camera, and a downward facing camera to see package deliveries. Currently, the 2nd camera is not seen by this plugin.

**Describe the solution you'd like:**
A potential solution would be the ability to treat the 2nd camera as a separate device so it can be seen on multi-camera views.

**Describe alternatives you've considered:**
The UniFi protect app has a picture-in-picture view that is convenient for switching, but not ideal for monitoring TVs.

**Comment by hjdhjd** [comment]
Coming soon.
