### ISSUE TITLE
Did 'Disable.Video.HKSV' and 'Enable.Motion.SmartDetect' change with the latest update?

### ISSUE THREAD

**Issue by StephenShamakian** [hjdhjd/homebridge-unifi-protect#903]
**Describe The Problem:**

After upgrading to v6.0.1 of the plugin my Unifi Protect Cameras are no longer using Unifi Protect's SmartMotion Events to detect activity. I used to rely on Unifi not HKSV to detect vehicles/people and it would pop up on my AppleTV. Now all the Unifi Cameras seem to think they are HKSV cameras and the "Activity Notifications" section switched from a simple "on/off" to a specific drop down that requires me to upload video to Apple and use HKSV to re-enable activity notifications for specific things (like person, vehicles).

In the past I had everything working perfectly with these features:

"Enable.Doorbell.Trigger",
"Enable.Log.Motion",
"Enable.Log.Doorbell",
"Enable.Motion.SmartDetect.NvrEvents",
"Enable.Motion.SmartDetect",
"Enable.Motion.NvrEvents",
"Disable.Video.HKSV"

But I cant find some of these now in the docs and not sure which ones were renamed vs. removed.

**To Reproduce:**

1. Use Unifi Protect with Smart Motion Cameras.
2. Upgrade to Unifi Protect HomeBridge Plugin to v6.0.1
3. Try to configure Activity notifications on Apple TV.
4. Activity notifications now thinks these cameras are HKSV cameras and require HKSV recording to be enabled for smart alerts from Unifi Protect.

**Logs:**

```
N/a
```

**Homebridge Configuration:**

```json
{
          "controllers": [
              {
                  "address": "url-here",
                  "name": "controller-name-here",
                  "password": "*****",
                  "username": "user-here"
              }
          ],
          "options": [
              "Enable.Doorbell.Trigger",
              "Enable.Log.Motion",
              "Enable.Log.Doorbell",
              "Enable.Motion.SmartDetect.NvrEvents",
              "Enable.Motion.SmartDetect",
              "Enable.Motion.NvrEvents",
              "Disable.Video.HKSV"
          ],
          "platform": "UniFi Protect"
      }
```

**Screenshots:**

N/a

**Environment:**

* **Homebridge Version:**  v1.6.0
* **Node Version:**  v18.13.0
* **Homebridge-UniFi-Protect Plugin Version:** v6.0.1
* **UniFi Protect Version:**  v2.7.33
* **UniFi Protect Controller Type:**  UNVR
* **UniFi Protect Controller Firmware Version:**  v3.0.16
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS, macOS, iPadOS, tvOS, (Basically All)
* **Operating System and OS Version:**  Docker

**Comment by hjdhjd** [comment]
Thanks for the report.

Please read the [changelog](https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/Changelog.md) and [feature option documentation](https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/FeatureOptions.md).

This isn't a bug - it's documented, expected behavior. This is a major version upgrade with several breaking changes. 😄

If you don't want to use HKSV, simply don't configure the camera as a HomeKit Secure Video camera in the Home app, and it will function as a "normal" camera. There's really no need for the HKSV feature option at this point - it's redundant given configuring HKSV is a user-controlled option in the Home app.

**Comment by StephenShamakian** [comment]
@hjdhjd 

I did read the docs... And I did try various options... I wouldn't have wasted my time or yours typing this very specific issue up that your GitHub repo demands if I didn't first exhaust all options I could find. I even searched your source code to figure out what happen and came up dry. Your docs here (https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/HomeKitSecureVideo.md) state it should be using Unifi Protect's mechanism if HKSV is disabled. How do you now disable HKSV if the option is gone?

Also, for the record, I changed nothing in HomeKit itself. I just updated this plugin. These cameras were not listed as HKSV video before this update. Now they are after your breaking change update.

**Comment by StephenShamakian** [comment]
@hjdhjd Also for further testing. I just deleted the HomeBridge Unifi Protect child bridge and re-added it. HomeKit gave me no options to "Disable HKSV". Just Off, Detect Activity, Stream or Stream&Record options. As the plugin now seems to be identifying all the cameras as HKSV capable by default.

Now the question is, if I enabled on tvOS "Any Motion" and I set the plugin to "Enable.Motion.SmartDetect". Will this replicate how it worked before? Where tvOS will only pop up the camera feed if Unifi Protect detects a smart motion event?

**Comment by hjdhjd** [comment]
That's correct.

"Off" = "Disable HKSV" in the Home app. Motion will be detected as it is for any camera by default.

Whether you enable HKSV in the Home app or not is what determines how motion events get to you. If you enable HKSV in the Home app, HomeKit takes control of when to notify you for motion events. If you do not enable HKSV, motion detection will work as it always has and HBUP will provide the notifications.

**Comment by StephenShamakian** [comment]
@hjdhjd 

These are those options:

![image](https://user-images.githubusercontent.com/6382844/228062733-927b2bf6-3eb4-4c83-875a-36cf2371b10e.png)

Wouldn't 'Off' disable the camera completely? No streaming it at all? I don't believe that means it disables the camera as being HKSV capable.


So far it seems if I set "Activity Alerts" in tvOS to "Any Motion" for the cameras and set the plugin feature "Enable.Motion.SmartDetect" it seems to mimic (so far) how it worked before. Where it alerts only on people and vehicles and HKSV isn't responsible for the AI processing, UniFi Protect is. That's my goal as I rather not offload that to Apple when Unifi's capability of doing it is good enough and local to UniFi Protect vs stored in my iCloud account.

**Comment by hjdhjd** [comment]
It doesn't mimic - it **is** the behavior that you had previously. 😄 It's the way it's always worked. You never needed to explicitly disable the HKSV feature option - that's part of why I removed it, it's simply adds to the confusion of users. A camera is a camera in the HomeKit world. HKSV is a bonus that you can choose to enable or not. Enabling it will override how motion events are delivered to the camera as I described above. 

And no, that's not what it means. You are in the Home app HKSV **recording** menu. The options should be viewed in that context. "Off" means don't enable HKSV. If you have an issue with how the Home app works - that's above my pay grade, go file a radar at Apple. 😛

**Comment by StephenShamakian** [comment]
@hjdhjd I will choose to ignore the condescending tone in your post as it seems to be working now so thanks (I think) for the help...

For others that may be having these issues the real change was the cameras appeared differently after the upgrade in HomeKit (specifically in the tvOS settings). Their Activity Alerts in tvOS changed from what they were "off /on" to a selection of items. I needed to select "All Motion" and make sure SmartDetection was enabled in the plugin (which it was). They were set to nothing after the plugin update.

By the way just for your reference, 'Off' will disable the camera. Just tried it. There are no other options besides that in the camera settings in HomeKit.

**Comment by hjdhjd** [comment]
Locking this issue for posterity.
