### ISSUE TITLE
6.0.1 web config Feature Options tab spinning gear

### ISSUE THREAD

**Issue by chriscarpenter12** [hjdhjd/homebridge-unifi-protect#904]
**Describe The Problem:**
Upgraded from a working 5.5.4 to 6.0.1 and the new web config ui gets a spinning gear on the `Feature Options` tab with an error in the console. From what I can tell functionality wise things are working correctly in HomeKit still with no changes required on my end. Using the previous defaults without issue. 

**To Reproduce:**

**Logs:**

With debug logging on

```
[3/27/2023, 1:54:20 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
```

Browser
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at showDevices (index.html?origin=http%3A%2F%2Fhomebridge&v=6.0.1:445:37)
```

**Homebridge Configuration:**

```json
        {
            "controllers": [
                {
                    "address": "xxx",
                    "password": "xxx",
                    "username": "xxx"
                }
            ],
            "_bridge": {
                "username": "0E:35:A3:8E:D9:BC",
                "port": 58971
            },
            "platform": "UniFi Protect"
        },
```

**Screenshots:**
![Screenshot 2023-03-27 at 1 48 34 PM](https://user-images.githubusercontent.com/458486/228024378-37c53b04-fd5b-4204-b0cd-ed9a097a4094.png)
![Screenshot 2023-03-27 at 1 49 01 PM](https://user-images.githubusercontent.com/458486/228024464-262d953a-567e-4d70-a6ad-ca1e0afc5fdb.png)

**Environment:**

* **Homebridge Version:** v1.6.0
* **Node Version:** v18.15.0
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 2.7.33
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 3.0.17
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:** Debian

**Comment by jk-andersen** [comment]
Same issue here

![Screenshot 2023-03-27 202618](https://user-images.githubusercontent.com/62281415/228032907-5517113a-4283-4de6-99a6-268394705dc6.png)

```
{
            "controllers": [
                {
                    "address": "10.0.xxx",
                    "mqttTopic": "unifi/protect",
                    "mqttUrl": "mqtt://xxxxx@xxxx",
                    "password": "xxxxxx,
                    "username": "xxxx"
                }
            ],
            "verboseFfmpeg": false,
            "platform": "UniFi Protect"
        }
```


Environment:

Homebridge Version: v1.6.0
Node Version: [18.14.2]
Homebridge-UniFi-Protect Plugin Version:
UniFi Protect Version: 2.7.34
UniFi Protect Controller Type: UDM SE
UniFi Protect Controller Firmware Version: 3.0.18
Apple Device and iOS / macOS / iPadOS / tvOS Version:
Operating System and OS Version: Synology Docker

**Comment by whitedonkey** [comment]
Same for me.

**Comment by ludgats** [comment]
> Same for me.

I should add that it works fine on my raspberry pi 4 but on my Mac it doesn’t. Hope that’s helpful.

**Comment by hjdhjd** [comment]
One person, one issue please. 

If you'd like support, please open a new issue. I'm only providing support in this thread to @chriscarpenter12.

Thanks for respecting how I choose to handle support.

**Comment by hjdhjd** [comment]
@chriscarpenter12 Can you let me know what browser you're running for this, and how you're accessing the Homebridge webUI? e.g. where is Homebridge running relative to everything else.

Going to look into this, but I need a bit to go on. 😄 

The webUI is useful, but as long as things are working you're up and running functionally at least. 

Obviously, I'd like to get the webUI to be as reasonably bulletproof as possible. Thanks!

**Comment by chriscarpenter12** [comment]
Should have included that info that's my bad.

Homebridge is running on in a Debian lxc container in a vlan on same network as cloud key device. Local dns resolver points directly to the private IP accessing it using hostname. No reverse proxying or anything fancy. Accessing from a MacBook 13.2.1 using Safari 16.3 and Chrome 111.0.5563.146. I also tested from my Ubuntu 22.04 laptop using Chrome 111.0.5563.110 and see the same error/behavior.

**Comment by hjdhjd** [comment]
Thanks Chris. I promise this is in my queue to look at. Need to resolve a couple of functional issues others are having first. Appreciate you providing some more context.

**Comment by chriscarpenter12** [comment]
Ya, no worries. Thanks for supporting this home bridge plugin!

**Comment by hjdhjd** [comment]
Chris - does this problem occur every time? Also, I presume there are devices attached to the Protect controller?

**Comment by hjdhjd** [comment]
Danke. I'm fascinated by this issue. I've been able to recreate and correct the issue. Should be fixed soon. Thanks @chriscarpenter12 - hope this next release does the trick.

**Comment by hjdhjd** [comment]
Give v6.0.2 a go Chris. Should do the trick.

**Comment by jfmach** [comment]
fwiw I had the same problem and the upgrade fixed it for me. Thank you!

**Comment by chriscarpenter12** [comment]
Can confirm I just updated to 6.0.3 and the `Feature Options` tab loads for me now. Thanks for the patch!

**Comment by jk-andersen** [comment]
Works for me, 2. Thanks @hjdhjd
