### ISSUE TITLE
Audio missing with v6.1.0+

### ISSUE THREAD

**Issue by kinoushe** [hjdhjd/homebridge-unifi-protect#909]
**Describe The Problem:**
After updating to [v6.1.0](https://github.com/hjdhjd/homebridge-unifi-protect/releases/tag/v6.1.0) the audio is missing. Rolling back to [v6.0.3](https://github.com/hjdhjd/homebridge-unifi-protect/releases/tag/v6.0.3) resolves the missing audio.

**To Reproduce:**
Update to v6.1.0+ and view the camera in the Home app.

**Logs:**

```
Audio support disabled. A version of FFmpeg that is compiled with fdk_aac support is required to support audio.
```

**Environment:**

* **Homebridge Version:** v1.6.0
* **Node Version:** v16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** v6.1.0
* **UniFi Protect Version:**  2.7.33
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 3.0.17
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 16.4
* **Operating System and OS Version:** Synology DSM 7.1.1-42962 Update 4 (INTEL Celeron J3355)

**Comment by hjdhjd** [comment]
Give v6.2.1 a go. Sorry about that!

**Comment by kinoushe** [comment]
Just tested and the audio is now working correctly, thanks for the quick fix!
