### ISSUE TITLE
iOS 14 Doorbell "Chime on HomePod"

### ISSUE THREAD

**Issue by fpuigb** [hjdhjd/homebridge-unifi-protect#91]
**Describe The Problem:**

Getting "could not complete operation" error when try to enable "Chime on HomePod" option.

**To Reproduce:**

Under the doorbell "Notifications" option the first one is "Chime on HomePod", if you switch it to enable the error pop-up.

**Environment:**

* **Homebridge Version**:  1.2.2
* **Homebridge UniFi Protect Version**: 3.7.4
* **Operating System and OS Version**: Ubuntu 16.04

**Comment by hjdhjd** [comment]
Thanks! I’m aware of the issue. It’s not getting resolved anytime soon. 😄 

Closing this - it’s going to take time, and it’s not a plugin issue per se. There’s more nuance.

**Comment by hjdhjd** [comment]
FYI - this functionality is dependent on the iOS 14 update on the HomePod. Once Apple releases that, things should work. This isn't a bug, or a plugin issue. Just wait. 😄

**Comment by fpuigb** [comment]
Ah, make sense 😉

**Comment by hjdhjd** [comment]
...and stop opening up bug reports the first week a new iOS release is out with almost no notice from Apple! 😄

**Comment by fpuigb** [comment]
lol, you should be on top of that! Come on with a plug-in like this one the developer should be ahead 🤣🤪😂
