### ISSUE TITLE
No more mqtt motion event sent

### ISSUE THREAD

**Issue by VincentWallet** [hjdhjd/homebridge-unifi-protect#910]
**Describe The Problem:**
For some time now, motion MQTT events are no longer being sent.

**To Reproduce:**
Trigger a motion event on camera and notice that the topic won't be modified on the broker. ( i use for example : unifi/protect/XXXXXXX/motion )

**Logs:**

```
[03/04/2023 15:55:21] [UniFi Protect] gambais uck gen 2: Connected to MQTT broker: mqtt://jeedom:REDACTED@localhost (topic: unifi/protect).
```

**Homebridge Configuration:**

```json
{
        {
            "controllers": [
                {
                    "address": "XXXXXXXX",
                    "mqttTopic": "unifi/protect",
                    "mqttUrl": "mqtt://jeedom:XXXXXXXXXXX@localhost",
                    "password": "XXXXXXXX",
                    "username": "homebridge-unifi"
                }
            ],
            "options": [
                "Enable.Motion.Switch"
            ],
            "platform": "UniFi Protect"
        }
    
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** v16.19.0
* **Homebridge-UniFi-Protect Plugin Version:** v6.2.1
* **UniFi Protect Version:** 2.7.33
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 3.0.17
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Iphone 14 pro 16.4
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Thanks for the report. I'll take a closer look.

**Comment by VincentWallet** [comment]
ok, sorry for bad handling my previous messages. Like i said before, nothing improved with the v6.2.2 on my side.

Still no motion event.

Via mqtt explorer, i retrieve only snapshots.

![image](https://user-images.githubusercontent.com/26494071/229932991-c6386a76-71a4-41bb-afd5-ff823afdf438.png)

For info, i have another similar installation with a unfi v3.X and homebridge-unifi-protect v5.5.4 that work perfectly concerning mqtt events.

Regards,

**Comment by hjdhjd** [comment]
No worries. Glad you sorted it out. Try v6.2.4 - which is the current release and let me know if that does the trick.

**Comment by VincentWallet** [comment]
Hi,

Sorry but after one test night, still no mqtt motion events was triggered.

I don't know if it's possible but i was thinking to downgrade to 5.5.4 just to hightlight the issue.

Regards,

**Comment by hjdhjd** [comment]
You haven't provided any meaningful information with which to understand the specific issue in a straightforward way that I can understand and address. You need to spend more than a moment or two typing in something for me to help you and to address if there's a bug in HBUP, and remediating it.

What you've provided above, by and large, doesn't do that other than to say "it doesn't work". That doesn't help solve the problem.

What is the exact nature of the issue? This means be very specific: WHAT MQTT message are you missing or not. What are you expecting to see?

How can one recreate it? What is the exact camera model you are using?

Are you certain you are running the latest version of HBUP and that you restarted Homebridge after updating the plugin?

I do not see and cannot reproduce any issues in MQTT support in v6.2.4 - v6.2.8 (the current release version of HBUP). Motion events are correctly published to MQTT when they occur in the way they are meant to, in my testing.

I'm happy to provide support as long as you're able to be complete and constructive in your request. Thanks.

**Comment by VincentWallet** [comment]
i agree that i did not provide many information but that's also a problem for me : i don't see what can i provide more and i am very ready to help more if needed ? 

The exact nature of the issue is simply all missing motion events. The system was working very well in the past but no more at the moment and like mentionned, the missing motion event are those ones : unifi/protect/XXXXXXX/motion and his smart derivate : unifi/protect/XXXXXXX/motion/smart/vehicle  and unifi/protect/XXXXXXX/motion/smart/person.

So i expect to see this boolean unifi/protect/XXXXXXX/motion topic with a true/false value.

At the moment, i only have those ones : unifi/protect/XXXXXXXX/snapshot and don't know which trigger update them when they are updated.

In the past (when it was working good) and to create the use case was just by triggering a motion (walk in front of the camera for exemple ) and see the value of the topic unifi/protect/XXXXXXX/motion switch to true then go back to false when the motion is ended.

Cameras that i have on this system are : 2x G3 instant and 1x G4 instant.

I have done many operation and pretty sure to have restarted homebridge after updating the plugin ( i did this multiple time and even rebooted the whole system many times).

Maybe could you share me a procedure that could let me do deeper testing ? Maybe could you activate some more verbose logs concerning all mqtt events in HBUP ? 

Thanks again for your time.

**Comment by VincentWallet** [comment]
Just some news : i continue to maintain HBUP updated and i am on the 6.4.1 at the moment.

thanks to your new telemetry feature :  i have access to it via mqtt. it's a lot information and a little hard to find something relevant and let me confirm maybe (i guess) that HBUP receive some motion event.

So at the moment, i still have snapshots from cameras and telemetry topics on the broker but still missing motion topics.


On telemetry, i captured those two messages in same second during a live motion that seem confirm it : 
```json
 {
  "header": {
    "action": "update",
    "newUpdateId": "a16204e8-fc94-4026-afae-7ed91feb3570",
    "modelKey": "camera",
    "id": "XXXXXXXX",
    "mac": "XXXXXXXX",
    "token": null
  },
  "payload": {
    "lastMotion": 1681165264100,
    "isMotionDetected": true,
    "recordingSchedules": [],
    "isRecording": true
  }
}
```

and 

```json 
{
  "header": {
    "action": "update",
    "newUpdateId": "11e328b3-5eb7-478c-9651-93f449aad65c",
    "modelKey": "camera",
    "id": "XXXXXXXXXXXXX",
    "mac": "XXXXXXXX",
    "token": null
  },
  "payload": {
    "eventStats": {
      "motion": {
        "today": 1,
        "average": 71,
        "lastDays": [81, 0, 0, 221, 78, 92, 29],
        "recentHours": [1, 7, 10, 11, 20, 33, 0, 0, 0, 0, 0, 0, 0]
      },
      "smart": { "today": 0, "average": 0, "lastDays": [0, 0, 0, 0, 0, 0, 0] }
    },
    "recordingSchedules": []
  }
}
```

**Comment by hjdhjd** [comment]
> @VincentWallet   I just upgraded from v5.5.4 to v6.4.0 & v6.4.1 and noticed the same / very similar problem with motion events not working.  
> 
> For me anyway, cameras that didn't support smart motion were posting correctly, but ones that do support smart motion were not posting anything.  By adding the following in the config `"Enable.Motion.SmartDetect"` has seemed to put MQTT back to what I was expecting (all motions being posted).    So my options stanza part of the config looks like this.
> 
> ```
> 
> "options": [
> 
>                 "Enable.Log.Motion",
> 
>                 "Enable.Motion.SmartDetect"
> 
>             ],
> 
> ```

Fascinating. Say more please...what behavior were you expecting versus what are you actually seeing and how does it differ from 5.x?

I want to get the issue addressed if there is one.

**Comment by VincentWallet** [comment]
I tried the config previously posted just for testing purpose and confirm that my mqtt motions event for all cameras (G3 and G4, with/without smart detection)  are back but with no smart detection on the G4 instant camera : 


```
"options": [
                "Enable.Log.Motion",
                "Enable.Motion.SmartDetect"
            ],
```


My logs of the test
```
[4/11/2023, 1:16:45 AM] [UniFi Protect] XXXXXXX: Connected to the UniFi Protect API at XXXXXXX
[4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Protect controller telemetry enabled.
[4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered nvr: gambais uck gen 2 [UCK G2 Plus] (address: XXXXXXX mac: XXXXXXX).
[4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered camera: Allee [G4 Instant] (address: XXXXXXX mac: XXXXXXX).
[4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered camera: Salon [G3 Instant] (address: XXXXXXX mac: XXXXXXX).
[4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered camera: Cabane [G3 Instant] (address: XXXXXXX mac: XXXXXXX).
[4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: Smart motion detection enabled: person, vehicle.
[4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: WARNING: Smart motion detection and HomeKit Secure Video provide overlapping functionality. Only HomeKit Secure Video, when event recording is enabled in the Home app, will be used to trigger motion event notifications for this camera.
[4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Connected to MQTT broker: mqtt://jeedom:REDACTED@127.0.0.1:1883 (topic: unifi/protect).
[4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Default doorbell message set to: WELCOME.
[4/11/2023, 1:16:46 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video event recording enabled: 1920x1080@30fps (High), 2000 kbps with a 4 second timeshift buffer.
[4/11/2023, 1:16:46 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Cabane [G3 Instant]: HomeKit Secure Video event recording enabled: 1920x1080@30fps (High), 2000 kbps with a 4 second timeshift buffer.
[4/11/2023, 1:16:46 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: HomeKit Secure Video event recording enabled: 2688x1512@30fps (High), 2000 kbps with a 4 second timeshift buffer.
[4/11/2023, 1:18:29 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: Motion detected.
[4/11/2023, 1:18:39 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
[0;37m[4/11/2023, 1:19:48 AM] [0m[0;36m[Homebridge UI][0m [homebridge-unifi-protect] Terminating child process...
[0;37m[4/11/2023, 1:19:49 AM] [0m[0;36m[Homebridge UI][0m [homebridge-unifi-protect] Child process ended
[4/11/2023, 1:20:29 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: Motion detected.
[4/11/2023, 1:20:42 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: Motion detected.
[4/11/2023, 1:20:49 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video has recorded a 23 second motion event.
[4/11/2023, 1:20:49 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
[4/11/2023, 1:20:50 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
[HDS 192.168.1.95] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
[4/11/2023, 1:20:52 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: FFmpeg ended unexpectedly due to issues with the media stream provided by the UniFi Protect livestream API. This error can be safely ignored - they will occur occasionally.
[4/11/2023, 1:21:00 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: Motion detected.
[4/11/2023, 1:21:59 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
[4/11/2023, 1:22:00 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: Motion detected.
```

Thanks again.

Regards,

**Comment by sfeakes** [comment]
> > @VincentWallet   I just upgraded from v5.5.4 to v6.4.0 & v6.4.1 and noticed the same / very similar problem with motion events not working.
> > For me anyway, cameras that didn't support smart motion were posting correctly, but ones that do support smart motion were not posting anything.  By adding the following in the config `"Enable.Motion.SmartDetect"` has seemed to put MQTT back to what I was expecting (all motions being posted).    So my options stanza part of the config looks like this.
> > ```
> > 
> > "options": [
> > 
> >                 "Enable.Log.Motion",
> > 
> >                 "Enable.Motion.SmartDetect"
> > 
> >             ],
> > ```
> 
> Fascinating. Say more please...what behavior were you expecting versus what are you actually seeing and how does it differ from 5.x?
> 
> I want to get the issue addressed if there is one.

v5.5.4 I had `"Enable.Log.Motion"` set and would get the following posted to MQTT
```
protect/NON_SMART_MOTION_MAC/motion  ( true or false )
protect/SMART_MOTION_MAC/motion  ( always false )
protect/SMART_MOTION_MAC/motion/smart/vehicle ( true or false )
protect/SMART_MOTION_MAC/motion/smart/person ( true or false )
```

When upgraded to v6.4.0  and then v6.4.1, all I got were the following.
```
protect/NON_SMART_MOTION_MAC/motion  ( true or false )
```

Setting `"Enable.Motion.SmartDetect"` in V6.4.1 put it back to the full motions that I was expecting with one differance.
```protect/SMART_MOTION_MAC/motion  ( true and false, rather than always false  )```

I didn't change my config when upgrading from 5.5.4 to 6.4.0, so the only other thing I can think or, other that logic change around that config parameter, is maybe the upgrade process nuked that Enable.Motion.SmartDetect line.

**Comment by hjdhjd** [comment]
> > > @VincentWallet   I just upgraded from v5.5.4 to v6.4.0 & v6.4.1 and noticed the same / very similar problem with motion events not working.
> > > For me anyway, cameras that didn't support smart motion were posting correctly, but ones that do support smart motion were not posting anything.  By adding the following in the config `"Enable.Motion.SmartDetect"` has seemed to put MQTT back to what I was expecting (all motions being posted).    So my options stanza part of the config looks like this.
> > > ```
> > > 
> > > "options": [
> > > 
> > >                 "Enable.Log.Motion",
> > > 
> > >                 "Enable.Motion.SmartDetect"
> > > 
> > >             ],
> > > ```
> > 
> > 
> > Fascinating. Say more please...what behavior were you expecting versus what are you actually seeing and how does it differ from 5.x?
> > I want to get the issue addressed if there is one.
> 
> v5.5.4 I had `"Enable.Log.Motion"` set and would get the following posted to MQTT
> 
> ```
> protect/NON_SMART_MOTION_MAC/motion  ( true or false )
> protect/SMART_MOTION_MAC/motion  ( always false )
> protect/SMART_MOTION_MAC/motion/smart/vehicle ( true or false )
> protect/SMART_MOTION_MAC/motion/smart/person ( true or false )
> ```
> 
> When upgraded to v6.4.0 and then v6.4.1, all I got were the following.
> 
> ```
> protect/NON_SMART_MOTION_MAC/motion  ( true or false )
> ```
> 
> Setting `"Enable.Motion.SmartDetect"` in V6.4.1 put it back to the full motions that I was expecting with one difference.
> 
> ```
> protect/NON_SMART_MOTION_MAC/motion  ( true or false )
> protect/SMART_MOTION_MAC/motion  ( true and false, rather than always false  )
> protect/SMART_MOTION_MAC/motion/smart/vehicle ( true or false )
> protect/SMART_MOTION_MAC/motion/smart/person ( true or false )
> ```
> 
> I didn't change my config when upgrading from 5.5.4 to 6.4.0, so the only other thing I can think of, other than logic change around that config parameter, is maybe the upgrade process nuked that Enable.Motion.SmartDetect line.

That was a bug in 5.5.4 and operating correctly in 6.x...it should **not** be notifying on smart motion events unless you specifically request it to. That it was doing so in 5.x might have been the behavior you wanted, but it wasn't the behavior that was *intended*. The intent is the way things work in 6.x:

when you specifically opt into smart motion events, as defined by the Protect controller, you will be notified as such. Otherwise, all motion events are treated the same - namely any motion event triggers the motion messages in MQTT. 

This was always the documented behavior in both 5.x and 6.x - the behavior you want was actually a bug in 5.x. :smile:

Hope that helps...and glad you got the behavior you're looking for by explicitly opting into it. Again, what you are describing isn't a bug, but rather the fixing of a bug in the 5.x series to match the original intent, and documentation.

**Comment by hjdhjd** [comment]
> I tried the config previously posted just for testing purpose and confirm that my mqtt motions event for all cameras (G3 and G4, with/without smart detection) are back but with no smart detection on the G4 instant camera :
> 
> ```
> "options": [
>                 "Enable.Log.Motion",
>                 "Enable.Motion.SmartDetect"
>             ],
> ```
> 
> My logs of the test
> 
> ```
> [4/11/2023, 1:16:45 AM] [UniFi Protect] XXXXXXX: Connected to the UniFi Protect API at XXXXXXX
> [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Protect controller telemetry enabled.
> [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered nvr: gambais uck gen 2 [UCK G2 Plus] (address: XXXXXXX mac: XXXXXXX).
> [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered camera: Allee [G4 Instant] (address: XXXXXXX mac: XXXXXXX).
> [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered camera: Salon [G3 Instant] (address: XXXXXXX mac: XXXXXXX).
> [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered camera: Cabane [G3 Instant] (address: XXXXXXX mac: XXXXXXX).
> [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: Smart motion detection enabled: person, vehicle.
> [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: WARNING: Smart motion detection and HomeKit Secure Video provide overlapping functionality. Only HomeKit Secure Video, when event recording is enabled in the Home app, will be used to trigger motion event notifications for this camera.
> [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Connected to MQTT broker: mqtt://jeedom:REDACTED@127.0.0.1:1883 (topic: unifi/protect).
> [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Default doorbell message set to: WELCOME.
> [4/11/2023, 1:16:46 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video event recording enabled: 1920x1080@30fps (High), 2000 kbps with a 4 second timeshift buffer.
> [4/11/2023, 1:16:46 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Cabane [G3 Instant]: HomeKit Secure Video event recording enabled: 1920x1080@30fps (High), 2000 kbps with a 4 second timeshift buffer.
> [4/11/2023, 1:16:46 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: HomeKit Secure Video event recording enabled: 2688x1512@30fps (High), 2000 kbps with a 4 second timeshift buffer.
> [4/11/2023, 1:18:29 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: Motion detected.
> [4/11/2023, 1:18:39 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
> �[0;37m[4/11/2023, 1:19:48 AM] �[0m�[0;36m[Homebridge UI]�[0m [homebridge-unifi-protect] Terminating child process...
> �[0;37m[4/11/2023, 1:19:49 AM] �[0m�[0;36m[Homebridge UI]�[0m [homebridge-unifi-protect] Child process ended
> [4/11/2023, 1:20:29 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: Motion detected.
> [4/11/2023, 1:20:42 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: Motion detected.
> [4/11/2023, 1:20:49 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video has recorded a 23 second motion event.
> [4/11/2023, 1:20:49 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
> [4/11/2023, 1:20:50 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
> [HDS 192.168.1.95] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
> [4/11/2023, 1:20:52 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: FFmpeg ended unexpectedly due to issues with the media stream provided by the UniFi Protect livestream API. This error can be safely ignored - they will occur occasionally.
> [4/11/2023, 1:21:00 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: Motion detected.
> [4/11/2023, 1:21:59 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
> [4/11/2023, 1:22:00 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: Motion detected.
> ```
> 
> Thanks again.
> 
> Regards,

What does the camera configuration show in the Protect controller? Are smart events enabled there?

G3 series cameras do not support smart motion detection in Protect, so it's a non-issue: Ubiquiti cameras before the G4 series do not do smart motion detection.

**Comment by VincentWallet** [comment]
> > I tried the config previously posted just for testing purpose and confirm that my mqtt motions event for all cameras (G3 and G4, with/without smart detection) are back but with no smart detection on the G4 instant camera :
> > ```
> > "options": [
> >                 "Enable.Log.Motion",
> >                 "Enable.Motion.SmartDetect"
> >             ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > My logs of the test
> > ```
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] XXXXXXX: Connected to the UniFi Protect API at XXXXXXX
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Protect controller telemetry enabled.
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered nvr: gambais uck gen 2 [UCK G2 Plus] (address: XXXXXXX mac: XXXXXXX).
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered camera: Allee [G4 Instant] (address: XXXXXXX mac: XXXXXXX).
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered camera: Salon [G3 Instant] (address: XXXXXXX mac: XXXXXXX).
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Discovered camera: Cabane [G3 Instant] (address: XXXXXXX mac: XXXXXXX).
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: Smart motion detection enabled: person, vehicle.
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: WARNING: Smart motion detection and HomeKit Secure Video provide overlapping functionality. Only HomeKit Secure Video, when event recording is enabled in the Home app, will be used to trigger motion event notifications for this camera.
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Connected to MQTT broker: mqtt://jeedom:REDACTED@127.0.0.1:1883 (topic: unifi/protect).
> > [4/11/2023, 1:16:45 AM] [UniFi Protect] gambais uck gen 2: Default doorbell message set to: WELCOME.
> > [4/11/2023, 1:16:46 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video event recording enabled: 1920x1080@30fps (High), 2000 kbps with a 4 second timeshift buffer.
> > [4/11/2023, 1:16:46 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Cabane [G3 Instant]: HomeKit Secure Video event recording enabled: 1920x1080@30fps (High), 2000 kbps with a 4 second timeshift buffer.
> > [4/11/2023, 1:16:46 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: HomeKit Secure Video event recording enabled: 2688x1512@30fps (High), 2000 kbps with a 4 second timeshift buffer.
> > [4/11/2023, 1:18:29 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: Motion detected.
> > [4/11/2023, 1:18:39 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
> > �[0;37m[4/11/2023, 1:19:48 AM] �[0m�[0;36m[Homebridge UI]�[0m [homebridge-unifi-protect] Terminating child process...
> > �[0;37m[4/11/2023, 1:19:49 AM] �[0m�[0;36m[Homebridge UI]�[0m [homebridge-unifi-protect] Child process ended
> > [4/11/2023, 1:20:29 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: Motion detected.
> > [4/11/2023, 1:20:42 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: Motion detected.
> > [4/11/2023, 1:20:49 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video has recorded a 23 second motion event.
> > [4/11/2023, 1:20:49 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
> > [4/11/2023, 1:20:50 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
> > [HDS 192.168.1.95] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
> > [4/11/2023, 1:20:52 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: FFmpeg ended unexpectedly due to issues with the media stream provided by the UniFi Protect livestream API. This error can be safely ignored - they will occur occasionally.
> > [4/11/2023, 1:21:00 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: Motion detected.
> > [4/11/2023, 1:21:59 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Allee [G4 Instant]: HomeKit Secure Video event recording ended early: The request timed out.
> > [4/11/2023, 1:22:00 AM] [UniFi Protect] gambais uck gen 2 [UCK-G2-PLUS] Salon [G3 Instant]: Motion detected.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks again.
> > Regards,
> 
> What does the camera configuration show in the Protect controller? Are smart events enabled there?
> 
> G3 series cameras do not support smart motion detection in Protect, so it's a non-issue: Ubiquiti cameras before the G4 series do not do smart motion detection.

In protect controller, smart detection on my G4 is activated ( with person and vehicule also) and on my other G3, motion detection is activated.

On my side, the behavior became totally correct since i put "Enable.Log.Motion" and "Enable.Motion.SmartDetect". I recovered all mqtt trigger on both G3 and G4 : basic motion and smart motion.

But like said before, without this otption (log and smart detection), no mqtt event were published.

For the moment, i stay with those option to let my system reliable.

Regards,

**Comment by hjdhjd** [comment]
Yep - there's a bug. I'm on it. 😄

**Comment by hjdhjd** [comment]
Try v6.4.2 - should fix this issue, and thanks for taking the time to explain it more completely.

Let me know how it goes.

**Comment by VincentWallet** [comment]
Everything is fine for me with this release. Smart motion with the option feature and classic motion without for all camera.

Thanks a lot again for all your work !
