### ISSUE TITLE
"Camera" device type be passed through so the Alexa plug in can report to Alexa that the device is a camera

### ISSUE THREAD

**Issue by mbcooper9734** [hjdhjd/homebridge-unifi-protect#911]
**Is your feature request related to a problem? Please describe:**
I'm using the Alexa plugin.  Alexa can't see the stream device presented by the unifi plugin as a camera.  The motion has a type of "Motion Sensor".  The stream has no type

**Describe the solution you'd like:**
Add a camera device type that can be passed down the line for other plugins

**Describe alternatives you've considered:**
Allow the editing of device types in the device setup

**Additional context:**
Thanks for the work you've done

**Comment by hjdhjd** [comment]
Thanks for the (unusual? 😄) request...I genuinely have no idea about what Alexa expects or not...and I don't really support anything other than HBUP.

Have you tried homebridge-camera-ffmpeg? Can you access the camera that way?

**Comment by rasod** [comment]
@mbcooper9734 out of curiosity what Alexa plugin are you referring to? The most popular one I know of, homebridge-alexa doesn't support cameras at all.
