### ISSUE TITLE
G4 Doorbell no longer chiming HomePods

### ISSUE THREAD

**Issue by PocketTim** [hjdhjd/homebridge-unifi-protect#914]
**Describe The Problem:**
Since updating to v6.4.0+, my UniFi Doorbell G4 is no longer making any of the three HomePod Mini's in the house chime.

All devices have been restarted, my USW and UDM-Pro have all been restarted and POE power cycled, all iOS devices and HomePods are up to date. HomeBridge is on the latest version 1.6. 

The camera and audio feed can be seen in the Home App no problem, and the HomePods have the option to enable or disable chime (which I have cycled) but no chime ever comes through to them.

**To Reproduce:**
Push the doorbell button, only the UniFi protect app is triggered, no chime occurs on the HomePods.

**Environment:**

* **Homebridge Version:** 1.6
* **Node Version:** v18.15.0 (was on 16.9, updated to see if part of issue)
* **Homebridge-UniFi-Protect Plugin Version:** v6.4.1
* **UniFi Protect Version:** 2.2.1
* **UniFi Protect Controller Type:** UDMP
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 16.4.1 (iPhone/HomePod) Apple TV 16.4
* **Operating System and OS Version:** Raspian Bullseye 11

**Comment by hjdhjd** [comment]
@PocketTim I believe this is a specific artifact of running on pre-UniFi OS 3 environments like UDMPs are currently.

Can you confirm what the LAST working version is to confirm this for me? I'd like to get this solved for folks like you.

**Comment by PocketTim** [comment]
> @PocketTim I believe this is a specific artifact of running on pre-UniFi OS 3 environments like UDMPs are currently.
> 
> Can you confirm what the LAST working version is to confirm this for me? I'd like to get this solved for folks like you.

You're going to hate me for this but I honestly can't remember. We don't get a huge amount of visitors and so I cannot say with confidence at exactly what point it stopped working. It may have been an update to the plugin that killed the functionality, however, I have just also in the last few days brought every iOS device to 16.4.1 and accepted the update to HomeKit suggested in the app too. As a fellow dev I'm ashamed to say I've become my own worst, enemy and I've been foolish and changed too many variables to say for certain which one may have caused damage.

I can say for certain however, that I've been on v2+ (pre OS3 of UniFi) for quite some time now as partook in the early access of it. I'm now on stable and have been for about a month and haven't noticed any issues with the chime throughout that period.

I'm happy to downgrade the plugin a few versions if that's at all helpful/possible. Just tell me how and I'll be happy to experiment if you think it will help get to the bottom of it.

**Comment by PocketTim** [comment]
> First, try v6.4.2...see if that helps. Just released it.
> 
> Second...if that doesn't work, in the Homebridge webUI...go to the plugins tab...click on the wrench icon for HBUP, and install alternate version. There will be a full list of prior releases you can install.

So I tried the new version, that didn't work. I then rolled back to 6.3.0, and not only did that not work but killed video access in the Home app as well with the following error in the log:

`typeerror: this.nvr.ufpApi.fetch is not a function    at ProtectStreamingDelegate.getSnapshot (file:///usr/lib/node_modules/homebridge-unifi-protect/src/protect-stream.ts:933:44)    at ProtectCamera.configureSnapshotUpdates (file:///usr/lib/node_modules/homebridge-unifi-protect/src/protect-camera.ts:645:26)    at ProtectCamera.configureDevice (file:///usr/lib/node_modules/homebridge-unifi-protect/src/protect-camera.ts:154:15)    at processTicksAndRejections (node:internal/process/task_queues:95:5)[12/04/2023, 11:12:04] [homebridge-unifi-protect] Child bridge process ended`

Version 6.2.X and 6.1.X also produced the same outcome.

So now I've rolled back to 5.5.4 and all is working as it should. I think I'll stick on this version for the time being (as I've got a lot of deliveries coming this week). However if you have further suggestions or want me to do any testing with more versions, please let me know.

**Comment by hjdhjd** [comment]
Well…stick with what works for you, to be certain. That said - when you’re ready, please reopen this issue and happy to work through the challenges with you. For what it’s worth, I tested on an RPi I lad lying around without an issue…the only variable between us is that you have a UDMP.

I’d like to understand exactly what is and isn’t working in the current release for you - is the only issue you have relate to chimes? Does the Homebridge log show you the doorbell rings occurring?

**Comment by PocketTim** [comment]
> Well…stick with what works for you, to be certain. That said - when you’re ready, please reopen this issue and happy to work through the challenges with you. For what it’s worth, I tested on an RPi I lad lying around without an issue…the only variable between us is that you have a UDMP.
> 
> I’d like to understand exactly what is and isn’t working in the current release for you - is the only issue you have relate to chimes? Does the Homebridge log show you the doorbell rings occurring?

Ideally I'd like to leave this open and get to the bottom of it, was much happier with the video performance of the newer versions but the chime is my defacto reason for using your plugin as I have no hardware chime in the house and don't have easy means to add one.

When I get some time later I'll go back up to latest version and check the logs for you, see what it comes back with.

**Comment by hjdhjd** [comment]
I don't like keeping issues open without activity...don't worry, I'm still here. You can add to this issue if it auto-closes. 😄 

That said, the chime is one of my de facto reasons for creating the plugin...I'm all for chasing it down. When you get a chance, using the latest released version of HBUP:

1. Check to see if doorbell rings are detected by HBUP. Ring events are logged by default, so you should see it in the Homebridge logs if it's detected.
2. Assuming the answer to (1) is that you do **not** see it detected, humor me and delete and recreate the local user account you created for Homebridge on the UDMP. I've seen issues similar to this, primarily on UniFiOS3+, but there seems to be some funkiness that Ubiquiti has in some versions with respect to permissions/user setup. This is a total moonshot, but harmless ultimately if it doesn't work.
3. Try disabling the doorbell in HBUP, restart Homebridge, and then add it back in so it gets flushed out of HomeKit and see if that works. A more annoying step to be sure...but let's see.

**Comment by hjdhjd** [comment]
> I'm pretty sure I am experiencing the same issue. Unfortunately, this was a newly installed device after the 6.4 upgrade, so it technically hasn't ever worked.
> 
> I noticed that the device shows up as a camera in homebridge and the home app, not as a doorbell as I would have expected. I have a feeling this may be the root cause of the issue.
> 
> Your questions above:
> 
> 1. Rings are not detected, and nothing shows up in the logs.
> 2. No joy, same issue
> 3. I'm not sure how to do this.  Is this the "Make this device available in HomeKit"?
> 
> Edit to add Environment info:
> 
> Homebridge Version: 1.6 Node Version: v18.13 Homebridge-UniFi-Protect Plugin Version: v6.4.2 UniFi Protect Version: 2.2.1 UniFi Protect Controller Type: UDMP Apple Device and iOS / macOS / iPadOS / tvOS Version: iOS 16.4.1 (HomePod) Apple TV 16.4 Operating System and OS Version: Ubuntu Focal Fossa (20.04.5 LTS)

Please do not hijack someone else's support request @JonathanOBrien. If you'd like support, please open a new issue. Thanks for respecting the way I choose to provide support. I'm only working with @PocketTim here.

**Comment by JonathanOBrien** [comment]
> > I'm pretty sure I am experiencing the same issue. Unfortunately, this was a newly installed device after the 6.4 upgrade, so it technically hasn't ever worked.
> > I noticed that the device shows up as a camera in homebridge and the home app, not as a doorbell as I would have expected. I have a feeling this may be the root cause of the issue.
> > Your questions above:
> > 
> > 1. Rings are not detected, and nothing shows up in the logs.
> > 2. No joy, same issue
> > 3. I'm not sure how to do this.  Is this the "Make this device available in HomeKit"?
> > 
> > Edit to add Environment info:
> > Homebridge Version: 1.6 Node Version: v18.13 Homebridge-UniFi-Protect Plugin Version: v6.4.2 UniFi Protect Version: 2.2.1 UniFi Protect Controller Type: UDMP Apple Device and iOS / macOS / iPadOS / tvOS Version: iOS 16.4.1 (HomePod) Apple TV 16.4 Operating System and OS Version: Ubuntu Focal Fossa (20.04.5 LTS)
> 
> Please do not hijack someone else's support request @JonathanOBrien. If you'd like support, please open a new issue. Thanks for respecting the way I choose to provide support. I'm only working with @PocketTim here.

My intent was to help fix the issue, not hijack someone else's support request.  5.5.4 works still, so I'll see my way out.

**Comment by hjdhjd** [comment]
@JonathanOBrien Poor choice of words perhaps on my part, but thanks for respecting how I choose to mind my little corner of the world. Happy to provide you support, just not in someone else's support thread. Thanks again.

**Comment by henkied** [comment]
same issue here now back on 5.5.4

**Comment by hjdhjd** [comment]
Fixed in 6.4.4. Open a new issue if it persists. Thanks!
