### ISSUE TITLE
External motion sensor, trigger protect detection

### ISSUE THREAD

**Issue by tbaur** [hjdhjd/homebridge-unifi-protect#918]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**
Potential for a new automation, where having an external (non unifi) motion sensor fire, which would trigger homekit automation and force a unifi protect detection plus "motion recording" event, even if the protect camera itself did not detect motion per se. There are cases of motion, that protect cameras do not actually sense. If I can use other sensors to further support, that would be perfect.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by hjdhjd** [comment]
Thanks for the suggestion, but these features already exist - it’s called a motion trigger. 

If your intention is to trigger a motion recording event on the Protect **controller** - nope. That’s not going to happen with this plugin. There’s no known way to force the Protect controller to record an arbitrary event.

**Comment by tbaur** [comment]
Right, motion trigger doesn't force a recording event, already known -- thats what I asked originally, re does the API exist, so apparently not. Thanks.

**Comment by hjdhjd** [comment]
Best of luck. Cheers.
