### ISSUE TITLE
Github spamming me with 500+ emails from this project in last 8hrs

### ISSUE THREAD

**Issue by brianmedia** [hjdhjd/homebridge-unifi-protect#920]
**Describe The Problem:**

Getting inundated by mass emails from the project today. over 500 today alone

Sample

![CleanShot 2023-04-15 at 20 58 33](https://user-images.githubusercontent.com/12058199/232260537-49d38552-7c2e-417f-846f-2ab76278a602.png)

**To Reproduce:**

NA

**Logs:**

NA

**Homebridge Configuration:**
NA

**Screenshots:**

NA

**Environment:**

* **Homebridge Version:**  NA
* **Node Version:**  NA
* **Homebridge-UniFi-Protect Plugin Version:** 
* **UniFi Protect Version:**  NA
* **UniFi Protect Controller Type:**  NA
* **UniFi Protect Controller Firmware Version:**  NA
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** NA
* **Operating System and OS Version:**  NA

 NA

**Comment by hjdhjd** [comment]
Yep - instituting a new moderation policy and there’s going to be a one-time cleanup across the entirety of this project. You can disable alerts if you prefer, but it should be all done within a day or two. Cheers.
