### ISSUE TITLE
Name of the buttons for Cameras

### ISSUE THREAD

**Issue by PrzemyslawKlys** [hjdhjd/homebridge-unifi-protect#921]
**Describe The Problem:**
I have about 10 cameras and DoorBell Pro. I've noticed that I can go into camera or a doorbell and see related accessories. DoorBell Pro comes with 6 related accesories. Is there a way to know which one is which because in my HomeKit they are all named the same way which makes it very hard to figure out what those are for. 

Would it be possible to name them automatically "Camera <ThisButtonDoesThis>"? Or it's not possible and we have to find our own way around it? Aka go thru 40+ buttons, figure out what they do and rename them?

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** 18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 6.4.4
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** UNVR PRO

**Comment by hjdhjd** [comment]
Thanks for the report - all the cameras and related accessories are in fact named and coincide with what’s in Protect, initially unless you rename them. 

The issue is the Home app, and its recent changes in the way Apple chooses to organize things. If you use a non-Apple HomeKit app (Eve, Home+, etc.) you’ll be able to see the names as they’re intended to be, and you should be able to further rename things in any HomeKit app as you’d like. Best of luck.

**Comment by PrzemyslawKlys** [comment]
That's not what I am seeing. Even in eve app I only see Power next to all buttons.

![image](https://user-images.githubusercontent.com/15063294/233077283-e245dacb-ada1-4221-bd31-7611c3ebfacb.jpeg)

Could it be a case that i have been upgrading all the time and something got lost?

**Comment by hjdhjd** [comment]
This is a bug in iOS 16: https://github.com/homebridge/homebridge/issues/3210

Hopefully Apple gets to it at some point....

**Comment by PrzemyslawKlys** [comment]
@hjdhjd Can you take a look at this Discord channel discussing this issue: 
- https://discord.com/channels/432663330281226270/432672072859385856/1040394094528188416

![image](https://user-images.githubusercontent.com/15063294/234067765-25711a27-38a4-4b0f-9528-e5dba5e64458.png)

I've found it while lurking in this issue:
- https://github.com/thoukydides/homebridge-homeconnect/issues/116
