### ISSUE TITLE
Restart option 

### ISSUE THREAD

**Issue by heggink** [hjdhjd/homebridge-unifi-protect#923]
**Is your feature request related to a problem? Please describe:**

No
**Describe the solution you'd like:**

I'd like an option to restart the doorbell. Any mqtt topic that could support this?
**Describe alternatives you've considered:**

None possible 
**Additional context:**

I have a doorbell that sometimes locks itself. Restarting from the app works. Would be great to be able to automate.

**Comment by hjdhjd** [comment]
Appreciate the request, but I won’t be adding this feature. HBUP is already quite feature rich, and I view niche cases like this as being largely beyond the scope of what I’d like to provide from a user experience perspective.

Best of luck.
