### ISSUE TITLE
Delay X minutes after first notification (prevent notification spam)

### ISSUE THREAD

**Issue by herbi3** [hjdhjd/homebridge-unifi-protect#924]
**Is your feature request related to a problem? Please describe:**

Notification spam from the one event, I.e, if I walk from my door to the end of the driveway, two cameras detect me, and I get a notification from HomeKit x2 times every second or two (motion settings are set to 10s in protect)

**Describe the solution you'd like:**

Option within this plugin to ignore subsequent notifications after the first one for X minutes

**Describe alternatives you've considered:**

I enable the manual switches in plugin, and configured iOS automation to turn off the motion, people switches etc after 10 minutes of the first detection, but then EVERY notification after 10 minutes were sent at once, I was getting absolutely flooded with notifications. That workaround does not work nicely 

**Additional context:**

**Comment by hjdhjd** [comment]
Thanks for the request, this isn’t something that should be dealt with at the plugin level, rather it’s configuration should take place in how you define your motion zones either on the Protect controller, or in HKSV.

Best of luck.

**Comment by herbi3** [comment]
One camera looks down the driveway. If I walk down the driveway, I get 3-4 notifications... it needs to be at the plugin level since it needs to delay the subsequent notifications after sending the first one.

If I change the activity window then I may as well not have a camera there at all.
