### ISSUE TITLE
Delay X minutes after first notification

### ISSUE THREAD

**Issue by herbi3** [hjdhjd/homebridge-unifi-protect#925]
Is your feature request related to a problem? Please describe:

Notification spam from the one event, I.e, if I walk from my door to the end of the driveway, two cameras detect me, and I get a notification from HomeKit x2 times every second or two (motion settings are set to 10s in protect)

One camera using this plugin will send 3-4 notifications if I simply walk down my driveway. If I change the activity window, then I may as well not have any cameras at all, hence this needs to be at the plugin level since it cannot be adjusted anywhere else.

Describe the solution you'd like:

Option within this plugin to ignore subsequent notifications after the first one for X minutes

Describe alternatives you've considered:

I enable the manual switches in plugin, and configured iOS automation to turn off the motion, people switches etc after 10 minutes of the first detection, but then EVERY notification after 10 minutes were sent at once, I was getting absolutely flooded with notifications. That workaround does not work nicely

**Comment by hjdhjd** [comment]
The motion duration setting already exists - you can set it for as long as you’d like directly, though the webUI will not let you set it higher than 20 seconds. If you want to set it to ten minutes between motion events, then go ahead and set motionDuration to 600 in the configuration JSON.

I have no plans to implement anything beyond that at this time.

Best of luck.
