### ISSUE TITLE
Configured Names for sub-switches

### ISSUE THREAD

**Issue by PrzemyslawKlys** [hjdhjd/homebridge-unifi-protect#931]
**Describe The Problem:**

This is continuation of:
- https://github.com/hjdhjd/homebridge-unifi-protect/issues/921

Sorry if you have read it and it's not that, but since bot closed it and you may be ignoring additions to dead issues but wanted to try and point you in the right direction. Again sorry, if you're aware about it.

@hjdhjd Can you take a look at this Discord channel discussing this issue: 
- https://discord.com/channels/432663330281226270/432672072859385856/1040394094528188416

![image](https://user-images.githubusercontent.com/15063294/234067765-25711a27-38a4-4b0f-9528-e5dba5e64458.png)

I've found it while lurking in this issue:
- https://github.com/thoukydides/homebridge-homeconnect/issues/116

The author of the other plugin seems to say it fixed his issues, so maybe (?) applicable to this plugin as well. And from what he says it's exactly what I see in my HomeKit for lots of Homebridge devices.

**Homebridge Configuration:**

Not applicable, affects all configurations.

**Environment:**

* **Homebridge Version:** 1.6.0
* **Node Version:** 18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 6.4.4
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** UNVR PRO
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
Appreciate it. I’ll look into this. Thanks for raising it.

**Comment by hjdhjd** [comment]
Fixed in v6.5.0.
