### ISSUE TITLE
Wait until someone else in this home stops viewing this camera and try again

### ISSUE THREAD

**Issue by AndrewMorsillo** [hjdhjd/homebridge-unifi-protect#94]
**Describe The Problem:**
I left a stream from a g3 micro running for a long time (hours, as a baby monitor). When I came back to it the screen was black and the stream was not running.

Now if I attempt to stream the camera from any device the Home app says "Camera not available. Wait until someone else in this home stops viewing this camera and try again"

If I restart homebridge the camera is available again. I suspect that homebridge-unifi-protect is not handling a case where a connection is interrupted or some sort of timeout happens after which the camera is still marked as "in use" when there are actually no streams running.

**To Reproduce:**
Leave a stream running for a long time, wait for it to stop on its own, then try to reconnect to the camera.

**Logs:**
None. When attempting to connect to the camera nothing is logged.

**Homebridge Configuration:**

```json
   {
            "controllers": [
                {
                    "address": "192.168.1.xxx",
                    "password": "mypassword",
                    "username": "myusername"
                }
            ],
            "platform": "UniFi Protect"
        }
```

**Screenshots:**
N/A

**Environment:**

* **Homebridge Version**: 1.2.2
* **Homebridge UniFi Protect Version**: 3.7.5
* **Operating System and OS Version**: Win 10

**Comment by hjdhjd** [comment]
Thanks for the report. Where to start...you're really quite the edge case. :smile:

Congrats on the baby front!

What Apple devices are you using, and what iOS versions are we talking about?

**Comment by AndrewMorsillo** [comment]
I'm using iOS 14 on an iPad (7th gen I think) and an iPhone 11 pro. 

I haven't been able to replicate the exact issue so far but the stream does seem to fail after several hours regularly. Only once did it give me the specific error above, the rest of the times homebridge was hung and I had to manually restart it. Sorry I wasn't able to grab logs at the time, if it happens again I'll see if I can grab anything interesting.

**Comment by hjdhjd** [comment]
I'd chalk this up to iOS 14 bugs for the time being...I've run cameras for 24+ hours without an issue.

Wait for iOS 14.1 or 14.2...see if the issue persists...and open a new bug report if it persists, or if you can reliably recreate this with a specific set of steps.

Good luck!
