### ISSUE TITLE
No chime and error with FFMPEG an hardware acceleration

### ISSUE THREAD

**Issue by tbone7467** [hjdhjd/homebridge-unifi-protect#946]
**Describe The Problem:**
[5/30/2023, 9:22:49 PM] [UniFi Protect] Error running FFmpeg: Command failed: /usr/bin/vcgencmd get_mem gpu

[5/30/2023, 9:22:49 PM] [UniFi Protect] Unable to complete plugin startup without a working version of FFmpeg.

I also can not get the Doorbell pro to chime thru my HomePods. I had this feature working before I reset my whole network for another issues.

**To Reproduce:**
restart Homebridge this error comes up every time. I have tried Sudo Raspi-config to set memory to no avail. I also tried this install process https://www.npmjs.com/package/ffmpeg-for-homebridge

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
 "controllers": [
                {
                    "address": "Godzilla",
                    "password": 
                    "username": 
                }
            ],
            "name": "UniFi Protect",
            "platform": "UniFi Protect"
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** <1.6.1>
* **Node Version:** <18.16.0>
* **Homebridge-UniFi-Protect Plugin Version:**6.7.0
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
You’re on a Raspberry Pi 4, I presume. You don’t have vcgencmd available where HBUP expects it. You can google around for where to get those tools or how to install them: I provide no support how to do it.

I’ll improve the error reporting in a future version to make this a bit more clear, though hardware acceleration will not be enabled without having the above tools available and installed on your RPi.

Best of luck and thanks for the report.

**Comment by hjdhjd** [comment]
Regarding HomePod chimes: if HBUP logs show that a doorbell ring has been detected, it’s passed on the event to HomeKit, beyond that, it’s a black box. You might want to reboot your HomePods and see if that helps. You can also search the web to see how people resolved similar issues with other HomeKit doorbells - this is a general HomeKit issue especially if you reset your network, not an HBUP one, assuming the doorbell rings are logged in the Homebridge log, indicating the ring has been detected and sent to HomeKit.

**Comment by tbone7467** [comment]
Thank you I’ll keep trying to look for it. I have had no luck so far. If you have any suggestions on where to look I appreciate it. Than you for the plug in I love it. As for the chime I can’t get the door bell to pass it to HomePod. Is there something I’m missing? Sent from my iPhoneOn May 31, 2023, at 11:29 AM, hjdhjd ***@***.***> wrote:﻿
You’re on a Raspberry Pi 4, I presume. You don’t have vcgencmd available where HBUP expects it. You can google around for where to get those tools or how to install them: I provide no support how to do it.
I’ll improve the error reporting in a future version to make this a bit more clear, though hardware acceleration will not be enabled without having the above tools available and installed on your RPi.
Best of luck and thanks for the report.

**Comment by tbone7467** [comment]
Thank you I appreciate this. I got this email after I replied sorry. Sent from my iPhoneOn May 31, 2023, at 11:31 AM, hjdhjd ***@***.***> wrote:﻿
Regarding HomePod chimes: if HBUP logs show that a doorbell ring has been detected, it’s passed on the event to HomeKit, beyond that, it’s a black box. You might want to reboot your HomePods and see if that helps. You can also search the web to see how people resolved similar issues with other HomeKit doorbells - this is a general HomeKit issue especially if you reset your network, not an HBUP one, assuming the doorbell rings are logged in the Homebridge log, indicating the ring has been detected and sent to HomeKit.

**Comment by hjdhjd** [comment]
Should be a native command on the RPi4. Try typing in `vcgencmd` on the command line on your RPi and see if it finds it. Otherwise - you might want to try updating the OS/tools on your RPi and see if that helps. A future version will address this to make it a bit more robust and fail more gracefully.

**Comment by tbone7467** [comment]
Thank you for your time. Sent from my iPhoneOn May 31, 2023, at 11:50 AM, hjdhjd ***@***.***> wrote:﻿
Should be a native command on the RPi4. Try typing in vcgencmd on the command line on your RPi and see if it finds it. Otherwise - you might want to try updating the OS/tools on your RPi and see if that helps. A future version will address this to make it a bit more robust and fail more gracefully.

**Comment by tbone7467** [comment]
Your brilliant!! I reset the HomePods again a that worked perfectly. Is there a contribute button for your plug in? Sent from my iPhoneOn May 31, 2023, at 11:31 AM, hjdhjd ***@***.***> wrote:﻿
Regarding HomePod chimes: if HBUP logs show that a doorbell ring has been detected, it’s passed on the event to HomeKit, beyond that, it’s a black box. You might want to reboot your HomePods and see if that helps. You can also search the web to see how people resolved similar issues with other HomeKit doorbells - this is a general HomeKit issue especially if you reset your network, not an HBUP one, assuming the doorbell rings are logged in the Homebridge log, indicating the ring has been detected and sent to HomeKit.
