### ISSUE TITLE
Can't watch livestream on local network

### ISSUE THREAD

**Issue by romainmunier** [hjdhjd/homebridge-unifi-protect#948]
**Describe The Problem:**
Hello,

First aff all, thank you very much for your work.

When I'm on my wifi network, I can't view the live feed from my Unifi G3 Instant cameras. However, the thumbnail display updates correctly.

When I switch to the 5G network, I can see the stream from my cameras again.

The cameras are connected to the same wifi network as me, and Homebridge is connected to the same VLAN as my cameras and iPhone.

The logs say I can stream but on my iPhone it says camera not responding

**Logs:**
```
[6/2/2023, 10:13:12 AM] [UniFi Protect] Cloud Key [UCK-G2-PLUS] Canapé [G3 Instant]: Streaming request from 10.10.5.X: 1280x720@30fps, 299 kbps. Using 1920x1080@30fps (High), 3000 kbps.
[6/2/2023, 10:13:37 AM] [UniFi Protect] Cloud Key [UCK-G2-PLUS] Canapé [G3 Instant]: Stopped video streaming session.
```

**Homebridge Configuration:**

```json
{
            "controllers": [
                {
                    "address": "...",
                    "password": "...",
                    "username": "..."
                }
            ],
            "name": "UniFi Protect",
            "options": [
                "Enable.Log.Motion.D021F9D667C5",
                "Enable.Motion.SmartDetect.ObjectSensors.D021F9D667C5",
                "Enable.Motion.SmartDetect.D021F9D667C5"
            ],
            "occupancyDuration": 300,
            "motionDuration": 10,
            "verboseFfmpeg": false,
            "platform": "UniFi Protect"
        }
```

**Screenshots:**
![image](https://github.com/hjdhjd/homebridge-unifi-protect/assets/60402546/bfe4f250-250e-448b-8c36-8015c87a6191)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.13.0
* **Homebridge-UniFi-Protect Plugin Version:** 6.7.0
* **UniFi Protect Version:** 2.7.34
* **UniFi Protect Controller Type:** UCK Gen 2+
* **UniFi Protect Controller Firmware Version:** UCK G2 Plus v3.0.17
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 14 Pro / Apple TV 4K / iPad Air 4
* **Operating System and OS Version:** MacOS

**Comment by hjdhjd** [comment]
Generally an issue like this has to do with Homebridge not knowing which interface to send out local streaming traffic to. Take a look at the troubleshooting documentation for HBUP: https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/docs/Troubleshooting.md#network-issues

Follow the link to the Homebridge documentation on how to do that. Best of luck.

**Comment by romainmunier** [comment]
I had already tried this method and it hadn't worked. I've just tried it again and it seems to be working.

Thank you very much for your time and help!
