### ISSUE TITLE
No hardware accelerated decoding on Raspberry Pi 4 Model B Rev 1.5 

### ISSUE THREAD

**Issue by MiOrt** [hjdhjd/homebridge-unifi-protect#949]
**Describe The Problem:**
Upon start of Homebridge I get the message "...: Unable to enable hardware accelerated decoding. Your video processor does not have support for the h264_mmal decoder. Using software decoding instead."

In config.txt the settings are 
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

With config-tool I set GPU Memory to 128

**To Reproduce:**
Restart Raspi or Homebridge

**Logs:**
[8.6.2023, 09:14:15] [homebridge-unifi-protect] Dream Machine Pro [UDM-PRO] G3 Instant [G3 Instant]: Unable to enable hardware accelerated decoding. Your video processor does not have support for the h264_mmal decoder. Using software decoding instead.
[8.6.2023, 09:14:15] [homebridge-unifi-protect] Dream Machine Pro [UDM-PRO] Tuerklingel [G4 Doorbell]: Unable to enable hardware accelerated decoding. Your video processor does not have support for the h264_mmal decoder. Using software decoding instead.
[8.6.2023, 09:14:15] [homebridge-unifi-protect] Dream Machine Pro [UDM-PRO] Kamera Torhaus [G4 Bullet]: Unable to enable hardware accelerated decoding. Your video processor does not have support for the h264_mmal decoder. Using software decoding instead.
[8.6.2023, 09:14:15] [homebridge-unifi-protect] Dream Machine Pro [UDM-PRO] Kamera Innenhof [G4 Bullet]: Unable to enable hardware accelerated decoding. Your video processor does not have support for the h264_mmal decoder. Using software decoding instead.

**Homebridge Configuration:**
{
            "controllers": [
                {
                    "address": "192.168.30.1",
                    "password": "deleted",
                    "username": "deleted"
                }
            ],
            "options": [
                "Enable.Motion.SmartDetect",
                "Disable.Motion.SmartDetect.68D79AE590C7",
                "Disable.Doorbell.Messages.FromDoorbell",
                "Enable.Doorbell.Trigger.68D79ACF6023",
                "Disable.Video.Stream.High"
            ],
            "verboseFfmpeg": false,
            "_bridge": {
                "username": "0E:77:82:65:D5:24",
                "port": 36559
            },
            "platform": "UniFi Protect"
        }

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 6.8.1
* **UniFi Protect Version:** 2.7.34
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 3.0.20
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** n/a
* **Operating System and OS Version:** Bullseye

**Comment by hjdhjd** [comment]
Thanks for the report. HBUP is telling you the issue in its log. The version of FFmpeg you’re using for HBUP doesn’t have h264_mmal support builtin. You can check the list of what codecs your version of FFmpeg supports by looking at the output of

`ffmpeg -codecs | grep h264`

On RPi should see something like:

`DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m h264_mmal ) (encoders: libx264 libx264rgb h264_omx h264_v4l2m2m )`

If you’re using the bundled version of FFmpeg that comes when you install HBUP, it should be located at:

`/where/you/installed/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg`

Beyond that, please note: I provide minimal support for hardware acceleration on any platform. Happy to help where I can, but don’t expect miracles. 😄 

You’re always welcome to ignore the messages - HBUP will work just fine without hardware acceleration, albeit without the extra fun that one might get in using it.

**Comment by MiOrt** [comment]
Thanks for that fast answer. I installed the plugin without any extra configuration through the UI and am not really a linux user. Would you be so kind and shortly point me to the process of installing the required codec? Although everything is running fine I just wanted to reduce the load of the processor by using hardware acceleration. I just discovered the "error messages" after restarting home bridge.

**Comment by hjdhjd** [comment]
Unfortunately, that isn’t trivial, as with most things related to FFmpeg I’m afraid. You can lookup how to compile a version of FFmpeg your system supports more directly, or given that you’re using a Raspberry Pi…my strong suggestion is that you just download the Homebridge Raspberry Pi image and use that. It should already have everything you need.

One more tidbit…I would encourage you to use the Discord and the `#unifi-protect` channel there - there’s a good community to help you get up and running.

Finally - please note that the messages above aren’t telling you that HBUP isn’t working, they are just telling you that it’s going to default to using software-based H.264 decoding rather than the hardware-accelerated capabilities available to do so. My suggestion is that you first get up and running, then work on optimizing the experience to your liking.

Best of luck.

**Comment by MiOrt** [comment]
Ok, thanks a lot
