### ISSUE TITLE
Can't enable HKSV on G4 Doorbell

### ISSUE THREAD

**Issue by bearattack11** [hjdhjd/homebridge-unifi-protect#950]
**Describe The Problem:**
When attempting to change the recording settings of my G4 Doorbell in the Home app to "Stream & Allow Recording", I get a spinning wheel and eventually get an error "There was an error updating the setting for this camera.". Changing to other settings works as expected.

I also have a G3 Bullet camera in my setup, and am able to change the to "Stream & Allow Recording" without any issues.

**To Reproduce:**

1. Go to the G4 Doorbell settings in the Home app
2. Tap "Recording Options"
3. Tap "When Home" (current setting is Stream)
4. Tap "Stream & Allow Recording"

**Logs:**
There are no logs when attempting to enable the setting. Interesting, there is a log for I toggle off the HKSV setting for the G3 Doorbell.

```
[20/06/2023, 21:02:12] [UniFi Protect] [UDM-PRO] Driveway Camera [G3 Bullet]: Disabling HomeKit Secure Video event recording.
```

**Homebridge Configuration:**

```json
"controllers": [
              {
                  "address": "X"
                  "password": "X",
                  "username": "X"
              }
          ],
          "options": [
              "Disable.Doorbell.Messages",
              "Enable.Log.Motion",
              "Enable.Motion.SmartDetect",
              "Enable.Motion.SmartDetect.ObjectSensors",
              "Enable.Video.Transcode.Hardware",
              "Enable.Audio.Filter.Noise.X",
              "Enable.Audio.Filter.Noise.FftNr.X.90",
              "Enable.Audio.Filter.Noise.HighPass.X.200",
              "Enable.Audio.Filter.Noise.LowPass.X.1000"
          ],
          "platform": "UniFi Protect"
```

**Screenshots:**
![IMG_79C88CFA54F2-1](https://github.com/hjdhjd/homebridge-unifi-protect/assets/71990654/b2d5aeb8-e868-4106-a186-99dfc6e3a836)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 6.9.0
* **UniFi Protect Version:** 2.8.28
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 3.0.20
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 13 Pro Max, iOS 16.5
* **Operating System and OS Version:** Raspbian Bullseye 11 (official Homebridge image)

**Comment by hjdhjd** [comment]
Thanks for the report! While I understand why it may appear that HBUP is at issue here, it really isn't. This is a HomeKit issue, not an HBUP one. HomeKit's new architecture will often time out and have all sorts of other delay/hang-related issues when enabling HKSV or altering what alert types you're interested in. HBUP has nothing to do with any portion of that process - HomeKit is a black box to HBUP...when you tap to enable HKSV in the Home app, it's talking to the HomeKit hub, not to HBUP. The hub, once it acknowledges the request, will eventually communicate with HBUP.

My advice: reboot your HomeKit hubs and try again. There's nothing to be done here on the plugin end I'm afraid, and the fact that things work fine for your G3 bullet is an indicator that things are working just fine, once HomeKit hub decides to actually communicate with devices on the network.

Best of luck - sorry I can't offer a more satisfying answer here other than reboot your HomeKit hubs and keep trying.

**Comment by bearattack11** [comment]
Rebooting the home hubs did the trick! Thanks so much!
