### ISSUE TITLE
Feature Request: Support for Protect All-In-One Sensor

### ISSUE THREAD

**Issue by guysbrown** [hjdhjd/homebridge-unifi-protect#956]
**Is your feature request related to a problem? Please describe:**
Please add support for the UniFi Protect All-In-One Sensor

**Describe the solution you'd like:**
I like the following sensors exposed to HomeKit:

Temperature
Humidity
Door/Window Sensor
Motion Detecter

**Describe alternatives you've considered:**
None

**Additional context:**
None

**Comment by hjdhjd** [comment]
Please read the documentation. This support has existed since the day the sensors were released to GA. The same is true of **every** UniFi Protect GA product in this plugin. Cheers.
