### ISSUE TITLE
Feature Request - Option to change settings of 'dumb' hardware chimes.

### ISSUE THREAD

**Issue by Robmanzzz** [hjdhjd/homebridge-unifi-protect#959]
**Is your feature request related to a problem? Please describe:**
No technical problem. Just convenience.

**Describe the solution you'd like:**
As previously stated by another user in this request: https://github.com/hjdhjd/homebridge-unifi-protect/issues/854 I(we) would love to see the option to toggle the chime setting. You did implement a way to control the Unifi Chime but I would like to change the setting of the non-Unifi 'dumb' hardware chimebox. 

I've read and searched in the documentation and changelog but at version 6.2.0 it says: 

"New feature: support for chime accessories. They will appear as dimmer accessories in HomeKit and can be used to control the volume level of the Protect chimes. Unfortunately, this is the best we can do given there are no speaker / volume accessories in HomeKit."

So I'm pretty sure it has not yet been implemented.

**Describe alternatives you've considered:**
Changing this setting in Unifi Protect instead.

**Additional context:**

Thanks in advance for considering! :)

![Screenshot 2023-07-13 at 12 48 49](https://github.com/hjdhjd/homebridge-unifi-protect/assets/8589665/b747314d-9cea-4994-9688-cf6bb7879bb2)

**Comment by hjdhjd** [comment]
Thanks for the request…yep, still on the backlog. Stay tuned. Thanks!

**Comment by hjdhjd** [comment]
This will be in the next release of HBUP. 😄 Enjoy!

**Comment by hjdhjd** [comment]
Implemented in v6.11.0.
