### ISSUE TITLE
Ability to coalesce multiple Motion Sensor notifications based on time

### ISSUE THREAD

**Issue by burnflare** [hjdhjd/homebridge-unifi-protect#96]
**Is your feature request related to a problem? Please describe:**
When I'm pacing around in front of one of my UniFi cameras for a couple of minutes, I tend to get 10-30 Motion notification events from HomeKit on my phone which could get frustrating . Would it be possible to have a setting to coalesce these motion events from the same camera based on a time range?

**Describe the solution you'd like:**
Perhaps a new non-default option along the lines of `Enable.MotionSensor.Coalescer` that takes in `seconds` as an input. The HomeBridge plugin could internally start a timer for x seconds when the first Motion event it sent to HomeKit for that particular camera and suppress all future Motion notifications from that camera until that timer expires.

**Comment by hjdhjd** [comment]
Thanks for the suggestion!

RTFM. 😄 

Go to Advanced Settings, Motion Event Duration in the webUI configuration.

**Comment by hjdhjd** [comment]
Granted, it’s not per-camera. I’m reluctant to add that option, because it doesn’t belong in this plugin. You should really adjust the sensitivity on the camera itself...not circumvent it by configuring the plugin instead of configuring your motion zones.

**Comment by burnflare** [comment]
Oooh didn't know about that setting. I'm going to push it up to 30s and try living on that for a while.
