### ISSUE TITLE
Cannot update the plugin

### ISSUE THREAD

**Issue by Markmaster** [hjdhjd/homebridge-unifi-protect#962]
**Describe The Problem:**
Update pop-up in the Homebridge. Running the update causes an error.

**To Reproduce:**
Run update of the plugin

**Logs:**

```
USER: markmaster
DIR: /usr/local
CMD: npm install -g homebridge-unifi-protect@6.11.0

npm ERR! code EEXIST
npm ERR! syscall rename
npm ERR! path /Users/markmaster/.npm/_cacache/tmp/4f4a5551
npm ERR! dest /Users/markmaster/.npm/_cacache/content-v2/sha512/17/3e/a02f35730fcc806520f6bfcda87637db1634829c80fcea5e5fdba18b43e061ba7341978bd3d348295a0f87fd331ba75674526bbcb5c1c4a0fc7cef7f22c8
npm ERR! errno -13
npm ERR! EACCES: permission denied, rename '/Users/markmaster/.npm/_cacache/tmp/4f4a5551' -> '/Users/markmaster/.npm/_cacache/content-v2/sha512/17/3e/a02f35730fcc806520f6bfcda87637db1634829c80fcea5e5fdba18b43e061ba7341978bd3d348295a0f87fd331ba75674526bbcb5c1c4a0fc7cef7f22c8'
npm ERR! File exists: /Users/markmaster/.npm/_cacache/content-v2/sha512/17/3e/a02f35730fcc806520f6bfcda87637db1634829c80fcea5e5fdba18b43e061ba7341978bd3d348295a0f87fd331ba75674526bbcb5c1c4a0fc7cef7f22c8
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in: /Users/markmaster/.npm/_logs/2023-07-24T18_59_33_444Z-debug-0.log

Operation failed. Please review log for details.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** v18.17.0
* **Homebridge-UniFi-Protect Plugin Version:** homebridge-unifi-protect v6.10.0
* **UniFi Protect Version:** 2.8.28
* **UniFi Protect Controller Type:** UDR
* **UniFi Protect Controller Firmware Version:** 2.8.28
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**iOS 16.6
* **Operating System and OS Version:** 13.4.1 (c) (22F770820d)

**Comment by hjdhjd** [comment]
This isn’t an HBUP issue. This is a Homebridge webUI issue. Please open an issue there instead. You might want to simply uninstall the plugin and install it again using the Homebridge webUI. You shouldn’t lose your configuration settings when you uninstall (it should ask). Or do so from the command line.

Best of luck!
