### ISSUE TITLE
Unify Doorbell Pro only shows package camera

### ISSUE THREAD

**Issue by Ab4321** [hjdhjd/homebridge-unifi-protect#963]
**Is your feature request related to a problem? Please describe:**
I have a Unify Doorbell Pro which has two cameras - front facing and downward facing. There is no way to select the front facing camera to show up in HomeKit, it instead only pulls in the downward facing package camera.

**Describe the solution you'd like:**
Pull the feed for both videos or allow you to choose which of the two cameras to pull.

**Describe alternatives you've considered:**
None

**Additional context:**
None

**Comment by hjdhjd** [comment]
Both cameras are exposed in HomeKit already...your feature suggestion was already implemented many months ago. 😄
