### ISSUE TITLE
Liveview scene protect-home with no cameras not being recognised

### ISSUE THREAD

**Issue by dpcryer** [hjdhjd/homebridge-unifi-protect#968]
Brilliant plugin working really well now I've stopped using HOOBS and moved over to HomeBridge so I can be up to date, thank you very much for all your work here.

**Describe The Problem:**

I am using the liveview scenes to control the motion detection of my cameras and am having trouble when I've got no cameras with motion still enabled in the protect-home view. Message being logged when trying to switch to Home mode is:

[8/9/2023, 9:05:38 PM] [UniFi Protect] My CK [UCK-G2-PLUS]: No liveview configured for this security system state. Create a liveview named protect-home in the Protect webUI to use this feature.

If I add a camera to the liveview on the Unifi controller it all works:

[8/9/2023, 9:08:12 PM] [UniFi Protect] My CK [UCK-G2-PLUS]: Setting the liveview scene: protect-home.

I was expecting to have motion detection disabled on all the cameras if there were no camera defined in the liveview scene (I'm using the security system accessory for various other bits of automation which is why I'm trying to use the Home state rather than Off).

Looking at the code I'm guessing it's down to this line in protect-securitysystem.ts:
if(newState !== SecuritySystemCurrentState.DISARMED && !targetCameraIds.length) {

Is it possible to change this logic in some manner so it realises the scene is defined and just processes it accordingly disabling the motion detection on all the cameras.

**To Reproduce:**

Remove all cameras from the protect-home liveview in the Unifi UI
Change the security system state to Home

(from the code I'd expect this to happen for the other states as well but doing the same for protect-night on my system didn't cause the same symptoms which surprised me).

**Logs:**

No cameras present in liveview protect-home, other liveviews working correctly:
[8/9/2023, 9:05:38 PM] [UniFi Protect] My CK [UCK-G2-PLUS]: No liveview configured for this security system state. Create a liveview named protect-home in the Protect webUI to use this feature.
[8/9/2023, 9:06:22 PM] [UniFi Protect] My CK [UCK-G2-PLUS]: Setting the liveview scene: protect-away.
[8/9/2023, 9:06:22 PM] [UniFi Protect] My CK [UCK-G2-PLUS]: protect-away -> G3 Flex: Motion detection enabled.
[8/9/2023, 9:06:22 PM] [UniFi Protect] My CK [UCK-G2-PLUS]: protect-away -> G3 Instant: Motion detection enabled.

Added a camera to liveview protect-home and it now sets the cameras motion detection as expected:
[8/9/2023, 9:08:12 PM] [UniFi Protect] My CK [UCK-G2-PLUS]: Setting the liveview scene: protect-home.
[8/9/2023, 9:08:12 PM] [UniFi Protect] My CK [UCK-G2-PLUS]: protect-home -> G3 Flex: Motion detection disabled.

**Homebridge Configuration:**

```json
        {
            "controllers": [
                {
                    "address": "xxx.xxx.x.x",
                    "password": "xxxxxxxxxxxxxxxx",
                    "username": "xxxxxx"
                }
            ],
            "name": "UniFi Protect",
            "options": [
                "Enable.Motion.Switch"
            ],
            "platform": "UniFi Protect"
        }
```

**Screenshots:**

N/A

**Environment:**

* **Homebridge Version:** v1.6.1
* **Node Version:** v18.13.0
* **Homebridge-UniFi-Protect Plugin Version:** homebridge-unifi-protect v6.12.0
* **UniFi Protect Version:** Protect 2.8.35
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** UCK G2 Plus v3.1.14
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** AppleTV 4K latest TvOS
* **Operating System and OS Version:** Docker on Synology NAS

**Comment by hjdhjd** [comment]
Thanks for the compliment and the report! The behavior is documented and exists by design and won't be changing. The `Off` setting is what you want. :smile: 

You may not like the semantics, but they exist for a reason, namely ensuring that the state is never ambiguous when it comes to when motion is disabled and for which cameras: you **must** explicitly opt cameras into liveview scenes. There's no getting around it.

Thanks again!

**Comment by dpcryer** [comment]
Thanks for your really quick response and updates there.

I'm afraid I'm still slightly confused based on the documentation. I thought that the "protect-home" liveview was one of the liveviews associated with the security system accessory so from the docs...

_It will lookup all the cameras associated with that liveview and activate motion detection for those cameras, and it will disable motion detection on all other cameras. Put another way - when using this feature, and you enable a specific security system state, only those cameras will have motion detection active. All other cameras will have motion detection set to off._ 

and

_The security system accessory will disable motion detection on all cameras not explicitly configured in a given liveview scene_

My scene has no cameras explicitly configured so I thought that motion detection should be disabled on all of my cameras.

Sorry about this, I'm not trying to be awkward, and if I'm missing something really obvious I'm more than happy to have it pointed out.

**Comment by hjdhjd** [comment]
No worries. The component you are missing is that you have no cameras configured for a liveview state.

***You must have at least one camera configured for a given liveview scene***. This is an intentional design decision on my part.

Meaning that if you have no cameras configured for the *protect-home* liveview scene, it will be ignored, entirely.  This is also in the documentation you are referencing, at the end of the introduction:

> Please note: by design, you must have at least one camera configured in a given liveview scene. The reason for this is to ensure there is no ambiguity in which cameras will and will not have motion detection enabled. The Off state in the [security system](https://github.com/hjdhjd/homebridge-unifi-protect/issues/968#security-system) accessory is intentionally the only one that will universally disable motion detection across all cameras (presuming you don't override this behavior as described below).

The only way to get all cameras to disable motion detection at once through a single setting is to use the *off* state in the security system accessory.

The alternative way to accomplish what you want, as I shared above, is to use the **motion switch** feature option, which will add a switch accessory on a given camera or all cameras, and enable or disable motion detection through automation or manually.

**Comment by dpcryer** [comment]
Ah, that's very obvious now you point it out - it's even in bold!!! Sorry to have wasted your time on this, I'll work out how I want to work round it to get the behaviour I'm wanting.

Thanks again for a great plugin.
