### ISSUE TITLE
Camera feeds show "No Response" when viewing outside network

### ISSUE THREAD

**Issue by iTim314** [hjdhjd/homebridge-unifi-protect#972]
**Describe The Problem:**
All camera feeds work as expected as long as I am looking on a device that's connected to the local network / WiFi. If I disconnect from the WiFi and switch to cellular — with or without a VPN connection back to my home network — all cameras show "No Response" in the Home app. 

**To Reproduce:**
1. Disconnect from the LAN
2. Try to view any camera

**Logs:**
I looked to see if any logs were generated when the camera failed to stream, and there were none. If I'm on WiFi and can get the stream to work, I see a log showing that the stream starts, but not outside the network.

Example of a successful stream (does NOT show outside network):

```
UDM-Pro [UDM-PRO] Alley [G4 Dome]: Streaming request from 10.x.x.x: 1280x720@30fps, 299 kbps. Using 640x360@24fps (Low), 300 kbps.
```

**Homebridge Configuration:**

```json

        {
            "controllers": [
                {
                    "address": "10.y.y.y",
                    "password": "redacted",
                    "username": "redacted"
                }
            ],
            "name": "UniFi Protect",
            "options": [
                "Enable.Video.Stream.Only.Low"
            ],
            "_bridge": {
                "username": "redacted",
                "port": 40913
            },
            "platform": "UniFi Protect"
        }
```

**Screenshots:**
![IMG_1545](https://github.com/hjdhjd/homebridge-unifi-protect/assets/57271008/d56dfb23-f33a-4f1c-9e86-f674fd208f2f)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 6.12.2
* **UniFi Protect Version:** 2.8.35
* **UniFi Protect Controller Type:** UDMP
* **UniFi Protect Controller Firmware Version:** 3.1.15
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iPhone 12, iOS 16.6
* **Operating System and OS Version:** Ubuntu 22.04.2

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. —>

**Comment by hjdhjd** [comment]
Appreciate the report but I will direct you to the troubleshooting documentation and the Homebridge Discord. This isn’t an HBUP issue from what I can see - this is either a network setup issue, a configuration issue on the machine you are using for Homebridge, or your home hubs may be acting funky and need to rebooted.

Unfortunately that’s about the extent of the support I provide on here for a configuration issue rather than a bug - happy to help, along with the community, on Discord.

But first I would start with the troubleshooting documentation. 😀

**Comment by iTim314** [comment]
Hi @hjdhjd. I appreciate the quick response. I did review the troubleshooting guide yesterday. I tried restarting all by hubs, and then enabled `Enable.Video.Stream.Only.Low` as suggested in the guide. The problem persists. 

I will engage on Discord.
