### ISSUE TITLE
UP-Sense - Contact sensor enable/disable switch

### ISSUE THREAD

**Issue by jaredfiorali** [hjdhjd/homebridge-unifi-protect#975]
**Is your feature request related to a problem? Please describe:**
No problem, just a feature request!

**Describe the solution you'd like:**
I'd like to have a switch that could turn contact sensors on and off. Currently the UP-Sense has the contact sensor feature exposed to HomeKit, but I was looking to automate an alarm if the sensor detects a door is open. By having a switch to enable this, I can set the contact sensor to trigger only when I've left the house.

**Describe alternatives you've considered:**
Since the sensor is exposed already, I've thought about simply using notifications, but I'm worried I'll get notification blindness after a while since I open and close the doors when I'm at home.

**Additional context:**
I know there are other switches to enable/disable features (motion for example on cameras). I also [submitted a motion request for the UP-Sense earlier](https://github.com/hjdhjd/homebridge-unifi-protect/issues/889#issue-1615695521). Would be nice to have a similar feature for the contact sensor.

Also just want to say that this app is AMAZING. Top notch work! Really appreciate your hard work!

**Comment by hjdhjd** [comment]
Unlikely to add this one at this time...I just don't see a pervasive need for something that can be managed by setting the appropriate constraints on notifications.

You can selectively tell HomeKit to not notify you about certain things if you're home...and with a fair amount of granularity (notify when someone is home vs everyone vs no-one etc.). Why is that insufficient?

**Comment by jaredfiorali** [comment]
Ah, good point. Are you suggesting I create an automation that will only run when certain people aren't home? Currently my automations are:

- When all people leave the home, the home is armed for away
- The motion sensors for the UP-Sense devices are enabled
- An existing automation is set to trigger an "Alarm" scene if motion is detected on any device

I guess if I modified the automations to only run when the designated people aren't home, then the contact sensors can be used in that case. I'll try that first and get back to you.

Thanks for the suggestion, and I appreciate the fast turn around!
