### ISSUE TITLE
Event License Plate detected notification with recognized license plate as content

### ISSUE THREAD

**Issue by appcoders** [hjdhjd/homebridge-unifi-protect#976]
**Is your feature request related to a problem? Please describe:**
I own an AI Pro camera which automatically detects license plates. Unfortunately, the license plates are only shown in Protect Desktop app and cannot be used for real-time notifications (e.g. blacklist, open gate on certain licenses plates and so on).

**Describe the solution you'd like:**
Provide a notification with the recognized license plate to build other actions on it, e.g. open a gate.

**Describe alternatives you've considered:**
Non yet.

**Additional context:**
If I can help you with API debugging or things like that, please let me know.

**Comment by hjdhjd** [comment]
You can already action based on any license plate being detected at all, assuming you've enabled the object sensors feature option.

Actioning based on specific license plates...stay tuned. It's already on the backlog. Thanks.
