### ISSUE TITLE
Remote video slow. 

### ISSUE THREAD

**Issue by jacobhallgren** [hjdhjd/homebridge-unifi-protect#982]
**Describe The Problem:**
Hi

I have problem with remote streams. Its very slow and sometimes even not responding. The local streams are instant. The unifi app works great remote but not streams from this plugin. I have 4G/LTE with 80 mbit/s and home I have 250mbit up and down. Tried to turning on/off transcoding even change  to low video quality. No improvement. 

Looking for suggestions.  

**To Reproduce:**
Open the a camera stream remote

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

    "name": "UniFi Protect",
            "options": [
                "Disable.Device.F4E2C60DA8F9",
                "Enable.Video.Transcode.Hardware.F4E2C60E9356"
            ],

**Screenshots:**

**Environment:**

* **Homebridge Version:** v18.16.0
* **Node Version:** v18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** v6.14.0
* **UniFi Protect Version:** 2.8.35
* **UniFi Protect Controller Type:** UDM SE
* **UniFi Protect Controller Firmware Version:** 2.8.35
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 16.6.1
* **Operating System and OS Version:** Ubuntu

**Comment by hjdhjd** [comment]
Thanks for the report, but there's not much to do here...HBUP simply responds with the quality of the stream that's being requested. There's not much I can recommend here. Best of luck!

**Comment by jacobhallgren** [comment]
> Thanks for the report, but there's not much to do here...HBUP simply responds with the quality of the stream that's being requested. There's not much I can recommend here. Best of luck!

Ok, So you dont have any suggestions on things to try/ or edit some settings. It working perfect on the wifi. But not remote. 

Also thanks for this great addon  for homebridge.

**Comment by jacobhallgren** [comment]
Ok so I found the issue. Its iOS 17 on apple tv. I tried with a apple tv thats is on 16.X and then cameras work fine remote. But If I connect the iOS17 its dead slow. Will see if some fix comes out from apple or if this plugin cant work good with atv IOS 17?

**Comment by hjdhjd** [comment]
HBUP works well across Apple's ecosystem, including Apple TV. Best of luck...none of these are plugin bugs or issues. You're welcome to use the Discord for further community support. Cheers.
