### ISSUE TITLE
UP-Floodlight

### ISSUE THREAD

**Issue by ukypayne** [hjdhjd/homebridge-unifi-protect#986]
**Is your feature request related to a problem? Please describe:**
Add support for flood light control

**Describe the solution you'd like:**
Support for flood light control. Time edit, alerts for movement.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by hjdhjd** [comment]
Literally in the list of options for this plugin right on the main page for this project. 😄 

This is already supported, as are **all** generally available UniFi Protect devices. Please read the documentation prior to opening new enhancement requests. Thanks!
