### ISSUE TITLE
Settings page does not render using MS Edge Browser

### ISSUE THREAD

**Issue by tpellegrini** [hjdhjd/homebridge-unifi-protect#995]
**Describe The Problem:**
The Settings page does not display correctly when using MS Edge 117.0.2045.55 on MacOS. The Header and Footer are displayed, but all the configuration options are not visible. Google Chrome and Safari work correctly. Edge 116.0.1938.79 on iPad OS 16.6.1 also does work correctly.

**To Reproduce:**
Open the plugin configuration page using the prescribed browser.

**Logs:**
N/A

**Screenshots:**
![image](https://github.com/hjdhjd/homebridge-unifi-protect/assets/26607300/bb7b7609-199c-4566-a41b-474e140871fd)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.17.1
* **Homebridge-UniFi-Protect Plugin Version:** 6.15.0
* **UniFi Protect Version:** 2.8.35
* **UniFi Protect Controller Type:** UDM Pro
* **UniFi Protect Controller Firmware Version:** 3.1.15
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Mac Mini M1 Sonoma 14.0
* **Operating System and OS Version:**   Homebridge Raspbian v1.0.24 - Raspberry Pi 3 Model B Rev 1.2

**Comment by hjdhjd** [comment]
This is not a bug in HBUP, it is a bug in Homebridge's webUI. You can (and should) report and provide additional data points if needed here: https://github.com/homebridge/homebridge-config-ui-x/issues/1527

If you disable ad blockers, things should work fine. Thanks for the report.
