### ISSUE TITLE
API error: Unable to connect to the Protect controller.

### ISSUE THREAD

**Issue by Chibale11** [hjdhjd/homebridge-unifi-protect#998]
**Describe The Problem:**
 API error: Unable to connect to the Protect controller. This is usually temporary and will occur during Protect controller reboots and firmware updates. Can not resolve

**To Reproduce:**
Raspbian GNU/Linux Buster (10) -  homebridge-unifi-protect v6.15.1. Node v18.16.0.

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "IP Removed",
            "password": "Password Removed",
            "username": "USER Removed"
        }
    ],
    "name": "UniFi Protect",
    "options": [
        "Enable.Video.HKSV",
        "Enable.Video.HKSV.Recording.Only.Medium",
        "Enable.Video.Stream.High",
        "Enable.Video.Stream.Only.High.F492BF8AD1AA",
        "Enable.Video.Transcode.Hardware",
        "Enable.Video.Transcode.Hardware.F492BF8AD1AA"
    ],
    "verboseFfmpeg": false,
    "_bridge": {
        "username": "MAC Address Removed",
        "port": 31216
    },
    "platform": "UniFi Protect"
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** Version 1.6.1
* **Node Version:** v18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** v6.115.1
* **UniFi Protect Version:** UniFi OS 3.1.16
* **UniFi Protect Controller Type:** Unifi Dream Machine Pro
* **UniFi Protect Controller Firmware Version:** v3.1.16
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** All of the above latest version for all
* **Operating System and OS Version:** Raspbian GNU/Linux Buster (10) / Mac Mini

**Comment by hjdhjd** [comment]
Thanks…unfortunately, the error message says it all. 😄  There are issues with the last couple of Protect firmware versions…you can reboot the controller from time to time. The issues are going to occur.  Best of luck.
